### ISSUE TITLE
compliance: remove compliance CRD from deploy/static and helm

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#102]
Perhaps we should not apply the CRDs for compliance on the cluster while we are not supporting it. It might be misleading.

![Screenshot from 2022-06-06 19-58-05](https://user-images.githubusercontent.com/34032/172262786-0f414ab1-f5b0-4468-8255-78cd09c7e10e.png)

**Comment by josedonizetti** [comment]
@chen-keinan  wdyt?

**Comment by chen-keinan** [comment]
ok, can be removed for now.
