### ISSUE TITLE
node-collector enabled\disabled

### ISSUE THREAD

**Issue by rkashasl** [aquasecurity/trivy-operator#1030]
Please add support for Boolean 'enabled' feature for 'nodeCollector' so we can turn it on and off when needed
thanks!

`nodeCollector:
  enabled: true
`

**Comment by chen-keinan** [comment]
@rkashasl you can disable it by setting [infraAssessmentScannerEnabled](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L62)

**Comment by giovannirco** [comment]
hey @rkashasl, have you seen something similar [to this issue](https://github.com/aquasecurity/trivy-operator/issues/1012)?

**Comment by chen-keinan** [comment]
@rkashasl Closing as configuration already available.
