### ISSUE TITLE
Unable to pull github action 

### ISSUE THREAD

**Issue by LatVAlY** [aquasecurity/trivy-operator#1063]
**What steps did you take and what happened:**
trying to run the github actions and it fails with: 
Dockerfile:1
  --------------------
     1 | >>> FROM ghcr.io/aquasecurity/trivy:0.38.1
     2 |     COPY entrypoint.sh /
     3 |     RUN apk --no-cache add bash curl npm
  ERROR: failed to solve: failed to fetch anonymous token: unexpected status: [50](https://git.i.mercedes-benz.com/WLTP-Frontend/api-gateway/runs/1752287?check_suite_focus=true#step:3:50)3 Service Unavailable
  Warning: Docker build failed with exit code 1, back off 4.794 seconds before retry.

  --------------------
github actions uses: aquasecurity/trivy-action@master

Note: this is was working couple days ago

**Comment by chen-keinan** [comment]
@LatVAlY you meant to open this issue in [github-action repo](https://github.com/aquasecurity/trivy-action/issues) ?

**Comment by talheim-it** [comment]
We have something similar now.

```
Failed to pull image "ghcr.io/aquasecurity/trivy:0.38.2": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/aquasecurity/trivy:0.38.2": failed to resolve reference "ghcr.io/aquasecurity/trivy:0.38.2": failed to authorize: failed to fetch anonymous token: unexpected status: 503 Service Unavailable

**Comment by pkoraca** [comment]
There's a Github Registry outage right now https://www.githubstatus.com/

**Comment by LatVAlY** [comment]
The issue is resolved, after Github fix
