### ISSUE TITLE
Trivy opeartor failed to start if disable vulnerabilityScanner

### ISSUE THREAD

**Issue by Wyifei** [aquasecurity/trivy-operator#1074]
**What steps did you take and what happened:**

Helm chart values:
operator:
    vulnerabilityScannerEnabled: false
    infraAssessmentScannerEnabled: false
    rbacAssessmentScannerEnabled: false

Trivy opeartor pod failed to start, check the log:

**property vulnerabilityReports.scanner not set**

**Helm template logic:**
  {{- if .Values.operator.vulnerabilityScannerEnabled }}
  vulnerabilityReports.scanner: {{ .Values.trivyOperator.vulnerabilityReportsPlugin | quote }}
  {{- end }}

**What did you expect to happen:**

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.12.1
- Kubernetes version (use `kubectl version`): 1.2.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Amazon Linux2

**Comment by chen-keinan** [comment]
@Wyifei according to [code](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/operator/operator.go#L145) , you'll have to disable both `ExposedSecretScannerEnabled` and `VulnerabilityScannerEnabled`
Related #1090
