### ISSUE TITLE
priorityClassName in ScanJob

### ISSUE THREAD

**Issue by WatcherWhale** [aquasecurity/trivy-operator#1076]
It would be nice to have a priorityClassName for the scan jobs.

**Comment by chen-keinan** [comment]
@WatcherWhale could be a nice addition , you can pick it up if you have time

**Comment by SamarSidharth** [comment]
Hello,
I would like to contribute to this project, can I pick this issue?
Thanks

**Comment by chen-keinan** [comment]
@SamarSidharth sure ,you can  pick up any issue you like

**Comment by SamarSidharth** [comment]
I am planning to implement it with trivy-operator config map. The approach would be to except it as an input parameter in the CM and then update the job's pod template spec `priorityClassName` attribute value. 

I have few queries:
1. By scan job do we mean all the jobs created by the trivy operator (node-collector, scan-vulnerabilityreport ) or only the scan-vulnerabilityreport job?
2. Need to figure out what other jobs does trivy-operator create (if we have some design document for trivy-operator that I could refer to for quick lookup regarding the this info)

Also if  we want to make changes to node-collector job we will have to make changes in `github.com/aquasecurity/trivy-kubernetes/pkg/jobs`

**Comment by chen-keinan** [comment]
> 
> I have few queries:
> 
> 1. By scan job do we mean all the jobs created by the trivy operator (node-collector, scan-vulnerabilityreport ) or only the scan-vulnerabilityreport job?
> 2. Need to figure out what other jobs does trivy-operator create (if we have some design document for trivy-operator that I could refer to for quick lookup regarding the this info)
> 
> Also if we want to make changes to node-collector job we will have to make changes in `github.com/aquasecurity/trivy-kubernetes/pkg/jobs`

1. its up to you to decide where to add it , I think `scan-vulnerabilityreport` could be a good start
2. there are [general docs](https://aquasecurity.github.io/trivy-operator/v0.12.1/) not specific.
 trivy-operator create only two type of jobs `scan-vulnerabilityreport` and `node-collector` , I assume you can start with
