### ISSUE TITLE
Node-collector mounts for CNI binaries

### ISSUE THREAD

**Issue by rwkarg** [aquasecurity/trivy-operator#1088]
**What steps did you take and what happened:**

Installed trivy-operator via: https://github.com/aquasecurity/trivy-operator/blob/main/deploy/static/trivy-operator.yaml

`node-collector` job is unable to be created with error in Event:

`failed to generate container "e5a..." spec: failed to generate spec: failed to mkdir "/opt/cni/bin/": mkdir /opt/cni: read-only file system: CreateContainerError`

**What did you expect to happen:**
`node-collector` runs without error

**Anything else you would like to add:**
It looks like this is where the cni binaries are for Cilium (the CNI in use), but I don't see a way to configure that for `node-collector`:

```
volumeMounts:
  - mountPath: /host/opt/cni/bin
    name: cni-path
```

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.12.1
- Kubernetes version (use `kubectl version`): 1.25.6-gke.1000
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): GKE
- CNI: Cilium (via DataplaneV2)

**Comment by chen-keinan** [comment]
@timclifford @rwkarg I assume you mean that you want the the volume (on host) --> `hostPath` to be configurable , right? 
example: 
```
- name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin/
```

**Comment by timclifford** [comment]
@chen-keinan Yes, for my use case the calico CNI plugin is installed to a different location than the default '/opt/cni/bin', being able to change the mount path would fix this issue for me.
