### ISSUE TITLE
crd symlink is not followed when deploying via helm

### ISSUE THREAD

**Issue by daniel-laszlo** [aquasecurity/trivy-operator#1100]
**What steps did you take and what happened:**

We are using helmfile to deploy certain helm charts including trivy-operator. It uses `helm template` in the background. When running deploy, I get following error:

```
STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "cis" namespace: "" from "": no matches for kind "ClusterComplianceReport" in version "aquasecurity.github.io/v1alpha1"
  ensure CRDs are installed first, resource mapping not found for name: "nsa" namespace: "" from "": no matches for kind "ClusterComplianceReport" in version "aquasecurity.github.io/v1alpha1"
  ensure CRDs are installed first, resource mapping not found for name: "pss-baseline" namespace: "" from "": no matches for kind "ClusterComplianceReport" in version "aquasecurity.github.io/v1alpha1"
  ensure CRDs are installed first, resource mapping not found for name: "pss-restricted" namespace: "" from "": no matches for kind "ClusterComplianceReport" in version "aquasecurity.github.io/v1alpha1"
  ensure CRDs are installed first]
```

Seemingly the crds symlink is not followed by helm in https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm.

**What did you expect to happen:**

symlink followed, CRDs are also deployed, and no error for `cis`, `nsa`, `pss-restricted`, `pss-baseline` clustercompliancereports.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.12.1
- Kubernetes version (use `kubectl version`): 1.24
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A

**Comment by chen-keinan** [comment]
@daniel-laszlo will using real `crds` folder instead of symlik will solve you issue ?

**Comment by benoitbayol** [comment]
Hey,

same error messages chart version 0.20.2 and helmfile version 0.160 but I assume the fix has been integrated long ago in a previous release.

Is there a rollback to crd symlink after the fix ?

Thanks,

**Comment by chen-keinan** [comment]
@benoitbayol there is no sym link for crd anymore.
