### ISSUE TITLE
trivy-operator: clustervulnerabilityreports only installed for helm

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#111]
The CRD `ClusterVulnerabilityReport` is installed when using `helm` but not by the static `kubectl apply -f`.
Which one is correct? 

`helm install`
```
$ kubectl api-resources | grep aqua | grep vuln
clustervulnerabilityreports       clustervuln,clustervulns   aquasecurity.github.io/v1alpha1        false        ClusterVulnerabilityReport
vulnerabilityreports              vuln,vulns                 aquasecurity.github.io/v1alpha1        true         VulnerabilityReport
```

`kubectl apply -f`
```
$ kubectl api-resources | grep aqua | grep vuln
vulnerabilityreports              vuln,vulns           aquasecurity.github.io/v1alpha1        true         VulnerabilityReport
```

**Comment by josedonizetti** [comment]
@chen-keinan do you know if we should have `clustervulnerabilityreports` installed by `kubectl apply -f` or should we not install it with `helm`?

**Comment by chen-keinan** [comment]
@josedonizetti thinking about it again, maybe we should keep it with partial results

**Comment by josedonizetti** [comment]
@chen-keinan partial results? Helm installing but kubeclt no?

**Comment by chen-keinan** [comment]
> @chen-keinan partial results? Helm installing but kubeclt no?

any way we use to do kubectl manually

**Comment by josedonizetti** [comment]
@chen-keinan Not following what you mean. Do you think is it okay for the two commands below to install something different? Shouldn't they be equivalent?

```
helm repo add aqua https://aquasecurity.github.io/helm-charts/
helm repo update
helm install trivy-operator aqua/trivy-operator \
   --namespace trivy-system \
   --create-namespace \
   --set="trivy.ignoreUnfixed=true" \
   --version v0.0.5
```

```
kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.0.5/deploy/static/trivy-operator.yaml
```

**Comment by josedonizetti** [comment]
@chen-keinan and I spoke about it, and the `clustervulnerabilityreports` is legacy, we can remove it from the helm installation as well.
