### ISSUE TITLE
Trivy vulnerability report access through web page

### ISSUE THREAD

**Issue by mohang6770** [aquasecurity/trivy-operator#1119]
Is there a feature to access vulnerability report through web or download as csv

**Comment by chen-keinan** [comment]
@mohang6770 see the integration with [PolicyReporter](https://aquasecurity.github.io/trivy-operator/v0.12.1/tutorials/integrations/policy-reporter/)

**Comment by chen-keinan** [comment]
@chen-keinan I thin we can close this issue, wdyt ?
