### ISSUE TITLE
trivy-operator: add plural to configaudit CRD

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#112]
The configaudit reports are namespaced, and they are created for several resources, we should have a plural for it. Currently it only supports singular:

```
configauditreports                configaudit                    aquasecurity.github.io/v1alpha1        true         ConfigAuditReport
```

**Comment by josedonizetti** [comment]
@chen-keinan any point against?

**Comment by pradeepnnv** [comment]
I would like to work on it.

**Comment by chen-keinan** [comment]
> @chen-keinan any point against?

All good !!!

**Comment by josedonizetti** [comment]
@pradeepnnv Let us know if you have any questions. Thank you!

**Comment by pradeepnnv** [comment]
When I describe the configauditreport, I do see a plural for it.

```
 k describe crd configauditreports.aquasecurity.github.io

Status:
  Accepted Names:
    Kind:       ConfigAuditReport
    List Kind:  ConfigAuditReportList
    Plural:     configauditreports
    Short Names:
      configaudit
    Singular:  configauditreport
```

@josedonizetti , looks like I'm missing something. Can you please clarify?

**Comment by josedonizetti** [comment]
@pradeepnnv Yes, I was referencing about the short names.
