### ISSUE TITLE
README.md - Getting started link gives 404

### ISSUE THREAD

**Issue by EirikAskheim** [aquasecurity/trivy-operator#1122]
**What steps did you take and what happened:**

Clicked the link in the README on github.com.

[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**

Getting to getting started guide.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Earth

- Trivy-Operator version (use `trivy-operator version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@EirikAskheim thanks for reporting this issue , it will be fixed shortly
