### ISSUE TITLE
vulnerabiliy id 

### ISSUE THREAD

**Issue by mohang6770** [aquasecurity/trivy-operator#1123]
how to get the vulnerabiliy id in prometheus.
            - name: OPERATOR_METRICS_VULN_ID_ENABLED
              value: "true"
still cant get it on prometheus
![image](https://user-images.githubusercontent.com/48823895/229097599-12e75b1b-8c8e-4231-b29e-d97e800a31bd.png)

**Comment by dotdc** [comment]
Not a problem with trivy-operator.
Check my comment in https://github.com/dotdc/grafana-dashboards-kubernetes/issues/40

**Comment by chen-keinan** [comment]
@mohang6770 the metric name is `trivy_vulnerability_id`

**Comment by chen-keinan** [comment]
@mohang6770 any additional input required on this issue ?

**Comment by chen-keinan** [comment]
@mohang6770 I think we can close this issue wdyt ?

**Comment by chen-keinan** [comment]
Closing following to confirmation from @mohang6770
