### ISSUE TITLE
Reconcile errors base64

### ISSUE THREAD

**Issue by githubcdr** [aquasecurity/trivy-operator#1144]
Hi,

I'm seeing this error in trivy-operator, the scanner works but it looks like some images cause this issue;

```
{"level":"error","ts":"2023-04-04T13:13:21Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-6df54dd7bf","namespace":"trivy-system"},"namespace":"trivy-system","na
me":"scan-vulnerabilityreport-6df54dd7bf","reconcileID":"98294841-b8eb-49ed-8a41-ffd2590fd7b3","error":"unexpected EOF","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/s
igs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal
/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"error","ts":"2023-04-04T13:13:21Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-5db54c7f7d","namespace":"trivy-system"},"namespace":"trivy-system","na
me":"scan-vulnerabilityreport-5db54c7f7d","reconcileID":"54342246-0a3a-4820-abcc-0d0d825c1e1b","error":"illegal base64 data at input byte 109226","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\
t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-ru
ntime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"
}
```

This is on trivy-operator 1.13.0 kubernetes 1.24.5

Is this a bug?

**Comment by chen-keinan** [comment]
@githubcdr could you please share the output (if it is not confidential) of the pods.
`kubectl logs <pod name> -n trivy-system`

**Comment by githubcdr** [comment]
Unfortunately I'm unable to share this information, but for completed pods the output is a valid base64 result. I'm not sure why some containers cause this issue, maybe it is resource related.

**Comment by chen-keinan** [comment]
> Unfortunately I'm unable to share this information, but for completed pods the output is a valid base64 result. I'm not sure why some containers cause this issue, maybe it is resource related.

@githubcdr  could you delete the related jobs (which produce the pods) and restart

**Comment by githubcdr** [comment]
I removed all jobs and restarted the operator, but the issue persists. Not sure but it might be related to resources or db download issues in Trivy.

**Comment by chen-keinan** [comment]
@githubcdr do you mind repeating these steps again , maybe uninstall `trivy-operator` and install again but this time with flag [compressLogs=false](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L146) could be there is an error that is not seen and you could review it with pod logs.

if you get an error  and the pod is stuck with status completed , please check it logs and let me know if any error found
