### ISSUE TITLE
Expose detail info for config audit report as  Prometheus metrics

### ISSUE THREAD

**Issue by JKnino** [aquasecurity/trivy-operator#1148]
is it possible to get configAudit ID (KSV) in Prometheus, would like to have them in grafana, thank you

**Comment by JKnino** [comment]
actually you have made great work with vulnerabilityID/VulnerabilityReport exposing all need Infos which help us to create more detailed grafana panels/dashboards , it would just make sense to do that in same way for all other segments as:

ConfigAuditReport
RbacAssessmentReport
InfraAssessmentReport
ClusterComplianceReport 

since having just number and status does not tell to much and we need to use lens or look to k8 directly

**Comment by AP-XD** [comment]
I have also mentioned about the same thing in #1121 . Being able to access the ClusterComplianceReport in the metrics endpoint would be very helpful! For now I am using a custom REST API to serve the json in https://www.npoint.io/ and then using it via JSON API plugin in Grafana dashboard.

**Comment by geoffrey1330** [comment]
Hi @chen-keinan could you assign this issue to me.
