### ISSUE TITLE
Feature Request : Provide a config in CIS compliance to specify benchmark version

### ISSUE THREAD

**Issue by AP-XD** [aquasecurity/trivy-operator#1152]
It would be very helpful if a config to specify benchmark version in trivy operator is provided as we used to specify in kube bench by using the` -- benchmark` parameter.
For now Trivy provides all benchmarks with 1.23 version of CIS Benchmark, I would like to be able to change the config in Trivy operator too

**Comment by dlaidlaw** [comment]
It would also be nice to be able to choose a benchmark for the major cloud provider managed kubernetes offerings. Such as EKS, AKS, GKE, and others provided by CIS.
