### ISSUE TITLE
Image scanning should be based on actual running container image

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#118]
I suspect that the operator is scanning images based on the workload specification. This might not always be accurate, and I think it would be better if the scanning was based on the actual image the Pod container is running on.

We have developed an in-house operator similar to trivy-operator, but would like to abandon this work and put our effort into the trivy-operator instead. There might be several ways to fix this issue, but in our operator we watch pods (filtering events) instead of the workload. That allows us to pull out the actual running container image digest from the Pod [containerStatuses](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#containerstatus-v1-core), and that will always give accurate results.

Possibly related issue: https://github.com/aquasecurity/trivy-operator/issues/101

**Comment by philippn** [comment]
+1 for scanning images by digest.
