### ISSUE TITLE
The false item reported by the infra scan does not match the actual kubelet configuration

### ISSUE THREAD

**Issue by srikwang** [aquasecurity/trivy-operator#1181]
**What steps did you take and what happened:**
I deployed trivy-operator in the EKS cluster of AWS, and tried to repair it according to the report content of infra, and found that the false item in the report did not match my actual kubelet configuration, as shown in the figure below
**Environment:**
AWS EKS 
- Trivy-Operator version (use `trivy-operator version`): 1.30.1
- Kubernetes version (use `kubectl version`): 1.22.17
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):centos8
**kubelet config**
![img_v2_6e0f4619-63a7-45c0-b1dc-5ea3f1003c1g](https://user-images.githubusercontent.com/129261014/233916779-5485c578-7736-4e93-9dc0-2cceee214ee9.jpg)
**infra report**
![image](https://user-images.githubusercontent.com/129261014/233916947-55aee8b7-d1bd-43c1-a14e-6ab6c63d3665.png)

**Comment by chen-keinan** [comment]
@srikwang thanks for reporting this , can you run the following command on the node and let me know the results :
`ps -ef | grep kubelet |grep ' --anonymous-auth'`

and

`ps -ef | grep kubelet |grep ' --read-only-port'`

**Comment by srikwang** [comment]
> 
I started it by specifying the file with --config
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/129261014/233921795-bddec7bc-59f8-40b4-b442-d5fd35086d5c.png">

**Comment by chen-keinan** [comment]
> > 
> 
> I started it by specifying the file with --config <img alt="image" width="1313" src="https://user-images.githubusercontent.com/129261014/233921795-bddec7bc-59f8-40b4-b442-d5fd35086d5c.png">

@srikwang  thanks for the input , I will check it and update

**Comment by chen-keinan** [comment]
> Isnt this caused by the fact that Trivy uses the "generic" CIS kubernetes benchmark ? not the EKS specific one: https://workbench.cisecurity.org/benchmarks/9681 Maybe Trivy should also support the EKS benchmark ? like kube bench does: https://github.com/aquasecurity/kube-bench

not sure as , the check issue reported is on worker Node, which is visible on cloud provider and match EKS spec.
