### ISSUE TITLE
Add vuln-type configuration parameter

### ISSUE THREAD

**Issue by 3rgfbrgf** [aquasecurity/trivy-operator#119]

**Comment by 3rgfbrgf** [comment]
It would be useful to have an option for setting up vuln-type parameter for the operator

**Comment by josedonizetti** [comment]
@3rgfbrgf do you mind expand a little bit more on this request?

**Comment by 3rgfbrgf** [comment]
@josedonizetti sure.
I would like to have an option to enable libs scan only, without OS scan.

**Comment by chen-keinan** [comment]
> I'm also interested in this configuration to have os level scans only.

the [config](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L313) has been added and will be released within next release, trivy-operator v0.14.0

**Comment by chen-keinan** [comment]
Fixed by #1184

**Comment by rgarcia89** [comment]
Has someone tested if this really works? I am not seeing the library scanned for an image using the trivy operator. OS is fine. In my case I am comparing the results with a trivy image scan triggered via the CLI

**Comment by rgarcia89** [comment]
I have opened an issue in regards to the parameter https://github.com/aquasecurity/trivy-operator/issues/1886
