### ISSUE TITLE
Helm Chart: Missing quotes around cron expressions

### ISSUE THREAD

**Issue by ErikLundJensen** [aquasecurity/trivy-operator#1190]
Specifying a cron expression that starts with an asteriks, e.g. `*/10 * * * *` fails during rendering of the chart.
The content of .Values.compliance.cron must be quoted. For example: {{  .Values.compliance.cron | quote }}

https://github.com/aquasecurity/trivy-operator/blob/ec6a40fdc57bdaabf435a0b074c65dd2125ee2c7/deploy/helm/templates/specs/cis-1.23.yaml#L12

There are a few more places where the cron element is used.

**Environment:**

- Trivy-Operator Helm Chart 0.13.1

**Comment by chen-keinan** [comment]
@ErikLundJensen thanks you for reporting this issue , you can pick up this issue and create PR if you have time

**Comment by jbiers** [comment]
@chen-keinan I would like to work on this issue if there's no problem with you guys

**Comment by chen-keinan** [comment]
> @chen-keinan I would like to work on this issue if there's no problem with you guys

go for it 💪

**Comment by chen-keinan** [comment]
@jbiers are you working on this issue? we need a fix for it (it requested for more then once)
