### ISSUE TITLE
private registries scan

### ISSUE THREAD

**Issue by 3rgfbrgf** [aquasecurity/trivy-operator#120]
It's technically possible to scan private registries if we have a way to pass
TRIVY_INSECURE
TRIVY_USERNAME
TRIVY_PASSWORD
variables to the trivy scanner.
We could set up TRIVY_INSECURE parameter via env.
And we could get TRIVY_USERNAME&TRIVY_PASSWORD from k8s secret with registry pull rights (or any other way).

**Comment by chen-keinan** [comment]
@3rgfbrgf Trivy-operator knows to find references to image pull secrets (direct references and via service account).
and create the temporary secret with basic credentials for each container of the scanned workload.
create the scan job that references the temporary secret. The secret has the ownerReference property set to point to the job.

**Comment by 3rgfbrgf** [comment]
@chen-keinan ok, what about the TRIVY_INSECURE flag? It's needed for scanning private registries with trivy CLI.
Hot to set it up for the operator?

**Comment by erikgb** [comment]
> @chen-keinan ok, what about the TRIVY_INSECURE flag? It's needed for scanning private registries with trivy CLI.

It is not always needed when using private registries. If you private registry has a public signed cert, you don't need it.

**Comment by chen-keinan** [comment]
@3rgfbrgf see above

**Comment by 3rgfbrgf** [comment]
@chen-keinan I don't see this parameter in the latest pulled helm chart (0.0.5)

**Comment by chen-keinan** [comment]
> @chen-keinan I don't see this parameter in the latest pulled helm chart (0.0.5)

I have a task to work out the documentation for it, in the mean, while take a look at trivy [scanning config](https://github.com/aquasecurity/trivy-operator/blob/main/docs/vulnerability-scanning/trivy.md). you'll need to update the `trivy-operator-trivy-config configmap`  with this param
