### ISSUE TITLE
Webhook eventually stop sending vulnerability reports

### ISSUE THREAD

**Issue by guipal** [aquasecurity/trivy-operator#1208]
**What steps did you take and what happened:**

Deploy operator on cluster with a scanreportTtl set to 12h and webhookurl configured

**What did you expect to happen:**

Operator to send report through the webHook either on new reports or recreated ones.

**What really happens**

Operator eventually stop sending events for any report. This also happens for new created workloads. The error disappear when restarting the pod. 

**Anything else you would like to add:**

After some debugging it appears that operator is considering all reports as historical. Somehow the value for Ttl gets to 0s while the annotation is correct

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.13.2
- Kubernetes version (use `kubectl version`): tbc
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): eks cluster

**Comment by guipal** [comment]
Additionally, I increased the log level to debug an  added information about the annotation value. Here you can see an example of the problem:
![image](https://user-images.githubusercontent.com/10268389/236771280-bf217cab-94a7-4b5e-ab1e-32f6a6dfd95c.png)
As you can see the reportTtl is 0s on the webhookreporter.go
`func (r *WebhookReconciler) reconcileReport(reportType client.Object) reconcile.Func {
	return func(ctx context.Context, request reconcile.Request) (reconcile.Result, error) {
		log := r.Logger.WithValues("report", request.NamespacedName, "ttl", reportType.GetAnnotations()[v1alpha1.TTLReportAnnotation])
		log.V(1).Info("Reconciling report")
		if ignoreHistoricalReport(reportType) {
			log.V(1).Info("Ignoring historical report")
			return ctrl.Result{}, nil
		}
		verb := Update`
In the other hand, the report annotation is set to 12h1m5s as we can see in the next screenshot.
![image](https://user-images.githubusercontent.com/10268389/236771865-7419407a-d95e-4088-b0b7-b012eab1440a.png)

Hope this can give you more insights about what can be the problem.

Thank you!

**Comment by chen-keinan** [comment]
> There's no specific error in the log, but as I already mentioned operator is not even sending reports created for new deployments. (This can't be historical reports).
> 
> How do you consider a report is historical? Is there any logic or is just by setting the annotation to 0s?

when an existing deployment is changed , example :
1. deploy `kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml`
2. update deployment via `kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.16.1` (update nginx version)

the initial report with `nginx=v0.1.14.2` is consider now as historical as a. new report has been created with `nginx:1.16.1`

here is the [logic](https://github.com/aquasecurity/trivy-operator/blob/983283ec90d33b96f6847a7f8054bcddf772f585/pkg/operator/workload/helper.go#L50)

**Comment by guipal** [comment]
Yes, I checked that part. The problem is that this seems to be applied to all the vulnerabilityReports get from the cluster. As ALL the vulnerabilityReports are coming with 0s as that value.

**Comment by guipal** [comment]
Hello. Was able to reproduce the issue FINALLY 😓 .  The problem is that once you roll out a new version of a deployment, automatically all the reconcileReport events return TTL=0s. Even for other deployments in the cluster or newly created ones. Apparently, this value gets cached in the [controller manager ](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.1/pkg/manager/manager.go#L149). Kudos @achetronic

**Comment by guipal** [comment]
Last comment. Tested this change as a workaround an it fixes the problem:`func (r *WebhookReconciler) reconcileReport(reportType client.Object) reconcile.Func {
	return func(ctx context.Context, request reconcile.Request) (reconcile.Result, error) {
		log := r.Logger.WithValues("report", request.NamespacedName, "ttl", reportType.GetAnnotations()[v1alpha1.TTLReportAnnotation])
		log.V(1).Info("Reconciling report")

		err := r.Client.Get(ctx, request.NamespacedName, reportType)
		log = r.Logger.WithValues("report", request.NamespacedName, "ttl", reportType.GetAnnotations()[v1alpha1.TTLReportAnnotation])
		log.V(1).Info("Reconciling report after get")
		verb := Update

		if err != nil {
			if !errors.IsNotFound(err) {
				return ctrl.Result{}, fmt.Errorf("getting report from cache: %w", err)
			}
			if !r.WebhookSendDeletedReports {
				log.V(1).Info("Ignoring cached report that must have been deleted")
				return ctrl.Result{}, nil
			}
			verb = Delete
		}

		if ignoreHistoricalReport(reportType) {
			log.V(1).Info("Ignoring historical report")
			return ctrl.Result{}, nil
		}

		if r.WebhookSendDeletedReports {
			msg := WebhookMsg{OperatorObject: reportType, Verb: verb}

			return ctrl.Result{}, sendReport(msg, r.WebhookBroadcastURL, *r.WebhookBroadcastTimeout)
		}
		return ctrl.Result{}, sendReport(reportType, r.WebhookBroadcastURL, *r.WebhookBroadcastTimeout)
	}
}`

I will create the PR if you do agree with the approach.
