### ISSUE TITLE
more granular way to set up security context in helm chart

### ISSUE THREAD

**Issue by 3rgfbrgf** [aquasecurity/trivy-operator#121]
It would be nice to have a way to set up securityContexts for:
 - initContainers
 - jobs, which are being run during scans. Including compliance scan jobs, which require a lot of host-level access.

**Comment by chen-keinan** [comment]
@3rgfbrgf could you add an example ?

**Comment by 3rgfbrgf** [comment]
@chen-keinan sure.
Let's take as an example any scan-vulnerabilityreport job spec.
There is an initContainer with an empty securityContext.
We have an admission controller in our cluster, which prevents this from running by design.

As for compliance scans - pod for that job should mount host paths and so on.
It should be configurable by providing clear and obvious permissions for host PID, host network, host path etc in security context.
Currently it just needs privileged mode, as I can understand.

Also, PSP is deprecated, but still the case, so it's better to have an opportunity to create and customise it in your helm chart.

**Comment by chen-keinan** [comment]
@3rgfbrgf please confirm if the PR #362 solve your use case or you need it more granular in container level

**Comment by chen-keinan** [comment]
closing this issue as it been implemented by #362 @3rgfbrgf if still an issue feel free to open it

**Comment by FelixKampfer** [comment]
Hi, I thinkk #362 doesn't address the securityContext of initContainers. I opened https://github.com/aquasecurity/trivy-operator/pull/459 as a possible solution.
