### ISSUE TITLE
Support private certificate authority

### ISSUE THREAD

**Issue by gaeljw** [aquasecurity/trivy-operator#1210]
_(Follow up of discussion https://github.com/aquasecurity/trivy/discussions/4194)_

When using Trivy against a private image registry which HTTPS certificate is signed by a private authority, the error described in https://github.com/aquasecurity/trivy/issues/757 is raised:

```
Get "https://registry.private.net/v2/": x509: certificate signed by unknown authority
```

The workaround described in https://github.com/aquasecurity/trivy/issues/757 is to disable TLS verification for the registry which can be done via Trivy Operator Helm values:
```yaml
trivy:
  insecureRegistries:
    myprivateregistry: registry.private.net
```

But it would be even better if Trivy Operator supported customizing the trusted authorities by being able to provide CA certificate through a ConfigMap for instance (this is what ArgoCD does to support private CA).

It was suggested that being able to define `SSL_CERT_DIR` env variable should be enough (which Trivy Operator does not support yet) but, if it makes sense according to you, I'd go further in providing an easy way (at least in the Helm chart) for configuring private CA without having to care about this env var directly.

**Comment by SammyA** [comment]
This is only a partial fix as we also need to download the vulnerability database. This is done through an init container or in the trivy-server, both do not get the ssl dir mounted. As also mentioned, a certificate injected through a configmap (or secret) would be way more convenient than mounting a hostpath.

**Comment by chen-keinan** [comment]
@SammyA Do you mind opening  a separate issue for it.

**Comment by SammyA** [comment]
See #1675 and #1676
