### ISSUE TITLE
Cant remove the namespace because of the reports

### ISSUE THREAD

**Issue by tothger** [aquasecurity/trivy-operator#1224]
**What steps did you take and what happened:**

Tried to remove a namespace what contains reports like

`configauditreport.aquasecurity.github.io/xxx`

I received the following error

`Some content in the namespace has finalizers remaining: [starboard-exporter.giantswarm.io/configauditreport](http://starboard-exporter.giantswarm.io/configauditreport) in 3 resource instances
`
**What did you expect to happen:**
I can remove the namespace without any problems

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):  0.13.0 Helm version
- Kubernetes version (use `kubectl version`): 1.25.5

**Comment by chen-keinan** [comment]
@tothger could you please add more details , like how did you remove it and what is your goal ?

**Comment by tothger** [comment]
sure.
I had a namespace called: `namespace01`
I had a replicaset called `replicaset-rs-5987c949f2`

and I had a related configauditreport in that namespace
`configauditreport.aquasecurity.github.io/replicaset-rs-5987c949f2`                Trivy   77d

Im trying to delete the namespace with terraform but the deletion of these resources cannot be completed, thus getting the namespace stuck in `terminating ` state

As a temp solution we removed the finalizers from these reports
`kubectl patch vulnerabilityreports.aquasecurity.github.io replicaset-rs-5987c949f2 --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]' -n namespace01`

And this is in the metadata of the report
```
Metadata:
  Creation Timestamp:             2023-03-28T06:34:20Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2023-05-05T16:46:43Z
  Finalizers:
    starboard-exporter.giantswarm.io/configauditreport
  Generation:  4
```

**Comment by chen-keinan** [comment]
@tothger sorry for late response , have you tried to delete CRDs before deleting namespace ? 
example:
```
kubectl delete crd vulnerabilityreports.aquasecurity.github.io
kubectl delete crd exposedsecretreports.aquasecurity.github.io
kubectl delete crd configauditreports.aquasecurity.github.io
kubectl delete crd clusterconfigauditreports.aquasecurity.github.io
kubectl delete crd rbacassessmentreports.aquasecurity.github.io
kubectl delete crd infraassessmentreports.aquasecurity.github.io
kubectl delete crd clusterrbacassessmentreports.aquasecurity.github.io
kubectl delete crd clustercompliancereports.aquasecurity.github.io
kubectl delete crd clusterinfraassessmentreports.aquasecurity.github.io
kubectl delete crd clusterconfigauditreports.aquasecurity.github.io
```

**Comment by chen-keinan** [comment]
@tothger is this issue still relevant or can be closed ?

**Comment by tothger** [comment]
I manually deleted the old reports from Starboard with the finalizer patch. 

I still have an issue to clean all old reports from the cluster.

So it looks the problem is with the „old“ Starboard Operator - Trivy collaboration, not with the Trivy Operator
