### ISSUE TITLE
 Unable to control scan time via crontab

### ISSUE THREAD

**Issue by srikwang** [aquasecurity/trivy-operator#1226]
**What steps did you take and what happened:**
I try to control the time interval of the scan by modifying the following parameters
```
compliance:
  failEntriesLimit: 30000
  reportType: all
  cron: 0 0 */2 * *
```

**What did you expect to happen:**

Scanning occurs every two days at 00:00
**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.13.2
- Kubernetes version (use `kubectl version`):v1.22.17
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):centos8

**Comment by srikwang** [comment]
I get the report through webhook,and found that most of the reports are generated periodically, but the time seems irregular
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/7eaa1adf-9545-4791-8cbf-1030068cff62)

**Comment by chen-keinan** [comment]
the cron expression you put is for  `0 0 */2 * *` =  `At 00:00 on every 2nd day-of-month` is this is what  you wanted ?

**Comment by srikwang** [comment]
no, The following example:
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/99da3113-0c28-4d77-a125-67cda126a639)
Every two days at 00:00

**Comment by chen-keinan** [comment]
@srikwang are you using helm ? maybe it related to #1190

**Comment by srikwang** [comment]
Yes, it may be the same problem. In addition, I want to control the scanning time interval of rbac, clusterrbac, infra, config, etc. Is there any way?

**Comment by chen-keinan** [comment]
> Yes, it may be the same problem. In addition, I want to control the scanning time interval of rbac, clusterrbac, infra, config, etc. Is there any way?

the compliance report generation works differently from the other reports,
- compliance report work base on cron (as define)  
- rbac, clusterrbac, infra, config are event base , every time a new resource or node is deployed

**Comment by srikwang** [comment]
> .
But the information I got through the webhook shows that the reports of rbac, clusterrbac, and clusterinfra are sent out periodically, as shown in the figure below, could it be a problem with the webhook settings?

**Comment by srikwang** [comment]
> > Yes, it may be the same problem. In addition, I want to control the scanning time interval of rbac, clusterrbac, infra, config, etc. Is there any way?
> 
> the compliance report generation works differently from the other reports,
> 
> * compliance report work base on cron (as define)
> * rbac, clusterrbac, infra, config are event base , every time a new resource or node is deployed

But I saw rbac, clusterrbac, and infra through the report time sent by webhook, these are periodic reports, as shown in the figure below,
Is there a problem with the setting of webhook?
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/e94415cc-f30e-4904-b8ad-cd87f959a8f5)

**Comment by chen-keinan** [comment]
@srikwang the webhook controller is event base  , meaning every time new/updated report is generated the webhook controller is triggered.
as mention above all reports except of compliance are generated based on event (when new/updated resource or node is deployed ) only compliance is generated based on cron.

rbac and infra report should not be periodic , can you check timestamp of these reports and let know if it is the same for all three ?

**Comment by srikwang** [comment]
After reviewing, I saw that the report creation time is the same, but the webhook will be sent out periodically, can this be modified?
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/263808ac-f35e-4831-b562-a10e4cbdd193)

**Comment by chen-keinan** [comment]
@srikwang I meant if you can check the report via `kubectl get ...` and confirm it timestamp

**Comment by chen-keinan** [comment]
for example: `kubectl get clusterinfraassessmentreport` and see if generation is greater then 1
```yaml
apiVersion: v1
items:
- apiVersion: aquasecurity.github.io/v1alpha1
  kind: ClusterInfraAssessmentReport
  metadata:
    creationTimestamp: "2023-05-22T06:56:40Z"
    generation: 1
```

**Comment by chen-keinan** [comment]
> It looks like it <img alt="image" width="745" src="https://user-images.githubusercontent.com/129261014/239829760-faef14e8-bf70-4f14-8c1f-ce25c81f2108.png">

thanks for the update so you should get for it only one event , I'l check if there is issue with webhook

**Comment by srikwang** [comment]
> > It looks like it <img alt="image" width="745" src="https://user-images.githubusercontent.com/129261014/239829760-faef14e8-bf70-4f14-8c1f-ce25c81f2108.png">
> 
> thanks for the update so you should get for it only one event , I'll check if there is issue with webhook
Ok, thank you. Looking forward to your reply

**Comment by srikwang** [comment]
Yes, I found the main cause of the problem, I reopened an issue [#1250](https://github.com/aquasecurity/trivy-operator/issues/1250#issue-1733282011)
