### ISSUE TITLE
create not allowed while custom resource definition is terminating

### ISSUE THREAD

**Issue by tothger** [aquasecurity/trivy-operator#1238]
**What steps did you take and what happened:**

Deployed the Trivy operator with helm

This error message in the Trivy operator pod logs
```
{"level":"error","ts":"2023-05-23T10:56:59Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-fb4474b98","namespace":"monitoring-test"},"namespace":"monitoring-test","name":"scan-vulnerabilityreport-fb4474b98","reconcileID":"81d3cbd3-7cf1-46ec-a7a7-517b43070c25","error":"create not allowed while custom resource definition is terminating","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
```

I have similar error messages for every namespaces and with the following kinds
controllerKind":"Service"
controllerKind":"Job"
controllerKind":"ReplicaSet"

Is that a permission issue? Or what type?

**What did you expect to happen:**

No that errors.  

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.13.0 Helm version
- Kubernetes version (use `kubectl version`): 1.25.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@tothger have you deleted CRDs before install or performed any other action ?

**Comment by tothger** [comment]
@chen-keinan yes. I deleted all the CRD-s before the installation. Basically it was required due to the install failed because of the difference CRD structures. ( especially it failed at the clustercompliance report ).
the old Starboard operator with Trivy were installed before on my cluster.
Good to mention. I deleted only the CRD-s for the reports but not every single reports what created for every resource by Starboard.
So I did the intended steps what mentioned in the helm chart. Wasnt that enough? 

These were the steps
    kubectl delete crd vulnerabilityreports.aquasecurity.github.io
    kubectl delete crd configauditreports.aquasecurity.github.io
    kubectl delete crd clusterconfigauditreports.aquasecurity.github.io
    kubectl delete crd rbacassessmentreports.aquasecurity.github.io
    kubectl delete crd infraassessmentreports.aquasecurity.github.io
    kubectl delete crd clusterrbacassessmentreports.aquasecurity.github.io

**Comment by chen-keinan** [comment]
@tothger its look like it related , need to confirm that env. is clean without any terminating resources in process.
can you confirm that and try again ?
