### ISSUE TITLE
webhook periodically resends the same report content

### ISSUE THREAD

**Issue by srikwang** [aquasecurity/trivy-operator#1250]
**What steps did you take and what happened:**
Deploy the trivy-operator as normal, and set the reports to be sent via webhook. After some time, I found out that the webhook periodically sends old reports. I think that the reports sent by the webhook should be live content, not old content.

**What did you expect to happen:**
 I think that the reports sent by the webhook should be live content, not old content.
**Anything else you would like to add:**
The following is an example of a compliance report, but the others are also
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/df476fb8-2b71-4b3d-a309-3e72f8388771)

**Environment:**

- Trivy-Operator version (use trivy-operator version): 0.13.2
- Kubernetes version (use kubectl version):v1.22.17
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):centos8

**Comment by chen-keinan** [comment]
@srikwang I think we fixed (#1216 ) it in latest `trivy-operator v0.14.0-rc` , can you confirm ?

**Comment by srikwang** [comment]
> 

Ok, I will continue to verify this issue in the environment after the next release, thanks

**Comment by chen-keinan** [comment]
@srikwang  please re-check with trivy-operator v0.140

**Comment by srikwang** [comment]
> @srikwang please re-check with trivy-operator v0.140


It doesn't seem to be fixed. After upgrading trivy-operator to 1.40.0, I observed for a while and found that the old report can still be seen through webhook.

**Comment by chen-keinan** [comment]
@srikwang are you referring to compliance reports ?

**Comment by srikwang** [comment]
> 

Not just compliance reports,as follow
![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/c26c6eb8-9bd1-4af0-8f1b-f84a4f75de82)

**Comment by chen-keinan** [comment]
@srikwang  should't all report appear on the exact same time if it was periodically ?

**Comment by srikwang** [comment]
I think there may be several problems:
   1. The content of the report sent periodically is actually an old report sent through webhook, and no substantive scanning events have occurred by trivy-operator
   2. Can the time for periodically sending reports be controlled, because the current periodic time is not stable through the observation of the time axis, and there will be certain deviations

**Comment by srikwang** [comment]
> 
Hi
Can the reporting cycle be controlled? At present, I only know that compliance can be controlled

**Comment by srikwang** [comment]
> @srikwang should't all report appear on the exact same time if it was periodically ?
Hi
Can the reporting cycle be controlled? At present, I only know that compliance can be controlled

**Comment by chen-keinan** [comment]
> > @srikwang should't all report appear on the exact same time if it was periodically ?
> 
> Hi Can the reporting cycle be controlled? At present, I only know that compliance can be controlled

@srikwang you refer to compliance report which is generated cron-job based ?

**Comment by srikwang** [comment]
> 

Yeah

**Comment by srikwang** [comment]
> > > @srikwang should't all report appear on the exact same time if it was periodically ?
> > 
> > 
> > Hi Can the reporting cycle be controlled? At present, I only know that compliance can be controlled
> 
> @srikwang you refer to compliance report which is generated cron-job based ?

Yeah

**Comment by chen-keinan** [comment]
@srikwang all other report are generated on event (Create, Update, Delete) base. so it cannot be controlled.

**Comment by srikwang** [comment]
> 

![image](https://github.com/aquasecurity/trivy-operator/assets/129261014/3be0063f-788f-4511-a236-684f6790c612)
As shown in the figure above, there are some past reports issued periodically, can this be controlled?

**Comment by chen-keinan** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/129261014/258750585-3be0063f-788f-4511-a236-684f6790c612.png) As shown in the figure above, there are some past reports issued periodically, can this be controlled?

I do not think its periodically , its event base statistically its appear like it but that way `trivy-operator` reconcile resources (which is the trigger for report generation) is based on event
