### ISSUE TITLE
allow configuring trivy-server securityContext and podSecurityContext

### ISSUE THREAD

**Issue by jemag** [aquasecurity/trivy-operator#1253]
Currently the container and pod securityContext of trivy-server is not configurable:
https://github.com/aquasecurity/trivy-operator//blob/c5d74116e98b2228748d94cf0b76fd9cd80854aa/deploy/helm/templates/trivy-server.yaml#L68-L71
https://github.com/aquasecurity/trivy-operator//blob/c5d74116e98b2228748d94cf0b76fd9cd80854aa/deploy/helm/templates/trivy-server.yaml#L80-L82

It would be nice to:
- Allow users to configure the securityContext and podSecurityContext, just like the other pods.
- Provide good default values to those securityContext.

In regards to the good default values, I am not sure what is currently possible with trivy-server, but it would be nice if we could add the following:
```yaml 
allowPrivilegeEscalation: false
```
and
 ```yaml
  capabilities:
    drop:
    - ALL
  ````
and 
```yaml
 seccompProfile:
    type: RuntimeDefault
```
This would improve the default security out of the box for helm chart users. If the containers currently support it, there isn't much downside to improving the default security.

It also helps clarifying to the end-user that these values are officially supported and will not cause any problem with the containers. By having them already specified, the end-user does not need to do extensive testing to ensure it does not cause any issue.

**Comment by chen-keinan** [comment]
@jemag feel free to pick it up if you have time

**Comment by jemag** [comment]
I likely won't have time for now, but I will ask a colleague to take a look.
