### ISSUE TITLE
Support for the AWS scanner ?

### ISSUE THREAD

**Issue by valorl** [aquasecurity/trivy-operator#1255]
The Trivy Operator CRDs, especially when combined with the adapter for Policy Reporter, provide a nice centralized pane of glass for security posture of the cluster. 

I think even though it's not necessarily scoped to just to a particular Kubernetes cluster, it could be valuable to have the operator be able to run the `trivy aws` scanner and report the results in the same way. This could be only running as part of a "management" cluster or even in every cluster as an indicator of "How safe is the account where this cluster is running?"

**Comment by chen-keinan** [comment]
@valorl  these are interesting thoughts , are you referring to when using eks ?

**Comment by chen-keinan** [comment]
@valorl another thought , as the cluster is a subset of the account , persisting the report should be placed in a higher level to the cluster , no? , wdyt ?

**Comment by valorl** [comment]
@chen-keinan I'm not sure, I think that depends on the use-case. This is why I mentioned the "management cluster". It is indeed a bit strange to be storing results for the entire account in just one cluster, but then again you can have one dedicated cluster for things like that. It's a bit similar to provisioning infra with controllers (e.g. ACK, Crossplane, etc) where it is also the case that the account-wide scope is being handled by _some_ K8S cluster.

**Comment by chen-keinan** [comment]
> @chen-keinan I'm not sure, I think that depends on the use-case. This is why I mentioned the "management cluster" approach. It is indeed a bit strange to be storing results for the entire account in just one cluster, but then again you can have one dedicated cluster for things like that. It's a bit similar to provisioning infra with controllers (e.g. ACK, Crossplane, etc) where it is also the case that the account-wide scope is being handled by _some_ K8S cluster.

Thanks for clarifications , maybe using the `webhook integrations` could leverage aws account results and send it to an external system

**Comment by fengshunli** [comment]
aws can convert accout into token for scanning @chen-keinan

**Comment by raffis** [comment]
Can this be reopened? It would be a nice feature and I am currently looking into how we integrate the aws scanning part. We are 100% running things on kubernetes and the trivy operator should support this use case. Not talking about a webhook integration, it should rather scan aws and store the results in a crd, provide metrics and stuff. 
We integrated trivy nicely now with node and image scanning using this operator and for aws I would now need to create a self baked solution. 
As it was already mentioned above kubernetes is not necessarily just a  "subset" of the aws account. One could operate a kubernetes cluster as the provisioning mechanism for aws things (using crossplane or other similar approaches) so it makes very much sense to store the trivy report for aws in kubernetes itself as well.

I am happy to create a pr if this is something which will be merged.
