### ISSUE TITLE
Docs: Document ServiceMonitor option in Helm Chart better

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/trivy-operator#1266]
I realised that we are not detailing anywhere in the docs how to customize the Helm Chart/the different customization options that are common

Location for the Helm customization:
https://aquasecurity.github.io/trivy-operator/v0.13.2/getting-started/installation/helm/
Also, pointing out Prometheus under integrations -- we used to have a section in previous versions, so I am proposing to add the section again: https://aquasecurity.github.io/trivy-operator/v0.0.8/integrations/lens/
(Not for Lens but for Prometheus)

**Comment by AnaisUrlichs** [comment]
Hmm, the Helm Chart customisation is detailed here: https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm
So maybe just pointing that out more in the docs is enough under the Helm installation + separate integration section in the docs for Prometheus?

**Comment by AnaisUrlichs** [comment]
Actually, the ServiceMonitor option is only shared in the valyes.yaml file itself, so the customisation options have to be updated as well

**Comment by chen-keinan** [comment]
@AnaisUrlichs service monitor options will be updated under `docs` section next to lens ?
