### ISSUE TITLE
Cannot authenticate trivy operator to private docker registry

### ISSUE THREAD

**Issue by madhavansri2022** [aquasecurity/trivy-operator#1279]
### Discussed in https://github.com/aquasecurity/trivy-operator/discussions/1260

<div type='discussions-op-text'>

<sup>Originally posted by **madhavansri2022** June  5, 2023</sup>
I followed the docs(https://aquasecurity.github.io/trivy-operator/v0.5.0/tutorials/private-registries/) for authenticating our private registry to scan images. Only the first option seems to work.But we are not comfortable running Trivy as root. The second,third and fourth options seem to get ACCESS DENIED error. I could see that error in the logs.
Logs:
"Error","status.message":"time\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image ([registry.private.com/project:4**7](http://registry.private.com/project:4**7)): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* GET https://gitlab.private.com/jwt/auth?scope=repository%3Arepo%2Fproject%3Apull&service=container_registry: DENIED: access forbidden\n\n\n"
Note: I did try above options with the recommended token format. Also we have a gitlab registry for our images</div>

**Comment by chen-keinan** [comment]
@madhavansri2022 can you please share more info on the k8s env. you are using .
- is it cloud managed or onPrem? 
- are you using imagePull Secrets in pods or services account?

**Comment by chen-keinan** [comment]
@Kaktor can you please add more info how you are setting for [private registries](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/private-registries/) ?

**Comment by Kaktor** [comment]
Im using trivy just for scanning container images inside the cluster ( `trivy.command.command: image` ).
The settings for private registry done with `trivy-operator.image.registry`  and `trivy.image.registry` - what else information is necessary?

**Comment by chen-keinan** [comment]
> Im using trivy just for scanning container images inside the cluster ( `trivy.command.command: image` ). The settings for private registry done with `trivy-operator.image.registry` and `trivy.image.registry` - what else information is necessary?

The setting you mention is for downloading `trivy-operator` and `trivy` images from private registries but you'll need to follow this [tutorials](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/private-registries/) if the images you wish to scan are stored in private registries

**Comment by Kaktor** [comment]
> > Im using trivy just for scanning container images inside the cluster ( `trivy.command.command: image` ). The settings for private registry done with `trivy-operator.image.registry` and `trivy.image.registry` - what else information is necessary?
> 
> The setting you mention is for downloading `trivy-operator` and `trivy` images from private registries but you'll need to follow this [tutorials](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/private-registries/) if the images you wish to scan are stored in private registries

i dont want to access the container registry with trivy - i simply want to run the scan inside my cluster, thats why im using the default mode `trivy.command.command: image`

**Comment by chen-keinan** [comment]
> i dont want to access the container registry with trivy - i simply want to run the scan inside my cluster, thats why im using the default mode `trivy.command: image`

this command download images from registry , if you want scan images on k8s node fs you'll have to use
`trivy.command: filesystem` option one in this [tutorials](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/private-registries/)

**Comment by madhavansri2022** [comment]
> 

@chen-keinan 
Sure. We are using k8s in cloud and we orchestrate using kOps. And yes we do use ImagePullSecrets on pod level.

**Comment by madhavansri2022** [comment]
I believe I tried something similar but in yaml
apiVersion: v1
data:
  .dockercfg: <<encoded({"auths":{"<<registry url>>":{"auth":"encoded(account:password)"}}}%)>>
kind: Secret
metadata:
  name: <<name>>
  namespace: <<namespace>>
type: kubernetes.io/dockercfg

**Comment by chen-keinan** [comment]
> I believe I tried something similar but in yaml apiVersion: v1 data: .dockercfg: <encoded({"auths":{"":{"auth":"encoded(account:password)"}}}%)> kind: Secret metadata: name: namespace: type: kubernetes.io/dockercfg

at the end trivy need to authenticate with credentials ,
if you can pull images with `accout:password` then it should be good for trivy otherwise you'll have to set it up with `user:password`

**Comment by chen-keinan** [comment]
Secert for app should be only on app namespace , trivy-system namespace is used for operator usage only.

**Comment by Kaktor** [comment]
> > i dont want to access the container registry with trivy - i simply want to run the scan inside my cluster, thats why im using the default mode `trivy.command: image`
> 
> this command download images from registry , if you want scan images on k8s node fs you'll have to use `trivy.command: filesystem` option one in this [tutorials](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/private-registries/)

omg :D i missunderstood the manual! thank you

**Comment by VF-mbrauer** [comment]
We scan Private Registries (AWS ECR) with the help of Trivy-Operator already. We use the Instance-Profile to do STS-Assume and get a Role with ECR Read permission. To get it properly working created some time back a PR https://github.com/aquasecurity/trivy-operator/pull/186

**Comment by chen-keinan** [comment]
@madhavansri2022 thanks for the update
