### ISSUE TITLE
Coincidental Replicaset(s) are not scanned and added to vulnerability list

### ISSUE THREAD

**Issue by VF-mbrauer** [aquasecurity/trivy-operator#1318]
**What steps did you take and what happened:**

On one of our clusters, we have the issue that in some namespaces specific PODs (replica set) are not properly scanned.
Some PODs in a namespace are scanned and some others are not. Even in the same Namespace replicaSets are not scanned.
So, we found no indication between 1 replicaset which is working, and the other replicaset which is NOT working.

**What did you expect to happen:**
All PODs (replicaset) should be properly scanned inside each of the namespaces.

**Anything else you would like to add:**

Deinstallation and Re-Installation of Trivy-Operrator via HELM chart has also not changed the situation.
LogFile in Debug Mode with the Info about the POD (replicaSet) which was failing:
```
1.6866599947487166e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "Pod", "name": "{{ POD-name}}-7cf47f76dc-pxlpg"}
1.6866599947487452e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring managed pod    {"kind": "Pod", "name": "{{ POD-name}}-7cf47f76dc-pxlpg", "controllerKind": "ReplicaSet", "controllerName": "{{ POD-name}}-7cf47f76dc"}
1.6866599962622077e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "{{ POD-name}}-7cf47f76dc"}
1.6866599962627e+09     DEBUG   reconciler.vulnerabilityreport  Scan job already exists {"kind": "ReplicaSet", "name": "{{ POD-name}}-7cf47f76dc", "podSpecHash": "bb6696d6c", "job": "trivy-system/scan-vulnerabilityreport-5456688f94"}
```

**Environment:**

- Trivy-Operator version 0.14.1
- Kubernetes version 1.23

**Comment by chen-keinan** [comment]
@VF-mbrauer can we close this issue ?

**Comment by chen-keinan** [comment]
closing following to @VF-mbrauer confirmation

**Comment by pandakkkk** [comment]
Sorry... What is the solution here?

**Comment by chen-keinan** [comment]
@pandakkkk it was context timeout issue , as it took too long to scan image:
[scanJobTimeOut](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L48) and [trivy timeout](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L317)
