### ISSUE TITLE
Multiple trivy server replicas

### ISSUE THREAD

**Issue by mazay** [aquasecurity/trivy-operator#1321]
I'd like to be able to deploy multiple trivy server replicas for redundancy.

The change seems to be fairly simple:
1. add a new variable for setting the desired number of trivy server replicas
2. change [this line](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/trivy-server.yaml#L35) to something like - `replicas: {{ .Values.trivy.replicas | default 1 }}`

Please let me know if this would be accepted and I gladly file a PR.

**Comment by chen-keinan** [comment]
@mazay sure it is reasonable , feel free to submit a PR
