### ISSUE TITLE
Use automaxprocs to automatically set GOMAXPROCS

### ISSUE THREAD

**Issue by jon-rei** [aquasecurity/trivy-operator#1360]
# Description

With a large number of CPU threads on nodes, the trivy operator is throttled.
We have implemented a solution with kustomize to add the `GOMAXPROCS` environment variable with the appropriate CPU limit to avoid throttling. We would like to avoid this workaround and not use kustomize.

# Possible solution

Use https://github.com/uber-go/automaxprocs to "Automatically set `GOMAXPROCS` to match Linux container CPU quota."

**Comment by chen-keinan** [comment]
@jon-rei happy to have this change , feel free to raise a PR
