### ISSUE TITLE
Trivy-operator IAM serviceAccount unexpected status code 401 Unauthorized to aws ECR

### ISSUE THREAD

**Issue by nikolai-ivanisenko** [aquasecurity/trivy-operator#1365]
hi! I followed this guide https://aquasecurity.github.io/trivy-operator/v0.5.0/vulnerability-scanning/managed-registries/#amazon-elastic-container-registry-ecr, by using of terraform created iam role, associated it with service account by using oidc provider (AWS EKS), policy attached to ima role have all required permissions. In pod i can see all atributes of aws iam connectivity:
```
k describe po addon-trivy-operator-85697f87c6-chbqb  -n addon
...
Environment
      AWS_STS_REGIONAL_ENDPOINTS:      regional
      AWS_DEFAULT_REGION:                         us-west-1
      AWS_REGION:                                           us-west-1.
      AWS_ROLE_ARN:                            arn:aws:iam::123456789123:role/trivy-operator-role
      AWS_WEB_IDENTITY_TOKEN_FILE:        /var/run/secrets/eks.amazonaws.com/serviceaccount/token
Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-slzpc (ro)
...
```
In scan-vulnerabilityreport i can find the same configuration, but i have an error in scan-vulnerabilityreport-* pods:
```
{"level":"error","ts":"... image scan error: scan error: scan failed: failed analysis: unable to get missing layers: unable to fetch missing layers: twirp error permission_denied: Error from intermediary with HTTP status code 403 \"Forbidden\ ...}
```
I have separately installed trivy server new the operator, it is working in clientServer mode
What i have missed? Thx for the help

- Trivy-Operator version (use `trivy-operator version`): 0.14.1
- Kubernetes version (use `kubectl version`): 1.23 AWS EKS
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Linux

**Comment by chen-keinan** [comment]
@nikolai-ivanisenko can you please share trivy-operator config-maps

**Comment by nikolai-ivanisenko** [comment]
gm @chen-keinan
i have deleted it and returned to use a starboard, but i'd like to install it anyway.

# Source: trivy-operator/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator
  namespace: default
  labels:
    helm.sh/chart: trivy-operator-0.14.1
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
data:
  nodeCollector.volumes: "[{\"hostPath\":{\"path\":\"/var/lib/etcd\"},\"name\":\"var-lib-etcd\"},{\"hostPath\":{\"path\":\"/var/lib/kubelet\"},\"name\":\"var-lib-kubelet\"},{\"hostPath\":{\"path\":\"/var/lib/kube-scheduler\"},\"name\":\"var-lib-kube-scheduler\"},{\"hostPath\":{\"path\":\"/var/lib/kube-controller-manager\"},\"name\":\"var-lib-kube-controller-manager\"},{\"hostPath\":{\"path\":\"/etc/systemd\"},\"name\":\"etc-systemd\"},{\"hostPath\":{\"path\":\"/lib/systemd\"},\"name\":\"lib-systemd\"},{\"hostPath\":{\"path\":\"/etc/kubernetes\"},\"name\":\"etc-kubernetes\"},{\"hostPath\":{\"path\":\"/etc/cni/net.d/\"},\"name\":\"etc-cni-netd\"}]"
  nodeCollector.volumeMounts: "[{\"mountPath\":\"/var/lib/etcd\",\"name\":\"var-lib-etcd\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kubelet\",\"name\":\"var-lib-kubelet\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kube-scheduler\",\"name\":\"var-lib-kube-scheduler\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kube-controller-manager\",\"name\":\"var-lib-kube-controller-manager\",\"readOnly\":true},{\"mountPath\":\"/etc/systemd\",\"name\":\"etc-systemd\",\"readOnly\":true},{\"mountPath\":\"/lib/systemd/\",\"name\":\"lib-systemd\",\"readOnly\":true},{\"mountPath\":\"/etc/kubernetes\",\"name\":\"etc-kubernetes\",\"readOnly\":true},{\"mountPath\":\"/etc/cni/net.d/\",\"name\":\"etc-cni-netd\",\"readOnly\":true}]"
  scanJob.podTemplateContainerSecurityContext: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true}"
  scanJob.compressLogs: "true"
  vulnerabilityReports.scanner: "Trivy"
  configAuditReports.scanner: "Trivy"
  compliance.failEntriesLimit: "10"
  report.recordFailedChecksOnly: "true"
  node.collector.imageRef: "ghcr.io/aquasecurity/node-collector:0.0.6"
---
# Source: trivy-operator/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-trivy-config
  namespace: default
  labels:
    helm.sh/chart: trivy-operator-0.14.1
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
data:
  trivy.repository: "123456789123.dkr.ecr.us-west-2.amazonaws.com/aquasec/trivy"
  trivy.tag: "0.42.0"
  trivy.additionalVulnerabilityReportFields: ""
  trivy.httpProxy: ""
  trivy.httpsProxy: ""
  trivy.noProxy: ""
  trivy.severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  trivy.slow: "true"
  trivy.dbRepository: "ghcr.io/aquasecurity/trivy-db"
  trivy.javaDbRepository: "ghcr.io/aquasecurity/trivy-java-db"
  trivy.command: "image"
  trivy.dbRepositoryInsecure: "false"
  trivy.useBuiltinRegoPolicies: "true"
  trivy.supportedConfigAuditKinds: "Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota"
  trivy.ignoreUnfixed: "true"
  trivy.timeout: "5m0s"
  trivy.mode: "ClientServer"
  trivy.serverURL: "http://addon-trivy-server.addon:4954"
  trivy.resources.requests.cpu: "100m"
  trivy.resources.requests.memory: "100M"
  trivy.resources.limits.cpu: "500m"
  trivy.resources.limits.memory: "500M"
---
# Source: trivy-operator/templates/policies.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-policies-config
  namespace: default
  labels:
    helm.sh/chart: trivy-operator-0.14.1
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
data:
# example
# policy.my_policy.kinds: Workload
# policy.my_policy.rego: "package builtin.kubernetes.KSV008
#
# import data.lib.kubernetes
# import data.lib.result
#
# default failHostIPC = false
#
# __rego_metadata__ := {
#	 "id": "KSV008",
#	 "avd_id": "AVD-KSV-0008",
#	 "title": "Access to host IPC namespace",
#	 "short_code": "no-shared-ipc-namespace",
#	 "version": "v1.0.0",
#	 "severity": "HIGH",
#	 "type": "Kubernetes Security Check",
#	 "description": "Sharing the host’s IPC namespace allows container processes to communicate with processes on the host.",
#	 "recommended_actions": "Do not set 'spec.template.spec.hostIPC' to true.",
#	 "url": "https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline",
#}
#
# __rego_input__ := {
#	 "combine": false,
#	 "selector": [{"type": "kubernetes"}],
# }
#
## failHostIPC is true if spec.hostIPC is set to true (on all resources)
# failHostIPC {
#	 kubernetes.host_ipcs[_] == true
# }
#
#deny[res] {
#	failHostIPC
#	msg := kubernetes.format(sprintf("%s '%s' should not set 'spec.template.spec.hostIPC' to true", [kubernetes.kind, kubernetes.name]))
#	res := result.new(msg, input.spec)
#}"

**Comment by chen-keinan** [comment]
@nikolai-ivanisenko  are you using trivy-operator [built-in server](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L85) ?

**Comment by nikolai-ivanisenko** [comment]
right now i have mostly 403 problem and i guess it relates to ecr auth but for starboard i have the same configuration
i have separated trivy server deployment thats why i dont want to use buildin server but i have not configuration, which is related to auth.

configmap of existing trivy server

apiVersion: v1
data:
  HTTP_PROXY: http://proxy.dev.sirius.tlzproject.com:80
  HTTPS_PROXY: http://proxy.dev.sirius.tlzproject.com:80
  NO_PROXY: ...,dkr.ecr.eu-west-2.amazonaws.com,... (LIST of PROXIES)
  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
  TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db
  TRIVY_DEBUG: "false"
  TRIVY_IGNORE_UNFIXED: "true"
  TRIVY_LISTEN: 0.0.0.0:4954
  TRIVY_SKIP_UPDATE: "false"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: addon-trivy-server
    meta.helm.sh/release-namespace: addon
  creationTimestamp: "2023-07-15T09:09:59Z"
  labels:
    app.kubernetes.io/instance: addon-trivy-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/version: latest
    helm.sh/chart: trivy-server-0.4.16
  name: addon-trivy-server
  namespace: addon
  resourceVersion: "853752709"
  uid: 3c9b0396-77d6-4b3d-9864-337289cc4e45
  
  secret:
  
  apiVersion: v1
data:
  GITHUB_TOKEN: ""
  TRIVY_PASSWORD: ""
  TRIVY_TOKEN: ""
  TRIVY_USERNAME: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: addon-trivy-server
    meta.helm.sh/release-namespace: addon
  creationTimestamp: "2023-07-15T09:09:59Z"
  labels:
    app.kubernetes.io/instance: addon-trivy-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/version: latest
    helm.sh/chart: trivy-server-0.4.16
  name: addon-trivy-server
  namespace: addon
  resourceVersion: "853522193"
  uid: 99225926-6f9a-4091-b786-88ea77da33ab
type: Opaque
  
  logs of trivy server:
  
2023-07-18T00:18:27.622Z	WARN	'TRIVY_SKIP_UPDATE' is deprecated. Use 'TRIVY_SKIP_DB_UPDATE' instead.
2023-07-18T00:18:27.633Z	INFO	Need to update DB
2023-07-18T00:18:27.633Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-07-18T00:18:27.633Z	INFO	Downloading DB...
2023-07-18T00:18:33.256Z	INFO	Listening 0.0.0.0:4954...

**Comment by nikolai-ivanisenko** [comment]
i also tried to add ecr:* to iam role and all read/download options to ecr repo policy but it still shows the same error:
`{"level":"error","ts":"... image scan error: scan error: scan failed: failed analysis: unable to get missing layers: unable to fetch missing layers: twirp error permission_denied: Error from intermediary with HTTP status code 403 \"Forbidden\ ...}`

**Comment by chen-keinan** [comment]
@nikolai-ivanisenko could be related to setting , how are you running the server ? helm ? 
can you try running operator with `built-in server` just to confirm if it is env. setting issue
