### ISSUE TITLE
Turning off exposed secret scanner causes constant rescanning

### ISSUE THREAD

**Issue by evandeaubl** [aquasecurity/trivy-operator#1369]
**What steps did you take and what happened:**

1. Deployed trivy-operator using Helm chart, setting `exposedSecretScannerEnabled` to `false`.
2. Workloads in cluster were being constantly rescanned, even with vulnerability reports within the TTL.

**What did you expect to happen:**

1. Workloads to be scanned once per TTL period.

**Anything else you would like to add:**

From looking at the code, it looks like when the controller determines whether it should scan a workload, it calls `hasReports` here: https://github.com/aquasecurity/trivy-operator/blob/7a8ca537166b95c9b0554cca4636bea0aa01d1d5/pkg/vulnerabilityreport/controller/workload.go#L149

Looking at the implementation of that method: https://github.com/aquasecurity/trivy-operator/blob/7a8ca537166b95c9b0554cca4636bea0aa01d1d5/pkg/vulnerabilityreport/controller/helper.go#L13

It looks like that method checks that the workload has **both** vulnerability and exposed secret reports regardless of settings, so turning off exposed secret scanning results in that method always returning `false`, triggering constant rescans.

Switching `exposedSecretScannerEnabled` back to `true` fixes the issue, but it causes the scan time of some of our images to increases by orders of magnitude, hence our desire to turn it off.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.14.0
- Kubernetes version (use `kubectl version`): 1.24.2
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): CentOS 7

**Comment by chen-keinan** [comment]
@evandeaubl thanks for the feedback , you can raise a PR if you have time, if not let me know I'll take a look at it later on
