### ISSUE TITLE
Trivy-Operator detects very few vulnerabilities when compared to trivy-CLI

### ISSUE THREAD

**Issue by rammanoj** [aquasecurity/trivy-operator#1379]
I have installed Trivy CLI and tested it out with a few images. It's definitely detecting a high number of vulnerabilities for various tools. Thanks a lot for all the support team! 

However, when I tried trivy-operator, it's not even detecting half of the vulnerabilities that trivy detected. I am not exactly sure what is the exact cause of this issue!

**Trivy Installation & Version:**

Installed through [this README](https://github.com/aquasecurity/trivy#get-trivy) 
Command: `brew install trivy`
Version: 0.43.1

**Trivy Operater Installation & Version:**
Installed through [this document](https://aquasecurity.github.io/trivy-operator/v0.15.0/getting-started/installation/helm/)
Command: ```helm install trivy-operator ./deploy/helm \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true"```
Version: 0.15.0

I've compared with 3 images (nginx:latest, node:latest and node:18.13-buster). 

**Trivy Output for each of images**:
nginx:latest --> 
![image](https://github.com/aquasecurity/trivy-operator/assets/21082378/3f40d1b1-9224-4dad-8018-6101b9421c28)

node:latest -->
![image](https://github.com/aquasecurity/trivy-operator/assets/21082378/62125da7-fd7a-4a2c-92b4-83749b7fda46)

node:18.13-buster -->
![image](https://github.com/aquasecurity/trivy-operator/assets/21082378/1ecfc17c-ef8c-49a1-979d-660f7404e581)

**Trivy Operator Output for each of the images:**
![image](https://github.com/aquasecurity/trivy-operator/assets/21082378/bd6a1ad2-00ce-42be-89aa-82e6c182eec3)

I couldn't find any changes in the trivia-operator default configuration that is causing this change. Is this due to the database refresh or something?

Any help is appreciated!

**Comment by rammanoj** [comment]
+ @chen-keinan

**Comment by chen-keinan** [comment]
@rammanoj I think I found the issue if you run trivy with `--ignore-unfixed` flag you'll get the same results :
```
trivy image --ignore-unfixed  nginx:latest
```

**Comment by rammanoj** [comment]
Thanks @chen-keinan, it worked. 

Shouldn't there be an intimation in the documentation saying this? I feel having an intimation would really help. I am happy to make a PR for it.
