### ISSUE TITLE
server returned HTTP status 500 Internal Server Error

### ISSUE THREAD

**Issue by win5923** [aquasecurity/trivy-operator#1383]
**What steps did you take and what happened:**

Hi, after I upgraded `trivy-operator` from `0.14.1` to `0.15.0`, I noticed that Prometheus cannot scrape metrics from `trivy-operator` anymore. Upon checking the endpoints, I found the error message `server returned HTTP status 500 Internal Server Error.'`However, when I rolled back to version `0.14.1`, everything was working fine.

![image](https://github.com/aquasecurity/trivy-operator/assets/56353753/17cd4142-a677-452c-b05f-4fcd8c779774)

**What did you expect to happen:**

endpoints should be up with v0.15.0.

**Anything else you would like to add:**

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.15.0
- Kubernetes version (use `kubectl version`): 1.27.1
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 20.04.6 LTS

**Comment by chen-keinan** [comment]
@win5923 is this still an issue with v0.15.0 ?

**Comment by win5923** [comment]
yes, But I found #1380  repetitive, so I closed it.
