### ISSUE TITLE
helm chart 0.15.1 is not available in the chart repository

### ISSUE THREAD

**Issue by nbarnum** [aquasecurity/trivy-operator#1391]
**What steps did you take and what happened:**

The latest helm chart version in the aquasecurity/helm-charts registry is still 0.15.0.

Steps to reproduce:

1. Add aquasecurity helm repository

```
$ helm repo add aquasecurity https://aquasecurity.github.io/helm-charts/
"aquasecurity" has been added to your repositories
```

2. Make sure repository is updated

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "aquasecurity" chart repository
Update Complete. ⎈Happy Helming!⎈
```

3. Check latest version of trivy-operator helm chart in the repository

```
$ helm search repo aquasecurity/trivy-operator

NAME                            CHART VERSION   APP VERSION     DESCRIPTION
aquasecurity/trivy-operator     0.15.0          0.15.0          Keeps security report resources updated
```

**What did you expect to happen:**

GitHub Action [Publish Helm chart #89](https://github.com/aquasecurity/trivy-operator/actions/runs/5670496262) should have updated the helm repository index.yaml.

**Anything else you would like to add:**

It appears the helm chart 0.15.1 upload worked fine, however the [Index helm chart](https://github.com/aquasecurity/trivy-operator/actions/runs/5670496262/job/15365516834#step:12:20) task incorrectly indicated that the old index.yaml was already up to date:

```
Run ./cr index -o aquasecurity -r helm-charts -c https://aquasecurity.github.io/helm-charts/ -i index.yaml
Using existing index at index.yaml
Index index.yaml did not change
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.15.1
- Kubernetes version (use `kubectl version`): 1.21.14
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Amazon Linux 2

**Comment by rtalipov** [comment]
Have the same issue with Postee helm chart
```
helm search repo aquasecurity/postee --version v2.13.0

No results found
```
While v2.13.0 was released a week ago. Looks common issue.

**Comment by chen-keinan** [comment]
@nbarnum @rtalipov  thanks for reporting this issue. I have republished it again. should be ok now

**Comment by nbarnum** [comment]
Thank you for the fast response @chen-keinan, I've confirmed that I can now install the trivy-operator chart at v0.15.1
