### ISSUE TITLE
Special flag for new Vulnerabilities

### ISSUE THREAD

**Issue by humpalu** [aquasecurity/trivy-operator#1397]
Im using Trivy Operator since 3-4 months and everything looks good.
But I have to send alerts to my team if a NEW Critical vulnerability arrive.

I tried to use Postee what is a great tool but its not able to see which Vulnerability is new and which one is old.

It looks for the Trivy Operator sending the results via webhook like a machine gun  but would be good If I can compare the new Vulnerabilities with the old ones or having a solution for that.

Thats why I would ask a "new" flag on newly discovered vulnerabilities.

BTW if someone already solved that question, feel free to share.

**Comment by chen-keinan** [comment]
@tothger if you get [indication](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/webhook/webhookreporter.go#L94) if a report has been delete via webhook , will it help ?

**Comment by tothger** [comment]
Basically Im looking in CVE level. 
Report level is not ok because ,multiple pods, replicasets can have the same CVE.
I would like to know if a new critical cve bumped up in my cluster
