### ISSUE TITLE
Trivy-Operator Pod 0.15.1 Scan Error

### ISSUE THREAD

**Issue by diegoballen** [aquasecurity/trivy-operator#1400]
**What steps did you take and what happened:**

I updated the Trivy Operator from the version 0.14.1 to 0.15.1 in my AKS cluster. After the update I found an error (see the last line of the attached log file) in the Trivy-Operator Pod related to the scan process.

**What did you expect to happen:**
To see no error as with the version 0.14.1.

**Anything else you would like to add:**
In the log file there are some other records  which looks suspicious and were not present with the version 0.14.1 (look for the string "DeltaFIFO Pop Process") 

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (0.15.1)
- Kubernetes version (Client Version: v1.27.3, Kustomize Version: v5.0.1, Server Version: v1.26.3)
- OS (Linux Container: "Alpine Linux v3.17")
[trivy-operator.txt](https://github.com/aquasecurity/trivy-operator/files/12193919/trivy-operator.txt)

**Comment by chen-keinan** [comment]
@diegoballen I do not think this issue related to v0.15.1  , the error related to load on controller manager queue. 
can you try restart the trivy-operator ?

**Comment by diegoballen** [comment]
@chen-keinan , I followed the steps. Before there was only one error at the end of the  pod log file. Now 3 more are visible.
However, the scanning is being made in other resources of the cluster. I see in my Grafana dashboard how the detected vulnerabilities are  being recognized.

I really cannot tell if this is an issue of our environment or the 0.15.1 version. As far as I know, our environment has have significant changes. These errors were not present with the version 0.14.1. 

Thank you for your help.
[trivy-operator.txt](https://github.com/aquasecurity/trivy-operator/files/12213774/trivy-operator.txt)

**Comment by chen-keinan** [comment]
> @chen-keinan , I followed the steps. Before there was only one error at the end of the pod log file. Now 3 more are visible (check the last 4 lines of the attached log file). However, the scanning is being made in other resources of the cluster. I see in my Grafana dashboard how the detected vulnerabilities are being recognized.
> 
> I really cannot tell if this is an issue of our environment or the 0.15.1 version. As far as I know, our environment has have significant changes. These errors were not present with the version 0.14.1.
> 
> Thank you for your help. [trivy-operator.txt](https://github.com/aquasecurity/trivy-operator/files/12213774/trivy-operator.txt)

I think its look ok now.

the error you see is related to authentication:
```
reason":"Error","status.message":"2023-07-31T09:33:54.334Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (mcr.microsoft.com/oss/calico/windows-upgrade:v3.24.0): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* GET https://mcr.microsoft.com/v2/oss/calico/windows-upgrade/manifests/v3.24.0: MANIFEST_UNKNOWN: manifest tagged by \"v3.24.0\" is not found; map[Tag:v3.24.0]\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/reconcile/reconcile.go:103\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
{"level":"error","ts":"2023-07-31T09:35:03Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-69dffb8544","container":"mrcmodule-liquibase","status.reason":"Error","status.message":"2023-07-31T09:34:37.789Z\t
```
when trivy unable to authenticate and download image from private registry

**Comment by chen-keinan** [comment]
@diegoballen any additional info is required or we can close this issue ?

**Comment by diegoballen** [comment]
@chen-keinan , we are checking this issue in our environment. In the mean time I think you can close this issue.

**Comment by chen-keinan** [comment]
Closing following to confirmation from @diegoballen

**Comment by azaborovskyi** [comment]
@diegoballen Did you manage to solve the problem? I have a similar situation after updating to 0.15.1, scanning worked on the previous version (0.14.1)

**Comment by chen-keinan** [comment]
> @diegoballen Did you manage to solve the problem? I have a similar situation after updating to 0.15.1, scanning worked on the previous version (0.14.1)

@azaborovskyi dis you follow my instruction above ?

**Comment by azaborovskyi** [comment]
@chen-keinan  Yes, I am getting an authentication related error in private ACR UNAUTHORIZED: authentication required; I use managed identity for AKS node pool for authorization in ACR, the previous version worked without problems.

**Comment by chen-keinan** [comment]
@azaborovskyi how you configure `trivy-operator` to authenticate with private registries ?  image pull secrets ?

**Comment by diegoballen** [comment]
@azaborovskyi , we still have the issue. We want to check if this is a problem related with our certificates. As soon as I have further information from my colleagues, I can let you guys know. 

I do not recall having this issue with the 0.14.1 version. However, I cannot guarantee that our environment is the same as when I used the 0.14.0 version. That is why we will check possible issues for the certificates of the  images which cannot be scanned.
