### ISSUE TITLE
Missing Metric "metricsExposedSecretInfo" in Trivy - Operator 0.15.1

### ISSUE THREAD

**Issue by diegoballen** [aquasecurity/trivy-operator#1401]
**What steps did you take and what happened:**

I installed the Trivy-Operator 0.15.1 and configured in the values.yaml file of the Helmchart the following parameters:
metricsVulnIdEnabled: true
metricsExposedSecretInfo: true
metricsConfigAuditInfo: true
metricsRbacAssessmentInfo: true

I see in Grafana all the expected metrics but the "metricsExposedSecretInfo" metric.

**What did you expect to happen:**

To see this metric in Grafana along the others.

**Anything else you would like to add:**
From the metric "trivy_image_exposedsecrets" I see that the issues found are actually 0. However, I would expect to see the metric "metricsExposedSecretInfo" as well.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Trivy-Operator version (0.15.1)
Kubernetes version (Client Version: v1.27.3, Kustomize Version: v5.0.1, Server Version: v1.26.3)
OS (Linux Container: "Alpine Linux v3.17")

**Comment by chen-keinan** [comment]
@diegoballen just tested this issue and find it working as expected.
In order for `exposedsecrets_info metric` to show it is require for report to have data. see below `Critical` and `Low`:
```
NAMESPACE            NAME                                                   REPOSITORY                       TAG                  SCANNER   AGE     CRITICAL   HIGH   MEDIUM   LOW
default              pod-tt-reg-test                                        chenkeinan/trivy                 exposesecret         Trivy     23s     1          0      0        1
```

**Comment by chen-keinan** [comment]
@diegoballen I think this issue can be closed , please confirm.

**Comment by chen-keinan** [comment]
@diegoballen any update ?

**Comment by diegoballen** [comment]
Hi @chen-keinan, we can not test at the moment since we do not have any exposed secrets. We are planning to test this at a later time.

**Comment by chen-keinan** [comment]
@diegoballen closing this issue for now, as there is nothing I can do with it , if you think that the issue still stand. you can re-open it
