### ISSUE TITLE
DB download error: oci download error x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by TDiazSouble** [aquasecurity/trivy-operator#1414]
Hi team, im having a problem with scans. Im getting:

ERROR    Unable to initialize the Java DB: Java DB update failed: Java DB update error: DB download error: oci download error: failed to fetch the layer: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:09f42d20aa7bb5301b163c16f6b05d88b3359e852b81eea154e453fa12f8b269?se=2023-07-20T18%3A05%3A00Z&sig=A2BTQINzQ3bQBm1zCNphON3eJkFbwUR5nAdJOEYoj1A%3D&sp=r&spr=https&sr=b&sv=2019-12-12": x509: certificate signed by unknown authority

Im currently using trivy-operator lastest version, installed with helm. 
I have enabled ghcr.io and pkg-containers.githubusercontent.com in my firewall. I have tried adding it to "insecureRegistries", but still cant resolve this issue. 
I have my proxy configured, increased timeout, dbRepositoryInsecure: "true", standalone, and command: image.

Other containers are scanned correctly, the error only appears when the jobs tries to download the db and does no use the "insecure" flag.

Environment:

- CRI-O
- kubernetes 1.24.1
- Only way of getting internet access is through the proxy

**Comment by chen-keinan** [comment]
@TDiazSouble can you please share trivy-operator config maps ?

**Comment by TDiazSouble** [comment]
This is 

Name:         trivy-operator-trivy-config
Namespace:    trivy-system
Labels:       app.kubernetes.io/instance=trivy-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=trivy-operator
              app.kubernetes.io/version=0.15.1
              helm.sh/chart=trivy-operator-0.15.1
Annotations:  meta.helm.sh/release-name: trivy-operator
              meta.helm.sh/release-namespace: trivy-system

Data
====
trivy.javaDbRepository:
----
ghcr.io/aquasecurity/trivy-java-db
trivy.mode:
----
Standalone
trivy.slow:
----
true
trivy.tag:
----
0.43.1
trivy.httpProxy:
----
http://user:pass@proxy.company.com:1234
trivy.repository:
----
ghcr.io/aquasecurity/trivy
trivy.timeout:
----
15m0s
trivy.additionalVulnerabilityReportFields:
----

trivy.dbRepository:
----
ghcr.io/aquasecurity/trivy-db
trivy.httpsProxy:
----
http://user:pass@proxy.company.com:1234
trivy.ignoreUnfixed:
----
true
trivy.noProxy:
----
localhost, 127.0.0.1, 10.96.0.1, .company.com
trivy.command:
----
image
trivy.severity:
----
UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
trivy.supportedConfigAuditKinds:
----
Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
trivy.useBuiltinRegoPolicies:
----
true
trivy.dbRepositoryInsecure:
----
true

BinaryData
====

Events:  <none>

**Comment by TDiazSouble** [comment]
I found a workaround. The problem was our certificate. I have added de directory of the certificate in 
`sslCertDir:`
But this didnt work, so i added it manually by creating a custom trivy image. This is the dockerfile i have created:

```
FROM ghcr.io/aquasecurity/trivy:0.43.1

USER root

# To be able to download `ca-certificates` with `apk add` command
COPY myCompany.crt /root/my-root-ca.crt
RUN cat /root/my-root-ca.crt >> /etc/ssl/certs/ca-certificates.crt

# Add again root CA with `update-ca-certificates` tool
RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*
COPY myCompany.crt/usr/local/share/ca-certificates
RUN update-ca-certificates

RUN apk --no-cache add curl

```

**Comment by chen-keinan** [comment]
@TDiazSouble As you put at the description the issue is with downloading the `trivy-java-db` , currently `trivy-java-db` is download by `scanning container` and not `init container` so `dbRepositoryInsecure` has no affect on it. I have created a PR which include `dbRepositoryInsecure` if configure in the scanning container
