### ISSUE TITLE
Trivy-Operator: SBOM

### ISSUE THREAD

**Issue by Twicefan98** [aquasecurity/trivy-operator#143]
Are there any plans for SBOM report generation in the future?

**Comment by chen-keinan** [comment]
@Twicefan98 thank you for raising it, its definitely something we are planning to look at

**Comment by chen-keinan** [comment]
@mcbenjemaa I will include it within next release

**Comment by mcbenjemaa** [comment]
Does this will allow pushing to Dependency track? 
However, Maybe I can help if you want.

**Comment by chen-keinan** [comment]
@mcbenjemaa  I assume it can be pushed to Dependency track  via [webhook integration](https://aquasecurity.github.io/trivy-operator/v0.14.0/tutorials/integrations/webhook/)

**Comment by mcbenjemaa** [comment]
I'm not sure if this accepts Sbom format.

**Comment by chen-keinan** [comment]
> I'm not sure if this accepts Sbom format.

there are two option:
- I think it can be done via postee it might need few tweaks on postee side
- or just use the webhook url to pass it to any external app.

but I'm almost sure it can be done via postee

**Comment by Ind0mitable** [comment]
Following this thread. Just to confirm - SBOM generation is going to be added on the next release? I have been attempting to add that functionality to the trivy-operator with no success. Thanks.

**Comment by chen-keinan** [comment]
@Ind0mitable yes its on the plan for next release

**Comment by kfox1111** [comment]
Is this feature generating sboms or pulling them that already exist attached to a container image? Are then images scanned based on the sbom report, or independent of it?

**Comment by chen-keinan** [comment]
> Is this feature generating sboms or pulling them that already exist attached to a container image? Are then images scanned based on the sbom report, or independent of it?

@kfox1111 thats a good point.  currently , scanning and sbom generation happen in the same go , with the same effort that we use to have for scanning no additiotnal effort.

there is plan to add scanning support by sbom in client server mode

**Comment by MPV** [comment]
> Is this feature generating sboms or pulling them that already exist attached to a container image?

I raised this follow-up issue on this topic:
- https://github.com/aquasecurity/trivy-operator/issues/1624
