### ISSUE TITLE
Option to skip DB update in ClientServer mode

### ISSUE THREAD

**Issue by ahalay** [aquasecurity/trivy-operator#1430]
It would be great to have a possibility to skip DB update in case of using external trivy-server (ClientServer mode). Since at the moment trivy-server do not support Java DB distribution in the same way as it works for common vuln db (and [that probably won't change anytime soon](https://github.com/aquasecurity/trivy/issues/3560)), this option will allow you to use your own docker image for trivy scan jobs, which already contains updated databases, and still use external trivy-server for caching scan results.

**Comment by chen-keinan** [comment]
@ahalay sure, it make sense , please free to pick it up and raise a PR , let me know if you need my help
