### ISSUE TITLE
integrate Cloudsploit into Trivy operator?

### ISSUE THREAD

**Issue by GitBurtHET** [aquasecurity/trivy-operator#1437]
Hi,

Cloudsploit is a relatively new project from Aquasec: https://github.com/aquasecurity/cloudsploit.

Would it make sense to include Cloudsploit into the Trivy operator?

Why;
Including Cloudsploit into the Trivy operator makes sense when you provision Cloud resources from within Kubernetes. For example in the case of;

- using k8s service of type load balancer
- using CSI drivers which creates cloud storage resources
- when using cloud resources in conjunction with k8s resources, such as an S3 bucket or managed cloud service e.g. message bus
- using Cloud resource provisioning with Crossplane, Flux Terraform controller etc
- Other k8s controllers such as the AWS Load Balancer controller

Why not; The scope of the operator might become too big. It will include a tool that is not Trivy (does this matter if this project was renamed from starboard?)

If the answer is no, does it make sense to create a separate operator for Cloudsploit?

**Comment by chen-keinan** [comment]
@GitBurtHET trivy-operator project has been design for k8s in-cluster scanning.
and yes you are right the `Cloudsploit` is one level up and represent a more broader view of the cloud.
I think its out of scope for `trivy-operator`

**Comment by chen-keinan** [comment]
Closing this issue as no planned
