### ISSUE TITLE
trivy-operator overwhelms smaller cluster with default Helm values

### ISSUE THREAD

**Issue by jmaerki** [aquasecurity/trivy-operator#146]
**What steps did you take and what happened:**

Tried out trivy-operator 0.0.7 today and installed it on my test cluster (k8s 1.23.6) via Helm. After the operator started it immediately began to run dozens of Jobs which quickly overwhelmed the cluster with very high CPU and memory consumption to the point where the whole cluster became unresponsive. Many of the Job pods got OOM killed.

**What did you expect to happen:**

Minimal impact of normal operation on the cluster. Basically, I expect trivy-operator to run things neatly in the background.

**Anything else you would like to add:**

I feel like I need an easy way to limit the number of concurrent Jobs the operator is allowed to run. I haven't found a corresponding parameter, yet. Not sure, if I have to start working with Resource Quotas somehow.

Or do you recommend to run trivy in ClientServer mode to limit resource usage?

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.0.7
- Kubernetes version (use `kubectl version`): 1.23.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Debian 5.10.92-1

Helm values:
trivy:
  ignoreUnfixed: true

**Comment by erikgb** [comment]
@jmaerki I think you can use the [operator.scanJobsConcurrentLimit](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L35) value to reduce the number of concurrent jobs. Let me know if this works for you. Setting a default value that suits a majority of users should be the goal.

**Comment by jmaerki** [comment]
I'm so blind. Sorry for that and thanks for the quick response. I've wrestled the cluster back under control and then changed operator.scanJobsConcurrentLimit to 1. The operator still runs 2 concurrent jobs but at least it doesn't bring the whole 4-node cluster to its knees anymore, just that single RaspberryPi 4 4GB node. I guess I will experiment with Trivy Client/Server mode.
I think it may make sense to reduce the default value from 10 to 2 or 1 so people trying this out on small test clusters with still some infrastructure on it don't have a bad first experience. Trivy seems very resource-hungry after all.
Feel free to close the issue if you think the default of 10 is fine.

**Comment by erikgb** [comment]
I think the default of 10 is fine. Running tiny clusters on RaspberryPi seems like an unusual case to me. Suggest closing.
