### ISSUE TITLE
Extension vulnerabilityreport for prometheus metrics

### ISSUE THREAD

**Issue by mavo86** [aquasecurity/trivy-operator#152]
For request „[expose findings as prometheus metrics #78](https://github.com/aquasecurity/trivy-operator/issues/78)“ was create a metric for vulnerabilityreport.

This metric is suitable for a Dashborad overview is count and risk of a Deployment. 

But there are no Information which kind of vulnerability is relatet to this deployment.

For a more descriptive Dashbord it would be nice to have more Information like

•	Score
•	Title
•	Vulnerability ID

**Comment by MiggL** [comment]
It would also be nice to have fixed version in the `trivy_vulnerability_id` metric.

If fixed version and title is added to the metric, we could basically have the whole report in a dashboard for real.
I find it unfortunate that we currently have to use `kubectl get vuln ...` to get all the details.

**Comment by chen-keinan** [comment]
@MiggL it is easy to extend , you can pick it up if you want

**Comment by MiggL** [comment]
@chen-keinan All right, PR is up.
