### ISSUE TITLE
ClusterInfra Assesment Incorrectly Reports Findings

### ISSUE THREAD

**Issue by schuman0** [aquasecurity/trivy-operator#1541]
**What steps did you take and what happened:**

We have Trivy Operator running in our EKS cluster and when it runs the clusterInfraAssessment report it comes back with checks that aren't valid. 

It returns KCV0080, KCV0081, KCV0090 even though they are setup correctly on the cluster.

**What did you expect to happen:**

Those checks should not return as unsuccessful because they are implemented correctly

**Anything else you would like to add:**

I have attached the report as well as the config file from a worker node. 

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16
- Kubernetes version (use `kubectl version`): 1.24
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): running on the cluster
[config.txt](https://github.com/aquasecurity/trivy-operator/files/12793545/config.txt)
[clusterInfraAssessmentReport.txt](https://github.com/aquasecurity/trivy-operator/files/12793547/clusterInfraAssessmentReport.txt)

**Comment by chen-keinan** [comment]
@schuman0 thanks for this input , can you please check please run [node-collector](https://github.com/aquasecurity/k8s-node-collector) on the cluster and let me know the output

**Comment by schuman0** [comment]
attaching output from node-collector
[output.txt](https://github.com/aquasecurity/trivy-operator/files/12804300/output.txt)

**Comment by chen-keinan** [comment]
@schuman0 its look like something is preventing from node-collector to properly run as I see that out put is empty.
do you see any error in operator log ?

**Comment by schuman0** [comment]
I can't find anything in the logs but at one point I did see that the node-collector jobs were listed as out of memory. Is there a parameter I can use to up the memory limits for node-collector? I don't see anything in the helm chart

**Comment by chen-keinan** [comment]
I'll add support and cut an Rc release for it

**Comment by chen-keinan** [comment]
> I can't find anything in the logs but at one point I did see that the node-collector jobs were listed as out of memory. Is there a parameter I can use to up the memory limits for node-collector? I don't see anything in the helm chart

I'll add support and cut an Rc release for it

**Comment by chen-keinan** [comment]
after trivy-operator v0.16.2 is releases you can use the same [resources config](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L363) for node collector

**Comment by schuman0** [comment]
Okay great, I will try that

**Comment by schuman0** [comment]
@chen-keinan I updated to 0.16.2 and added the resources lines to the node-collector config but when I look at the job on the cluster I still see the old resource config. 
![image](https://github.com/aquasecurity/trivy-operator/assets/6685345/24f5d842-e552-4858-aeb9-a7b7a84fb3c8)
![image](https://github.com/aquasecurity/trivy-operator/assets/6685345/2709ea89-be88-4fe2-b494-332f2fb7d7b3)

**Comment by chen-keinan** [comment]
@schuman0 you'll need to use the same [resource config](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L364) as for trivy scan job

**Comment by schuman0** [comment]
Okay, but I have that set much higher than the job on the node-collector config shows.

**Comment by chen-keinan** [comment]
> Okay, but I have that set much higher than the job on the node-collector config shows.

@schuman0 byt the image you put above I see that you set it on wrong helm params, trivy operator do not read the param from where you put it above it put it from the same param as [scan-job resources](resource config](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L364) please set it up correctly and update me with results

**Comment by schuman0** [comment]
Yes I had already done that: 
![image](https://github.com/aquasecurity/trivy-operator/assets/6685345/5f362e11-c684-4bbf-b56b-693ae32c03df)

**Comment by chen-keinan** [comment]
@schuman0 its the node collector job still have OOM issue ?

**Comment by chen-keinan** [comment]
> I have not seen those recently but I still can't get the reports or node-collector to work no matter what I try.

are you talking on the same initial issue `ClusterInfra Assesment ` are still generated wrongly or not generated at all, or you experience other issue

**Comment by schuman0** [comment]
that's correct. The reports are still generating the same. I also still can't get node collector, when done as above, to generate anything but a blank respose.
