### ISSUE TITLE
Unauthorized error, scanjob pods can't connect to ACR 

### ISSUE THREAD

**Issue by AndreiDoroftei** [aquasecurity/trivy-operator#1560]
**What steps did you take:**
Installed the helm with Terraform (helm release resource) and checked if it's working. When the trivy-operator pods starts up I can see that the scan-vulnerabilityreport pods are trying to connect to the ACR to scan the images.

**And what happened:**
The scan pods fail.

**What did you expect to happen:**
The scan pods would scan the images.

**Anything else you would like to add:**
The service account is configured according to the [documentation](https://aquasecurity.github.io/trivy-operator/v0.16.1/docs/vulnerability-scanning/managed-registries/#azure-container-registry-acr-workload-identity-support). The scan pods do have an azure-identity-token and the azure.workload.identity/use=true label. 
Here is the error:

`{
    "level": "error",
    "ts": "2023-10-10T06:53:43Z",
    "logger": "reconciler.scan job",
    "msg": "Scan job container",
    "job": "monitoring/scan-vulnerabilityreport-69d869d787",
    "container": "<IMAGE_NAME>",
    "status.reason": "Error",
    "status.message": "2023-10-10T06:53:38.907Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (<IMAGE_REGISTRY>.azurecr.io/<IMAGE_NAME>:<IMAGE_TAG>): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* GET https://<IMAGE_REGISTRY>.azurecr.io/oauth2/token?scope=repository%3A<IMAGE_NAME>%3Apull&service=<IMAGE_REGISTRY>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.\n\n\n",
    "stacktrace": "github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"
}`

The  <IMAGE_REGISTRY>, <IMAGE_NAME> AND <IMAGE_TAG> had the correct values.
- Trivy-Operator version (use 0.16.1):

**Comment by chen-keinan** [comment]
@AndreiDoroftei have you installed the [Mutating Admission Webhook](https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html#mutating-admission-webhook) ?

**Comment by AndreiDoroftei** [comment]
Yes, I have this workload-identity-addon-0.1.0-9db0aaa396c002128a1cc560f6544cd3b8eb2cf7 installed. When trying to install the helm chart I've got this:
Unable to continue with install: ClusterRole "azure-wi-webhook-manager-role" in namespace "" exists and cannot be imported into the current release.

I do have the client id and tenant id. I can't seem to find client secret. I have this instead.
AZURE_FEDERATED_TOKEN_FILE : /var/run/secrets/azure/tokens/azure-identity-token

**Comment by chen-keinan** [comment]
> @chen-keinan, Yes, I have this workload-identity-addon-0.1.0-9db0aaa396c002128a1cc560f6544cd3b8eb2cf7 installed. When trying to install the azure-workload-identity/workload-identity-webhook helm chart I've got this: Unable to continue with install: ClusterRole "azure-wi-webhook-manager-role" in namespace "" exists and cannot be imported into the current release.
> 
> I do have the client id and tenant id. I can't seem to find client secret. I have this instead. AZURE_FEDERATED_TOKEN_FILE : /var/run/secrets/azure/tokens/azure-identity-token

FYI.
the [Azure Container Registry](https://aquasecurity.github.io/trivy-operator/v0.14.0/docs/vulnerability-scanning/managed-registries/) is still supported , if it worked for you before.

**Comment by chen-keinan** [comment]
have you tried user our other options for [private registries](https://aquasecurity.github.io/trivy-operator/v0.16.1/tutorials/private-registries/) ?

**Comment by AndreiDoroftei** [comment]
I haven't tried them, I guess they could work, but I would appreciate a lot some info on how to debug this method..

**Comment by chen-keinan** [comment]
I suggest to start with the private registies instruction to get operator working and then look as aks settings on parallel

**Comment by chen-keinan** [comment]
@AndreiDoroftei any update on this issue? has you resolved it ?

**Comment by AndreiDoroftei** [comment]
@chen-keinan Nope, I am using this in the end:
`operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }`

**Comment by dioni-dev** [comment]
@AndreiDoroftei i use this method: operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" } but i am still having this issue.


This is my terraform helm:             serviceMonitor:
              enabled: true
            trivy:
              ignoreUnfixed: true
            operator:
              privateRegistryScanSecretsNames: {"default":"my-docker-creds"}

I use this version:
        repoURL        = "https://aquasecurity.github.io/helm-charts"
        chart          = "trivy-operator"
        targetRevision = "0.19.1"

And yes, i am having the same error of this post.

**Comment by chen-keinan** [comment]
@dioni-dev can you please share logs with error if you have any and how you create the secret ?

**Comment by dioni-dev** [comment]
> @dioni-dev can you please share logs with error if you have any and how you create the secret ?

@chen-keinan 

Sure:

`{"level":"info","ts":1604949462.0904198,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"batch","reconcilerKind":"Job","controller":"job"}
{"level":"info","ts":1604949462.090432,"logger":"controller","msg":"Starting workers","reconcilerGroup":"batch","reconcilerKind":"Job","controller":"job","worker count":1}
{"level":"error","ts":1604949471.7839265,"logger":"controller.job","msg":"Scan job container","job":"starboard-operator/2b1b65b9-e131-4e13-9601-68fa1eb3cab6","container":"platform-pnrhelperservice","status.reason":"Error","status.message":"2020-11-09T19:17:51.225Z\t\u001b[31mFATAL\u001b[0m\tunable to initialize a scanner: unable to initialize a docker scanner: 2 errors occurred:\n\t* unable to inspect the image (aagacr.azurecr.io/platform/pnrhelperservice:20201109.3): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* GET https://aagacr.azurecr.io/oauth2/token?scope=repository%3Aplatform%2Fpnrhelperservice%3Apull&service=aagacr.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.\n\n\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/aquasecurity/starboard/pkg/operator/controller/job.(*JobController).processFailedScanJob\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/job/job_controller.go:163\ngithub.com/aquasecurity/starboard/pkg/operator/controller/job.(*JobController).Reconcile\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/job/job_controller.go:69\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-`

I create the secret like this: kubectl create secret docker-registry my-docker-creds
--docker-server=<REGISTRY_NAME>.azurecr.io
--docker-username=<REGISTRY_USERNAME>
--docker-password=<REGISTRY_PASSWORD>
--docker-email=<ANY_EMAIL>

My environment is Azure. I am running the last Trivy Operator Version

**Comment by chen-keinan** [comment]
> @chen-keinan Nope, I am using this in the end: `operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }`

is this option works for you ?

**Comment by dioni-dev** [comment]
> > @chen-keinan Nope, I am using this in the end: `operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }`
> 
> is this option works for you ?

No, it doesn't work, i am having the same issue

**Comment by chen-keinan** [comment]
> 
> I create the secret like this: kubectl create secret docker-registry my-docker-creds --docker-server=<REGISTRY_NAME>.azurecr.io --docker-username=<REGISTRY_USERNAME> --docker-password=<REGISTRY_PASSWORD> --docker-email=<ANY_EMAIL>
> 
> My environment is Azure. I am running the last Trivy Operator Version

I assume that for your example above. the create secret should be named `trivy-auth` and deployed into namespace `monitoring` can you confirm ?

**Comment by dioni-dev** [comment]
> > I create the secret like this: kubectl create secret docker-registry my-docker-creds --docker-server=<REGISTRY_NAME>.azurecr.io --docker-username=<REGISTRY_USERNAME> --docker-password=<REGISTRY_PASSWORD> --docker-email=<ANY_EMAIL>
> > My environment is Azure. I am running the last Trivy Operator Version
> 
> I assume that for your example above. the create secret should be named `trivy-auth` and deployed into namespace `monitoring` can you confirm ?

Yes, i did, but the problem persists :(

**Comment by chen-keinan** [comment]
> > > @chen-keinan Nope, I am using this in the end: `operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }`
> > 
> > 
> > is this option works for you ?
> 
> No, it doesn't work, i am having the same issue

@AndreiDoroftei ?

**Comment by chen-keinan** [comment]
> > > I create the secret like this: kubectl create secret docker-registry my-docker-creds --docker-server=<REGISTRY_NAME>.azurecr.io --docker-username=<REGISTRY_USERNAME> --docker-password=<REGISTRY_PASSWORD> --docker-email=<ANY_EMAIL>
> > > My environment is Azure. I am running the last Trivy Operator Version
> > 
> > 
> > I assume that for your example above. the create secret should be named `trivy-auth` and deployed into namespace `monitoring` can you confirm ?
> 
> Yes, i did, but the problem persists :(

thanks , I'll try to reproduce it and update you.

**Comment by PhiRie** [comment]
@chen-keinan is there already a solution for this issue? Because we are facing the same issue if we want to use trivy operator in AKS with a private azure container registry (ACR) and managed identities/workload identities. 

Further I guess the setting: `operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }` references a secret for username and password authentication on the ACR. So for me this seems to be just a workaround and not a fix for the issue if we want to use workload identities. 

Additionally I guess the installation of the workload [Mutating Admission Webhook](https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html#mutating-admission-webhook) is replaced by enabling the workload identities directly via az aks (az aks update -g "${RESOURCE_GROUP}" -n myAKSCluster --enable-oidc-issuer --enable-workload-identity) and therefore not needed anymore, right?

**Comment by chen-keinan** [comment]
> @chen-keinan is there already a solution for this issue? Because we are facing the same issue if we want to use trivy operator in AKS with a private azure container registry (ACR) and managed identities/workload identities.
> 
> Further I guess the setting: `operator:privateRegistryScanSecretsNames: { "monitoring": "trivy-auth" }` references a secret for username and password authentication on the ACR. So for me this seems to be just a workaround and not a fix for the issue if we want to use workload identities.
> 
> Additionally I guess the installation of the workload [Mutating Admission Webhook](https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html#mutating-admission-webhook) is replaced by enabling the workload identities directly via az aks (az aks update -g "${RESOURCE_GROUP}" -n myAKSCluster --enable-oidc-issuer --enable-workload-identity) and therefore not needed anymore, right?

yes , should be supported , check our [docs](https://aquasecurity.github.io/trivy-operator/v0.18.1/docs/vulnerability-scanning/managed-registries/) for it

**Comment by PhiRie** [comment]
Thx for your fast response. Yes its supported but not working in our case. We get the same error as @dioni-dev

`{"level":"error","ts":"2024-01-17T09:50:16Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy/scan-vulnerabilityreport-c54c7d7f7","container":"loki","status.reason":"Error","status.message":"2024-01-17T09:50:13.809Z	
u001b[31mFATAL
u001b[0m	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (<privateacr>.azurecr.io/grafana/loki:2.9.2): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* containerd socket not found: /run/containerd/containerd.sock
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* GET https://<privateacr>.azurecr.io/oauth2/token?scope=repository%3Agrafana%2Floki%3Apull&service=<privateacr>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.


","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob
	/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1
	/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/reconcile/reconcile.go:111
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}`

We enabled workload identities in our AKS cluster (ACR access to pull images works for all other services we deploy in the cluster). And we followed the instructions you mentioned. 

We created a service account (via terraform/terragrunt):

`apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <client id>
    azure.workload.identity/tenant-id: <tenant id>
  creationTimestamp: "2024-01-16T14:49:57Z"
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: terragrunt
    app.kubernetes.io/name: trivy-operator
    azure.workload.identity/use: "true"
  name: trivy-operator
  namespace: trivy
  resourceVersion: "68899"
  uid: a9caf83e-74ff-4834-a28b-7a086b0b01a0`
  
  And we further set the `scanJob.podTemplateLabels=azure.workload.identity/use=true` label which is also reflected by our configmap: 

`apiVersion: v1
data:
  compliance.failEntriesLimit: "10"
  configAuditReports.scanner: Trivy
  node.collector.imageRef: <privateacr>.azurecr.io/aquasecurity/node-collector:0.0.8
  nodeCollector.volumeMounts: '[{"mountPath":"/var/lib/etcd","name":"var-lib-etcd","readOnly":true},{"mountPath":"/var/lib/kubelet","name":"var-lib-kubelet","readOnly":true},{"mountPath":"/var/lib/kube-scheduler","name":"var-lib-kube-scheduler","readOnly":true},{"mountPath":"/var/lib/kube-controller-manager","name":"var-lib-kube-controller-manager","readOnly":true},{"mountPath":"/etc/systemd","name":"etc-systemd","readOnly":true},{"mountPath":"/lib/systemd/","name":"lib-systemd","readOnly":true},{"mountPath":"/etc/kubernetes","name":"etc-kubernetes","readOnly":true},{"mountPath":"/etc/cni/net.d/","name":"etc-cni-netd","readOnly":true}]'
  nodeCollector.volumes: '[{"hostPath":{"path":"/var/lib/etcd"},"name":"var-lib-etcd"},{"hostPath":{"path":"/var/lib/kubelet"},"name":"var-lib-kubelet"},{"hostPath":{"path":"/var/lib/kube-scheduler"},"name":"var-lib-kube-scheduler"},{"hostPath":{"path":"/var/lib/kube-controller-manager"},"name":"var-lib-kube-controller-manager"},{"hostPath":{"path":"/etc/systemd"},"name":"etc-systemd"},{"hostPath":{"path":"/lib/systemd"},"name":"lib-systemd"},{"hostPath":{"path":"/etc/kubernetes"},"name":"etc-kubernetes"},{"hostPath":{"path":"/etc/cni/net.d/"},"name":"etc-cni-netd"}]'
  report.recordFailedChecksOnly: "true"
  scanJob.annotations: serviceAccountName=trivy-operator
  scanJob.compressLogs: "true"
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  scanJob.podTemplateLabels: azure.workload.identity/use=true
  vulnerabilityReports.scanner: Trivy
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: trivy-operator
    meta.helm.sh/release-namespace: trivy
  creationTimestamp: "2024-01-16T14:50:05Z"
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.16.1
    helm.sh/chart: trivy-operator-0.18.1
  name: trivy-operator
  namespace: trivy
  resourceVersion: "558824"
  uid: 50a61a24-52bf-46d5-b261-4d2d55617b17`

But we still get the UNAUTHORIZED issue. Is there anything wrong in our configuration?

**Comment by chen-keinan** [comment]
@PhiRie  checkout with @dferri  he integrated `trivy-operator` with AKS cluster and updated the docs with this PR #1766 few days ago

**Comment by PhiRie** [comment]
@dferri I would appreciate if you could share your experience/feedback to our configuration.

**Comment by PhiRie** [comment]
@dferri Thx for your response. We found the issue today. In our case we had to additionally create azure federated identity credential with our managed identity.
