### ISSUE TITLE
terminated node blocks node-selector scans upon initial scan

### ISSUE THREAD

**Issue by xopham** [aquasecurity/trivy-operator#1585]
**What steps did you take and what happened:**

* adjusted `deploy/helm/values.yaml` with tolerations, longer timeouts (20min)
* installed helm in AWS cluster (~35 nodes) via `helm upgrade --install trivy-operator ./deploy/helm   --namespace trivy-system   --create-namespace`
* intial scans start
* 1 node selector job failed as unschedulable (believed to be the case as the scheduled node was terminated in the time between installing the operator and working through all other nodes first)
* as only 1 concurrent node-selector job, was configured, the whole scan could not complete as it was blocked

**What did you expect to happen:**
trivy should terminate the node-selector job if the node does not exist anymore. It seems like it creates a list of nodes upon startup and just works the list off independent on whether node still exists.

**Anything else you would like to add:**
Please take the issue with a grain of sault as I resolved it by re-installing and could not fully confirm the behavior.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.3
- Kubernetes version (use `kubectl version`): 1.24.16-eks
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):  Linux 5.15.90.1-microsoft-standard-WSL2

**Comment by chen-keinan** [comment]
@xopham I was unable to reproduce it , can this issue be closed?  is it resolved after re-install (following to your comment)

**Comment by xopham** [comment]
@chen-keinan fine with me. Think it can be handled if it pops up again by choosing tolerations accordingly
