### ISSUE TITLE
Replicaset not scanned if there are multiple sets for a deployment

### ISSUE THREAD

**Issue by jVEWo64NbZ** [aquasecurity/trivy-operator#1593]
**What steps did you take and what happened:**

Trivy-operator is deployed to a cluster in AWS EKS (see Trivy settings below). It seems it is not scanning any replicasets if there are multiple sets for one deployment. Eg. if there are 3 replicasets (2 inactive, 1 with active pods) no vulnscanreport is generated at all. Configauditreport is generated. When a deployment contains only one replicaset it has vulnscanreport as well.

**What did you expect to happen:**

All replicasets with active pods should be scanned for vulnerabilities.

**Anything else you would like to add:**

Trivy deployed with Helm, current settings:
```
helm_values_override = {
    "trivy.ignoreUnfixed"               = "true"
    "compliance.reportType"              = "all"
    "operator.scanJobsConcurrentLimit"  = "2"
    "trivy.resources.requests.memory"   = "1000M"
    "trivy.resources.limits.memory"     = "1000M"
    "targetWorkloads"                   = ""
  }
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 
```
CHART trivy-operator-0.18.2
APP VERSION 0.16.2 
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.28.2-eks-f8587cb
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
`Bottlerocket OS 1.15.1 (aws-k8s-1.28)`

**Comment by chen-keinan** [comment]
@jVEWo64NbZ can you share the an example of `deployment` descriptor which describe the above

**Comment by chen-keinan** [comment]
I mean when there is always one replicaSet active and other is historical (non active) , example :
```sh
kubectl get rs

NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-559d658b74   3         3         3       18s
nginx-deployment-66b6c48dd5   0         0         0       44s
```

the `revisionHistoryLimit` define how many replicaSet to keep historically (not active)

**Comment by chen-keinan** [comment]
@jVEWo64NbZ this a revisionHistory rs which has been replaced by active one. if you which to get report for it you'll have to enable the following two helm params 
[vulnScanCurrentRevision](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L87)
[configAuditScanCurrentRevision](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L89)

**Comment by chen-keinan** [comment]
@jVEWo64NbZ I see , do you have any logs maybe got error for it?

**Comment by chen-keinan** [comment]
> @chen-keinan I do have errors if I run `kubectl logs trivy-operator-7688fb949d-mczbx -n trivy-system`, one example (changed account & api name):
> 
> ```
> {"level":"error","ts":"2023-11-03T09:11:50Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-58bd47bb9d","container":"an-api","status.reason":"Error","status.message":"2023-11-03T09:11:48.319Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (111111111111.dkr.ecr.us-east-1.amazonaws.com/backend/service/company-an-api:1.0.1014): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* GET https://111111111111.dkr.ecr.us-east-1.amazonaws.com/v2/backend/service/company-an-api/manifests/1.0.1014: unexpected status code 401 Unauthorized: Not Authorized\n\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}
> ```

@jVEWo64NbZ this error is Related to Registry authentication issue for image `111111111111.dkr.ecr.us-east-1.amazonaws.com/backend/service/company-an-api:1.0.1014`

**Comment by chen-keinan** [comment]
> @chen-keinan I tried to search through the log for other types of errors, but as far as I can see all of the errors are similar.

@jVEWo64NbZ no need to look for other logs this one implies on root cause , I'm referring you to out [private registries](https://aquasecurity.github.io/trivy-operator/v0.16.4/tutorials/private-registries/) guide , it will solve you issue for this one
