### ISSUE TITLE
Docs: add example of trivy operator installation in a k8s namespace with default deny all ingress/egress network policies

### ISSUE THREAD

**Issue by francRang** [aquasecurity/trivy-operator#1598]
It would be good if a section of the documentation was dedicated to installing the Trivy Operator in a K8s namespace with default deny-all ingress/egress network policies. There are a lot of connections between the Trivy Operator, the scanner pods, the Trivy server (when not downloading the vulnerability db every time per Trivy scan). Moreover, netpols to allow the necessary connections to core Kubernetes components (coredns, apiserver) from the namespace where Trivy is installed might also need to be documented/explained when having default deny-all netpols. I think a lot of the Trivy users have similar K8s environments, and the assumption of the current state of the documentation is that the environment where Trivy-operator+other Trivy components are currently being deployed to is set to allow all egress/ingress, debugging/researching this issue first-hand can be very time consuming (had to do it for an installation).

I could add it under the following section: https://aquasecurity.github.io/trivy-operator/v0.16.3/getting-started/installation/troubleshooting/

Willing to open a PR if you think this is worth a try 😃

**Comment by chen-keinan** [comment]
@francRang thank you for supporting us , feel free to raise a PR
