### ISSUE TITLE
Add OS EOSL/EOL to Vuln Report and add optional metric

### ISSUE THREAD

**Issue by cnwaldron** [aquasecurity/trivy-operator#1609]
It would be very useful to track the OS end of service life from Trivy scans like below:
```json
{
  "SchemaVersion": 2,
  "ArtifactName": "centos:centos6.10",
  "ArtifactType": "container_image",
  "Metadata": {
    "OS": {
      "Family": "centos",
      "Name": "6.10",
      "EOSL": true
    }, ...

```

I would be very helpful for security teams to be able to track down the EOL images running in the cluster.

**Comment by chen-keinan** [comment]
@cnwaldron feel free to raise a PR
