### ISSUE TITLE
 operator.metricsVulnIdEnabled: true

### ISSUE THREAD

**Issue by gerbil** [aquasecurity/trivy-operator#1612]
**What steps did you take and what happened:**

operator.metricsVulnIdEnabled: true -> service monitor -> server returned HTTP status 500 Internal Server Error 

**What did you expect to happen:**

Metrics should work and contain vulns ids

**Environment:**

- Trivy-Operator version v0.16.2

**Comment by chen-keinan** [comment]
@gerbil this issue has been fixed with `trivy-operator v0.16.3`

**Comment by gerbil** [comment]
Thank you! Working fine now.
