### ISSUE TITLE
Report from SBOMs attached to OCI images

### ISSUE THREAD

**Issue by MPV** [aquasecurity/trivy-operator#1624]
Following up on the discussion in:
- https://github.com/aquasecurity/trivy-operator/issues/143#issuecomment-1652387802

What would be needed to support reporting from SBOMs attached to OCI images?

Thinking of for example this kind of attached SBOMs:
- https://hackmd.io/@Feynman/BkY78jiDi
- https://learn.microsoft.com/en-us/azure/container-registry/container-registry-oras-artifacts#attach-a-sample-sbom-to-the-image-in-the-registry
- https://github.com/sigstore/cosign/blob/main/specs/SBOM_SPEC.md
- https://github.com/opencontainers/image-spec/issues/827

A benefit to this could be that an SBOM created from an earlier (build) step could be fetched and used (as it might contain more data with better accuracy).

**Comment by MPV** [comment]
...or is this already supported now, as per below?
- https://github.com/aquasecurity/trivy/issues/3735

**Comment by chen-keinan** [comment]
@MPV is it supported with trivy cli ?

**Comment by MPV** [comment]
> @MPV is it supported with trivy cli ? 

Yes, though it seems it's an opt-in for some reason, using: `trivy image --sbom-sources oci`

**Comment by chen-keinan** [comment]
> > @MPV is it supported with trivy cli ?
> 
> Yes, though it seems it's an opt-in for some reason, using: `trivy image --sbom-sources oci`
@MPV how would you suggest for `trivy-operator` to detect the oci-referrers

**Comment by chen-keinan** [comment]
> > @MPV how would you suggest for `trivy-operator` to detect the oci-referrers ?
> 
> I'm not sure how you mean (excuse my missing knowledge of internals in trivy-operator).
> 
> I assume you don't mean something as simple as:
> 
> "just deciding when to run trivy with the `--sbom-sources oci` flag" (if not always)?

I'll explain how the operator reconciles workload events (such as Deployment, Pod, ReplicaSet, etc.). When you deploy, update, or delete a workload, the operator receives an event with the resource manifest.

Subsequently, the trivy-operator retrieves the image reference (`registry/repository:tag`) from the reconciled resource and initiates a scan using Trivy (a scan job operates behind the scenes):

```
trivy image registry/repository:tag
```

To scan the `oci-referrers`, the operator needs to obtain the `sbom-ref` from a specific source.

**Comment by MPV** [comment]
Oh, I thought that was already supported as per my previous comment above (but I may be misreading the implementation)?

> ...or is this already supported now, as per below?
> 
> - https://github.com/aquasecurity/trivy/issues/3735
> 
> - https://github.com/aquasecurity/trivy/pull/3768

**Comment by chen-keinan** [comment]
> Oh, I thought that was already supported as per my previous comment above (but I may be misreading the implementation)?
> 
> > ...or is this already supported now, as per below?
> > 
> > * [discover sbom in OCI registry trivy#3735](https://github.com/aquasecurity/trivy/issues/3735)
> > * [feat(image): discover SBOM in OCI referrers trivy#3768](https://github.com/aquasecurity/trivy/pull/3768)

trivy-operator is cluster scope only and k8s native meaning it automatically should detect resources (images) for scanning , you suggest it for sbom-referrers scanning which is I think more sutibale for cli (trivy) , I'm open for ideas if one can be archived

**Comment by kfox1111** [comment]
Some containers (ex: chainguard) are providing sboms along with the container images and can be pulled from the same container registry. Scanning the sbom rather then the full container can speed up the processing quite a bit.

**Comment by chen-keinan** [comment]
> Some containers (ex: chainguard) are providing sboms along with the container images and can be pulled from the same container registry. Scanning the sbom rather then the full container can speed up the processing quite a bit.

@kfox1111 make sense there for I have added sbom caching (https://github.com/aquasecurity/trivy-operator/pull/1606) however `trivy-operator` need to know if image on registry has `sbom` in addition to image (otherwise can result will fail) , maybe add a label or else to workload , wdyt ?

**Comment by MPV** [comment]
> Some containers (ex: chainguard) are providing sboms along with the container images and can be pulled from the same container registry. 

Thanks for clarifying, this was my thought also. 

>Scanning the sbom rather then the full container can speed up the processing quite a bit.

And it also allows one to use different tools for building the SBOM (i.e. not requiring Trivy), as it's still a standard in motion and some SBOM creators may still lack some data. 

For example Syft is currently better at detecting licensing than Trivy, i.e:
- https://github.com/aquasecurity/trivy/issues/4734
- (and other open issues for NPM and Python)
