### ISSUE TITLE
nil-pointer during scan job

### ISSUE THREAD

**Issue by cwrau** [aquasecurity/trivy-operator#1663]
**What steps did you take and what happened:**

Just have trivy running I guess? 🤷

**What did you expect to happen:**

No crashes

**Anything else you would like to add:**

I've tracked it down to https://github.com/aquasecurity/trivy-operator/blob/main/pkg/vulnerabilityreport/controller/scanjob.go#L156-L157.

If there is an error, it's collected and the code continues, hitting a nil-pointer on line 156

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.17.0
- Kubernetes version (use `kubectl version`): 1.26.9
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A

**Comment by cwrau** [comment]
I can open a PR to surround those 2 lines with an if, but is that the right way?

**Comment by bdols** [comment]
I'm also seeing this with 0.17.0.

**Comment by chen-keinan** [comment]
@cwrau can you please add logs

**Comment by bdols** [comment]
logs for nil pointer deref on scanjob.go:156
[trivy-trivy-operator-5f9cf974-2dk2g-1701238834178938845.log](https://github.com/aquasecurity/trivy-operator/files/13496808/trivy-trivy-operator-5f9cf974-2dk2g-1701238834178938845.log)

**Comment by chen-keinan** [comment]
@bdols thanks for this input , creating a fix and new release
