### ISSUE TITLE
trivy-operator scan error for fluentd-hec image

### ISSUE THREAD

**Issue by thomasroot** [aquasecurity/trivy-operator#1670]
**What steps did you take and what happened:**

Helm installation:
```
helm repo add aqua https://aquasecurity.github.io/helm-charts/
helm repo update
helm install trivy-operator aqua/trivy-operator  --namespace trivy-system  --create-namespace  --version 0.17.1
```

Create a sample deployment:
`kubectl create deployment sample-scan --image=splunk/fluentd-hec:1.3.3 --replicas=1`

=> The trivy-operator fails to scan the newly created deployment after approximately 3 minutes with the following error:
`{"level":"error","ts":"2023-11-27T11:38:11Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-7599bf8d6c","container":"fluentd-container","status.reason":"Error","status.message":"2023-11-27T11:38:06.075Z\\t\\u001b\[31mFATAL\\u001b\[0m\\timage scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:d8eb1cd53414391d2ef9211f02391f20bb68285336edb914b8b7c64136485ac5): walk error: failed to extract the archive: read tcp 10.124.1.148:36528->10.X.X.X:443: read: connection reset by peer\\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(\*ScanJobController).processFailedScanJob\\n\\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299\\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(\*ScanJobController).reconcileJobs.func1\\n\\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\\n\\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(\*Controller).Reconcile\\n\\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(\*Controller).reconcileHandler\\n\\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(\*Controller).processNextWorkItem\\n\\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(\*Controller).Start.func2.2\\n\\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}`

**What did you expect to happen:**

It's interesting that scanning the container image with the trivy-cli without any issues: trivy image splunk/fluentd-hec:1.3.3

I would expect that the trivy-operator behaves more or less similar like the trivy cli? Is it possible that there are some differences in the configuration which could cause this issue? 

**Anything else you would like to add:**

I installed the trivy-operator in several environments with and without adjusted configuration params:

- OnPrem airgapped VMware TKG cluster and GKE cluster
- Pulling the image splunk/fluentd-hec:1.3.3 from Artifactory (airgapped) and directly from dockerhub
- Adjusting the scan time out parameter in the values.yaml file of the trivy-operator helm installation
- The issues is also reproducable with other versions of the splunk/fluentd-hec container image. e. g. splunk/fluentd-hec:1.3.2

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): We tested with v0.16.0 and v0.17.1 (latest)
- Kubernetes version (use `kubectl version`): 1.25-1.28
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by thomasroot** [comment]
Yes only for this particular image, but it works with the trivy cli.

**Comment by thomasroot** [comment]
Sorry for the late answer! 

> Do you mind try a simple test scan the but image but make sure that the following [helm setting](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L348) is false

Awesome! That did the trick. Now the image was scanned properly 🥳

**Comment by chen-keinan** [comment]
Closing following to last comment from @thomasroot
