### ISSUE TITLE
Trivy scheduled scanning

### ISSUE THREAD

**Issue by fnzv** [aquasecurity/trivy-operator#1696]
Hi there!

I was trying to force a scheduled scanning natively, i read on this page:
- https://aquasecurity.github.io/trivy-operator/v0.3.0/operator/

That this is something planned into the next features, is there a GH issue that i can follow to see the status of the implementation?

The end goal would be something like:
- Schedule scan for the entire Kubernetes cluster or specified namespaces
- Plus, but this could be done outside Trivy with a custom implementation, notify the results of the scans (e.g. email or webhook) 

This would cover most of the needs on security operation side

Thank you for your time

**Comment by chen-keinan** [comment]
@fnzv you can schedule a scan as its event base , every time a new resource is deployed then a new scan is triggered

**Comment by fnzv** [comment]
Hi @chen-keinan 
Thank you for your reply, could you share with me the documentation related to that?

**Comment by chen-keinan** [comment]
> Hi @chen-keinan Thank you for your reply, could you share with me the documentation related to that?

here is the [flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L72) to control report TTL

**Comment by fnzv** [comment]
Okk perfect thank you for that, i will go through the helm chart values and test it
