### ISSUE TITLE
Missing ConfigAuditReport for kind: Ingress

### ISSUE THREAD

**Issue by 1337andre** [aquasecurity/trivy-operator#1703]
**What steps did you take and what happened:**

when i try to do some configaudits for ingress, it is missing

I think some here is missing for kind ingress: https://github.com/aquasecurity/trivy-operator/blob/1df3205f58b9e3321e601aee282e07fd6274ad36/pkg/configauditreport/controller/policyconfig.go#L58

**What did you expect to happen:**

ConfigAudits should create for ingress as well

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.17.1
- Kubernetes version (use `kubectl version`): 1.27.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): ubuntu 20.04

**Comment by chen-keinan** [comment]
@1337andre contribution are welcome :)
