### ISSUE TITLE
Server token update

### ISSUE THREAD

**Issue by gerbil** [aquasecurity/trivy-operator#1711]
**What steps did you take and what happened:**

- Install operator in ClientServer mode with builtin server
- Tried to upgrade helm release with trivy.serverToken
- Failed with

```
Error: UPGRADE FAILED: cannot patch "trivy-server" with kind StatefulSet: StatefulSet.apps "trivy-server" 
is invalid: spec:
Forbidden: updates to statefulset spec for fields other than
 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' 
and 'minReadySeconds' are forbidden
```

**What did you expect to happen:**

serverToken should be added to statefull set 

**Environment:**

- Trivy-Operator version 0.16.4
- Kubernetes version (use `kubectl version`): 1.26.3

**Comment by chen-keinan** [comment]
@gerbil can you please share steps to reproduce + example of upgrade command

**Comment by gerbil** [comment]
As wo statefull set might be removed completely before helm upgrade

**Comment by gerbil** [comment]
> @gerbil can you please share steps to reproduce + example of upgrade command

- install helm release with clientServer mode with builtin server
- upgrade the release with just trivy.serverToken = abc
- check error

**Comment by chen-keinan** [comment]
> > @gerbil can you please share steps to reproduce + example of upgrade command
> 
> * install helm release with clientServer mode with builtin server
> * upgrade the release with just trivy.serverToken = abc
> * check error

thanks ,  I'll give it a try

**Comment by gerbil** [comment]
btw.. i can't see server token on scan jobs (even after trivy.serverToken upgrade) on clients

**Comment by chen-keinan** [comment]
@gerbil this issue is only when patching ? I have make a clean install and seems to work ok
```sh
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="operator.builtInTrivyServer=true" \
  --set="trivy.serverToken=abc" \
  --version 0.19.1
```

**Comment by gerbil** [comment]
Yeap, only on upgrade

**Comment by gerbil** [comment]
The same for storageClass (or any other stateful set) updates; Btw.. why server is stateFul set anyway?

**Comment by chen-keinan** [comment]
@gerbil updating the `secret` will not do the work ? 
```sh
kubectl patch secret trivy-operator-trivy-config -n trivy-system \
  --type merge \
  -p "$(cat <<EOF
{
  data": {
    "trivy.serverToken": "$(echo -n $GITHUB_TOKEN | base64)"
  }
}
EOF
)"
```

**Comment by gerbil** [comment]
The problem is that we are using Terraform Helm releases for Trivy server rollouts - so i guess next release will still try to update Helm values trigerring Stateful set change with error.

**Comment by chen-keinan** [comment]
@gerbil I see thanks for the clarification , its look like statefulSet limitation
