### ISSUE TITLE
UNAUTHORIZED: authentication required error

### ISSUE THREAD

**Issue by gerbil** [aquasecurity/trivy-operator#1721]
**What steps did you take and what happened:**

Pod start to trigger scan;

ERROR - reconciler.scan job - Scan job container:
```json
{
    "job": "trivy-system/scan-vulnerabilityreport-79698df7fc",
    "container": "xxx",
    "status.reason": "Error",
    "status.message": "2023-12-27T09:05:03.864Z\t\u001B[31mFATAL\u001B[0m\timage scan error: 
scan error: unable to initialize a scanner: unable to initialize the remote docker scanner: 5 errors occurred:\n\t* 
unable to inspect the image (xxx-registry.cn-shanghai.cr.aliyuncs.com/xxx/xxx:20231214.2): 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* 
containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize 
Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* 
GET https://xxx.cn-shanghai.cr.aliyuncs.com/v2/xxx/xxx/manifests/20231214.2: 
MANIFEST_UNKNOWN: manifest unknown; map[Tag:20231214.2]\n\t*
GET https://xxx.cr.aliyuncs.com/v2/xxx/xxx/manifests/20231214.2: 
UNAUTHORIZED: authentication required; [map[Action:pull Class: Name: xxx/xxxx Type: repository]]\n\n\n"
}
```

**What did you expect to happen:**

Successfull scan via remove trivy server

**Anything else you would like to add:**

Most interesting part i think:
UNAUTHORIZED: authentication required; [map[Action:pull Class: Name: xxx/xxxx Type: repository]
Pull credentials available in Namespace by acr-crendetianls-helper + images are pulled successfully from this repo

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.4

**Comment by chen-keinan** [comment]
@gerbil could you please advice on secret format , is it in form of:
```sh
kubectl create secret docker-registry regcred --docker-server=<registry url> --docker-username=<user name> --docker-password=<password> --docker-email=<mail> -n <namespace>
```

**Comment by gerbil** [comment]
Yeap. 
Type - kubernetes.io/dockerconfigjson
Name - acr-credential-3116cc9c114553be212af054bca2ba72
Data - 
{"auths":{"xxx.cr.aliyuncs.com":{"Username":"cr_temp_user","Password":"xxx","Email":"cs@aliyuncs.com","Provider":null}}}

**Comment by gerbil** [comment]
Seems like the problem is not within Trivy Operator itself, since i can see inconsistent behaviour in those namespaces for pulling images.
