### ISSUE TITLE
/version endpoint - DownloadedAt bug

### ISSUE THREAD

**Issue by gerbil** [aquasecurity/trivy-operator#1730]
**What steps did you take and what happened:**

```json
{
    "Version": "0.47.0",
    "VulnerabilityDB": {
        "Version": 2,
        "NextUpdate": "2024-01-02T06:17:23.143259016Z",
        "UpdatedAt": "2024-01-02T00:17:23.143259376Z",
        "DownloadedAt": "0001-01-01T00:00:00Z"
    }
}
```

**What did you expect to happen:**

Correct date for DownloadedAt

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.4

**Comment by chen-keinan** [comment]
@gerbil this bug should be open in [trivy project](https://github.com/aquasecurity/trivy)
