### ISSUE TITLE
[Feature Request] Possibility for configuring custom annotations for node-collector job and pod

### ISSUE THREAD

**Issue by Zeratoxx** [aquasecurity/trivy-operator#1735]
As with the scan jobs using `trivyOperator.scanJobAnnotations`, it should be possible to configure the node collector's annotations

We need this feature to provide job/pod annotations to disable automatic injection of Linkerd proxies.

```[tasklist]
### Tasks
```

**Comment by chen-keinan** [comment]
@Zeratoxx is [this](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L222) is what you are looking for ?

**Comment by Zeratoxx** [comment]
> @Zeratoxx is [this](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L222) is what you are looking for ?

No, this is what I was referencing in my initial message :) Unfortunately, this value does not do the trick, it only alters the annotations for the scan jobs. 

There could be a misunderstanding of my initial message here is a bit different version:

It should be possible to configure custom annotations for the node collector similar to how it is possible to set custom annotations for the scan jobs with `trivyOperator.scanJobAnnotations`.

**Comment by chen-keinan** [comment]
@Zeratoxx I see thanks for clarification ,I will take a look at it

**Comment by sylvainOL** [comment]
hey @Zeratoxx , looking at the code (https://github.com/aquasecurity/trivy-operator/blob/main/pkg/configauditreport/controller/node.go#L174) , it seems that scanJobAnnotations are also set to the node collector

**Comment by sylvainOL** [comment]
ok, after tests, `trivyOperator.scanJobAnnotations` adds annotations at `Job` level but we would needs them at `Job.Spec.Template` level

**Comment by Zeratoxx** [comment]
> ok, after tests, `trivyOperator.scanJobAnnotations` adds annotations at `Job` level but we would needs them at `Job.Spec.Template` level

Oh, thank you for your investigation! :)

Also nice findings in your tests 😄

So that means it's more like a bug I guess. But I would also say that it isn't very clear that `scanJobAnnotations` also alters the node collector.. A separate value would be more intuitive I think? 🤔

**Comment by chen-keinan** [comment]
@sylvainOL @Zeratoxx the annotation is added in the [job.spec.template](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/vulnerabilityreport/builder.go#L188) already, can you please advice

**Comment by chen-keinan** [comment]
@Zeratoxx please reviewed my lastest comment ?

**Comment by Zeratoxx** [comment]
@chen-keinan Sorry, I saw your comment but forgot about it 😅

As far as I see you linked me to the place where ScanJobs are getting built, am I right? If true, that's not what this Github Issue is about.

I created this issue because the contents that a user enters in the helm value `scanJobAnnotations` will not be applied to the NodeCollector job nor is it possible to set custom annotations solely for the NodeCollector. And that's what I need, if you ask me this directly :)

**Comment by chen-keinan** [comment]
> @chen-keinan Sorry, I saw your comment but forgot about it 😅
> 
> As far as I see you linked me to the place where `ScanJobs` are getting built, am I right? If true, that's not what this Github Issue is about.
> 
> I created this issue because the contents that a user enters in the helm value `scanJobAnnotations` will not be applied to the `NodeCollector` Job, nor is it possible to set custom annotations solely for the NodeCollector. And that's what I need, if you ask me this directly :)

thanks for clarification adding a fix now

**Comment by chen-keinan** [comment]
> @chen-keinan Soo, it was a bug that gets solved with a version bump?

its not just a version bump, the new version include the fix. see the [PR](https://github.com/aquasecurity/trivy-kubernetes/pull/321)

**Comment by Zeratoxx** [comment]
Ohhh okay, I just didn't understand the project structure, now it's clear to me 😅👍
