### ISSUE TITLE
[Feature Request] Enable passing ENV variables via Secret or ConfigMap

### ISSUE THREAD

**Issue by flash-me** [aquasecurity/trivy-operator#1737]
Currently, most of the configuration OPTIONS, that can be configured via environment variables, need to be passed as Helm Values. See the [deploment.yaml](https://github.com/aquasecurity/trivy-operator/blob/67a005d83069dcc759f37b9f9b111ed92c10fb84/deploy/helm/templates/deployment.yaml#L35-L129) 

There are cases, where these configurations might not be hardcoded as Helm Values but rather passed located in Kubernetes Secrets and/or ConfigMaps.
Currently, there is no way to refer to ConfigMaps/Secrets to get the configuration for the Trivy-Operator Helm Chart. 

Kubernetes itself does support setting environment variables both 
- for [Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data)
- and for [ConfigMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)

And it is a widely used pattern. 
Should be technically not difficult to enable such a pattern with a priority like:

1. Use value from Helm Value if set
2. Use value from ConfigMap if set (and override Helm Value)
3. Use value from Secret if set (and override both Helm Value and ConfigMap)

cheers
flash ⚡

**Comment by chen-keinan** [comment]
@flash-me contributions are welcome :)

**Comment by flash-me** [comment]
Spend some time looking at it. This can be trickier and initially presumed.
Unfortunately, `envFrom` does not work here. 
Due to [Precedence of Environment Variables in the Pod Spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#container-v1-core), the order is 
`env` > `envFrom` > `predefined in container`.
And everything is already defined by `env` variables in the [deployment.yaml](https://github.com/aquasecurity/trivy-operator/blob/67a005d83069dcc759f37b9f9b111ed92c10fb84/deploy/helm/templates/deployment.yaml#L35-L129).

And wrapping every possible Value into a `if` block feels also not great. Hhmhm..

**Comment by flash-me** [comment]
Alrighty, 

tried another approach by extracting all the `OPERATOR_*` env variables into their own ConfigMap and then refer to them with [envFrom configMapRef](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables). 
This avoids the previously mentioned **Precedence** an enables using additional sources.

This means:
- Most of the `deployment.yaml` [Env's](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/deployment.yaml#L46-L129) moved to a new ConfigMap
- A new Property `.Values.operator.<PROP>` is added to the `values.yaml` file
- Everything completely optional with breaking changes

@chen-keinan May you assign me this issue? I'd create the according pull request next few days hopefully. 

cheers
flash ⚡
