### ISSUE TITLE
Allow config nodeSelector of pod node-collector from value file

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#1779]
Currently pod node-collector is pending and it could not locate to any node in cluster
We check that there is default config of this pod as below:

```
nodeSelector:
    kubernetes.io/hostname: <ip>.<region>.compute.internal
```

Expectation: Config nodeSelector of pod node-collector could be configured from value file.

Thanks!

**Comment by chen-keinan** [comment]
@chary1112004 do you wish to configure it for every node ?

**Comment by chary1112004** [comment]
> @chary1112004 trivy-operator automatically detect the `name` of the `Node` to be assign to node selector.
> 
> probably better have helm flag:
> 
> ```yaml
> useNodeSelector: true
> ```
> 
> wdyt?

yes, lgtm
