### ISSUE TITLE
Bumped helm chart from v0.18.4 to v0.19.1, CRDS aren't updated.

### ISSUE THREAD

**Issue by AndreiDoroftei** [aquasecurity/trivy-operator#1788]
**What steps did you take and what happened:**
Bumped helm chart from version v0.18.4 to v0.19.1.
The helm release is deployed and upgraded using Terraform.
**What did you expect to happen:**
Everything to work as expected
**Anything else you would like to add:**
This is the list of CRDS on the cluster after upgrading:
![image](https://github.com/aquasecurity/trivy-operator/assets/91670767/e1ec3c53-b855-4082-9122-2e217280173f)

And this is the list of CRDS of a fresh install of the same version (v0.19.1):
![image](https://github.com/aquasecurity/trivy-operator/assets/91670767/b73384bf-4126-4ad6-b36b-c735832a25b4)

This is the error I receive when not doing a fresh install, but just an upgrade:
`unable to run trivy operator: starting controllers manager: failed to wait for clustersbomreport caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.ClusterSbomReport`

Also, 
`"error":"failed to get restmapping: no matches for kind \"ClusterSbomReportList\" in group \"aquasecurity.github.io\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}`

**Comment by AndreiDoroftei** [comment]
On the fresh install, none for the moment, on the upgraded one:
error: the server doesn't have a resource type "clustersbom"
0

**Comment by chen-keinan** [comment]
I think you are right regarding helm upgrade.

this is how you delete clustersbom crd : 
`kubectl delete crd clustersbomreports.aquasecurity.github.io`

CRD  folder is [here](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm/crds) in-case CRD is not deployed again. you can deploy it manually

**Comment by AndreiDoroftei** [comment]
Thank you! I've searched for that folder but couldn't find it. Have a nice day!
