### ISSUE TITLE
CRD not found causes Operator to crash loop?

### ISSUE THREAD

**Issue by lepicodon** [aquasecurity/trivy-operator#1807]
**What steps did you take and what happened:**
I noticed (late) the trivy-operator v0.18.1 pod kept crashing so I updated to v0.18.2, but I keep seeing the same behavior.
Looking at the pod logs I get this error (as if I was missing a CRD though no changes were made):

{"level":"error","ts":"2024-01-29T15:14:26Z","logger":"controller-runtime.source.EventHandler","msg":"if kind is a CRD, it should be installed before calling Start","kind":"ClusterVulnerabilityReport.aquasecurity.github.io",**"error":"no matches for kind \"ClusterVulnerabilityReport\" in version \"aquasecurity.github.io/v1alpha1\"**","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/source/kind.go:63\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/loop.go:87\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/loop.go:88\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/source/kind.go:56"}

**What did you expect to happen:**
The pod was previously running without restarting constantly until I saw the 3700+ restarts in 17 days (I didn't look for some time)!

**Environment:**
- Trivy-Operator version (use `trivy-operator version`):
Version: "0.18.2"
Commit: "2c2f55673de7db8528da65ab0761fd1219fb0c65"

- Kubernetes version (use `kubectl version`): K8s v1.28.5

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): K8s Cluster running on Rocky Linux 9.3

Should I helm uninstall, clean the AquaSecurity CRDs and helm install again?
Thanks for the help!

**Comment by chen-keinan** [comment]
@lepicodon how are deploying the to the cluster ?

**Comment by lepicodon** [comment]
I'm using helm to deploy the operator, using custom values.

ConfigMap:

kubectl describe cm -n trivy-system trivy-operator-trivy-config

Name:         trivy-operator-trivy-config
Namespace:    trivy-system
Labels:       app.kubernetes.io/instance=trivy-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=trivy-operator
              app.kubernetes.io/version=0.18.2
              helm.sh/chart=trivy-operator-0.20.3
Annotations:  meta.helm.sh/release-name: trivy-operator
              meta.helm.sh/release-namespace: trivy-system

Data
====
trivy.dbRepositoryInsecure:
----
false
trivy.includeDevDeps:
----
false
trivy.javaDbRepository:
----
ghcr.io/aquasecurity/trivy-java-db
trivy.mode:
----
Standalone
trivy.tag:
----
0.48.2
trivy.useBuiltinRegoPolicies:
----
true
trivy.additionalVulnerabilityReportFields:
----

trivy.imageScanCacheDir:
----
/tmp/trivy/.cache
trivy.resources.limits.memory:
----
500M
trivy.resources.requests.cpu:
----
100m
trivy.resources.requests.memory:
----
100M
trivy.sbomSources:
----

trivy.skipJavaDBUpdate:
----
false
trivy.slow:
----
false
trivy.imagePullPolicy:
----
IfNotPresent
trivy.dbRepository:
----
ghcr.io/aquasecurity/trivy-db
trivy.resources.limits.cpu:
----
500m
trivy.severity:
----
UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
trivy.supportedConfigAuditKinds:
----
Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
trivy.timeout:
----
5m0s
trivy.command:
----
image
trivy.repository:
----
ghcr.io/aquasecurity/trivy
trivy.filesystemScanCacheDir:
----
/var/trivyoperator/trivy-db

BinaryData
====

Events:  <none>

**Comment by lepicodon** [comment]
sorry for the markdown output...

**Comment by chen-keinan** [comment]
@lepicodon do you mind try uninstall operator and install it again.

**Comment by lepicodon** [comment]
I helm uninstalled and then reinstalled (newer v0.18.3) and all seems to be good now, now more restarts and missing CRD in the logs!
Thank you!!
