### ISSUE TITLE
add ExposedSecret Report summary metrics

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#181]
Trivy-Operator now supports ExposedSecret Report summary metrics.
the metric collector needs to be updated to collect exposed secret summary metrics as well.
CRD ref :[Exposed Secrets](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/crd/exposedsecretreports.crd.yaml)

**Comment by itaysk** [comment]
I believe this is in scope of #78 isn't it? closing unless it's necessary to track separately
