### ISSUE TITLE
But why is there no "Remediations" in ClusterComplianceReports of "Trivy-operator"

### ISSUE THREAD

**Issue by toasahi** [aquasecurity/trivy-operator#1815]
**What steps did you take and what happened:**
When I run the cis benchmark kubernetes in "kube-bench", I get the "Remediations" output. But why is there no "Remediations" in ClusterComplianceReports of "Trivy-operator"? Also, there is no change when reportType=all is specified.

**Environment:**

- Trivy-Operator version (0.20.4)
- Kubernetes version 1.26.0 EKS

**Comment by chen-keinan** [comment]
@toasahi you are right , you can get more info on aqua vulnerability db service , pass id in this url
https://avd.aquasec.com/misconfig/kubernetes/general/<avd-ID>/

example:
https://avd.aquasec.com/misconfig/kubernetes/general/avd-ksv-0003/

**Comment by toasahi** [comment]
@chen-keinan Thank you very much.
I was expecting to see "Recommended Action" in ClusterComplianceReports. Why is it not outputting?I don't know.

Also, I could not see the "Recommended Action" in ClusterComplianceReports in Trivy-Operator at the following URL
https://avd.aquasec.com/misconfig/kubernetes/general/id/

https://avd.aquasec.com/misconfig/kubernetes/general/avd-kcv-0006/
<img width="400" alt="スクリーンショット 2024-01-30 23 16 50" src="https://github.com/aquasecurity/trivy-operator/assets/82006976/b1dc309f-d388-4c57-9e88-0f6b793ae47a">


Just an example
<img width="400" alt="スクリーンショット 2024-01-30 23 08 47" src="https://github.com/aquasecurity/trivy-operator/assets/82006976/a5d20ed9-568a-437b-9850-5c992300fb15">

I could see the image at the following URL
https://avd.aquasec.com/compliance/kubernetes/cis-1.23/cis-1.23-master/1.1/

I would like to eventually get and visualize metrics such as "ID", "Severity", "Recommended Action" of ClusterComplianceReports in Grafana. Is it possible to visualize "ID", "Severity", "Recommended Action", etc. of the current Trivy-Operator with Grafana?

**Comment by chen-keinan** [comment]
@toasahi it could be a bug , I'll have a look at it

**Comment by toasahi** [comment]
@chen-keinan Thank you very much.
