### ISSUE TITLE
trivy operator 0.18.3 : crashing , config not working , metrics endpoint down

### ISSUE THREAD

**Issue by prabhapa** [aquasecurity/trivy-operator#1818]
want to install and run trivy operator on my EKS cluster on fargate.
I can see the operator constantly crashing due to probe failures. Also some configuration are not working as expected. And metrics end point is down.
below is segregation of issues:
**Part 1: crash issue**
1)**installation:**
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --version 0.18.3 \
  --values trivy-values.yaml    
```   
trivy:tag: 0.48.3 / 0.48.2

2) adding some more permissions on SA to access ECR repo.
3) restarting trivy-operator pod to affect the permisison changes.
4) observing pod crash (crash debug log attached)
5) followed by crashloopback (logs attached)
6) pod describe logs to see events (attached)

****Part 2:** configuration does not work as expected.**

1) found out none of the below configuration are working as expected: (full values file attached)
operator:
  scanJobsConcurrentLimit: 2
  scanNodeCollectorLimit: 1
serviceAccount:
  create: true
  annotations: {"eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxx:role/cluster-dev-node"}
nodeCollector: 
  excludeNodes: eks.amazonaws.com/compute-type=fargate

**Part 3: metrics end point is never up**
when i am curling metrics end point i am getting "500 server error."

please help addressing above issues.

**Environment:**

EKS cluster with fargate nodes and some autoscaling ec2 nodes.

- Trivy-Operator version (use `trivy-operator version`): 0.18.3
- Kubernetes version (use `kubectl version`): 1.28
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): fargate nodes

attachments:
[pod-describe.txt](https://github.com/aquasecurity/trivy-operator/files/14125687/pod-describe.txt)
[pod-logs-crashloop.txt](https://github.com/aquasecurity/trivy-operator/files/14125691/pod-logs-crashloop.txt)
[podlogs.txt](https://github.com/aquasecurity/trivy-operator/files/14125692/podlogs.txt)
[trivy-values.txt](https://github.com/aquasecurity/trivy-operator/files/14125713/trivy-values.txt)

**Comment by AnaisUrlichs** [comment]
Hi there, could you please paste the trivy-values.yaml manifest? Could you try again with the latest Trivy version?

**Comment by prabhapa** [comment]
Hi @AnaisUrlichs , I tried with latest version got similar issues. trivy-values.txt is attached already. Again pasting the values here:          
-------------------------------
global:
  image:
    registry: ""
managedBy: Helm
targetNamespaces: ""
excludeNamespaces: ""
targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
nameOverride: ""
fullnameOverride: ""
operator:
  namespace: ""
  replicas: 1
  revisionHistoryLimit: ~
  podLabels: {}
  leaderElectionId: "trivyoperator-lock"
  logDevMode: true
  scanJobTTL: ""
  scanJobTimeout: 5m
  scanJobsConcurrentLimit: 2
  scanNodeCollectorLimit: 1
  scanJobsRetryDelay: 30s
  vulnerabilityScannerEnabled: false
  sbomGenerationEnabled: false
  clusterSbomCacheEnabled: true
  scannerReportTTL: "24h"
  cacheReportTTL: "120h"
  configAuditScannerEnabled: true
  rbacAssessmentScannerEnabled: true
  infraAssessmentScannerEnabled: true
  clusterComplianceEnabled: true
  batchDeleteLimit: 10
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  configAuditScannerScanOnlyCurrentRevisions: true
  batchDeleteDelay: 10s
  accessGlobalSecretsAndServiceAccount: true
  builtInTrivyServer: false
  controllerCacheSyncTimeout: "5m"
  trivyServerHealthCheckCacheExpiration: 10h
  metricsFindingsEnabled: true
  metricsVulnIdEnabled: false
  exposedSecretScannerEnabled: true
  metricsExposedSecretInfo: true
  metricsConfigAuditInfo: true
  metricsRbacAssessmentInfo: true
  metricsInfraAssessmentInfo: true
  metricsImageInfo: true
  metricsClusterComplianceInfo: true
  webhookBroadcastURL: ""
  webhookBroadcastTimeout: 30s
  webhookSendDeletedReports: false
  privateRegistryScanSecretsNames: {}
  mergeRbacFindingWithConfigAudit: false
image:
  registry: "ghcr.io"
  repository: "aquasecurity/trivy-operator"
  tag: "0.18.3"
  pullPolicy: IfNotPresent
  pullSecrets: []
service:
  headless: true
  metricsPort: 80
  annotations: {}
serviceMonitor:
  enabled: true
  namespace: "cloud"
  interval: ~
  annotations: {}
  labels: {}
  honorLabels: true
  endpointAdditionalProperties: {}
trivyOperator:
  vulnerabilityReportsPlugin: "Trivy"
  configAuditReportsPlugin: "Trivy"
  scanJobCompressLogs: true
  scanJobTolerations: []
  scanJobNodeSelector: {}
  scanJobAutomountServiceAccountToken: true
  scanJobAnnotations: ""
  scanJobPodTemplateLabels: ""
  skipInitContainers: false
  scanJobPodTemplatePodSecurityContext: {}
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsUser: 0
  scanJobPodPriorityClassName: ""
  reportResourceLabels: ""
  reportRecordFailedChecksOnly: true
  skipResourceByLabels: ""
  metricsResourceLabelsPrefix: "k8s_label_"
  additionalReportLabels: ""
  policiesConfig: ""
trivy:
  createConfig: true
  image:
    registry: ghcr.io
    repository: aquasecurity/trivy
    tag: 0.48.3
    imagePullSecret: ~
    pullPolicy: IfNotPresent
  mode: Standalone
  sbomSources: ""
  includeDevDeps: false
  storageClassEnabled: true
  storageClassName: ""
  podLabels:
  priorityClassName: ""
  additionalVulnerabilityReportFields: ""
  httpProxy: ~
  httpsProxy: ~
  noProxy: ~
  nonSslRegistries: {}
  sslCertDir: ~
  insecureRegistries: {}
  registry:
    mirror: {}
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  slow: true
  ignoreUnfixed: true
  skipFiles:
  skipDirs:
  offlineScan: false
  timeout: "5m0s"
  ignoreFile: ~
  vulnType: ~
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 500m
      memory: 500M
  githubToken: ~
  clientServerSkipUpdate: false
  skipJavaDBUpdate: false
  serverInsecure: false
  serverToken: ~
  serverTokenHeader: "Trivy-Token"
  serverCustomHeaders: ~
  dbRegistry: "ghcr.io"
  dbRepository: "aquasecurity/trivy-db"
  dbRepositoryUsername: ~
  dbRepositoryPassword: ~
  javaDbRegistry: "ghcr.io"
  javaDbRepository: "aquasecurity/trivy-java-db"
  dbRepositoryInsecure: "false"
  useBuiltinRegoPolicies: "true"
  supportedConfigAuditKinds: "Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota"
  command: image
  imageScanCacheDir: "/tmp/trivy/.cache"
  filesystemScanCacheDir: "/var/trivyoperator/trivy-db"
  serverUser: ""
  serverPassword: ""
  serverServiceName: "trivy-service"
  debug: false
  server:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
    podSecurityContext:
      runAsUser: 65534
      runAsNonRoot: true
      fsGroup: 65534
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
    replicas: 1
compliance:
  failEntriesLimit: 10
  reportType: summary
  cron: 0 */6 * * *
rbac:
  create: true
serviceAccount:
  create: true
  annotations: {"eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/cluster-dev-node"}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
volumeMounts: []
volumes: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
automountServiceAccountToken: true
nodeCollector:
  useNodeSelector: true
  registry: ghcr.io
  repository: aquasecurity/node-collector
  tag: 0.1.1
  imagePullSecret: ~
  excludeNodes: eks.amazonaws.com/compute-type=fargate
  volumeMounts:
    - name: var-lib-etcd
      mountPath: /var/lib/etcd
      readOnly: true
    - name: var-lib-kubelet
      mountPath: /var/lib/kubelet
      readOnly: true
    - name: var-lib-kube-scheduler
      mountPath: /var/lib/kube-scheduler
      readOnly: true
    - name: var-lib-kube-controller-manager
      mountPath: /var/lib/kube-controller-manager
      readOnly: true
    - name: etc-systemd
      mountPath: /etc/systemd
      readOnly: true
    - name: lib-systemd
      mountPath: /lib/systemd/
      readOnly: true
    - name: etc-kubernetes
      mountPath: /etc/kubernetes
      readOnly: true
    - name: etc-cni-netd
      mountPath: /etc/cni/net.d/
      readOnly: true
  volumes:
    - name: var-lib-etcd
      hostPath:
        path: /var/lib/etcd
    - name: var-lib-kubelet
      hostPath:
        path: /var/lib/kubelet
    - name: var-lib-kube-scheduler
      hostPath:
        path: /var/lib/kube-scheduler
    - name: var-lib-kube-controller-manager
      hostPath:
        path: /var/lib/kube-controller-manager
    - name: etc-systemd
      hostPath:
        path: /etc/systemd
    - name: lib-systemd
      hostPath:
        path: /lib/systemd
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-cni-netd
      hostPath:
        path: /etc/cni/net.d/

**Comment by chen-keinan** [comment]
@prabhapa can you please share k8s/ operator logs on crash.

**Comment by prabhapa** [comment]
Hi @chen-keinan , those are attached with issue :
https://github.com/aquasecurity/trivy-operator/files/14125687/pod-describe.txt
https://github.com/aquasecurity/trivy-operator/files/14125691/pod-logs-crashloop.txt
https://github.com/aquasecurity/trivy-operator/files/14125692/podlogs.txt

**Comment by AnaisUrlichs** [comment]
@prabhapa is this the trivy-values.yaml file you are passing into the Trivy Operator? I meant more like this one: https://github.com/Cloud-Native-Security/monitor-security/blob/main/observability-conf/trivy-values.yaml

You don't need to pass in entire values.yaml file with the default values, just the values that you changed. This way, we can see the changes that you applied.

**Comment by AnaisUrlichs** [comment]
@prabhapa it would be easier if you could paste the logs directly as comments vs providing the files

**Comment by chen-keinan** [comment]
@prabhapa trivy-operator running and after a while it is crashing ? 

are you getting any report generated ?

**Comment by prabhapa** [comment]
@chen-keinan , no reports are being generated . its keep on crashing

**Comment by prabhapa** [comment]
@chen-keinan  , liveness/readiness probes failing. ```
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   LoggingEnabled  58m                   fargate-scheduler  Successfully enabled logging for pod
  Normal   Scheduled       58m                   fargate-scheduler  Successfully assigned trivy-system/trivy-operator-76df69bddf-n4qj2 to fargate-ip-10-149-10-146.eu-west-1.compute.internal
  Normal   Pulling         58m                   kubelet            Pulling image "ghcr.io/aquasecurity/trivy-operator:0.18.3"
  Normal   Pulled          58m                   kubelet            Successfully pulled image "ghcr.io/aquasecurity/trivy-operator:0.18.3" in 4.658s (4.658s including waiting)
  Normal   Created         57m (x2 over 57m)     kubelet            Created container trivy-operator
  Normal   Started         57m (x2 over 57m)     kubelet            Started container trivy-operator
  Normal   Pulled          57m                   kubelet            Container image "ghcr.io/aquasecurity/trivy-operator:0.18.3" already present on machine
  Warning  Unhealthy       56m                   kubelet            Liveness probe failed: Get "http://10.149.10.146:9090/healthz/": dial tcp 10.149.10.146:9090: connect: connection refused
  Warning  Unhealthy       56m (x9 over 57m)     kubelet            Readiness probe failed: Get "http://10.149.10.146:9090/readyz/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff         7m56s (x99 over 44m)  kubelet            Back-off restarting failed container trivy-operator in pod trivy-operator-76df69bddf-n4qj2_trivy-system(fceb00a3-b995-4c64-90db-232ea4c68375)
  Warning  Unhealthy       3m4s (x125 over 57m)  kubelet            Liveness probe failed: Get "http://10.149.10.146:9090/healthz/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by prabhapa** [comment]
@chen-keinan @AnaisUrlichs  , Any resolutions / recommendations why its happening in EKS cluster? my primary aim is not the vulnerability scan of the workloads but CIS and other benchmarks, config audits etc etc. Even I cant skip the vulnerability scan . Te parameter(operator.vulnerabilityScannerEnabled: false) does not work as per my observation.

**Comment by prabhapa** [comment]
Hi @chen-keinan , I wll try that .give me some time pls.
