### ISSUE TITLE
I cannot delete a report created by trivy-operator when I do "helm uninstall trivy-operator". Is there a workaround for this?

### ISSUE THREAD

**Issue by toasahi** [aquasecurity/trivy-operator#1838]
I cannot delete a report created by trivy-operator when I do "helm uninstall trivy-operator". Is there a workaround for this?

**Comment by chen-keinan** [comment]
@toasahi helm install do not delete report as the reports deployed to user namespaces.
you'll have to delete CRD manually see [docs](https://aquasecurity.github.io/trivy-operator/latest/getting-started/installation/helm/)
