### ISSUE TITLE
Registry pull secrets can become orphaned and never removed

### ISSUE THREAD

**Issue by stone-z** [aquasecurity/trivy-operator#1855]
**What steps did you take and what happened:**

Trivy Operator creates a Secret containing registry pull credentials to be used by a scan job when pulling images.

Under normal circumstances, Trivy Operator [adds an `OwnerReference` to the Secret ](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/vulnerabilityreport/controller/workload.go#L358)which ties the Secret's lifecycle to that of the Job performing the scan. Kubernetes garbage collection will remove the Secret when the Job is deleted.

However, since the `OwnerReference` is added after the Secret is created, it is possible that the update fails and the reference is never added to the Secret. This could be a side effect of API server issues, or a race condition I suspect but haven't been able to definitively nail down. When this happens, the Secret becomes orphaned and will remain in the cluster until manually removed, and we've observed several thousand such secrets in larger clusters.

**What did you expect to happen:**

Secrets automatically created by the operator should be eventually removed after their intended lifetime.

**Anything else you would like to add:**

Coming from a related discussion on Slack --> [here](https://aquasecurity.slack.com/archives/C03L2H45L3H/p1707756907171439)

Two potential approaches might be:
- introducing a CronJob to periodically remove orphaned secrets
- implementing cleanup inside a controller

In either case, it is probably necessary to apply a new label to the automatically generated secrets in order to select and differentiate them from other types of secrets.

The controller approach may be usable for other types of resources, if there are similar cleanup needs in other contexts.

We (Giant Swarm) would be open to implementing a solution of the maintainers' choice, but as we'd be somewhat unfamiliar with the current code structure, we'd appreciate a general hint about where the feature should live if some controller-based option is chosen.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): v0.18.3
- Kubernetes version (use `kubectl version`): v1.24.x, v1.25.x
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Flatcar 3602.2.3

**Comment by chen-keinan** [comment]
@stone-z one  to continue with your idea on slack channel the delete secrets periodically, ans as I prefer this solution to api-machinery native , we can add ttl for each secret and use the TTL reconciler to delete it , similar to what we have with [report ttl](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/operator/ttl_report.go#L27) , wdyt?

**Comment by stone-z** [comment]
Hey @chen-keinan yeah that looks promising. We'll have a look
