### ISSUE TITLE
configurable appProtocol in metrics service

### ISSUE THREAD

**Issue by seekermarcel** [aquasecurity/trivy-operator#1866]
I want to scrape metrics from trivy via istio service mesh. Unfortunately it seems like trivy is not supporting HTTP2 which is the default in prometheus (and I don't want to change that).

Now I want to change the appProtocol of the trivy-operator metrics service to `http`. At the moment this is not configurable.

I would implement this feature myself ❤️

**Comment by chen-keinan** [comment]
@seekermarcel sure you can go for it and we could review it later
