### ISSUE TITLE
Cannot access images in regional private GCR

### ISSUE THREAD

**Issue by dnskr** [aquasecurity/trivy-operator#1868]
**What happened:**

Trivy Operator cannot access images stored in private GCR in EU region. I'm getting `the length of usernames and passwords must match` error for images stored in `eu.gcr.io`, for example `eu.gcr.io/<company_name>/<application_name>`.

The issue was reported several times (https://github.com/aquasecurity/trivy-operator/issues/1095 https://github.com/aquasecurity/trivy-operator/issues/1298) and fixed by PR https://github.com/aquasecurity/trivy-operator/pull/1404, but it looks like the fix works for `gcr.io/*` images only. So, probably `eu.gcr.io`, `us.gcr.io` and `asia.gcr.io` users still experience the issue.

**Anything else you would like to add:**

I would guess, the the issue can be easily solved by fixing the following regex:
https://github.com/aquasecurity/trivy-operator/blob/9800cd29d4941c9ef90ae7cdcee5ecd9bf5676bb/pkg/plugins/trivy/jobspec.go#L20
If so, I would like to contribute the fix.

**Environment:**

- Trivy-Operator Helm chart version: 0.20.6
- Trivy-Operator version (use `trivy-operator version`): 0.18.5
- Kubernetes version (use `kubectl version`): 1.27

**Comment by chen-keinan** [comment]
@dnskr contributions are welcome.
