### ISSUE TITLE
Publish helm chart(s) also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by mkilchhofer** [aquasecurity/trivy-operator#1887]
The helm chart of trivy-operator is published using the classic approach with a static webserver and an index.yaml (on a separate Repository https://github.com/aquasecurity/helm-charts).

```bash
$ helm repo add aqua https://aquasecurity.github.io/helm-charts/
$ helm install trivy-operator aqua/trivy-operator \
     --namespace trivy-system \
     --create-namespace \
     --version 0.20.6
```

In helm 3.8+ the OCI method went GA:
- https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html?m=1
- https://helm.sh/docs/topics/registries/
- https://github.com/helm/helm/releases/tag/v3.8.0

I'd like to see you pushing the packaged helm chart(s) also on ghcr.io, alongside the container images and trivy-db's.

There is existing code available from multiple Kubernetes projects which could easily adapted:
- [renovatebot/helm-charts](https://github.com/renovatebot/helm-charts/blob/5457a71d97e5318f3b5c152c332429ddf6a694a7/.github/workflows/release.yaml#L37-L44)
- [nextcloud/helm](https://github.com/nextcloud/helm/blob/9d560de6668ed393f8a8dfa84f5692352cf62ff3/.github/workflows/release.yaml#L39-L43)
- [cloudnative-pg/charts](https://github.com/cloudnative-pg/charts/blob/001d78758b864f8ffd42799f6f44760c0ca5a671/.github/workflows/release-publish.yml#L49)
- [argoproj/argo-helm](https://github.com/argoproj/argo-helm/blob/2f82fb5992fe1e390d1ebdbc4be6d5d6c6549a37/.github/configs/cr.yaml#L12)
- many more ;)

After one implemented this, users can easily install trivy-operator via:

```bash
helm install trivy-operator oci://ghcr.io/aquasecurity/charts/trivy-operator --version x.y.z
```

**Comment by chen-keinan** [comment]
@mkilchhofer contributions are welcom

**Comment by mkilchhofer** [comment]
> @mkilchhofer contributions are welcom

Alright 👍 , Created a PR for that: https://github.com/aquasecurity/trivy-operator/pull/1889
