### ISSUE TITLE
Reports vulnerabilities different between trivy local and trivy kubernetes

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#1890]
**What steps did you take and what happened:**

We checked that reports vulnerabilities are different between trivy local and trivy kubernetes

- We have tried to use **trivy local** to scan image (**some vulnerabilities are detected**)

```
$ trivy image ghcr.io/external-secrets/external-secrets:v0.6.1 --ignore-unfixed

ghcr.io/external-secrets/external-secrets:v0.6.1 (debian 11.5)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)


bin/external-secrets (gobinary)

Total: 11 (UNKNOWN: 0, LOW: 0, MEDIUM: 7, HIGH: 4, CRITICAL: 0)

```

- While report in **trivy that is installed in kubernetes** (**no detect any vulnerability**)
![image](https://github.com/aquasecurity/trivy-operator/assets/76929085/ebe819a3-2137-4d40-921c-28f0dda6a8b5)

Any suggestion to resolve this issue would be very much appreciated!

Thanks

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.3
- Kubernetes version (use `kubectl version`): 1.25
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@chary1112004 are you using `command = filesystem` in trivy-operator?

**Comment by chary1112004** [comment]
@chen-keinan yes, we are using 'command = filesystem' in trivy-operator

**Comment by chen-keinan** [comment]
> @chen-keinan yes, we are using `command = filesystem` in trivy-operator

then you'll have to run `trivy fs ...` command and check it results if you want to compare to your trivy operator similar to #1886

**Comment by chary1112004** [comment]
> > @chen-keinan yes, we are using `command = filesystem` in trivy-operator
> 
> then you'll have to run `trivy fs ...` command and check it results if you want to compare to your trivy-operator similar to #1886

@chen-keinan thank you for your information. I have checked the document then I saw that `fs` and `image` are scanning same files then they should be expected same result, isn't it?
- Vulnerabilities
- Misconfigurations
- Secrets
- Licenses

Scan list for `image`
![image](https://github.com/aquasecurity/trivy-operator/assets/76929085/2b2b9b1b-8bc2-4999-abb4-06fab56af317)

Scan list for `fs`
![image](https://github.com/aquasecurity/trivy-operator/assets/76929085/ffe6f172-1864-4d56-9e7c-43bcc745f9b4)

Regards

**Comment by chen-keinan** [comment]
@chary1112004 take a look at #1886 we had a similar discussion
