### ISSUE TITLE
Vulnerabilityreports not created when one image isn't scanable

### ISSUE THREAD

**Issue by Remsboys** [aquasecurity/trivy-operator#1901]
First of all: Thanks for your amazing work with this application!

**What steps did you take and what happened:**

If one image of a pod (inside a replicaset) isn't scanable, no vulnerabilityreports are created at all.

Example: A pod consists of 1 init-container and 2 containers (app and nginx sidecar). When the scan of the nginx fails with the following error log, the vulnerabilityreports for the main app and the init-container aren't created as well.

`{"level":"error","ts":"2024-03-08T16:55:24Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-77f9448bc9","container":"demo-api-nginx","status.reason":"Error","status.message":"2024-03-08T16:54:46.562Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: 4 errors occurred:\n\t* docker error: unable to inspect the image (registry/demo-nginx:1.25.3): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd error: containerd socket not found: /run/containerd/containerd.sock\n\t* podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* remote error: unsupported MediaType: \"application/vnd.docker.distribution.manifest.v1+prettyjws\", see [https://github.com/google/go-containerregistry/issues/377\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227](https://github.com/google/go-containerregistry/issues/377/n/n/n%22,%22stacktrace%22:%22github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob/n/t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346/ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1/n/t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81/nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile/n/t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile/n/t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler/n/t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem/n/t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266/nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2/n/t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227)"}`

**What did you expect to happen:**

The scan of the nginx image fails (reason of this is not a subject of this issue) but the reports for the init-container and main app are getting created.

**Environment:**

- Trivy-Operator version: 0.18.3
- Kubernetes version: 1.27.8
- OS: Ubuntu 20.04 LTS

**Comment by chen-keinan** [comment]
@Remsboys is this image `registry/demo-nginx:1.25.3` stored in private registry ?

**Comment by Remsboys** [comment]
@chen-keinan Yes, a harbor instance

**Comment by Remsboys** [comment]
@chen-keinan Thanks for your reply. Let me explain, why i don't share the same supposition:

- The scans are working properly for all other images from the same private repository (harbor), using the similar authentification types
- The particular images aren't scanable because of using a old docker manifest "unsupported MediaType: \"application/vnd.docker.distribution.manifest.v1+prettyjws\", "
- The issue or question is now, why all scans for images in the same pod are stopped / the vulnerabilityreports aren't created, if only one of the included images failes
- My wish would be, that i get a vulnerabilityreports for at least the "main" container as this is possible to scan. Thanks.

**Comment by chen-keinan** [comment]
@Remsboys  I see your problem , I'll have a look , we could ignore on image incase of failure

**Comment by chen-keinan** [comment]
@Remsboys I have created a fix #1917  for this issue it will be out with next release

**Comment by Remsboys** [comment]
@chen-keinan Thank you very much for the fast fix. I tested the new version thoroughly and can happily report, that it works perfect.

**Comment by chen-keinan** [comment]
@Remsboys thanks for the update
