### ISSUE TITLE
Provide Grafana Dashboard for Prometheus Metrics

### ISSUE THREAD

**Issue by Dentrax** [aquasecurity/trivy-operator#193]
I was playing with the operator and couldn't find a Grafana Dashboard JSON file. As discussed in the https://github.com/aquasecurity/trivy-operator/issues/78, I just noticed this feature is very new and almost 1-week-old. https://github.com/aquasecurity/trivy-operator/pull/96/files by @erikgb 

I propose we should provide a new Grafana Dashboard at [Configuration](https://aquasecurity.github.io/trivy-operator/v0.0.8/operator/configuration/) section in docs. (screenshot included)

Are there any example dashboards created before? If not, I can get to it.

**Comment by erikgb** [comment]
It would be nice to add a Grafana dashboard, at least to show users an example on how to use the metrics produced by the operator. We have a dashboard for our internal operator, that we want to replace with trivy-operator. @mikaello

**Comment by movd** [comment]
@devopstales created three dashboards for their implementation of a trivy operator ([trivy-operator](https://github.com/devopstales/trivy-operator)); maybe they can be used as a starting point? 

Screenshot:

![screenshot custom trivy exporter grafana dashboard](https://devopstales.github.io/img/include/trivy-exporter.png)

**Comment by chen-keinan** [comment]
look very nice 🚀

**Comment by nthienan** [comment]
Interesting. Looking forward to seeing the dashboard released soon.

**Comment by LucasVanHaaren** [comment]
Hello,

Any news about it ? Is someone working on it right now ?

**Comment by schnatterer** [comment]
My colleague @pmarkiewka and I created a first version of a trivy op dashboard similar to the devopstales one:
![image](https://user-images.githubusercontent.com/1824962/196412446-2a3d4dfd-494a-4c2e-8089-3335f8657283.png)
Uploading with Grafana failed, so for now the source can be found [in this gist](https://gist.github.com/schnatterer/a88a2d35436662cfb7d29dec6058c4d2).

We're still struggling with alerting, though. **Did anyone of you succeed in alerting for new CVEs?**
We tried it, but ran into the issue that PromQL `increase()` considers creation of new timeseries as reset: prometheus/prometheus#1673. So we would miss the first CVE of each image version ☹️

BTW We shared what we learned about trivy op on [myCloudogu](https://community.cloudogu.com/t/continuously-scan-your-kubernetes-cluster-for-security-issues-using-trivy-operator/962).

**Comment by LucasVanHaaren** [comment]
Awesome news @schnatterer !

I will try your dashboard and take a look for alerting for new CVE ASAP

**Comment by pschulten** [comment]
It would be super cool if it would be implemented as a [mixin](https://monitoring.mixins.dev/) so users can customize it easily and add the library to their existing workflows.

**Comment by sherifkayad** [comment]
Hello fellaz, I managed to find this one here https://grafana.com/grafana/dashboards/16337-trivy-starboard-operator-vulnerabilities/ .. Is that probably a compatible / comprehensive dashboard with the latest versions of Trivy?

Unfortunately I didn't try it out just yet.

**Comment by chen-keinan** [comment]
Dashboard available here.

**Comment by mikaello** [comment]
> Dashboard available here.

Did you mean to attach a link? "here" is just normal text.

**Comment by chen-keinan** [comment]
> > Dashboard available here.
> 
> @chen-keinan Did you mean to attach a link? "here" is just normal text.
thanks for catch up , link is updated
