### ISSUE TITLE
[trivy-operator v0.21.0 update issue] timed out waiting for cache to be synced, v1alpha1.RbacAssessmentReport 

### ISSUE THREAD

**Issue by cp319391** [aquasecurity/trivy-operator#1932]
**What steps did you take and what happened:**
while updating the trivy-operator to v0.21.0 from v0.20.6

Our trivy-operator is restarting every 2 - 3minutes. It exits with the following error message:
`error: unable to run trivy operator: starting controllers manager: [failed to wait for rbacassessmentreport caches to sync:
timed out waiting for cache to be synced for Kind *v1alpha1.RbacAssessmentReport, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]`

**What did you expect to happen:**
Pod runs stable.

Trivy-Operator version: v0.21.0

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): v0.21.0

**Comment by cp319391** [comment]
this was for `aquasecurity/helm-charts` raised it there https://github.com/aquasecurity/helm-charts/issues/9

**Comment by cp319391** [comment]
trying following as suggested by [chen-keinan](https://github.com/chen-keinan)  deleting all rbacassessmentreport from all resources and restart. 
 no worries report will automatically created.

**Comment by cp319391** [comment]
after deleting `rbacassessmentreport`, it gives following error on `trivy-operator`. 
`unable to run trivy operator: starting controllers manager: [failed to wait for job caches to sync:
timed out waiting for cache to be synced for Kind *v1.Job, failed waiting for all runnables to end within grace per`

we deleted all the Job under trivy and restarted, it gave following 

`unable to run trivy operator: starting controllers manager: [failed to wait for configmap caches to sync:
timed out waiting for cache to be synced for Kind *v1.ConfigMap,
failed waiting for all runnables to end with`

**Comment by chen-keinan** [comment]
> after deleting `rbacassessmentreport`, it gives following error on `trivy-operator`. `unable to run trivy operator: starting controllers manager: [failed to wait for job caches to sync: timed out waiting for cache to be synced for Kind *v1.Job, failed waiting for all runnables to end within grace per`
> 
> we deleted all the Job under trivy and restarted, it gave following
> 
> `unable to run trivy operator: starting controllers manager: [failed to wait for configmap caches to sync: timed out waiting for cache to be synced for Kind *v1.ConfigMap, failed waiting for all runnables to end with`

I do no think issue related to operator upgrade, I can make context timeout configurable to give it more time to sync.
how big is your cluster in term of resources(config-maps and etc) ?

**Comment by cp319391** [comment]
yes, I guess we can give it a try to configure `context timeout`. 
not that big, but a pretty decent cluster. for specific to trivy we have around 10 `configmaps`, otherwise 300. 
`rbacassesmentreports` around 200.
