### ISSUE TITLE
[feature request] Excessive Failed Scan Retries

### ISSUE THREAD

**Issue by Hacks4Snacks** [aquasecurity/trivy-operator#1945]
Today it seems there is no limit or gate on the number of retries a resource will undergo leading to runaway retry attempts if an image is unable to be scanned.

There should be a configurable option that supports skipping container images after N failures to prevent excessive retries (that may never succeed depending on the reason).

**Comment by chen-keinan** [comment]
@Hacks4Snacks contributions are welcome
