### ISSUE TITLE
Add install mode to watch namespaces matching labels

### ISSUE THREAD

**Issue by owngr** [aquasecurity/trivy-operator#1948]
Hello,

As a Kubernetes operator, I would like to have a mode where the operator watches for events in all namespaces matching a label. 

This would allow me to trust the developer to put it only when necessary, and I could still forbid the usage of it by having admission controller rules.

From what I saw a part of it could be easily implemented, the greatest challenge would be if we want the operator to clean after itself if a namespace doesn't match the label anymore, not sure if the other modes already do that, though.

**Comment by chen-keinan** [comment]
@owngr contributions are welcome

**Comment by owngr** [comment]
Perfect, I'll look into it
