### ISSUE TITLE
Metrics: container and pod values indicates trivy-operator itself

### ISSUE THREAD

**Issue by Dentrax** [aquasecurity/trivy-operator#196]
**What steps did you take and what happened:**

I would expect both `container` and `pod` keys should indicate the _scanned target_ instead.

```
trivy_vulnerabilityreport_image_vulnerabilities{container="trivy-operator", endpoint="metrics", image_registry="index.docker.io", image_repository="library/redis", image_tag="7.0.0-alpine", instance="10.233.66.171:8080", job="trivy-operator", name="replicaset-argocd-redis-75bdb869bf-redis", namespace="argocd", pod="trivy-operator-c859875c7-ltzxk", service="trivy-operator", severity="Critical"}
```

**What did you expect to happen:**

container: `redis` (Container that have scanned, should not trivy-operator itself)
pod: `argocd-redis-75bdb869bf-ktgn5` (Pod that have scanned, should not trivy-operator pod)

Actual:

All metrics have `container="trivy-operator"` and `pod="trivy-operator-<UUID>"` instead.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): `0.0.8`
- Kubernetes version (use `kubectl version`): `1.20.7`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): `Ubuntu 20.04.3`

**Comment by chen-keinan** [comment]
@Dentrax strange this two labels are not part of the [vulnerabilityreport matrics labels](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/metrics/collector.go#L18)

**Comment by Dentrax** [comment]
Oh, thanks for the code link, checked the Prometheus config and noticed there are metric relabeling configurations to mutate those labels. Sorry for the inconvenience, closing this one.
