### ISSUE TITLE
Bug with helm-release in kubernetess error during start

### ISSUE THREAD

**Issue by HenryAndry** [aquasecurity/trivy-operator#1961]
have error on pod in kubentess during start container:

`unable to run trivy operator: starting controllers manager: [failed to wait for job caches to sync: timed out waiting for cache to be synced for Kind *v1.Job, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
`
then i see next error:
`W0329 14:17:30.845455       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools
E0329 14:17:30.845700       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.ClusterSbomReport: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools
W0329 14:17:33.015510       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools
E0329 14:17:33.015790       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.ClusterSbomReport: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools
W0329 14:17:35.729185       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools
E0329 14:17:35.729235       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.ClusterSbomReport: failed to list *v1alpha1.ClusterSbomReport: json: cannot unmarshal array into Go struct field Metadata.items.report.components.metadata.tools of type v1alpha1.Tools`
**Environment:**
chart-version: 0.21.2
- Kubernetes version (use `kubectl version`): 1.26

**Comment by chen-keinan** [comment]
@HenryAndry have you followed breaking notes on release #1913

**Comment by cdenneen** [comment]
@chen-keinan can we have the chart updated to ship with a pre-install and pre-upgrade hook to delete old reports? This would solve all these upgrade issues I feel.

**Comment by chen-keinan** [comment]
@cdenneen can you please elaborate more on this

**Comment by chen-keinan** [comment]
Closing as duplicate #1398
