### ISSUE TITLE
 error failed to apply the ignorePolicy

### ISSUE THREAD

**Issue by KateFiroozi** [aquasecurity/trivy-operator#1986]
trivvy-operator logs following error messages:

filter error: filtering error: unable to filter vulnerabilities: failed to apply the policy: unable to prepare for eval: 1 error occurred: trivy.rego:0: rego_parse_error: empty module

I expect ignoPolicicy config from values file apply via configMap on scan jobs. It did work before.

Scan jobs pods being OOMKilled.

**Environment:**

- Trivy-Operator version: 0.19.3
- trivy-operator helm chart version: 0.21.3
- Kubernetes version: v1.28.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): AKSUbuntu-2204

**Comment by chen-keinan** [comment]
@KateFiroozi have you updated [resources](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L424-L431)

**Comment by KateFiroozi** [comment]
> @KateFiroozi have you updated [resources](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L424-L431)

Yes, this issue we had to solve as well:
``` # -- resources resource requests and limits for scan job containers
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      # ephemeralStorage: "2Gi"
    limits:
      cpu: ""
      memory: 1Gi
      # ephemeralStorage: "2Gi"
```

we have also managed to solve ignorePolicy with this workaround in values.yaml (although it should have not be necessary):

````
  # ignorePolicy: |
  #   # applies to all other workloads
   ignorePolicy.kube-system.azure-.: |
     package trivy

     import data.lib.trivy

     default ignore = true
````

**Comment by KateFiroozi** [comment]
I guess so, but can then docs be updated to have proper instructions?

**Comment by chen-keinan** [comment]
@KateFiroozi sure, would you like to raise a PR ?
