### ISSUE TITLE
Configuring trivy.javaDbRepository does not take effect

### ISSUE THREAD

**Issue by 528548004** [aquasecurity/trivy-operator#1995]
ConfigMap:
<img width="1025" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/69660180/e978be5b-8a5b-475a-8567-502ec6ca50f0">
ERRORLOG:
```2024-04-10T16:55:29.902407501+08:00 {"level":"error","ts":"2024-04-10T08:55:29Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-65d5cb94d9","container":"fa-0101-msa-ntd","status.reason":"Error","status.message":"2024-04-10T08:55:27.207Z\t\u001b[31mERROR\u001b[0m\tUnable to initialize the Java DB: Java DB update failed: Java DB update error: oci error: OCI repository error: Get \"https://ghcr.io/v2/\": dial tcp 20.205.243.164:443: i/o timeout\n2024-04-10T08:55:27.218Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:953dd63db8ae1abc23da2307657a863a410a68ef06c2548deb1dd8b61614d444): post analysis error: post analysis error: Java DB update failed: Java DB update error: oci error: OCI repository error: Get \"https://ghcr.io/v2/\": dial tcp 20.205.243.164:443: i/o timeout\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:254\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:79\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}```
Question:
Instead of using the repository I configured, it was ghcr.io
What else do I need to do to make it work
trivy-operator version:0.12.1
kubernetes version: 1.23.17

**Comment by chen-keinan** [comment]
@528548004 its not clear if you are using private or public registry setting for java DB , can you add more details ?

**Comment by 528548004** [comment]
> @528548004 its not clear if you are using private or public registry setting for java DB , can you add more details ?

I downloaded ghcr's java-db and pushed it to our private harbor, which I tested locally with no problem

**Comment by chen-keinan** [comment]
@528548004 if you use public registry it works only if you use private registry (harbor) it doesn't work, correct? 
another question does harbor registry require credentials ?

**Comment by 528548004** [comment]
@chen-keinan Yes, a public registry is fine, but I modified it to a private registry, and it doesn't work, still using the public one

**Comment by chen-keinan** [comment]
> @chen-keinan Yes, a public registry is fine, but I modified it to a private registry, and it doesn't work, still using the public one

what about second question? 
> does harbor registry require credentials ?

**Comment by 528548004** [comment]
> > @chen-keinan Yes, a public registry is fine, but I modified it to a private registry, and it doesn't work, still using the public one
> 
> what about second question?
> 
> > does harbor registry require credentials ?

When I use the trivy command locally, the java-db-repositry specified is available without credentials

**Comment by 528548004** [comment]
<img width="1304" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/69660180/6b69e6d2-5a72-45a8-bcea-fe5af9200014">

**Comment by chen-keinan** [comment]
what is the trivy CLI version that you are using ?

**Comment by 528548004** [comment]
trivy-version:0.49.1

**Comment by chen-keinan** [comment]
> trivy-operator version:0.12.1

I saw that you are using trivy-operator version:0.12.1 which is very old one and use old trivy (v0.38.2)
wonder if it worth using latest operator with latest trivy incase some bugs were fixed in between

**Comment by 528548004** [comment]
> > trivy-operator version:0.12.1
> 
> I notice you are using `trivy-operator version:0.12.1` which is very old one and use old trivy (`v0.38.2`) wonder if it worth using latest operator with latest trivy incase some bugs were fixed in between

Problem solved, trivy-operator version: 0.12.1 did not add option: java-db-repository, it was only supported in version 0.13.2, thanks

**Comment by chen-keinan** [comment]
Closing following to comment from @528548004
