### ISSUE TITLE
Scan job tolerations set universally in helm chart instead of specific to certain scanners

### ISSUE THREAD

**Issue by Starttoaster** [aquasecurity/trivy-operator#1998]
Looking at:
https://github.com/aquasecurity/trivy-operator/blob/ba16b5731319572c4816e6e9e9018f5546d23711/deploy/helm/values.yaml#L231

```
  # -- scanJobTolerations tolerations to be applied to the scanner pods and node-collector so that they can run on nodes with matching taints
  scanJobTolerations: []
```

I just want tolerations applied to the node-collector Jobs because it wants to be scheduled on my controller nodes. Adding tolerations to the regular image scan jobs is not something I would like to do. It would be nice if these tolerations didn't apply to multiple sets of scanner type jobs. I don't want to run any workload that doesn't _need_ to be on a k8s controller on my k8s controllers.

**Comment by chen-keinan** [comment]
@Starttoaster please elaborate on this more, if your Nodes has taints how would scan-job be schedule on NOde if it do not have tolerations

**Comment by Starttoaster** [comment]
> @Starttoaster please elaborate on this more, if your Nodes has taints how would scan-job be schedule on Node if it do not have tolerations

That's the thing, the image scanners just run on my workers. This node scanner is the only thing that wants to be scheduled on my controller nodes. Hence, I'd like to control their tolerations separately.

**Comment by Starttoaster** [comment]
That was really quick! Thank you!
