### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by githubcdr** [aquasecurity/trivy-operator#2028]
**What steps did you take and what happened:**

After upgrading to version 0.20.0 I noticed that the trivy-operator process consumes a lot more memory. Previous version was able to run with 600Mb, Now I have to add at least 1G wit a steady 800Mi usage under load.

Why would an operator consume so much memory? It's just orchestrating scanners or is it?

- Trivy-Operator version 0.20.0
- Kubernetes version 1.29.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): talos linux

**Comment by chen-keinan** [comment]
@githubcdr it should no consume more memory than usual, the operator framework cache reports in order to improve performance but should be any additional effort on that area, are you getting errors in logs ?
