### ISSUE TITLE
Use controller-gen to generate code/configuration from Go markers

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#204]
I notice that trivy-operator uses [code-generator](https://github.com/kubernetes/code-generator) to generate code for API types. While most of the controllers/operators I work with, both open-source and in-house, uses [controller-gen](https://github.com/kubernetes-sigs/controller-tools). As I see it, controller-gen seems better suited for developing/maintaining 3. party controllers/operators, while code-generator seems more for in-tree API/controllers.

Is there any particular reason for using code-generator over controller-gen? If not, I will suggest to migrate to controller-gen through issues/PRs. It will allow us to generate CRDs and controller-manager RBAC role from markers in the api/controller Go-code, in addition to the deep-copy funcs that also code-generator generates. It seems like the only feature that would get lost in such migration is the generated clientsets, informers and listers. But are these in use? It seems like they are not in use by the trivy-operator, and I think it is unlikely that other projects pull in this code as a dependency - since they will get issues with transitive dependencies to apimachinery etc.

The best available documentation for controller-gen I have found, is part of the kubebuilder book: https://book.kubebuilder.io/reference/markers.html.

If we decide to move forward with this, I would suggest a stepwise approach in the lines of:

1. Replace code-generator with controller-gen for generating the required deep-copy funcs. This will also include deleting all other generated code: https://github.com/aquasecurity/trivy-operator/tree/main/pkg/generated
2. Generate the trivy-operator CRDs from markers in code.
3. Generate the trivy-operator ClusterRole from markers in code. (Related issue https://github.com/aquasecurity/trivy-operator/issues/187)

**Comment by chen-keinan** [comment]
@erikgb you can pick up this issue and raise a draft PR to be able to continue with evaluating the change
