### ISSUE TITLE
trivy-operator - error: json: cannot unmarshal number into Go value of type trivy.ScanReport

### ISSUE THREAD

**Issue by flngen** [aquasecurity/trivy-operator#206]
**What steps did you take and what happened:**

Installed trivy-operator 0.0.8 via helm on k8s v1.19.8. Ran:

```
kubectl logs -n trivy-system deployment/trivy-operator 
```
and observed the following in the log:

"stacktrace": "sigs.k8s.io/controller-runtime/pkg/interna/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/interna/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"

**What did you expect to happen:**

I expected to see vulnerability reports when running:

```
kubectl get vulnerabilityreports --all-namespaces -o wide
```

**Anything else you would like to add:**

I do see that vulnerability reports (scan jobs) run successfully and report vulns in the logs, however I am unable to retrieve them with the aforementioned kubectl command

**Environment:**

- Trivy-Operator version 0.0.8
- Kubernetes version 1.19.8:

**Comment by chen-keinan** [comment]
@flngen can you provide more info.
- are you getting this output `No resources found` ? 
- are you able to confirm that a vulnerability report has been generated via `kubectl get vulnerabilityreports --all-namespaces` ?

**Comment by flngen** [comment]
I get a "No resources found"; however if I run: kubectl -n trivy-system get pods, I see the "scan" pods listed, and when I run $ kubectl -n trivy-system logs <pod-name>, I see vulnerabilities in json format.

**Comment by flngen** [comment]
Ok I think we're talking in circles here. I get what you're saying that they're supposed to be persisted. That's the whole point, they are not. The error log is what I posted initially on the log. Please reread it. Something about unmarshalling something. 

The pods that start with "scan-<something-random>" for certain contain vulnerabilities in their logs. When you run the command I mention in the previous post, you see the full trivy vuln report, with a bunch of CVEs. However, I'd like to see them when I run ```kubectl get vulnerabilityreports --all-namespaces -o wide```. That's the whole point of this bug report.

**Comment by chen-keinan** [comment]
ok , we both understand that the issue is with the persistence, I tried to reproduce it but with no luck , can you provide a bigger context of the error log few line before / after , or even better if you are ok to share the vulnerability json output , so I could debug it.

**Comment by ollide** [comment]
I have exactly the same problem, but only when I deploy the operator with `trivy.mode: "ClientServer"`.

@flngen Do you by chance also use the ClientServer mode?

**Environment:**
- Trivy-Operator Chart Version 0.0.8
- Trivy Chart Version 0.4.15
- Kubernetes version 1.23.3 (Minikube)

**Comment by erikgb** [comment]
Just a "shot in the dark" from me, but could the issue be related to some kind of mismatch between the client and server versions of trivy? The error message sounds like a problem with unmarshalling.....

**Comment by ollide** [comment]
So far, I've tried it with Trivy 0.29.1 and 0.28.1 - both result in the unmarshal error.

I've been successfully using this setup with the Starboard Operator + Trivy in ClientServer mode before.

**Comment by chen-keinan** [comment]
@ollide there was a bug with client-server #190  mode which we fixed and to be released later on today with trivy-operator v0.1.0

**Comment by ollide** [comment]
I can confirm that it works with the v0.1.0 release. Thanks a lot! :+1:

**Comment by flngen** [comment]
> I have exactly the same problem, but only when I deploy the operator with `trivy.mode: "ClientServer"`.
> 
> @flngen Do you by chance also use the ClientServer mode?
> 
> **Environment:**
> 
> * Trivy-Operator Chart Version 0.0.8
> * Trivy Chart Version 0.4.15
> * Kubernetes version 1.23.3 (Minikube)

yea I'm running in ClientServer mode as well. I'll try the new version.

**Comment by chen-keinan** [comment]
this issue ` x509 certificate verification error the scan-vulnerabilityreport batch jobs experience` has also been fixed with trivy-operator 0.1.0

**Comment by flngen** [comment]
excellent ... I'll try it. I can confirm that it works in Standalone mode if I create my own trivy scanner image with my ca-bundle in /etc/ssl/certs/ca-certificates.crt. (trivy-operator 0.0.8). I'll update once I try 0.1.0.

**Comment by chen-keinan** [comment]
> excellent ... I'll try it. I can confirm that it works in Standalone mode if I create my own trivy scanner image with my ca-bundle in /etc/ssl/certs/ca-certificates.crt. (trivy-operator 0.0.8). I'll update once I try 0.1.0.

checkout setting for [x509 issue self sign](https://github.com/aquasecurity/trivy-operator/issues/127)

**Comment by VF-mbrauer** [comment]
I have updated to 0.1.0 and still running into these issues with the `standalone` mode
```
{"level":"error","ts":1657222140.634892,"msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","job":{"name":"scan-vulnerabilityreport-
547874795b","namespace":"trivy-operator"},"namespace":"trivy-operator","name":"scan-vulnerabilityreport-
547874795b","reconcileID":"1148df3f-f25a-444d-8b02-bd5de0cd3346","error":"json: cannot unmarshal string 
into Go value of type trivy.ScanReport","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.
(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-
runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.
(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-
runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
```

@chen-keinan: FYI

**Comment by chen-keinan** [comment]
@VF-mbrauer are you running is air-gapped env. ?

**Comment by chen-keinan** [comment]
@VF-mbrauer yes go ahead and split the issue

**Comment by VF-mbrauer** [comment]
> In the former Starboard Operator, I have not seen this issue at all. Everything was running smoothly without this issue.
> 
> @chen-keinan, @erikgb FYI.

I need to revert my statement. I see it also in the `starboard-operator`. So the same issue is also there.

**Comment by chen-keinan** [comment]
@VF-mbrauer I wouldn't expect to be different as the way we read the logs from Pod has not been changed.
we are losing  part of the json output on huge reports.

**Comment by VF-mbrauer** [comment]
@flngen which Operating System do you use underneath?

**Comment by VF-mbrauer** [comment]
After some tests, we found out that the issue is based on the containers log file rotation based on the size
```
--container-log-max-size string     Default: 10Mi
```

For a test we changed the kublet configuration to for example **30Mi**
Now the scanner can continuously write the vulnerabilities without getting interrupted it works.
Because when Trivy tries to stream to logs from the pod, it streams the new log which obviously will fail unmarshal (as it does not include the full report).

This can be used as a workaround to overcome this issue, but the better option would be to temporarily saved it on Filesystem (fs) to avoid the interruption.

@erikgb, @chen-keinan : cc

**Comment by chen-keinan** [comment]
> This can be used as a workaround to overcome this issue, but the better option would be to temporarily saved it on Filesystem (fs) to avoid the interruption.
> 

@VF-mbrauer thank you for checking it. I have open an item for long term solution

**Comment by MalteMagnussen** [comment]
```bash
(devenv) (venv) mhm@mhm:~/Documents/asset-search$ trivy -v    
Version: dev
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-09-10 12:15:45.179806233 +0000 UTC
  NextUpdate: 2024-09-10 18:15:45.179805872 +0000 UTC
  DownloadedAt: 2024-09-10 12:56:15.157477753 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2024-09-10 01:07:11.89544985 +0000 UTC
  NextUpdate: 2024-09-13 01:07:11.89544969 +0000 UTC
  DownloadedAt: 2024-09-10 13:02:34.42712956 +0000 UTC
(devenv) (venv) mhm@mhm:~/Documents/asset-search$ trivy image harbor.private.registry/opentofu
2024-09-10T15:05:10+02:00	INFO	[vuln] Vulnerability scanning is enabled
2024-09-10T15:05:10+02:00	INFO	[secret] Secret scanning is enabled
2024-09-10T15:05:10+02:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-09-10T15:05:10+02:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret#recommendation for faster secret detection
2024-09-10T15:05:11+02:00	INFO	Detected OS	family="ubuntu" version="22.04"
2024-09-10T15:05:11+02:00	INFO	[ubuntu] Detecting vulnerabilities...	os_version="22.04" pkg_num=474
2024-09-10T15:05:11+02:00	FATAL	Fatal error	image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages: failed vulnerability detection of OS packages: failed detection: failed to get Ubuntu advisories: failed to get Ubuntu advisories: failed to unmarshal advisory JSON: json: cannot unmarshal string into Go struct field dbAdvisory.Status of type int
```

This started when there was added "echo" statements to the entrypoint script.

@chen-keinan - Maybe this issue is not 100% fixed yet?
