### ISSUE TITLE
Trivy report is different with same image version with different number of instances 

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#2062]
**What steps did you take and what happened:**

Hi,

We saw there is issue when we configure trivy.command = rootfs then the report is different with same image version. The different is one is with 1 instance, another one is with 2 instances (it seems with 2 instances in same namespace it will make sum for all instances)

One is with 1 instance
![image](https://github.com/aquasecurity/trivy-operator/assets/76929085/e9eb2902-a542-41af-bc68-eb7a931ced58)

Another one is with 2 instances
![image](https://github.com/aquasecurity/trivy-operator/assets/76929085/3ef10b90-c20a-4225-b4a6-5037e40c3c2e)

Any suggestion to resolve this issue would be very much appreciated!

Thanks!

**What did you expect to happen:**
Report should be same for scanning same image version

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.19.0
- Kubernetes version (use `kubectl version`): 1.29
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@chary1112004 you mean two containers on same resource ?

**Comment by chary1112004** [comment]
@chen-keinan I mean 2 pods in same namespace. For example: pod mongodb-0 and mongodb-1 (one is primary, another one is secondary)

**Comment by chen-keinan** [comment]
@chary1112004 are you getting the same results if you are running? :
`kubetel get vulns -n dev`

**Comment by chary1112004** [comment]
@chen-keinan here are the results. Output are different, in dev there is arbiter, in feature-1 there is no arbiter. This could be the point, not number of instance.
```
$ kubectl get vulns -n dev
NAME                                                              REPOSITORY                                             TAG                    SCANNER   AGE
statefulset-mongodb-arbiter-mongodb-arbiter                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     6h26m
statefulset-mongodb-metrics                                       bitnami/mongodb-exporter                               0.40.0-debian-12-r16   Trivy     17h
statefulset-mongodb-mongodb                                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     17h

$ kubectl get vulns -n feature-1
statefulset-mongodb-mongodb                                       bitnami/mongodb                             7.0.9-debian-12-r1   Trivy     16h
```

**Comment by chen-keinan** [comment]
> @chen-keinan here are the results. Output are different, in dev there is arbiter, in feature-1 there is no arbiter. This could be the point, not number of instance.
> 
> ```
> $ kubectl get vulns -n dev
> NAME                                                              REPOSITORY                                             TAG                    SCANNER   AGE
> statefulset-mongodb-arbiter-mongodb-arbiter                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     6h26m
> statefulset-mongodb-metrics                                       bitnami/mongodb-exporter                               0.40.0-debian-12-r16   Trivy     17h
> statefulset-mongodb-mongodb                                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     17h
> 
> $ kubectl get vulns -n feature-1
> statefulset-mongodb-mongodb                                       bitnami/mongodb                             7.0.9-debian-12-r1   Trivy     16h
> ```

@chary1112004 forget to add output, do you mind running it again with the output wide:
```
kubectl get vulns -n dev -o wide
```

**Comment by chary1112004** [comment]
@chen-keinan here are outputs

```
$ kubectl get vulns -n dev -o wide
statefulset-mongodb-arbiter-mongodb-arbiter                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     6h57m   1          1      14       0     0
statefulset-mongodb-metrics                                       bitnami/mongodb-exporter                               0.40.0-debian-12-r16   Trivy     18h     1          3      14       0     0
statefulset-mongodb-mongodb                                       bitnami/mongodb                                        7.0.9-debian-12-r1     Trivy     18h     1          1      14       0     0

$ kubectl get vulns -n feature-1 -o wide
statefulset-mongodb-mongodb                                       bitnami/mongodb                             7.0.9-debian-12-r1   Trivy     17h     1          1      14       0     0
```

**Comment by chen-keinan** [comment]
@chary1112004 based on the output you put above the reports looks ok with accurate data , could be metrics setting on grafana issue ?

**Comment by chary1112004** [comment]
@chen-keinan thank you. I will check on grafana dashboard. So I close this ticket. Thanks!
