### ISSUE TITLE
CI should verify that all generated is up-to-date

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#207]
CI currently checks that the code generated by code-generator is up-to-date: https://github.com/aquasecurity/trivy-operator/blob/main/.github/workflows/build.yaml#L70-L71.

Since the static trivy-operator resources now are generated from the Helm chart, after https://github.com/aquasecurity/trivy-operator/pull/176 (and https://github.com/aquasecurity/trivy-operator/pull/185), I think it makes sense to include checks for that as well in our CI. (And also any other generated code/files that I might not be aware of...)

That will ensure a better contributor experience, since the CI for a PR will fail if this is forgotten by the PR author. We should ensure the error message is clear and informative, to lead the PR author to the corrective action.

Related PR, as an example on why we need this: https://github.com/aquasecurity/trivy-operator/pull/195

Also relevant issue: https://github.com/aquasecurity/trivy-operator/issues/204

**Comment by chen-keinan** [comment]
When thinking about it again , I'm not sure we should commit the static files , probably better add them to .gitignore.
as it used only for testing and development , we can generate it ad hoc, as long as we have the script to do it correctly.
`testing` - during ci pipeline
`dev` - locally 

I believe it will simplified, maintenance , dev and release

**Comment by erikgb** [comment]
> When thinking about it again , I'm not sure we should commit the static files , probably better add them to .gitignore. as it used only for testing and development , we can generate it ad hoc, as long as we have the script to do it correctly. `testing` - during ci pipeline `dev` - locally

Well, this is an interesting idea. IMO Helm is quite opinionated, and I know that a lot of users would prefer to avoid it. So personally I think we should officially support multiple options for installing trivy-operator. But I agree that supporting multiple installation approaches will require more from maintainers and contributors.

**Comment by chen-keinan** [comment]
I assume that a users who want to use another method of deployment can always run the script (we need to keep the script updated) and auto generate these deployment files (should be also very cleared in documentation).

**Comment by josedonizetti** [comment]
We could test the idea, support helm only and see what feedback we get, we can always return the statics.

**Comment by badgerspoke** [comment]
> We could test the idea, support helm only and see what feedback we get, we can always return the statics.

Sorry to necropost (this seems to be the closest issue to my concern around static manifest), but can I ask why _some_ of the static manifests were removed but not all?

The [docs still say](https://aquasecurity.github.io/trivy-operator/latest/getting-started/installation/kubectl/) that installing via the hosted manifest is valid but of course there's a load of fu that is missing, for example if we want to enable client-server mode the `StatefulSet` and associated `Service` are missing entirely because when using helm they get generated automatically based on the config.

We can generate the full manifest from helm and then import/kustomize/model as required but the docs are misleading at best on this topic.

**Comment by chen-keinan** [comment]
@badgerspoke its true, the manifest currently represent default setting same as you run helm install without setting specific params.

in order the get a customized manifest you'll need to to update helm values.yaml and run:
```sh
mage generate:all
```
I agree that docs need to be update as it doesn't address custom changes support.
feel free to raise a PR for it.

**Comment by badgerspoke** [comment]
Yeah it's impossible for you to cover all the options with a static manifest of course.
I was just a bit confused about some missing resources. I can't promise anything but I will see if I can find time for a PR

**Comment by chen-keinan** [comment]
@badgerspoke great, if you do not have time let me know and I'll add it.
your feedback would be helpful for other users as well.
