### ISSUE TITLE
Make the trivy-operator-policies-config config map optional in the helm chart

### ISSUE THREAD

**Issue by lsoica** [aquasecurity/trivy-operator#2098]
The trivy-operator-policies-config is a hardcoded name. The CM is created by default, without the option to disable it. Adding a feature flag to disable the CM creation from the CM would allow a consumer to provide the CM from an external source.

This helps with providing custom rego policies as the only option currently is to provide them as a multi line string as helm extra values.

**Comment by chen-keinan** [comment]
@lsoica contribution are welcome if you have time
