### ISSUE TITLE
scanJobAnnotations apply to the Pod only and not the Job

### ISSUE THREAD

**Issue by darkhelmet** [aquasecurity/trivy-operator#2109]
**What steps did you take and what happened:**

Trying to configure annotations to make botkube ignore the scanning activity. The notifications get noisy for us, and I don't need to hear about Trivy starting up all the time.

**What did you expect to happen:**

When using the `trivyOperator.scanJobAnnotations` value when configuring the operator helm chart, I would expect those annotations to apply to the Job resource, given the name.

**Anything else you would like to add:**

I imagine there is a case where you'd want to configure the Pod and Job annotations separately, so maybe it makes sense to have configuration for both, but applying the `scanJobAnnotations` to the actual Job resources seems like a good step.

An alternative is we configure botkube to ignore the triv-system namespace we have Trivy installed in, but the annotations should probably work here too.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.21.1
- Kubernetes version (use `kubectl version`): 1.28.9 EKS
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A

**Comment by chen-keinan** [comment]
@darkhelmet could be a nice enhancement, you can pick it up if you have time.
