### ISSUE TITLE
How to Ignore Specific exposed secret in Trivy-Operator?

### ISSUE THREAD

**Issue by mpv001** [aquasecurity/trivy-operator#2116]
**What steps did you take and what happened:**

I've been reviewing the `exposedsecretreport` for `ghcr.io/zalando/spilo-15` and noticed that it has the `ssl-cert-snakeoil.key` file, Trivy-operator is flagging it as a potential exposed secret. 

We also tried ignoring the key by implementing `ignoreFile`, `skipFiles`, but it did not work.

Flagged `exposedsecretreport`:

```
Secrets:
Category:  Asymmetric Private Key 
Match:     -----BEGIN PRIVATE KEY-----***********************************************-----END PRIVATE KEY
Rule ID:   private-key                     
Severity:  HIGH                                                                                                                            
Target:    /etc/ssl/private/ssl-cert-snakeoil.key          
Title:     Asymmetric Private Key
```

**What did you expect to happen:**

We are currently running Trivy-Operator on our Kubernetes cluster and to effectively manage security findings and reduce false positives, we need to configure Trivy-Operator to ignore specific exposed secret.

Is there any way to ignore alerts for exposed secrets in trivy-operator.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): v1.21.1
- Kubernetes version (use `kubectl version`): v1.26.11

**Comment by chen-keinan** [comment]
@mpv001 you use `.trivyignore` file:
```
# Ignore these rules
generic-unwanted-rule
aws-account-id
```

**Comment by mpv001** [comment]
We are using Trivy-operator and have added the below flag in the helm values as per operator documentation. However, we are still seeing the alert that it is not ignoring the key.

```
ignoreFile:
    - "AsymmetricPrivateKey"
```

**Comment by manikcoco** [comment]
@mpv001 are you able to ignore the exposed secret through `.trivyignore` file?

**Comment by chen-keinan** [comment]
@manikcoco @mpv001 tested it with this image `chenkeinan/image-secret-issue:1`
and ignore rule and find it working.
```yaml
 ignoreFile:
   - aws-secret-access-key
```
