### ISSUE TITLE
Installation with Helm and OLM have different  version in node.collector.imageRef:  ghcr.io/aquasecurity/node-collector

### ISSUE THREAD

**Issue by Jeansen** [aquasecurity/trivy-operator#2135]
**What steps did you take and what happened:**

Did two separate installations, that is, I installed trivy operator via helm, reset my cluster to a previous snapshot and installed trivy operator via OLM.

**What did you expect to happen:**

I had expected both installations use the same configuration.

**Anything else you would like to add:**

But what I found is that with helm the operator CM has the following entry:

`node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.2.1`

The installation via OLM on the contrary shows:

`node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.1.2`

**Environment:**

- Trivy-Operator version (0.21.3):
- Kubernetes version (1.30.0):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Debian 12

**Comment by chen-keinan** [comment]
Fixed by #2138
