### ISSUE TITLE
unable to run trivy operator: starting controllers manager: failed to wait for cronjob caches to sync: timed out waiting for cache to be synced

### ISSUE THREAD

**Issue by chaitrag4n** [aquasecurity/trivy-operator#2136]
I m deploying the latest trivy operator in my k8s cluster for security scanning but the operator pod keep restarting with the following error 
`{"level":"error","ts":1718101676.3287468,"msg":"Reconciler error","controller":"replicaset","controllerGroup":"apps","controllerKind":"ReplicaSet","replicaSet":{"name":"sgunturin-rwc-hop-17583-d000442b-2-6dc5dccb4b","namespace":"shared-endpoints"},"namespace":"shared-endpoints","name":"sgunturin-rwc-hop-17583-d000442b-2-6dc5dccb4b","reconcileID":"82822267-edee-4dea-8993-b4d16cb5f500","error":"getting service account by name: shared-endpoints/default: client rate limiter Wait returned an error: context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1718101676.3292227,"msg":"Reconciler error","controller":"replicaset","controllerGroup":"apps","controllerKind":"ReplicaSet","replicaSet":{"name":"demo-iso2-rwc-develop-70928db8-706-f894b84c8","namespace":"shared-endpoints"},"namespace":"shared-endpoints","name":"demo-iso2-rwc-develop-70928db8-706-f894b84c8","reconcileID":"5d663c1e-acd4-4d2c-bb80-299e877c45d6","error":"getting service account by name: shared-endpoints/default: client rate limiter Wait returned an error: context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"info","ts":1718101676.332867,"msg":"All workers finished","controller":"replicaset","controllerGroup":"apps","controllerKind":"ReplicaSet"}
{"level":"info","ts":1718101676.3328931,"msg":"Stopping and waiting for caches"}
{"level":"info","ts":1718101676.333098,"msg":"Stopping and waiting for webhooks"}
{"level":"info","ts":1718101676.3331146,"msg":"Wait completed, proceeding to shutdown the manager"}
unable to run trivy operator: starting controllers manager: failed to wait for cronjob caches to sync: timed out waiting for cache to be synced`

current status 
kubectl get all -n trivy-operator
NAME                                  READY   STATUS             RESTARTS       AGE
pod/trivy-operator-6d47b8b456-9zqcb   0/1     CrashLoopBackOff   10 (64s ago)   49m

NAME                     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/trivy-operator   ClusterIP   None         <none>        80/TCP    49m

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/trivy-operator   0/1     1            0           49m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/trivy-operator-6d47b8b456   1         1         0       49m

Also for some reasons i dont see vulnerabilityreports no matter what changes i do following the previous issues. 
 kubectl get vulnerabilityreports --all-namespaces -o wide
No resources found

Kindly help

**Comment by Jeansen** [comment]
How do you deploy the operator and what Kubernetes versions are you using?

Also, `getting service account by name` in the log above indicates to me that something is not right with your RBAC.

**Comment by chaitrag4n** [comment]
Im deploying using helm chart and argocd and using the latest version 
version: 0.23.3
appVersion: 0.21.3


what do you mean by this? "Also, getting service account by name in the log above indicates to me that something is not right with your RBAC." 

Please tell me how do I fix it

**Comment by Jeansen** [comment]
I think that something is blocking your deployment with respect to your RBAC settings. If you deploy with helm, how does your values.yaml look like? And what Kubernetes cluster are you using? For me, Helm deployment just works fine, btw, without any special settings in addition.
