### ISSUE TITLE
Could not wait for Cache to sync	{"controller": "cronjob", "controllerGroup": "batch", "controllerKind": "CronJob", "error": "failed to wait for cronjob caches to sync: timed out waiting for cache to be synced"}

### ISSUE THREAD

**Issue by chaitrag4n** [aquasecurity/trivy-operator#2141]
Upgraded to helm version 0.23.3
Deployed the app using argocd with version 0.23.3 and appverions 0.21.3

I dont see any jobs running for scanning
`kubectl get all -n trivy-operator
NAME                                  READY   STATUS             RESTARTS        AGE
pod/trivy-operator-6b9b4cc854-5g7dh   0/1     CrashLoopBackOff   7 (56s ago)     35m
pod/trivy-operator-6b9b4cc854-nmfvf   0/1     CrashLoopBackOff   8 (3m46s ago)   54m

NAME                     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/trivy-operator   ClusterIP   None         <none>        80/TCP    54m

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/trivy-operator   0/2     2            0           54m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/trivy-operator-6b9b4cc854   2         2         0       54m
`

but pods keep restarting with following error 
1.7183488849295952e+09	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "CronJob.batch", "error": "no matches for kind \"CronJob\" in version \"batch/v1beta1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext

unable to run trivy operator: starting controllers manager: failed to wait for cronjob caches to sync: timed out waiting for cache to be synced

- Trivy-Operator version (use `trivy-operator version`): 0.21.3
- Kubernetes version (use `kubectl version`): 1.30
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Macos

**Comment by chen-keinan** [comment]
@chaitrag4n do you have jobs running in the cluster trivy-operator namespace
```sh
kubectl get jobs -n trivy-operator
```
