### ISSUE TITLE
Redundancy of privateRegistryScanSecretsNames

### ISSUE THREAD

**Issue by Ais8Ooz8** [aquasecurity/trivy-operator#2150]
If image scans are made from the same cluster where they are running, then they already exist on the nodes. Is it possible not to request them again from public/private registries, but to take them from the cluster nodes? What disadvantages do you see in this approach?

**Comment by chen-keinan** [comment]
@Ais8Ooz8 in that case the scan-job will have to run on the same node of the image ?
