### ISSUE TITLE
Regular auto-updates of Trivy databases

### ISSUE THREAD

**Issue by Ais8Ooz8** [aquasecurity/trivy-operator#2151]
It is not entirely clear from the [documentation](https://aquasecurity.github.io/trivy-operator/latest/docs/vulnerability-scanning/trivy/) how up-to-date the databases are used and how often they are updated. For example, by default we download the database every time through the init container:

> Each Pod created by a scan Job has the init container that downloads the Trivy vulnerabilities database from the GitHub releases page and stores it in the local file system of the emptyDir volume. This volume is then shared with containers that perform the actual scanning. Finally, the Pod is deleted along with the emptyDir volume.

Another option is to set ```builtInTrivyServer: true```, but how often will the databases be updated? I think this should be described a little more transparently in the documentation.

**Comment by sheeeng** [comment]
> Another option is to set `builtInTrivyServer: true`, but how often will the databases be updated?

See https://github.com/aquasecurity/trivy-operator/discussions/2096.

> I think this should be described a little more transparently in the documentation.

I agree that the documentation is lacking these details.

**Comment by chen-keinan** [comment]
@sheeeng @Ais8Ooz8 contributions are welcome if you have time
