### ISSUE TITLE
Null values for some .spec.compliance.controls.checks in ClusterComplianceReport resources in the helm chart v0.24.0

### ISSUE THREAD

**Issue by verdel** [aquasecurity/trivy-operator#2167]
In version `0.23.3` of the helm chart, in the `ClusterComplianceReport` resource, if the `checks` array was empty in one of the elements of the `.spec.compliance.controls` block, the `checks` key was simply [absent](https://github.com/aquasecurity/trivy-operator/blob/e33caa6a1b8c3e305a45aeead4a0d8ca58d6e310/deploy/helm/templates/specs/cis-1.23.yaml#L459-L465). In version `0.24.0` of the chart, the `checks` key is [present](https://github.com/aquasecurity/trivy-operator/blob/0dead554cc5cc9fb1ca7bd671f86a65e00fce39c/deploy/helm/templates/specs/k8s-cis-1.23.yaml#L505-L512) with a `null` value. As a result, the `ClusterComplianceReport` resource fails schema validation when applying the CRD, because the CRD [specifies](https://github.com/aquasecurity/trivy-operator/blob/0dead554cc5cc9fb1ca7bd671f86a65e00fce39c/deploy/helm/crds/aquasecurity.github.io_clustercompliancereports.yaml#L67-L81) that the value of the checks key can only be an array.

This issue is present in the files:
- `templates/specs/eks-cis-1.4.yaml`
- `templates/specs/k8s-cis-1.23.yaml`
- `templates/specs/rke2-cis-1.24.yaml`

**Environment:**

- Trivy-Operator version : v0.22.0
- Trivy-Operator helm chart version: v.0.24.0

**Comment by chen-keinan** [comment]
@verdel thanks for catch up, I'll add a fix now

**Comment by verdel** [comment]
@chen-keinan, I can open a PR if that would be more convenient.

**Comment by chen-keinan** [comment]
sure go for it
