### ISSUE TITLE
trivy-operator pod crash

### ISSUE THREAD

**Issue by alejandropriv** [aquasecurity/trivy-operator#2170]
**What steps did you take and what happened:**

I did a installation of the trivy-operator following the official tutorials
I used the following configuration file:

    operator:
      privateRegistryScanSecretsNames: {"abc":"bcd"}
      logDevMode: true
      scanJobsConcurrentLimit: 10
      scanJobsRetryDelay: 30s 
      scannerReportTTL: "10m"
      cacheReportTTL: "120h"
      sbomGenerationEnabled: false 
      clusterSbomCacheEnabled: false 
      configAuditScannerEnabled: true 
      rbacAssessmentScannerEnabled: true 
      infraAssessmentScannerEnabled: true 
      clusterComplianceEnabled: true 
      storageClassEnabled: true
      storageClassName: ""
      additionalVulnerabilityReportFields: ""
      metricsVulnIdEnabled: true
      metricsExposedSecretInfo: true
      metricsConfigAuditInfo: true
      metricsRbacAssessmentInfo: true
      metricsInfraAssessmentInfo: true
      metricsImageInfo: true
      metricsClusterComplianceInfo: true

    serviceMonitor:
      enabled: true
      labels: {"abc":"bcd"}
    
    trivy:
      severity: CRITICAL
      slow: true
      useBuiltinRegoPolicies: "true"
      useEmbeddedRegoPolicies: "false"
      debug: true

    compliance:
      reportType: all
      cron: 0 */12 * * *

Infrastructure and RBAC assessment do not run
The trivy-operator pod keeps restarting - reason: Back-off

Error:
failed to load rego policies from [externalPolicies] 

**What did you expect to happen:**
- Vulnerability scans --> generated
- Exposed secrets --> generated
- Compliance reports. --> generated
- RBAC assessment reports --> Not generated
- config audit reports --> Not generated

**Anything else you would like to add:**
To remediate the issue I have turned off the following characteristics:
      configAuditScannerEnabled: true 
      rbacAssessmentScannerEnabled: true 
      infraAssessmentScannerEnabled: true 

[Miscellaneous information that will assist in solving the issue.]
Issue has already been reported and closed here:
[https://github.com/aquasecurity/trivy-operator/issues/2123#top](https://github.com/aquasecurity/trivy-operator/issues/2123#top)

According this should be solved in version: 0.21.3

**Environment:**
AKS cluster

- Trivy-Operator version (use `trivy-operator version`):0.22.0
- OS ubuntu
- Kubernetes version (use `kubectl version`):
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4

**Comment by chen-keinan** [comment]
@alejandropriv can you please add trivy-operator logs , more extended.

are you using air-gapped env ?

**Comment by alejandropriv** [comment]
Hi chen, no I am not using airgapped-env, the following are the logs

     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329
      sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266
      sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227
      2024-07-08T14:05:51Z	DEBUG	resourcecontroller	Checking whether configuration audit report exists	{"kind": 
              "Role", "name": {"name":"abc-service","namespace":"abc-service"}}
      2024-07-08T14:05:51Z	ERROR	Reconciler error	{"controller": "role", "controllerGroup": 
              "rbac.authorization.k8s.io", "controllerKind": "Role", "Role": {"name":"abc-admin","namespace":"abc-service"}, 
               "namespace": "log-projection-service", "name": "logprojection-admin", "reconcileID": "8fd85545-dff1-49f1- 
               8839-6ed7fada00af", "error": "evaluating resource: failed to load rego policies from [externalPolicies]: 1 error 
               occurred: externalPolicies/file_0.rego:1: rego_parse_error: unexpected minus token: expected number\n\t---\n\t ^"}
      sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	       /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329
      sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266
       sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	       /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227
        2024-07-08T14:05:51Z	DEBUG	resourcecontroller	Checking whether configuration audit report exists	{"kind": "ReplicaSet", "name": {"name":"def","namespace":"def"}}
        2024-07-08T14:05:51Z	ERROR	Reconciler error	{"controller": "replicaset", "controllerGroup": "apps", 
               "controllerKind": "ReplicaSet", "ReplicaSet": {"name":"def","namespace":"def"}, "namespace": "def", "name": 
                "def", "reconcileID": "a0cf6ee2-600b-40e1-8556-7eafd45324fb", "error": "evaluating resource: failed to load 
                rego policies from [externalPolicies]: 1 error occurred: externalPolicies/file_0.rego:1: rego_parse_error: 
                unexpected minus token: expected number\n\t---\n\t ^"}
       sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227
         2024-07-08T14:05:51Z	DEBUG	resourcecontroller	Checking whether configuration audit report exists	 
                {"kind": "StatefulSet", "name": {"name":"alertmanager-prometheus-operator-kube-p- 
                alertmanager","namespace":"monitoring"}}
         2024-07-08T14:05:51Z	ERROR	Reconciler error	{"controller": "statefulset", "controllerGroup": "apps", 
                 "controllerKind": "StatefulSet", "StatefulSet": {"name":"alertmanager-prometheus-operator-kube-p- 
                 alertmanager","namespace":"monitoring"}, "namespace": "monitoring", "name": "alertmanager-prometheus- 
                 operator-kube-p-alertmanager", "reconcileID": "b8122863-f836-4ed2-9e08-d33d0a6a4141", "error": 
                 "evaluating resource: failed to load rego policies from [externalPolicies]: 1 error occurred: 
                 externalPolicies/file_0.rego:1: rego_parse_error: unexpected minus token: expected number\n\t---\n\t ^"}
