### ISSUE TITLE
Helm Chart valuesFromSecret for trivy

### ISSUE THREAD

**Issue by kimdre** [aquasecurity/trivy-operator#2172]
Hi, the helm chart provides a key to set values for the operator from a secret, which I need because my http proxy config is inside a secret. 

```yaml
operator:
  valuesFromSecret: proxy-secrets
```

Would it be possible to add this for trivy aswell?

```y
trivy.httpProxy
trivy.httpsProxy
```

https://github.com/aquasecurity/trivy-operator/blob/7b0c518a622febde21e97c9dd5ac6c9b27ea60ed/deploy/helm/values.yaml#L384-L391

_Originally posted by @kimdre in https://github.com/aquasecurity/trivy-operator/discussions/2171_

**Comment by chen-keinan** [comment]
@kimdre contributions are welcome if you have time, it not let me know and I'll take it.
