### ISSUE TITLE
k8s-cis-1.23  ClusterComplianceReport Preventing ArgoCD Sync

### ISSUE THREAD

**Issue by jicunningham** [aquasecurity/trivy-operator#2184]
**What steps did you take and what happened:**

After upgrading to the latest chart in our lower environment, ArgoCD is giving us an error when trying to sync our changes. 

**What did you expect to happen:**

We expected a successful sync, which has worked with the previous version

**Anything else you would like to add:**

![image](https://github.com/user-attachments/assets/f88033d3-befd-4d42-ac6a-fa317eb9f6f2)

Head of "Desired Manifest"
```apiVersion: aquasecurity.github.io/v1alpha1
kind: ClusterComplianceReport
metadata:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.22.0
    argocd.argoproj.io/instance: av-gc-dev2-trivy-operator
  name: k8s-cis-1.23
  platform: k8s
  type: cis
spec:
  compliance:

**Comment by chen-keinan** [comment]
@jicunningham fix #2179 has been added.
take the latest helm

**Comment by chen-keinan** [comment]
can you delete the compliance spec and re-deploy it ?

**Comment by chen-keinan** [comment]
> yes if I delete the reports, then it sync's fine. but we don't want to sync them manually.
> 
> maybe it is because of the annotations on the report
> 
> ```
>  Annotations: argocd.argoproj.io/tracking-id: trivy-operator:aquasecurity.github.io/ClusterComplianceReport:trivy-operator/cis
> ```

I see , any suggestion ?
