### ISSUE TITLE
Prepare support for K8s 1.25 APIs and removal of PSP

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#221]
In order to prepare for the upcoming K8s 1.25 release, we should remove all use of already deprecated APIs that will be removed in 1.25. An overview of the APIs to be removed can be found here: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

I did a quick scan in the code-base, and it seems like we still use the following APIs:
- `batch/v1beta1 CronJob`; will need to be changed to use batch/v1 CronJob instead
- `policy/v1beta1 PodSecurityPolicy`; just remove use?

**Comment by josedonizetti** [comment]
Probably be able to support APIs based on the running k8s will give us more flexibility, even though those APIs will be deprecated, there will be people using older versions, and preferably we support old and newer APIs based on which k8s version the operator is running. We did something like it for `trivy-kubernetes`. WDYT?

**Comment by erikgb** [comment]
> Probably be able to support APIs based on the running k8s will give us more flexibility, even though those APIs will be deprecated, there will be people using older versions, and preferably we support old and newer APIs based on which k8s version the operator is running. We did something like it for `trivy-kubernetes`. WDYT?

That is an option, but I suspect that approach will add a lot of additional complexity to the code that could cause a lot of pain over time. IMO we should try to support as many versions as possible. But when in conflict, as in this case, I would prioritize supporting newer versions over versions that have passed EOL upstream. Ref. https://endoflife.date/kubernetes

**Comment by chen-keinan** [comment]
I would start with Trivy-operator deprecation notice (for two resources above) in next release. 
followed by removal in the release close to date of 1.25.

it can be shared with in the announcements

**Comment by erikgb** [comment]
Since `batch/v1 CronJob` was introduced in K8s 1.21, I think we need to drop support for K8s version < 1.21 if we want to support the upcoming K8s 1.25. I'll create an issue to initiate the process.

I still fear that what @josedonizetti suggested in https://github.com/aquasecurity/trivy-operator/issues/221#issuecomment-1170585201 will make things a lot more complex. But a PR would disclose that...

**Comment by chen-keinan** [comment]
as we only track this resource , we suggest to support `batch/v1beta1 CronJob` and `batch/v1 CronJob` and other by feature flag to give wider support for k8s version
