### ISSUE TITLE
Trivy Operator is not compatible with Kubernetes v1.31.0

### ISSUE THREAD

**Issue by cnwaldron** [aquasecurity/trivy-operator#2251]
**What steps did you take and what happened:**
We had a Kubernetes cluster that was recently updated to Kubernetes v1.31.0 and had Trivy Operator v0.22 already running. After the upgrade, I noticed that the vulnerability reports were not being created anymore. Then I looked at the namespace and saw the scan jobs were not being cleaned up but they were all successful. I looked at the trivy-operator log and saw reconcile error stating: "unrecognized scan job condition: SuccessCriteriaMet". I have checked the Kubernetes documents and found the Job Success Policy is in beta for v1.31.0 and turned on by default .(https://kubernetes.io/docs/concepts/workloads/controllers/job/#success-policy)

**What did you expect to happen:**

After a successful job is complete, trivy-operator will clean up the jobs and create the reports as usual.

**Anything else you would like to add:**
To see new policy feature: https://kubernetes.io/docs/concepts/workloads/controllers/job/#success-policy
The Job status conditions now have 2 conditions on a success: the first one is the `SuccessCriteriaMet` type and the second is the `Complete` type.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.22.0 (also ran with 0.18.5 as well)
- Kubernetes version (use `kubectl version`): 1.31.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): RHEL 9.3

**Comment by FranAguiar** [comment]
Hello, any idea when a patch will be released?

**Comment by allanian** [comment]
+1

**Comment by amrap030** [comment]
+1

**Comment by dpolpa** [comment]
+1

**Comment by Jhonnyzeroones** [comment]
+1

**Comment by inikolovski** [comment]
+1

**Comment by Prates23** [comment]
+1

**Comment by Hacks4Snacks** [comment]
I haven't seen a response on whether or not this project is going to continue being supported and I don't really plan on maintaining a long-term fork, but if anyone needs 1.31.0 to work in the near-term you can take a look at the changes I've made to get it working (reference: https://github.com/Hacks4Snacks/trivy-operator).

**Comment by Jhonnyzeroones** [comment]
@Hacks4Snacks Do you have an image registry that I can pull? I noticed that https://ghcr.io/Hacks4Snacks/trivy-operator was not operational. Have you published images for this or should I build my own trivy-operator image.

**Comment by Hacks4Snacks** [comment]
> @Hacks4Snacks Do you have an image registry that I can pull? I noticed that https://ghcr.io/Hacks4Snacks/trivy-operator was not operational. Have you published images for this or should I build my own trivy-operator image.

@Jhonnyzeroones I am not publishing artifacts to an image registry, I recommend building your own image.

**Comment by FranAguiar** [comment]
@Hacks4Snacks can you submit a PR with the fix? Not sure if is an option

**Comment by badgerspoke** [comment]
I've had a crack at a PR which appears to be working in my clusters.

**Comment by basdemirs** [comment]
> > @Hacks4Snacks Do you have an image registry that I can pull? I noticed that https://ghcr.io/Hacks4Snacks/trivy-operator was not operational. Have you published images for this or should I build my own trivy-operator image.
> 
> @Jhonnyzeroones I am not publishing artifacts to an image registry, I recommend building your own image.

Thanks @Hacks4Snacks

**Comment by Xeroxxx** [comment]
Is this project abandoned? Even the paid version does not seem to support 1.31 as its based on trivy-operator 0.20.1

**Comment by Kankarollo** [comment]
Are there some reasons why @badgerspoke's fix PR is not merged to trivy operator? Don't know if we should wait (or help with implementation here) or use this PR to build our own version.

**Comment by Kankarollo** [comment]
Can we do something to bump @badgerspoke PR that it will be reviewed quicker? It's a good blocker for our use cases and we don't know if we should wait or apply our own solution.

**Comment by simlecp** [comment]
Hello, 

We face the same issue on chart target 0.23.3 and 0.23.1,

Do you know when will the fix be applied ?

Best regards,
SD.

**Comment by afdesk** [comment]
> We face the same issue on chart target 0.23.3 and 0.23.1,
> 
> Do you know when will the fix be applied ?

Hello @simlecp! 
We understand it's a critical issue and trying to fix ASAP. 
I hope it'll be resolved in a few days (on this week).

sorry for inconvenience!

**Comment by Xeroxxx** [comment]
Any update on this matter? 1.31 was released on August 13th.

**Comment by badgerspoke** [comment]
I think it's being reviewed but ironically they're being rate limited pulling the checks db from GH.. I've seen over 20 build attempts

**Comment by badgerspoke** [comment]
Wow. When did that start, and what is being done about it?

**Comment by afdesk** [comment]
> Wow. When did that start, and what is being done about it?

it started a few month ago, it's a known issue - Github rate limits for Trivy - https://github.com/aquasecurity/trivy/discussions/7699

**Comment by 0054** [comment]
+1

**Comment by grigory-bogush** [comment]
+1

**Comment by lekks** [comment]
We need it too!

**Comment by badunzo** [comment]
+1

**Comment by mdnfiras** [comment]
+1

**Comment by Nimdim** [comment]
+1

**Comment by ArtRozhe** [comment]
+1

**Comment by matt-tvg** [comment]
+1

**Comment by CrashLoopBackOff-K8s** [comment]
+1, joining the chorus -- not to dogpile, but to hopefully get some more visibility for this one.

**Comment by D0Ge3** [comment]
+1

**Comment by Xeroxxx** [comment]
Thank you @badgerspoke. Can't watch this sadness overhere anymore.

Image contains fix, based on alpine 3.20.3. Unit tests 100%.

https://hub.docker.com/repository/docker/xeroxxx/trivy-operator/general
docker.io/xeroxxx/trivy-operator:0.22.0-1.31

Image will be delete after fix has been released for one month.

**Comment by badgerspoke** [comment]
Yeah I didn't rev the base image that much in my PR as that is clearly orthogonal and it's not clear what the appropriate level of change is per PR is for this project. I was hoping for some other PR/regular cadence for updating the base, but perhaps not?
It's clearly a bit crazy this project can't merge anything due to a GH rate limit. I get that it's open source aka just folks' best efforts where time allows but this feels a bit like a dead end

**Comment by afdesk** [comment]
> It's clearly a bit crazy this project can't merge anything due to a GH rate limit. I get that it's open source aka just folks' best efforts where time allows but this feels a bit like a dead end

Honestly I hope we found the solution for GH Limit issue, and #2301 will fix it ASAP.
after It merges we'll update and recheck another PRs.

**Comment by chyvak357** [comment]
+1 :cry:

**Comment by LaurinStreng** [comment]
@afdesk is a Release Planed to publish the support for 1.31?

**Comment by afdesk** [comment]
> @afdesk is a Release Planed to publish the support for 1.31?

sure, I hope it'll be cut today or tomorrow

**Comment by badgerspoke** [comment]
What's the status here now please - time marches by..

**Comment by afdesk** [comment]
> What's the status here now please - time marches by.. oh and what else is planned for inclusion in the next release please?

the latest release (v0.23.0) should support k8s v1.31.
Do you have any issue with this versions?
thanks

**Comment by badgerspoke** [comment]
Oh, you're right. Apologies I don't know how I missed that

**Comment by afdesk** [comment]
no problem.
thanks for your efforts. your PR is important in this release.
