### ISSUE TITLE
feat: opt-in TTL on trivy-operator managed jobs

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#228]
We are trying out trivy-operator in our multi-tenant (and air-gapped) clusters. Our clusters are quite big, and constantly growing. Because of the nature of our clusters, we probably have to adjust the trivy-operator configuration to support scanning across the cluster.

Currently our only feedback source seems to be the operator logs, and that is a bit overwhelming in a big cluster.....

So I would like to see some improvements to this over this. Some ideas:

- Introduce status on more trivy-operator CRDs. Personally I prefer a [kstatus](https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/README.md) compatible status structure, which seems like an adopting standard. I.e. FluxCD understands kstatus.
- Metrics indicating failing operator reconciles. This can easily get problematic because of Prometheus label cardinality, so status on CRDs is better IMO.

But as a workaround (and maybe even a minor improvement) to this, I suggest to introduce an option to keep jobs around some time after they are completed/failed (TTL). That will allow us to more easily track scanning issues per workload. WDYT?

**Comment by chen-keinan** [comment]
I think we should  start with workaround (to improve the immediate problem ), and log issue for long term solution

**Comment by erikgb** [comment]
I've had a look at the relevant code, and it seems like the jobs are deleted as soon as the job completes, and the report(s) are updated with the result:

The by far easiest solution would be to replace explicit Job deletions with setting[ `.spec.ttlSecondsAfterFinished`](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) on the Job on creation.. The potential issue with this change, is that the [`TTLAfterFinished` feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) was only enabled by default in K8s 1.21. For a core functionality like cleaning up completed jobs, we should not rely on users enabling this feature gate. So this will effectively force us to drop support for K8s version < 1.21.

Related issue #221.

**Comment by chen-keinan** [comment]
currently I see two issues (might be more) with suggested approach which needed to be addressed :
- After scan job has been completed `trivy-operator` is processing the logs and building the reports , if it to use the TTL approach then it need to be deterministic that job will be evict only after reports has been produced.

- deletion of the job is done on a several condition , not only on success , need to make sure that TTL approach will satisfied all conditions

**Comment by erikgb** [comment]
> The TTL-after-finished controller is only supported for Jobs. A cluster operator can use this feature to clean up finished Jobs (either Complete or Failed) automatically by specifying the .spec.ttlSecondsAfterFinished field of a Job, as in this [example](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically). The TTL-after-finished controller will assume that a job is eligible to be cleaned up TTL seconds after the job has finished, in other words, when the TTL has expired.

So the TTL will only start ticking once a job is **finished** (completed or failed). A TTL set to low will be a bad idea, at least if setting the value when trivy-operator creates the job, but I suggest setting a default value that allows the jobs completed reconciler in trivy-operator enough time to pull out the logs. Another option can be to set the TTL on jobs in the trivy-operator jobs completed reconciler, after processing the logs, which should address your concern for sure. The latter might need some special handling, since setting the TTL will trigger another reconcile.

**Comment by chen-keinan** [comment]
I'm in favor of the later one as it will remove the concern of post processing timing.
how about other cases where we delete the job ? there are 3 cases we delete the job before completion

**Comment by erikgb** [comment]
> I'm in favor of the later one as it will remove the concern of post processing timing. how about other cases where we delete the job ? there are three cases where we delete the job , which could be before completion/ fail

Could you reference the code in question? I think all explicit delete of jobs should be replaced by the TTL mechanism.

**Comment by chen-keinan** [comment]
> Could you reference the code in question? I think all explicit delete of jobs should be replaced by the TTL mechanism.
yes , probably all should be cleared by TTL
