### ISSUE TITLE
On a large Cluster - Timeout to list secrets

### ISSUE THREAD

**Issue by cdesaintleger** [aquasecurity/trivy-operator#230]
**What steps did you take and what happened:**

Hello, 
on a large cluster (250+ worker nodes , ~20k secrets) the operator return a lot of error messages about "secret listing timeout" (trace below ).
I think that , the operator query the dataplane to get all secrets in all namespaces, and reach a timeout 60sec. 

I don't understand why the operator want to get all secrets in one time. 
Maybe there is an option to tune it. 

`Trace[202191422]: [1m4.391699449s] [1m4.391699449s] END
E0630 13:10:31.239778       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.1/tools/cache/reflector.go:167: . Please retry. Original error: stream error: stream ID 37085; INTERNAL_ERROR; received from peer
W0630 13:11:33.944659       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.1/tools/cache/reflector.go:167: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 37089; INTERNAL_ERROR; received from peer
I0630 13:11:33.944735       1 trace.go:205] Trace[1291045998]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.1/tools/cache/reflector.go:167 (30-Jun-2022 13:10:33.624) (total time: 60319ms):`

**Anything else you would like to add:**

GKE 1.21
250+ nodes
20K secrets 

**Environment:**

- Trivy-Operator version 0.0.7
- Kubernetes version 1.21

Thank you for your assistance :)
Ch

**Comment by chen-keinan** [comment]
@cdesaintleger following to reviewing  this issue , I can confirm the following :
- trivy-operator doesn't use `client list secrets` as part of it functionality , in some case we get a single secret with  : 
   `r.client.Get(ctx, client.ObjectKey{Name: secretRef.Name, Namespace: ns}` with specific refName and namespace but never use ***secrets listing***.
   
- I do see that the builtin Informer [Reflector call ListAndWatch](https://github.com/kubernetes/client-go/blob/0bc005e72ff13ab4ceffd5c4e0ecb1774a7bf7f8/tools/cache/reflector.go#L221) ("Reflector ListAndWatch" as referred in the log above) list the k8s Objects and secret. it uses pager with [pagination of 500](https://github.com/kubernetes/client-go/blob/0bc005e72ff13ab4ceffd5c4e0ecb1774a7bf7f8/tools/cache/reflector.go#L276) entries by default , so it never list all secret only 500 at a time by default
   
  500 entries for page is not consider a lot of data to fetch , maybe the cluster API is overloaded and not responding  
  I assume it can happen for any type of resource as the Reflector ListAndWatch List all Objects used by informer to sync the cache.

**Comment by cdesaintleger** [comment]
@chen-keinan thank you for your investigation, 
about the situation, i think that it is important to precise that 98% of the secrets are Helm release ( Helm V3) so these secrets are very large (  ) compare to standard secret. 
After cleaning oldest Helm versions ( ~4500 secrets ) the situation seems ok.@chen-keinan thank you for your investigation, 
about the situation, i think that it is important to precise that 98% of the secrets are Helm release ( Helm V3) so these secrets are very large (  ) compare to standard secret. 
After cleaning oldest Helm versions ( ~4500 secrets ) the situation seems ok.
Do you know if we can override this default value of 500 entries per page to reproduce this situation and tune this value depending of cluster/secrets size/number ?

**Comment by erikgb** [comment]
One workaround could be to disable caching of secrets in trivy-operator - to avoid pulling down all secrets in the cluster. IMO trivy-operator should ideally not have access to secrets cluster-wide, but that is not currently possible because of the feature to support private registries. Discussed here: https://github.com/aquasecurity/trivy-operator/issues/187#issuecomment-1170466039

**Comment by chen-keinan** [comment]
>Do you know if we can override this default value of 500 entries per page to reproduce this situation and tune this value depending of cluster/secrets size/number ?

Nope, Only by implementing custom informer.

**Comment by cdesaintleger** [comment]
Arf :( 
For now i can't use this operator on these clusters. 

If you are interested by the cluster size & type that reach the limit or not :

**Does not works on :** 
- Cluster GKE 1.21
- 270 Nodes
- 11K pods
- 1125 Ns
- 16700 secrets
- 6116 config map

**Works fine on :** 
- Cluster GKE 1.21
- 239 Nodes
- 6.2K pods
- 396 Ns
- 6397 secrets
- 2022 config map

**Logs :** 
`Trace[993885509]: [1m0.308585203s] [1m0.308585203s] END
E0708 08:39:23.984175       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 203; INTERNAL_ERROR; received from peer
W0708 08:40:28.781557       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 213; INTERNAL_ERROR; received from peer
I0708 08:40:28.781614       1 trace.go:205] Trace[605553262]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (08-Jul-2022 08:39:25.326) (total time: 63455ms):
Trace[605553262]: ---"Objects listed" error:stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 213; INTERNAL_ERROR; received from peer 63455ms (08:40:28.781)
Trace[605553262]: [1m3.45508763s] [1m3.45508763s] END
E0708 08:40:28.781629       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 213; INTERNAL_ERROR; received from peer
W0708 08:41:31.087472       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 215; INTERNAL_ERROR; received from peer
I0708 08:41:31.087538       1 trace.go:205] Trace[1157924483]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (08-Jul-2022 08:40:30.737) (total time: 60349ms):
Trace[1157924483]: ---"Objects listed" error:stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 215; INTERNAL_ERROR; received from peer 60349ms (08:41:31.087)
Trace[1157924483]: [1m0.349566377s] [1m0.349566377s] END
E0708 08:41:31.087552       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 215; INTERNAL_ERROR; received from peer`
