### ISSUE TITLE
env TRIVY_INSECURE always set to TRUE in the job manifest

### ISSUE THREAD

**Issue by seb-835** [aquasecurity/trivy-operator#245]
**What steps did you take and what happened:**

After inspecting job manisfest, it looks like env   TRIVY_INSECURE is always set to True,
even though trivy-operator-trivy-config configmap contains :
 
  trivy.dbRepositoryInsecure: "false"
  trivy.serverInsecure: "false"

**What did you expect to happen:**

 TRIVY_INSECURE set to False  when   trivy.dbRepositoryInsecure: "false" and trivy.serverInsecure: "false"

**Anything else you would like to add:**

I may have missed a setting ? could you help please ?

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
```
{"level":"info","ts":1657004238.8778963,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.1.0","Commit":"63a98e9d08e8dc5fc97c57e5c07fbafbe32cf42f","Date":"2022-06-30T11:25:27Z","Executable":""}}
{"level":"info","ts":1657004238.8782058,"logger":"operator","msg":"Resolved install mode","install mode":"AllNamespaces","operator namespace":"trivy-system","target namespaces":[],"exclude namespaces":"kube-system,trivy-system"}
```

- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9"
```

**Comment by chen-keinan** [comment]
@seb-835 thanks for reporting , looking into it

**Comment by chen-keinan** [comment]
@seb-835 fix will be included with next trivy-operator
