### ISSUE TITLE
Docker.io rate limitation while pulling trivy

### ISSUE THREAD

**Issue by VF-mbrauer** [aquasecurity/trivy-operator#251]
Running into an issue with the new `trivy-operator` while it created the Scan-Jobs.
Each of the jobs will lead to a Docker.io pull for getting the `trivy-container`

```
{"level":"error","ts":1657020655.7990713,"logger":"reconciler.vulnerabilityreport","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-57455996dc","container":"ff8ec51e-1ac5-4a71-938e-dafffc1dabc8","status.reason":"Error","status.message":"2022-07-05T11:30:53.305Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (docker.io/aquasec/trivy:0.29.1): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* GET https://index.docker.io/v2/aquasec/trivy/manifests/0.29.1: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:363\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
```

**Comment by erikgb** [comment]
@VF-mbrauer What is the expected behavior? I don't think there is much trivy-operator can do with DockerHub rate limits. I just checked that the job container is created with `imagePullPolicy: IfNotPresent`. And that pretty much all that can be done here IMO. Do you have a registry proxy - that could avoid most of the traffic to DockerHub?

**Comment by VF-mbrauer** [comment]
Hi @erikgb, Trivy could be pushed to a not so limited Registry such as: `https://gallery.ecr.aws/`
That would be a possibility. And yes, this is not an issue of `trivy-operator`

**Comment by VF-mbrauer** [comment]
> I just checked that the job container is created with imagePullPolicy: IfNotPresent

According to the template **we can't specify** that via helm values:
https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/config.yaml#L48-L49

**Comment by erikgb** [comment]
> > I just checked that the job container is created with imagePullPolicy: IfNotPresent
> 
> According to the template **we can't specify** that via helm values: https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/config.yaml#L48-L49

What would you like to set it to? `IfNotPresent` is set by trivy-operator AFIAK, and IMO it is the most correct value to use. If you would like to set the `imagePullPolicy` to something else, please open an issue.

It seems like bitnami is providing trivy-images from [gallery.ecr.aws](https://gallery.ecr.aws/bitnami/trivy). Maybe you can use that as a workaround for the DockerHub rate limits?

**Comment by VF-mbrauer** [comment]
> What would you like to set it to? IfNotPresent is set by trivy-operator AFIAK, and IMO it is the most correct value to use. If you would like to set the imagePullPolicy to something else, please open an issue.

If that is already the default value when not specifying it, then it is fine.

> It seems like bitnami is providing trivy-images from [gallery.ecr.aws](https://gallery.ecr.aws/bitnami/trivy). Maybe you can use that as a workaround for the DockerHub rate limits?

good catch. Using it now and it works. 

What are we going to do with the issue then? Is that something Aqua should also think of, or would we leave it up to customers to decide either to use a different registry or apply the membership for docker.io to overcome the limits?

**Comment by erikgb** [comment]
> What are we going to do with the issue then? Is that something Aqua should also think of, or would we leave it up to customers to decide either to use a different registry or apply the membership for docker.io to overcome the limits?

I think this is something for users of trivy-operator to decide. :-) I would expect some users to have a registry proxy, and pull-push to your own registry is always a workaround.

For the trivy-operator jobs to pull **official trivy** images from other registries, **trivy** need to push images to those registries (in addition to DockerHub). Only after this is done, the default can be changed here in trivy-operator. Maybe start by creating an issue in https://github.com/aquasecurity/trivy, if you like this to happen?

**Comment by josedonizetti** [comment]
It seems we were pushing to `public.ecr.aws` before, but due to a problem it was removed. @chen-keinan created an issue to add it back -> https://github.com/aquasecurity/trivy-operator/issues/250

**Comment by VF-mbrauer** [comment]
Yes, I think he created that upon my chat with him about this specific issue. Let's wait for the outcome.

**Comment by chen-keinan** [comment]
@VF-mbrauer another quick solution is the use the the trivy images from `ghcr` .

You override this param in `trivy-operator-trivy-config` ConfigMap :
`trivy.imageRef : ghcr.io/aquasecurity/trivy:0.29.2`

**Comment by erikgb** [comment]
I set https://github.com/aquasecurity/trivy-operator/pull/267 as resolving this issue. I don't think there is much more we can do here. Feel free to reopen if you disagree.

**Comment by VF-mbrauer** [comment]
Hi @erikgb much appreciated. I totally agree here with you. Thanks for that. Let's wait for the merge and then we can close.
