### ISSUE TITLE
Remove all references to PodSecurityPolicy

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#275]
According to @chen-keinan in https://github.com/aquasecurity/trivy-operator/discussions/269#discussioncomment-3116062, `PodSecurityPolicy` is not actually in use by trivy-operator although the operator establishes an informer for podsecuritypolicies.

Since `PodSecurityPolicy` is removed in the upcoming Kubernetes 1.25, we should not reference it at all. Ref. https://github.com/aquasecurity/trivy-operator/issues/221.

Should also remove permissions to read PSP, ref. #187.

**Comment by erikgb** [comment]
I can work on this, if I can get a confirmation that PSPs are not actually in use.

**Comment by erikgb** [comment]
@chen-keinan Why was this closed as a duplicate to #187? I cannot see how they are related at all....

**Comment by chen-keinan** [comment]
> @chen-keinan Why was this closed as a duplicate to #187? I cannot see how they are related at all....

it will be done in the same scope for supporting k8s: 1.25

**Comment by erikgb** [comment]
But #187 is for RBAC, and I consider that issue an epic. Meaning it will take a long time to lock down RBAC.

**Comment by erikgb** [comment]
Maybe you meant https://github.com/aquasecurity/trivy-operator/issues/221? But why delay this?

**Comment by chen-keinan** [comment]
I want to make it as part of prep to 1.25. RBAC is iterative effort should not wait for it
