### ISSUE TITLE
clusterrole missing cm permission

### ISSUE THREAD

**Issue by githubcdr** [aquasecurity/trivy-operator#313]
It seems that the clusterrole trivy-operator does not allow creating configmaps. This prevents trivy-operator from starting;

```
 {"level":"info","ts":1657706766.2230577,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}                                     │
│ unable to run trivy operator: initializing Trivy plugin: configmaps is forbidden: User "system:serviceaccount:trivy-system:trivy-operator" cannot create resource "configmaps" │
│  in API group "" in the namespace "trivy-system"
```

**Comment by erikgb** [comment]
How do you provision trivy-operator? There is a Role that should allow trivy-operator to create configmaps in the trivy-system namespace:

https://github.com/aquasecurity/trivy-operator/blob/7ddaac9fd1dbe6b0ca4bf47732c2e73118bb4bd9/deploy/static/trivy-operator.yaml#L934-L954

**Comment by chen-keinan** [comment]
@githubcdr in version of `trivy-operator` was it occur ?

**Comment by githubcdr** [comment]
0.1.3

**Comment by erikgb** [comment]
> 0.1.3, I noticed the clusterrole is missing the permissions.

Why should the clusterrole include permissions to create configmaps cluster-wide? By the error message, it seems like you are missing the role and rolebinding.

**Comment by erikgb** [comment]
@githubcdr Maybe close this issue? 😄
