### ISSUE TITLE
Breaking template change in patch release of the operator helm chart.

### ISSUE THREAD

**Issue by andy-v-h** [aquasecurity/trivy-operator#314]
**What steps did you take and what happened:**

A recent minor release of the helm chart introduces a breaking regression. in #194, the `kind: Service` the `spec.ClusterIP` was changed to `None`. This breaks existing deployments, especially ones managed by a tool like ArgoCD since changes on services with assigned ClusterIP's to None are not allowed. 

ArgoCD users can work around this by selecting "Force" and Replace sync options, or by deleting the service and then applying. In the future, if the goal is to switch service type/spec definitions this can be avoided by changing the name for a service meant to expose metrics

**What did you expect to happen:**

Patch changes don't introduce breaking spec changes

**Anything else you would like to add:**

I'm sure this was innocuous. However we have 50+ clusters with the trivy operator and would like to use ArgoCD's auto-sync feature to assist in managing the deployment, and breaking template changes create a lot of failures that need to be manually addressed. 

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
- Kubernetes version (use `kubectl version`): 1.21,1.22,1.23
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@andy-v-h thanks for reporting , we will address this issue

**Comment by erikgb** [comment]
We also saw this when upgrading: `Error: UPGRADE FAILED: cannot patch "trivy-operator" with kind Service: Service "trivy-operator" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set`.

This was modified in https://github.com/aquasecurity/trivy-operator/pull/195, but I think we have documented that we don't support upgrades atm: https://aquasecurity.github.io/trivy-operator/v0.1.3/operator/installation/upgrade/. @andy-v-h Doesn't ArgoCD has some kind of `force` or `recreate` flag?

**Comment by andy-v-h** [comment]
> We also saw this when upgrading: `Error: UPGRADE FAILED: cannot patch "trivy-operator" with kind Service: Service "trivy-operator" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set`.
> 
> This was modified in #195, but I think we have documented that we don't support upgrades atm: https://aquasecurity.github.io/trivy-operator/v0.1.3/operator/installation/upgrade/. @andy-v-h Doesn't ArgoCD has some kind of `force` or `recreate` flag?

It does, however it was set up with auto sync enabled for 50+ clusters, so I had to disable that and apply with these options 
![Screen Shot 2022-07-13 at 10 13 14 AM](https://user-images.githubusercontent.com/5001148/178755282-009cac8c-0da7-4a9a-ab6d-99e151bf9b02.png)

I mostly want to make sure this issue is documented for other argocd users if they come looking and can see this.

**Comment by andy-v-h** [comment]
> @andy-v-h are you running the upgrade with `helm3 upgrade --install` ?

No, since I'm using argocd it's closest to a `helm template . | kubectl apply -f -`

**Comment by chen-keinan** [comment]
ahh, thanks for updating , I will make sure our documentation will be more clear about it.

**Comment by chen-keinan** [comment]
@andy-v-h FYI. #301

**Comment by chen-keinan** [comment]
Closing issue as no action to be taken. @andy-v-h ,  you can open it if you think any action is required
