### ISSUE TITLE
ServiceMonitor did not get installed as part of the Helm install

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/trivy-operator#332]
**What steps did you take and what happened:**

I followed the docs on deploying the Helm chart https://aquasecurity.github.io/trivy-operator/v0.1.3/operator/installation/helm/

However, the ServiceMonitor was not deployed by default so I could not automatically access vulnerability reports and other metrics from the operator in Prometheus.

**What did you expect to happen:**

Magic

hahah well, that all the components get deployed automatically -- maybe I missed something? Do I have to tell the Helm Chart to deploy the ServiceMonitor? If yes, what is the reasoning for it not getting deployed automatically?

**Comment by josedonizetti** [comment]
@AnaisUrlichs Yes, the servicemonitor is disabled by default, because installing it depends on having the https://github.com/prometheus-operator/prometheus-operator running. We didn't make the installation of trivy-operator depend on another operator.

**Comment by AnaisUrlichs** [comment]
So how do I enable the ServiceMonitor in the Trivy Operator Helm Chart? I had Prometheus running and tried helm upgrade on the Trivy Operator Helm Chart but that did not make it install the ServiceMonitor

**Comment by josedonizetti** [comment]
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="serviceMonitor.enabled=true" \
  --version 0.1.3
```

**Comment by josedonizetti** [comment]
@AnaisUrlichs Closing the issue. Feel free to reopen it if you think something is still missing.

**Comment by AnaisUrlichs** [comment]
All good, I'm happy
