### ISSUE TITLE
Opt-in to use k3d as an alternative to kind for local dev

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#355]
My development environment is docker-based. Long story, but mainly to be able to work on Linux, as my company only provides workstations with Windows pre-installed. We are working on a WSL2 setup, but that will still take some time.

And kind does not run on docker, but [k3d](https://k3d.io/) does. We use k3d a lot internally, so each time I want to test trivy-operator on my local workstation, I have to modify the Makefile to replace the kind import image with the corresponding k3d command. This is unfortunate, so I suggest to add an opt-in to the Makefile for using k3d as an alternative to kind.

I am not sure how the UX should be, as I don't have too much experience with makefiles, but maybe a new environment variable `TRIVY_OPERATOR_CLUSTER`, with the supported values `kind` (default) and `k3d`?

**Comment by chen-keinan** [comment]
not sure about this requirements , look like personal use case , kind is highly used and popular. maybe try to find a way to support both

**Comment by erikgb** [comment]
> maybe try to find a way to support both

Of course! :-) I am not at all suggesting to drop kind. Kind should still be the default and no changes in the UX.
