### ISSUE TITLE
Suggestion for refactoring: Split WorkloadController

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#370]
I think the WorkloadController struct has too much responsability, as it is actually two controllers in one struct. This makes the [Go file](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/vulnerabilityreport/controller.go) large, which could be fixed by just splitting funcs between files. But for testing, it would be much easier if we had two structs, one for each controller: `WorkloadController` (create scan jobs from workload) and `ScanJobController` (creating reports from finished scan jobs).

**Comment by chen-keinan** [comment]
its very low priority , I'll put in the backlog in the meantime try to manage with out it
