### ISSUE TITLE
Operator doesn't have permissions to list deployments

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#373]
**What steps did you take and what happened:**

After upgrading trivy-operator to the latest release (0.1.4), I notice this in our logs:

````
W0720 09:22:13.597998 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:trivy-system:trivy-operator" cannot list resource "deployments" in API group "apps" at the cluster scope
````

**What did you expect to happen:**

No errors in logs.

**Anything else you would like to add:**

I am pretty sure that this bug was introduced by https://github.com/aquasecurity/trivy-operator/pull/215/files, and I will look into where access to deployments seems required, and either remove the requirement or update the clusterrole.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.4
- Kubernetes version (use `kubectl version`): RKE2 1.23.8
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): RHEL 8.5 on K8s hosts

**Comment by josedonizetti** [comment]
@erikgb Not sure as well from the point of view of tighten RBAC, but maybe it does make sense to only scan a rs if there is one active on the cluster? But not a high priority change I would say, perhaps raising an issue to further discuss the idea with the community?

**Comment by erikgb** [comment]
> @erikgb Not sure as well from the point of view of tighten RBAC, but maybe it does make sense to only scan a rs if there is one active on the cluster? Not a high priority change I would say, perhaps raising an issue to further discuss the idea with the community?

@josedonizetti I can create an issue for this, sure. But then I think it should apply for all Pod-controller resources. So not only replicasets, but also statefulsets+++.
