### ISSUE TITLE
Operator should NOT establish list/watch for multiple API versions of the same resource

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#382]
I notice that we bootstrap the workload controller with two list/watch for cronjobs: https://github.com/aquasecurity/trivy-operator/blob/6916d7b1476cc50638a7d3f66822cfa96ad92b4e/pkg/vulnerabilityreport/controller.go#L79-L80

I don't know the controller-runtime internals that well, but that seems very wrong to me, and might be cause for the races seen occasionally by @josedonizetti when reviewing/testing https://github.com/aquasecurity/trivy-operator/pull/337.

Also this will fail on K8s 1.25, since `v1beta1.CronJob` is removed in 1.25.

**Comment by josedonizetti** [comment]
Yup, I think this one slipped during the review. if you not taking it, i'll make a PR for it. About the data races, I will keep running some tests on it today, keep you posted.

**Comment by erikgb** [comment]
> Yup, I think this one slipped during the review. if you not taking it, i'll make a PR for it. About the data races, I will keep running some tests on it today, keep you posted.

Feel free to pick it up, I am not going to. This is part of the "enterprise adjustments" that you from Aqua should care for. 😉
