### ISSUE TITLE
Twirp error unauthenticated: invalid token

### ISSUE THREAD

**Issue by lahiruperamune** [aquasecurity/trivy-operator#383]
**What steps did you take and what happened:**

The trivy operator is running fine. But log shows following error for some containers. These images are from our private registry (Gitlab).
We do see that the temporary secrets with the imagePullSecrets are created and the credentials are correct.

`image scan error: scan error: image scan failed: failed analysis: unable to get missing layers: unable to fetch missing layers: twirp error unauthenticated: invalid token
`

**What did you expect to happen:**

The image vulnerability scan should created for every image.

**Environment:**

- Trivy-Operator version: 0.1.3
- Kubernetes version: v1.22.5
- OS: Ubuntu 22.04 LTS

**Comment by josedonizetti** [comment]
@lahiruperamune Thanks for reporting the issue. Are you using ClientServer mode?

**Comment by lahiruperamune** [comment]
Yes @josedonizetti. It is ClientServer mode.

**Comment by josedonizetti** [comment]
@lahiruperamune what is the server version? I think this bug is due to a mismatch of versions between client/server.

**Comment by lahiruperamune** [comment]
Trivy-Sever Version is: `0.29.2`  (The Helm-Chart version is `0.4.16`)
Trivy-Operator Version is: `0.1.3`  (This is also the Helm-Chart version)
Trivy version of pods being scanned via the operator is: `0.29.1`

**Comment by lahiruperamune** [comment]
Hi @chen-keinan Thanks for your comment. There was a problem with the configMap and now it is working.
