### ISSUE TITLE
Don't scan workloads with desired replicas=0

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#387]
This issue is a follow-up on a discussion started after a bug to trivy-operator clusterrole: https://github.com/aquasecurity/trivy-operator/issues/373#issuecomment-1191222047

To reduce the number of reports, metrics etc., I am proposing to NOT scan any workload with desired replicas=0. This will at least apply to replicasets, statefulsets and replicationcontrollers. All workload resources supported by trivy-operator with desired replicas should have this new requirement applied if this issue is implemented.

This will obsolete the `VulnerabilityScannerScanOnlyCurrentRevisions` and `ConfigAuditScannerScanOnlyCurrentRevisions` settings, at least I think so.

This will also allow us to remove the operator cluster-wide permission to read deployments, at least I think so. Not a big deal, but keeping the clusterrole as small as possible cannot be wrong.

**Comment by NissesSenap** [comment]
Sounds very reasonable.

Could it be a good thing to show in the vulnerability report which deployment the RS come from? Might it even be worth having it as a label in metrics?
Yes the image vulnerability is the most important part, but it will make things easier if we can see where the image is used.

I can't remember how the current data looks like but it wouldn't surprise me if it's already there ;)
