### ISSUE TITLE
Add ConfigAuditScannerScanOnlyCurrentRevisions  and VulnerabilityScannerReportTTL active by default

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#390]
it is required to make ConfigAuditScannerScanOnlyCurrentRevisions and VulnerabilityScannerReportTTL active by default.

This change will solve 2 problems:

- Removed old reports revisions of replicates which are not running in the cluster 
- The reports (vulnerability/configaudit and etc) will be updated with latest vulnDB and security policies data. on a daily basis

Related to issue #393

**Comment by erikgb** [comment]
Related issue: https://github.com/aquasecurity/trivy-operator/issues/387
