### ISSUE TITLE
Add TTL  capability to all Reports

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#393]
Add Time To Live  attribute to config audit/rbac/expose secrets reports (similar to existing TTL in vulnerability report).

This feature will enable `trivy-operator` to a rescan of resources for builtin policies lib updates

**Comment by josedonizetti** [comment]
@chen-keinan wonder if we shouldn't also have it for exposedsecrets considering we will add TTL to all reports with this issue. wdyt?

**Comment by chen-keinan** [comment]
> @chen-keinan wonder if we shouldn't also have it for exposedsecrets considering we will add TTL to all reports with this issue. wdyt?

yes, I think  we should have it for every report which relay on set of rules
