### ISSUE TITLE
Add variable for `automountServiceAccountToken`

### ISSUE THREAD

**Issue by ichasco-heytrade** [aquasecurity/trivy-operator#402]
Hi, I would like to variabilize the `automountServiceAccountToken` field. It's needed if someone want to use a tool like `vault-secret-webhook` to retrieve the secrets. In the operator and in the jobs.

Thanks!

**Comment by chen-keinan** [comment]
@ichasco-heytrade you can pick up this issue if you like :)

**Comment by ichasco-heytrade** [comment]
This has to be changed in the jobs. But I don't know how to do it. If it had been be in the HELM templates I would have done myself

**Comment by ichasco-heytrade** [comment]
Hi, @chen-keinan I have tried but have not succeeded :(

**Comment by chen-keinan** [comment]
@ichasco-heytrade no worries , we will pick it up and you could review it
