### ISSUE TITLE
Doesn't work on openshift

### ISSUE THREAD

**Issue by davidkarlsen** [aquasecurity/trivy-operator#405]
**What steps did you take and what happened:**
scanner started

```
Defaulted container "kube-scheduler" out of: kube-scheduler, kube-scheduler-cert-syncer, kube-scheduler-recovery-controller, wait-for-host-port, d7a8c404-d3a7-4f3b-b746-8a99b515857f (init)
2022-08-03T14:36:09.852Z        FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
        * unable to inspect the image (quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d93172761591818abdc54aa4f994eb4104c045a277cb96456ef69dd706bf4118): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
        * unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
        * containerd socket not found: /run/containerd/containerd.sock
        * Get "https://quay.io/v2/": dial tcp 54.159.249.120:443: i/o timeout
        * 
```

**What did you expect to happen:**
it being able to pull images and scan them

**Anything else you would like to add:**

Openshift 4.10.x, which runs podman

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.5
- Kubernetes version (use `kubectl version`): 1.23.3
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): redhat coreos

**Comment by chen-keinan** [comment]
@davidkarlsen thank you for reporting this issue , we will review it.

**Comment by davidkarlsen** [comment]
it works if I configure a http_proxy, and I see that you can configure that via the configmap (although I had to look a bit around to find the options).
It seems it tries to obtain the image with:
* docker socket (won't work on OCP, as it uses CRIO / podman)
* crio (but then it needs to mount a socket)
* containerd (not relevant on OCP)
* directly over api's

is this mechanism for fetching the image documented somewhere - how does it work?

**Comment by chen-keinan** [comment]
> is this mechanism for fetching the image documented somewhere - how does it work?

Looking at [Trivy Code - NewContainerImage](https://github.com/aquasecurity/trivy/blob/aef02aa1747c78bc2deca8ce1572a549bfc30dac/pkg/fanal/image/image.go#L47)
its look like its follow this chain depend on the option is get:
- dockerd
- podman
- containerd
- registry
