### ISSUE TITLE
rego_type_error: undefined function data.lib.result.new when using custom policy

### ISSUE THREAD

**Issue by dirien** [aquasecurity/trivy-operator#407]
**What steps did you take and what happened:**

I wrote a custom rego poliy for misconfiguration and I get following error message in the log:

```bash
1.6595473647064686e+09	ERROR	Reconciler error	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "pod": {"name":"test","namespace":"default"}, "namespace": "default", "name": "test", "reconcileID": "7c38e510-c587-42c1-a91c-fbb772618369", "error": "evaluating resource: 1 error occurred: externalPolicies/file_0.rego:26: rego_type_error: undefined function data.lib.result.new"}
```
The rego file looks like this, and works in standalone trivy:

```
...
data:
  policy.ED001.kinds: "Pod"
  policy.ED001.rego: |
    package trivyoperator.policy.k8s.custom

    import future.keywords.in
    import data.lib.result

    default allowedContainerRegistry = "docker.io"

    __rego_metadata__ := {
        "id": "ED001",
        "title": "Docker Hub not allowed",
        "severity": "CRITICAL",
        "description": "The usage of Docker Hub as container registry is not allowed.",
    }

    __rego_input__ := {
        "selector": [
            {"type": "kubernetes"},
        ],
    }

    deny[res] {
        input.kind == "Pod"
        some container in input.spec.containers
        not startswith(container.image, allowedContainerRegistry)
        msg := sprintf("Image '%v' comes from not approved container registry in `%v`", [container.image, allowedContainerRegistry])
        res := result.new(msg, container)
    }
```

**What did you expect to happen:**

The custom policy gets processed and ready to applied to the selected kind.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.5
- Kubernetes version (use `kubectl version`): v1.22.11+k3s1
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS

**Comment by chen-keinan** [comment]
@dirien thanks yo for reporting this issue , we will review it and update

**Comment by dirien** [comment]
Hi @chen-keinan,

do you need any additional informations from me?

**Comment by chen-keinan** [comment]
> Hi @chen-keinan,
> 
> do you need any additional informations from me?

nope , sorry it is taking long time. I'm on it.

**Comment by chen-keinan** [comment]
@dirien is the flag [useBuiltinRegoPolicies](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L245) on you env has been disabled?

**Comment by chen-keinan** [comment]
@dirien any update ?

**Comment by dirien** [comment]
hi @chen-keinan,

sorry for the late reply, this is my values.yaml. I disabled useBuiltinRegoPolicies

```yaml
  operator:
    logDevMode: true
  trivy:
    ignoreUnfixed: true
    imageRef: ghcr.io/aquasecurity/trivy:0.30.4
    useBuiltinRegoPolicies: "false"
```

**Comment by chen-keinan** [comment]
> hi @chen-keinan,
> 
> sorry for the late reply, this is my values.yaml. `useBuiltinRegoPolicies` was disabled
> 
> ```yaml
>   operator:
>     logDevMode: true
>   trivy:
>     ignoreUnfixed: true
>     imageRef: ghcr.io/aquasecurity/trivy:0.30.4
>     useBuiltinRegoPolicies: "false"
> ```

this is the problem , two option to solve it :
-  in `trivy-operator-v0.1.9` version,  enable `useBuiltinRegoPolicies` and the error will disappear.
- wait for next `trivy-operator-v0.2.0` (issue is fixed)

**Comment by dirien** [comment]
Thanks @chen-keinan, will test this!
