### ISSUE TITLE
Add support for pulling trivy scanner image from private repository

### ISSUE THREAD

**Issue by zhenfangwg2** [aquasecurity/trivy-operator#409]
In a K8s system, when the controller submits a scanner job, the credentials for composing "imagePullSecret" comes from the credential of the target container. But if the target container is public accessible (no imagePullSecret), but the `trivy` image is located in a private registry, then the scanner job will never succeed.

We wonder if we could add an extra imagePullSecret configuration in configmap to allow a pre-defined secret to be added into scanner job's manifest

**Comment by maswertyDT** [comment]
^Requesting the same feature

**Comment by chen-keinan** [comment]
@zhenfangwg2 sound reasonable.  feel free to pick up this issue if you want :) .

**Comment by genofire** [comment]
For that we use the workaround to deploy an own ServiceAccount with imagePullSecrets. That works for the scan-jobs itself.

But sadly it does not support for the trivy.dbRepository - is the scan-job use docker-in-docker?
That was solved for the to scanned-image in (TODO-filling).

**Comment by chen-keinan** [comment]
@zhenfangwg2 it will be the user responsibility to put the secret in `trivy-system` namespace , I assume , this is what you had in mind ?

**Comment by SecretMineDE** [comment]
Does this also apply to the trivy dbRepository? I'd like to host the dbRepository in a private repository with authentification.
