### ISSUE TITLE
0.1.6 release ?

### ISSUE THREAD

**Issue by nerzhul** [aquasecurity/trivy-operator#420]
Hello, regarding our recent contributions we'd like to do more test on the upstream version of the project, and prevent an internal (and temporary) fork to continue our tests on the solution. Is this possible to release a 0.1.6 with at least the security context changes for the jobs ?

Thanks :)

**Comment by chen-keinan** [comment]
@nerzhul a new. version of `trivy-operator` will be release later on this week.

**Comment by nerzhul** [comment]
@chen-keinan glad to hear :) i'm waiting for it :)

**Comment by nerzhul** [comment]
if you need some feedback tell me, we'll install it on cluster with thousands of pods, if i have issues i will tell you

**Comment by chen-keinan** [comment]
thanksm,  I'll appreciate you'r feedback
