### ISSUE TITLE
Discussions tab not found / unable to ask a question

### ISSUE THREAD

**Issue by elchenberg** [aquasecurity/trivy-operator#43]
**What steps did you take and what happened:**

1. I have a question.
2. I read the contributing guidelines that tell me to create a discussion in the Discussions tab.
3. I could not find the Discussions tab.
4. I opted for a new issue. I got to choose between "Bug report", "Feature request", and "Ask a question". The button for "Ask a question" opened the page <https://github.com/aquasecurity/trivy-operator/discussions/new?category_id=18526498> which could not be found.

:slightly_smiling_face:

**Comment by chen-keinan** [comment]
@elchenberg thanks for the feedback, discussion tab is enabled now :)

**Comment by elchenberg** [comment]
Thanks!
