### ISSUE TITLE
Go Module: ClusterComplianceDetailReports Informer gets wrong argument type 

### ISSUE THREAD

**Issue by fjogeleit** [aquasecurity/trivy-operator#44]
**What steps did you take and what happened:**

I am using the latest version of the trivy-operator go module to transform different CRDs in a unified format. While working with the ClusterComplianceDetailReports Informer I have the issue that the Objects in the Informer Callbacks are `*v1alpha1.ClusterComplianceReport`.

**What did you expect to happen:**

Expected to get `*v1alpha1.ClusterComplianceDetailReport` objects from the ClusterComplianceDetailReports Informer.

**Anything else you would like to add:**

Code Snippet I am using:

```go
import (
	"github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	"github.com/aquasecurity/trivy-operator/pkg/generated/clientset/versioned"
	"github.com/aquasecurity/trivy-operator/pkg/generated/informers/externalversions"
	corev1 "k8s.io/api/core/v1"
)

client, _ := versioned.NewForConfig(k8sConfig)

factory := externalversions.NewFilteredSharedInformerFactory(client, 0, corev1.NamespaceAll, nil)

informer := factory.Aquasecurity().V1alpha1().ClusterComplianceDetailReports().Informer()
informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
	AddFunc: func(obj interface{}) {
		fmt.Printf("%T\n", obj)
	},
})

informer.Run(ctx.Done())
```

Output:

```bash
*v1alpha1.ClusterComplianceReport
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.0.3
- Kubernetes version (use `kubectl version`): v1.22.3
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS

**Comment by chen-keinan** [comment]
@fjogeleit ClusterCompliance reports (including detailed report) functionality  has been disabled on Trivy-operator.
We are working on additional adjustment to make it available on Trivy and Trivy operator.
Once it is ready again , we will announce it.

**Comment by fjogeleit** [comment]
Okay, thanks for the quick response.
