### ISSUE TITLE
chore: release candidates should not have the changelog

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#458]
We want to always have a release candidate before a release, though, currently when we release the RC the changelog is tied to it, then when we release the final version, it contains no changelog. We want the RC to be like tracee, eg:

https://github.com/aquasecurity/tracee/releases/tag/v0.8.0-rc-2
https://github.com/aquasecurity/tracee/releases/tag/v0.8.0

**Comment by jrhunger** [comment]
Looks like all you had to do was get Trivy to 0.8.0 like tracee. :)
Anyway, i think maybe this was fixed in v0.8.0 because that release includes the changes from v0.8.0 RCs.  Just wanted to raise that in case someone wants to close this.

**Comment by jrhunger** [comment]
Based on what I see in the release notes for v0.8.0 I think it has.  v0.8.0 release includes a list of the fixes that are also listed under the v0.8.0rcX releases. 
I did not report this big but just wanted to highlight to whoever did that they should review for themselves and see if they think it is fixed.

**Comment by chen-keinan** [comment]
> Based on what I see in the release notes for v0.8.0 I think it has. v0.8.0 release includes a list of the fixes that are also 

@bgoareguer its not fix , I'm doing it manually for now :)
