### ISSUE TITLE
Whitelist CVE + Image name/regex

### ISSUE THREAD

**Issue by jonny-wg2** [aquasecurity/trivy-operator#490]
Referencing https://github.com/aquasecurity/trivy-operator/discussions/489#discussioncomment-3566772

In short, it would be great to improve the ignore file to whitelist a CVE and say an image name or some type of regex. The problem with the current setup is that some systems we can't update and need to accept the risk but others we can do something about.

E.g. 
CVE-XYZ123 registry.company.com/reg/teamname/appname:tag-1234
CVE-XYZ123 registry.company.com/reg/teamname/appname*

**Comment by chen-keinan** [comment]
@jonny-wg2 trivy-operator support [ignore policy](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L283) , meaning you can pass rego script and you can add filtering logic as you need

**Comment by jonny-wg2** [comment]
@chen-keinan Thanks for the response. Looking closer into it, I believe this type of filter would work as it gives more flexibility.

Just for clarification, if I understand correctly, an `ignore policy` of the following would ignore the CVE for all of kube-system - correct?

```
ignorePolicy.kube-system: |
  CVE-XYZ123
```

**Comment by chen-keinan** [comment]
> @chen-keinan Thanks for the response. Looking closer into it, I believe this type of filter would work as it gives more flexibility.
> 
> Just for clarification, if I understand correctly, an `ignore policy` of the following would ignore the CVE for all of kube-system - correct?
> 
> ```
> ignorePolicy.kube-system: |
>   CVE-XYZ123
> ```

exactly , please follow [rego policy examples](https://github.com/aquasecurity/trivy/blob/v0.38.1/contrib/example_policy/basic.rego) to put

**Comment by jonny-wg2** [comment]
Thanks for the update and confirmation, will close issue! :D
