### ISSUE TITLE
Please break trivy.imageRef into separate pieces

### ISSUE THREAD

**Issue by evgkrsk** [aquasecurity/trivy-operator#522]
To fetch scanner image from private mirror, now we have to override trivy.imageRef with full path with registry, repository and image tag. As a consequence, scanner image will be hardcoded and won't update during helm release updating, unlike trivy-operator's image, that have separate image tag option in values.yaml. Now we have to manually update trivy scanner image reference.

Could you separate trivy.imageRef to registry, repository and tag? Or maybe to image path and tag.

**Comment by dirien** [comment]
Hi @evgkrsk,

we have the the same "pain" as you. In my company we have a private registry. So when we update the operator via the helm chart, we needed to check the original `trivy.imageRef` to see if the tag changed too.

Now I split the `trivy.imageRef` into `trivy.repository` and `trivy.tag`

@chen-keinan, let me know if this is okay? or you prefer:

```yaml
trivy:
 image:
   repository: yyy
   tag: zzzz
```

Or as @evgkrsk suggested `registry`, `repository` and `tag`. My PR just used `repository` and `tag` similar to the operator image itself.

**Comment by chen-keinan** [comment]
@evgkrsk @dirien sound like a legitimate requirement. 
I'm adding it to backlog , you can pick it up if you want or I can get to it later.

**Comment by dirien** [comment]
Hi @chen-keinan,

thanks! Here is the PR https://github.com/aquasecurity/trivy-operator/pull/524
