### ISSUE TITLE
Reconciler error "bzip2 data invalid: bad magic value" and no vulnerabilityreports

### ISSUE THREAD

**Issue by ledroide** [aquasecurity/trivy-operator#549]
**What steps did you take and what happened:**

For one of my clusters, and only this one (same configuration and version everywhere), there is no vulnerabilityreport over the whole cluster.

I find may lines that mention a `Reconciler error ; bzip2 data invalid: bad magic value` in logs from trivy operator v0.2.1.
I have tried upgrading trivy-operator : it is not fixed in v0.3.0 
```
$ kubectl logs deployment.apps/trivy-operator

{"level":"info","ts":1664167723.8917875,"msg":"Starting workers","controller":"daemonset","controllerGroup":"apps","controllerKind":"DaemonSet","worker count":1}
{"level":"error","ts":1664167724.290116,"msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-94d5d8d4c","namespace":"trivy-system"}
,"namespace":"trivy-system","name":"scan-vulnerabilityreport-94d5d8d4c","reconcileID":"4ba4b515-f58e-4cb0-9c1e-f357303d15d1","error":"illegal base64 data at input byte 6; illegal base64 data at input byte 6","errorCauses":[{"error":"illegal base64 data at input byte 6"},{"error":"illegal base64 data at input byte 6"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
[...]
```

Maybe the difference with other clusters is the higher number of namespaces and pods that are running.

**Environment:**

- Trivy-Operator version : v0.2.1 then now v0.3.0 (same issue)
- Kubernetes version : 1.24.3

**Comment by chen-keinan** [comment]
@ledroide thank you for reporting this issue. I'll explain what could cause this error:
when `vulnerability scan job` is completed it compress the output of the report to `bz2` to make it smaller for `trivy-operator` to stream it.

Could be that your `vulnerability scan job` output is not compressed (maybe old output , plain JSON) and therefore when `trivy-operator` tried to read it it fails.

can you run few commands and send the output there:
1. `kubectl get pods -n trivy-system`

if you have scan vulnerability pod with state `completed` which stuck,  could you please get it logs :
`kubectl logs <pod name> -n trivy-system`

**Comment by ledroide** [comment]
@chen-keinan thanks for your answer. Here is what you have asked for.
```
$ kubectl get pods -n trivy-system
NAME                                        READY   STATUS      RESTARTS   AGE
scan-vulnerabilityreport-5748569476-p7v4h   0/2     Completed   0          2d14h
scan-vulnerabilityreport-584c98cdbb-94nlz   0/2     Completed   0          5d18h
scan-vulnerabilityreport-649b544cdf-rzbmc   0/2     Completed   0          2d13h
scan-vulnerabilityreport-64db8448bb-p7pl9   0/2     Completed   0          5d3h
scan-vulnerabilityreport-69b7766cd4-b5w2l   0/2     Completed   0          5d3h
scan-vulnerabilityreport-69fb4d7956-6mhm9   0/2     Completed   0          5d3h
scan-vulnerabilityreport-6c5b5cdfcb-xcbf5   0/2     Completed   0          2d14h
scan-vulnerabilityreport-7457767589-hbnwp   0/2     Completed   0          43h
scan-vulnerabilityreport-7b8745fb74-gkgm8   0/2     Completed   0          5d16h
scan-vulnerabilityreport-94d5d8d4c-fw582    0/2     Completed   0          5d3h
trivy-operator-7b9f9cc8c5-cz6mr             1/1     Running     0          5h12m
```
Logs for these pods are fully base64 encoded : 
```
$ kubectl logs scan-vulnerabilityreport-7457767589-hbnwp | tail -10
Defaulted container "v2-ui" out of: v2-ui, nginx-exporter, 948e0443-b4b5-4617-a065-6d575d45ddc6 (init)
/soUEVCcj6A8ibKE9n7w4KjmioAH5IqKemKq64CqFRQQ07DNGYtv7QT9xXmFw3TAchanH0CODIYg
gaLfKISBxvagbaQ3rAMg50RSYorpggkg6+qSmk8zbecA+6Ey/r0VNZqtbmi0RItdHJ3JQZYTvyBh
RV3bSAjPIHqDXSYM9rfbvF5SQbnIhO5dBCD4FmH3MPGIcoLzgz9gul6HOVa0k+zpOX2mKnd9unLk
8JOFPobYQkztV8qH88Qe+BssHR/Dstb5XZaLByxoELf7j/HflKZ5hzKHQ56TZuwoUvgaaCUCVfeV
oeK7SLIHcPu3zxmp80Dm3UINMF8o+YmBbgIZwQHw6eXszyb7YyQ9+2SRMUI8lmDUSMlUTCUKO1sI
iSSZNAwICHYxh1HafoRQMcAp2ZvDZDBITCJrotYoPYVlsuiZRA1nFHjqP3nljywJ1ngTZDkTwC4U
fu313yWwY0lfI73fh4412Lrs3M3kfj6Y0hqOXRG0w+LkyZN5rfIvlAMvFOSKn2zu6VzQgzFPZ5af
AhsSOZl5FnUPBomOd6dvbErC4aidsKHTb1wxBDGyGMkpTfaZolXA7I+93Py6GxceGaqm2d1DQmBb
bqdif2rv0YMeQI1y3KNzn54aExDcWa+FFceCWuj5HMb17B2dKMG1j91jVNJrOTgO0lsN1yaKKR8/
```
Note that there is a warning at first, that says `Defaulted container "v2-ui" out of: v2-ui, nginx-exporter, 948e044...`.
It is related to the pod that this scan had picked in its args, and the original deployment contains the following annotation that defines the default container in the pod : 
```yaml
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: v2-ui
    spec:
      containers:
        - name: v2-ui
```
Maybe it has nothing to do with this issue, but I have also seen this log about `illegal base64 data at input byte 6` in the trivy-operator pod : 
``` 
{"level":"error","ts":1664186307.130853,"msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-64db8448bb","namespace":"trivy-system"},"namespace":"trivy-system","name":"scan-vulnerabilityreport-64db8448bb","reconcileID":"fd782915-bb3a-4b42-9728-c9f71a6db61d","error":"illegal base64 data at input byte 6; illegal base64 data at input byte 6","errorCauses":[{"error":"illegal base64 data at input byte 6"},{"error":"illegal base64 data at input byte 6"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
``` 
Maybe the root cause could be a limit in the ephemeral storage for bzip2 or base64 operations ?

**Comment by chen-keinan** [comment]
> 
> Note that there is a warning at first, that says `Defaulted container "v2-ui" out of: v2-ui, nginx-exporter, 948e044...`. It is related to the pod that this scan had picked in its args, and the original deployment contains the following annotation that 

Yes , The 1st line `Defaulted container "v2-ui" out of: v2-ui, nginx-exporter, 948e0443-b4b5-4617-a065-6d575d45ddc6 (init)` cause he problem as its not part of the output (vulnerability report ) and not compressed , therefore `trivy-operator` tries to `bz2` decompress it and fails

**Comment by ledroide** [comment]
> The 1st line Defaulted container "v2-ui" out of: v2-ui, nginx-exporter cause he problem as its not part of the output

Nevertheless, this annotation is legit and even recommended, and [documented in Kubernetes](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container). Lots of our deployments contain this annotation, every time a pod embeds more than one container.

**Comment by chen-keinan** [comment]
@ledroide I see , let's keep this issue open , I want to investigate it and see if I can workaround it.

**Comment by chen-keinan** [comment]
@ledroide not sure its related to annotation (kubectl.kubernetes.io/default-container: v2-ui).
 Could you please run another command on the same pod with specific container name and put here the output (for both container) , I want to make sure output it not corrupted :
- `kubectl logs scan-vulnerabilityreport-7457767589-hbnwp v2-ui`
-`kubectl logs scan-vulnerabilityreport-7457767589-hbnwp nginx-exporter`

**Comment by ledroide** [comment]
@chen-keinan : The first container's logs show an empty line at the beginning. The second one does not. There is nothing interresting to see at the end of the logs - it's base64 encoded.
```
$ kubectl logs scan-vulnerabilityreport-7457767589-hbnwp v2-ui | head -5

23plIOHtjVqYyUt8obMoy6eNnfIv0aYphnGcVIbe20c7XRGg44xGzVrQ2Y6Ryly1I8785rCCfxe6
jZ6r3b58ZRb46/c4018NdSMSH0dct22ZBg3aU4abYMRTVRMNSiIGE60gI7DdopFiHzLwMxcliJj9
v58+k5uCYymeIHvIynlbK+DJzJFcuvKMMdcWuYcyRXG/q4Szoxk5RLbplrO5JtSZzLRvqoy5RJoZ
TjEm7UpW9D1c53Vqpkaa1cqu4UfaSHQcdULwzOich+g/S0Ir4vcgt/nGDMhH7oP+3fFxN7MqL+TA

$ kubectl logs scan-vulnerabilityreport-7457767589-hbnwp nginx-exporter | head -5
QlpoOTFBWSZTWQ1Kkx0AB7lfgFUQWBf/8n/n3/6/7/9qUAV727nNrAdRRTr27L1nCSSBpJp4QMJP
VP1J6aI9TE00MNNBA9I9TIGSU8jGkptqjT1DID0gAAPSAAAAJITUppoGg9Q0AGg0ADQGgAA0G1JN
BNqTaTyNTT1APU9QAAAAAAAkiJkyAQ1JpmoNAAA0GgAaACQQLDP5iwsEQc4wNFL0yhoUwA53JNBC
CKBgBmSHZPJTBIQXoELeIHGQzDMJGI3dX8+UW7s8YnHMokurxhsMEnSSApr5r6Gk83Lx09/7ehgi
NLM55UXKpAkSx16LVadRkmV4+9hBommEkfxVERR7GGgYgb5aqj9M0VU4IsJY3uQYoG410ccdlagc
```

Extra info : 
```
$ kubectl logs scan-vulnerabilityreport-7457767589-hbnwp | head -2
Defaulted container "v2-ui" out of: v2-ui, nginx-exporter, 948e0443-b4b5-4617-a065-6d575d45ddc6 (init)

23plIOHtjVqYyUt8obMoy6eNnfIv0aYphnGcVIbe20c7XRGg44xGzVrQ2Y6Ryly1I8785rCCfxe6

$ kubectl logs scan-vulnerabilityreport-7457767589-hbnwp 948e0443-b4b5-4617-a065-6d575d45ddc6 
2022-09-24T14:43:45.652Z        INFO    Need to update DB
2022-09-24T14:43:45.652Z        INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2022-09-24T14:43:45.652Z        INFO    Downloading DB...
392.56 KiB / 34.22 MiB [>____________________________________________________________] 1.12% ? p/s ?2.32 MiB / 34.22 MiB [---->__________________________________________________________] 6.77% ? p/s ?8.72 MiB / 34.22 MiB [--------------->______________________________________________] 25.47% ? p/s ?17.85 MiB / 34.22 MiB [------------------------->______________________] 52.17% 29.16 MiB p/s ETA 0s26.94 MiB / 34.22 MiB [------------------------------------->__________] 78.71% 29.16 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [---------------------------------------------->] 100.00% 29.16 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [---------------------------------------------->] 100.00% 29.03 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [---------------------------------------------->] 100.00% 29.03 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [---------------------------------------------->] 100.00% 29.03 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [---------------------------------------------->] 100.00% 27.16 MiB p/s ETA 0s34.22 MiB / 34.22 MiB [-------------------------------------------------] 100.00% 18.80 MiB p/s 2.0s
```
I have checked the other pods like scan-vulnerabilityreport-xxxxx : they all mention these 3 containers beginning with v2-ui and nginx-exporter + scan container

Hope it helps.

**Comment by chen-keinan** [comment]
@ledroide thanks for this input , the last container is the init container (where we download the vulndb)
can you please check another thing run the following and just let me know if you got a JSON report without error :

`kubectl logs scan-vulnerabilityreport-7457767589-hbnwp v2-ui | base64 --decode | bzip2 -d`

`kubectl logs scan-vulnerabilityreport-7457767589-hbnwp nginx-exporter | base64 --decode | bzip2 -d`

**Comment by ledroide** [comment]
Issue is solved, however hard to explain.
I have added this variable to ConfigMap/trivy-operator-trivy-config :
```yaml
data:
  trivy.imageRef: ghcr.io/aquasecurity/trivy:latest
```
On the other hand, this variable is supposed to be useless since trivy-operator v0.3.0 - that uses instead these variables : 
```yaml
data: 
  trivy.repository: ghcr.io/aquasecurity/trivy
  trivy.tag: latest
```
Using all 3 variables works for me. I will investigate later.

**Comment by chen-keinan** [comment]
@ledroide do you want to keep this issue open ?
