### ISSUE TITLE
remove the kube-bench plugin

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#55]
it is required to remove the kube-bench plugin
- plugin logic
- controller
- helm chart
- crds

**Comment by josedonizetti** [comment]
@chen-keinan Removing kube-bench, also means removing ClusterComplianceReport (logic, controller, helm chart, crd, right? Because the cluster compliance is a mix of info from kube-bench/configaudit reports.

**Comment by chen-keinan** [comment]
> @chen-keinan Removing kube-bench, also means removing ClusterComplianceReport (logic, controller, helm chart, crd, right? Because the cluster compliance is a mix of info from kube-bench/configaudit reports.

not really, lets keep compliance report as we are going to replace kube-bench checks with OPA rego policies
