### ISSUE TITLE
Add metrics about CVE vulnerability ID

### ISSUE THREAD

**Issue by MatthieuFin** [aquasecurity/trivy-operator#562]
Currently operator exposed metrics about VulnerabilityReport.
That's a good thing, but there is nothing about CVE. 

I propose to add metrics `trivy_vulnerability_id` which is a sensibly the same as current `trivy_image_vulnerabilities` but with the label `vuln_id` which permit to build dashboard focused en CVE, and made simple prometheus queries to search specific CVE in whole cluster.

In the past we have build something like that based on starboard with a json exporter, but this was hard to maintain and scale. Integrate this feature in operator metrics seems for me to be a good idea.

**Comment by MatthieuFin** [comment]
FYI, this is an example of grafana dashbord modification available with this feature, which run on one of our test purpose cluster with a lot vulnerabilities:
![2022-10-05_16-41](https://user-images.githubusercontent.com/4145084/194090097-71a4e084-91c1-4a66-bd70-984781bf325e.png)

**Comment by JAORMX** [comment]
While that looks quite useful, it seems to me like it would greatly explode the cardinality of metrics. While this would work well in a small demo or a small cluster with a couple of images, this would be quite problematic in bigger clusters.
