### ISSUE TITLE
Use same labels value case

### ISSUE THREAD

**Issue by jfcoz** [aquasecurity/trivy-operator#568]
**What steps did you take and what happened:**

When using new metrics from https://github.com/aquasecurity/trivy-operator/issues/562,
- I get theses label values `trivy_vulnerability_id` severity: `CRITICAL`, `HIGH`…
- whereas on `trivy_image_vulnerabilities` I get `Critical`, `High`…

**What did you expect to happen:**

Same case for all label values

**Comment by chen-keinan** [comment]
@jfcoz this fix has not been released officially yet, have you tested it on the RC version ?

**Comment by jfcoz** [comment]
Yes, I've tested it

**Comment by chen-keinan** [comment]
> Yes, I've tested it

Thanks for the update , I'll check it out.

**Comment by MatthieuFin** [comment]
Hi,
I have work on it by adding a type `SeverityLabel` on overlap Severity Labels case. And i have setup some unit tests on these feature specifically.
