### ISSUE TITLE
Trivy-Operator CRDs out-of-sync if deployed using ArgoCD

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#58]
**What steps did you take and what happened:**

- I deployed the trivy-operator helm chart using an ArgoCD application and noticed a small issue.
The trivy operator get's installed and it's working perfectly, but the trivy-operator CRDs are staying out-of-sync in ArgoCD.
This is because the `categories:` field of all trivy-operator CRD is an empty list and get's dropped by Kubernetes.
While this might not be an issue for trivy-operator and kubernetes, it is for argocd that sees a diff between the desired state and the live state.

**What did you expect to happen:**

- I expect to have all trivy-operator CRD in sync after the helm chart deployment.

**Anything else you would like to add:**

- Coming back with a PR to fix

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-operator version (use `trivy-operator version`): v0.0.3
- Kubernetes version (use `kubectl version`): v1.20.15-eks (aws eks)
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): archlinux

**Comment by dotdc** [comment]
Just realized that this project is the follow-up to starboard.
I'm the author of the original [issue #1021](https://github.com/aquasecurity/starboard/issues/1201) on Starboard.
I will re-open the PR here.

Maybe you should display a warning banner in the starboard `README.md` to redirected people to trivy-operator :wink:
