### ISSUE TITLE
Failed scan-vulnerabilityreport Job : read-only filesystem

### ISSUE THREAD

**Issue by LucasVanHaaren** [aquasecurity/trivy-operator#620]
Hello everybody, I just experienced an issue with trivy-operator :

**What steps did you take and what happened:**

After installing **trivy-operator** (in client/server mode), all the images in my cluster are scanned. 
But 2 of these images constantly create an error in **trivy-operator**.
The error message evokes a temporary file writing problem but this is not clear to me, here is the error in trivy-operator's logs :

```json
{
   "level":"error",
   "ts":1666776971.8307042,
   "logger":"reconciler.vulnerabilityreport",
   "msg":"Scan job container",
   "job":"trivy-system/scan-vulnerabilityreport-798488c974",
   "container":"my-container",
   "status.reason":"Error",
   "status.message":"2022-10-26T09:36:10.861Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer: sha256:0848bc0012cb9f2005677b3daf3a5e5fe3e8ad944eaad35d680a9a2fc36135e3 : walk error: failed to process the file: failed to analyze file: failed to analyze opt/job/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: unable to open opt/job/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: failed to open: failed to create the temp file: open /tmp/fanal-2646250566: read-only file system\n",
   "stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:539\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:370\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"
}
```
PS: the two images that have this issues are custom ones pulled from private registry.

**What did you expect to happen:**

I expect the Job to succeed like all the others.

**Anything else you would like to add:**

- What filesystem is in read-only and why trivy want to create temp file on it ?
- Why the error message mention "failed to open" and also "failed to create the temp file" ? 

**Environment:**

- Trivy-Operator : `v0.2.0`
- Kubernetes : `v1.20.15`
- Nodes OS : `Ubuntu 18.04.6`

Thanks in advance for your help :love_you_gesture:

**Comment by chen-keinan** [comment]
@LucasVanHaaren thanks for reporting , we will check it out.

**Comment by LucasVanHaaren** [comment]
I just tested to run trivy image (and fs) scans from my host system instead of k8s cluster and trivy successfully scanned the same image.

**NB:** I tested both standalone `trivy v0.33.0` on my host system and ser `trivy server v0.30.4`.

**Comment by chen-keinan** [comment]
@LucasVanHaaren I see where the problem is. 

 When trivy scan large files it saving it  into `/tmp` folder (to avoid loading it to memory) for analysis purposes.

Trivy-operator in `client /server` mode do not mount `/tmp` folder  in `scanjob` container.
I'll create a PR with a fix for next release

**Comment by LucasVanHaaren** [comment]
Nice ! Thank you so much for your efficiency @chen-keinan :smiley:
