### ISSUE TITLE
Missing ClusterComplianceReport

### ISSUE THREAD

**Issue by jicunningham** [aquasecurity/trivy-operator#621]
**What steps did you take and what happened:**
Install via helm
[A clear and concise description of what the bug is, and what commands you ran.]
After I noticed the trivy pod had restarted several times, I checked the logs and found these lines:
`
{"level":"error","ts":1666794056.989362,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"ClusterComplianceReport.aquasecurity.github.io","error":"no matches for kind \"ClusterComplianceReport\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:139\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
{"level":"error","ts":1666794065.0388808,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"ClusterComplianceDetailReport.aquasecurity.github.io","error":"no matches for kind \"ClusterComplianceDetailReport\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:139\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
`
**What did you expect to happen:**
The operator pod to keep running and not restarting
**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.4.0
- Kubernetes version (use `kubectl version`): 
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.22.12-gke.2300
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@jicunningham thanks for reporting , is this fresh install or upgrade (from starboard)?  its really weird  as we removed `ClusterComplianceReport` from `trivy-operator` from the beginning

**Comment by chen-keinan** [comment]
@jicunningham thanks will remove it for now 
 btw : we are woking these days to introduce it back , so keep watching our repo.
