### ISSUE TITLE
High memory requirements when Pod contains many containers

### ISSUE THREAD

**Issue by philippn** [aquasecurity/trivy-operator#632]
**What steps did you take and what happened:**

In our cluster we are using the Elasticsearch on Kubernetes (ECK) operator. When deploying a Elasticsearch cluster using it, it will spawn a Pod with no less than 5 (!) containers. Because of #359, we had to increase the memory to 1500M. Now this adds up to an overall memory requirement of a whopping 7,5 Gig for the scan job, because the scan job seems to replicate each of the containers of the original pod.  Unfortunately, the scan Job will never be scheduled in our case, because we are hitting resource constraints.

**What did you expect to happen:**

Perhaps it would be better to create one scanjob per container per pod instead of one scan job per Pod? Assuming the high memory usage only applies to the init container, it might also help to be able to specify the resources of the init container which pulls the DB and the resources of the actual scan jobs independently from each other.

**Anything else you would like to add:**

My feeling is that we didn't encounter this problem with Trivy Operator 0.3.0 before. I'm not 100% sure though, because there could also be slightly different workloads now.

Apart from that, thanks for your efforts. Your work is highly appreciated!

**Environment:**

- Trivy-Operator version: 0.4.0
- Kubernetes version: 1.22.6
- OS: Windows 10

**Comment by philippn** [comment]
Another possible solution that came to mind is to assemble the scan job as a bunch of init containers. Because init containers are executed sequentially, this should also solve the problem.

**Comment by chen-keinan** [comment]
@philippn have you consider running `trivy-operator` in client/server (as in client server mod we do not call init container) mode also together with #416  should solve you issue

**Comment by philippn** [comment]
Hello @chen-keinan ,
thanks for your quick reply. No, I haven't considered this yet (hadn't heard about this yet), but from the looks of it it might indeed solve the issue.

**Comment by philippn** [comment]
@chen-keinan  Just a quick heads up: I have now deployed a trivy server using this [Helm chart](https://github.com/aquasecurity/trivy/tree/main/helm/trivy). After doing so I could reduce the memory limits to 1000M without running into OOMKilled errors, while 500M still brings up OOMKilled errors . Previously I needed 1500M as per #359.

So overall it improved the situation somewhat, at least for me. However, the memory usage for simple client usage still seems to be pretty high.

Anyways, thanks for the pointer!

**Comment by chen-keinan** [comment]
@philippn thanks for the update.  it is ongoing effort for us to reduce the memory footprint.
