### ISSUE TITLE
Ability to pass image pulling secrets/credentials to trivy operator container to pull trivy image from private repository

### ISSUE THREAD

**Issue by amansharif** [aquasecurity/trivy-operator#633]
**Feature request:** Ability to pass image pull secrets to trivy operator for pulling trivy image to run the vulnerability scan jobs.

**Description:** Currently we can pass image pull secrets to trivy-operator image but there's no capability to pass image pull secrets for trivy image as well. As trivy operator manages the scan jobs and takes care of pulling trivy image, we need some mechanism to pass image pull secrets for trivy image pulling as well. Probably through environment variables or some other means.

**Context:** We are running trivy on Rancher tenant cluster behind corporate firewall. So, we need to build custom trivy image with our private CA and put into our image repository. We need to pass image pull secrets to be able to pull our custom trivy image. Probably other will come across same kind of use case sooner than later.

**Comment by chen-keinan** [comment]
@amansharif I think this the PR#628 to solve it and associated issue #409 .

**Comment by amansharif** [comment]
Yeah. looks like that. I will try out once it's merged. Thank you.

**Comment by amansharif** [comment]
Hi @chen-keinan it seems the PR #628 and #409 has been merged. However, when I tried with the latest helm chart and trivy-operator image (i.e. 0.5.0), it did not work and I could not find imagePullSecret field in scan jobs manifests. Later I checked the release notes  and found that those PRs were not there in the latest release i.e. 0.5.0. May I ask  when those PRs/features will be released ?

**Comment by chen-keinan** [comment]
> Hi @chen-keinan it seems the PR #628 and #409 have been merged. However, when I tried with the latest helm chart and trivy-operator image (i.e. 0.5.0), it did not work and I could not find imagePullSecrets field in scan jobs manifests. Later, I checked the release notes  and found that those PRs were not there in the latest release i.e. 0.5.0. May I ask  when those PRs/features will be released ?

@amansharif the PR has been merged after `trivy-opetator v0.5.0` has been released, so its not part of `trivy-operator v0.5.0` , it will be out with `trivy-operator v0.6.0`

**Comment by chen-keinan** [comment]
@amansharif `trivy-operator v0.6.0-rc3` is available you can try the feature with it

**Comment by chen-keinan** [comment]
@amansharif closing this issue as it has been fixed with `trivy-operator v0.6.0` if you think its still an issue , you can re-open it.

**Comment by amansharif** [comment]
yes. it is working. thank you for quick response.
