### ISSUE TITLE
feat(helm): allow an user defined existing secret

### ISSUE THREAD

**Issue by cebidhem** [aquasecurity/trivy-operator#638]
Hey there,

We are using Trivy for a long time in our CI, but we recently decided to give a try to the Trivy Operator.
As I noted for trivy in https://github.com/aquasecurity/trivy/issues/2586, all secrets for trivy-operator must be defined as values in order to get consumed by the secret (see https://github.com/aquasecurity/trivy-operator/blob/v0.5.0/deploy/helm/templates/config.yaml#L134). 
It would be nice to have a way to define a secret created outside of the chart (we're using external-secrets but it could be something else).

I will submit a PR on this shortly since I haven't seen any.

Let me know if it was on purpose, I'll close.

**Comment by cebidhem** [comment]
Hi @chen-keinan I don't know how the project works, should I ping a codeowner or reviewer in the PR to get it reviewed ?

Or are PRs assigned by someone else in the project ?

**Comment by chen-keinan** [comment]
@cebidhem its ok , I review new PRs on a daily basis.  your PR is on my queue
