### ISSUE TITLE
trivy-operator: secrets scanning

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#64]
Trivy now has support to secrets scanning. We should upgrade it, and make sure secrets are supported.

**Comment by josedonizetti** [comment]
That makes sense. But I wonder do we want to create reports for all `security-checks`? For example, `trivy image` checks for 3 different security checks `vuln, config, and secrets` (and maybe there will be newer in the future, sbom?). The operator currently only parses vulnerabilities, so it generates 1 vulnerability report for the target (image), if we are saying we will a report specifically for secret for the target (image), are we also generating a config report for the image target? 

Something like:

```
Report - Target (image)
vulnerabilityreport - josedonizetti/personalimage:v0.1.0
secretreport - josedonizetti/personalimage:v0.1.0
configauditreport - josedonizetti/personalimage:v0.1.0 
```

Tbh, I would prefer a `imagereport` CRD with all the information about the image (all security-checks).  

@knqyf263 @chen-keinan @itaysk thoughts?

**Comment by itaysk** [comment]
I'm fine with either way, just noted that it will be a deviation from current model (which is fine). I would also solicit feedback from more people before making a decision (I will send this to some people)
anyway, IF we do one CRD, then I think it should be at the resource level not at the image level, since minsonf/secrets will need to report on resources (not only inside the image).

**Comment by itaysk** [comment]
BTW, do you think that secrets can fit within config audit? the name is generic enough

**Comment by josedonizetti** [comment]
> BTW, do you think that secrets can fit within config audit? the name is generic enough

I really like it, `configaudit` can cover both security-checks `secret` and `config`, the different is the target, instead of targeting a `resource` it target an image, eg:

```
kubectl get configaudit
NAME                       SCANNER          AGE
deployment-orion   Trivy-Operator   10h. --> configaudit on a resource
library/alpine            Trivy-Operator   10h. --> configaudit the image of the resource, showing both secrets and misconfigs (--security-checks=config/secrets)
```
