### ISSUE TITLE
Adding labels with non-alphanum characters (.,/) to reportResourceLabels fails to generate metrics

### ISSUE THREAD

**Issue by dkulchinsky** [aquasecurity/trivy-operator#646]
**What steps did you take and what happened:**

defined report resource labels to include the Kubernetes [standard labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels):
```yaml
reportResourceLabels: "app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance"
```

**What did you expect to happen:**

was expecting to see the above labels added to the vulnerability reports and metrics, however the operator failed to create the metrics with these labels:
```
trivy-operator unable to run trivy operator: starting controllers manager: descriptor Desc{fqName: "trivy_image_vulnerabilities", help: "Number of container image vulnerabilities", constLabels: {}, variableLabels: [namespace name image_registry image_repository image_tag image_digest severity k8s_label_app.kubernetes.io/name k8s_label_app.kubernetes.io/component k8s_label_app.kubernetes.io/instance]} is invalid: "k8s_label_app.kubernetes.io/name" is not a valid label name for metric "trivy_image_vulnerabilities"
```

which resulted in a crash loop.

**Anything else you would like to add:**

Since prometheus metrics labels cannot include characters such as `.` or `/` the K8s labels need to be sanitized and replaced with `_` (this is common practice in most exporters, for example kube-state-metrics)

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.5.0
- Kubernetes version (use `kubectl version`): 1.22.12
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu

**Comment by chen-keinan** [comment]
@dkulchinsky thanks for reporting it , we will add sanitization to label name.

**Comment by dkulchinsky** [comment]
thanks for the quick fix @chen-keinan!
