### ISSUE TITLE
Scans take 10+ min in air-gapped cluster for some images as trivy tries to reach search.maven.org

### ISSUE THREAD

**Issue by nobbs** [aquasecurity/trivy-operator#657]
**What steps did you take and what happened:**

I've deployed the trivy-operator successfully on a cluster running on [RKE2](https://docs.rke2.io/) using the Helm chart. Operator is starting as expected and logs do show that it is also being triggered when workloads are created. Unfortunetaly, it is not able to scan images and returns the following error:

```json
{
    "level": "error",
    "ts": 1667817961.652814,
    "logger": "reconciler.vulnerabilityreport",
    "msg": "Scan job container",
    "job": "trivy-operator/scan-vulnerabilityreport-788955dd59",
    "container": "nginx",
    "status.reason": "Error",
    "status.message": "2022-11-07T10:45:59.392Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (nginx:1.16): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* Get \"https://index.docker.io/v2/\": dial tcp 18.206.20.10:443: connect: connection refused\n\n\n",
    "stacktrace": "github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:551\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:376\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"
}
```

It looks like it can't find the `containerd.sock` as it's only looking in one default place, i.e. `/run/containerd/containerd.sock`.

RKE2 does use containerd as its CRI, but it does not rely on the system provided containerd setup and instead provids its own builtin containerd, thus also using its own path for the socket, i.e. `/run/k3s/containerd/containerd.sock`. This is not picked up by trivy / the trivy-operator and thus the above errors.

**What did you expect to happen:**

Deployed the trivy-operator and deployed an example workload. Expected to get a report on vulnerabilities.

**Anything else you would like to add:**

It looks like there is an experimental way in trivy to change the path used for the socket, see <https://aquasecurity.github.io/trivy/v0.34/docs/advanced/container/containerd/>.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
  - `{"level":"info","ts":1667817292.0559022,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.5.0","Commit":"e43a4c63a33aa35c0d1c2c3600be41b6d0ded7d0","Date":"2022-10-30T12:26:08Z","Executable":""}}`
- Kubernetes version (use `kubectl version`):
  - `version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+rke2r1", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-13T17:54:54Z", GoVersion:"go1.19.2 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}` 
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
  - rke2 running on RHEL 8.6

**Comment by chen-keinan** [comment]
@nobbs thanks for you feedback , I'll review this option

**Comment by chen-keinan** [comment]
@nobbs have you consider using the `client/server` mode,  you can put your server outside of the cluster where it is accessible from cluster and internet , does it make sense ?

**Comment by nobbs** [comment]
That would certainly be possible to some degree (using a whitelist-proxy, so would need to gather the domains that trivy will try to call) - to be honest, the `--offline-scan` option would be probably be the far simpler solution in my case (and the results good enough anyway).

I could try to implement it myself and provide a PR for this if you want - I haven't written go in a while, so that probably will take a while.

**Comment by chen-keinan** [comment]
@nobbs sure go for 🚀  ping me if you have any question

**Comment by sherifkayad** [comment]
@chen-keinan @nobbs just a question for my understanding as I hit this issue today: what are the down sides of turning on the `offline` scans? (setting the flag `--offline-scan`)?

**Comment by nobbs** [comment]
> @chen-keinan @nobbs just a question for my understanding as I hit this issue today: what are the down sides of turning on the `offline` scans? (setting the flag `--offline-scan`)?

To my understanding the `offline scan` option only affects Java vulnerability reports, as Java / jar files will be checked against the maven API for additional vulnerability information. But even with offline scan you will get results for those files. Can't say if there's a difference in quality or quantity of reported vulnerabilities. 

Check the docs, esp. [this troubleshooting section](https://aquasecurity.github.io/trivy/v0.36/docs/references/troubleshooting/#maven-rate-limiting-inconsistent-jar-vulnerability-reporting) and the one on air capped setups. 

The offline scan does not block the downloading of the main vulnerability database, just additional requests to maven (at least in the current releases of trivy).
