### ISSUE TITLE
Add reference to artifacthub.io

### ISSUE THREAD

**Issue by HaveFun83** [aquasecurity/trivy-operator#665]
It will be great to the list the trivy-operator helmchart as official artifact within Artifact Hub.
https://artifacthub.io/docs/topics/repositories/helm-charts/#helm-charts-repositories

**Comment by chen-keinan** [comment]
@HaveFun83 you can pick this this issue up if you have time

**Comment by HaveFun83** [comment]
> @HaveFun83 you can pick this this issue up if you have time

I can try but someone with artifacthub credentials need to create the repository there first.
Looks like aquasecurity already has an account there:
https://artifacthub.io/packages/search?user=deployment-aqua&sort=relevance&page=1

**Comment by chen-keinan** [comment]
@HaveFun83 I see  `trivy-operator` has been created by its not the one from `aquasecurity`

**Comment by chen-keinan** [comment]
> Yeah i saw this. Nevertheless someone with the "deployment-aqua" user need to create a repository for the "aquasecurity[trivy-operator" within articathub or sign-up as new user.
> 
> if i do this the artifacthub .io repository will be under my sovereignty

thanks for looking at it  I will create it

**Comment by chen-keinan** [comment]
@HaveFun83 now `trivy-operator` is [available](https://artifacthub.io/packages/helm/trivy-operator/trivy-operator) on artifacthub.io

**Comment by HaveFun83** [comment]
@chen-keinan Thank you so much. 👍
