### ISSUE TITLE
Implement "Caching Scan Results by Image Reference"

### ISSUE THREAD

**Issue by neiser** [aquasecurity/trivy-operator#668]
I'm interested in the status of the document [Caching Scan Results by Image Reference](https://github.com/aquasecurity/trivy-operator/blob/main/docs/design/caching_scan_results_by_repo_digest.md), as my team would really appreciate such a feature being implemented. The document reads as if there was already some implementation attempt for the operator code here, but I can't find any pull request or reference in the document to that code. I also checked in the original starboard repo and only [found a similar document](https://github.com/aquasecurity/starboard/blob/main/docs/design/caching_scan_results_by_repo_digest.md).

Telling from the git history, maybe @NissesSenap or @danielpacak can comment how far implementation-wise this feature is? Also, maybe @chen-keinan knows? I hope it's ok that I mention you guys directly.

Any pointer is appreciated, and if you don't have any objections, I could try and start implementation of this feature on my own.

**Comment by NissesSenap** [comment]
@neiser I started looking in to it in the starboard project but I haven't been active in the aquasecurity project in a long time so I can't remember to be honest.

I know that  @danielpacak started on a PR before he stopped and instead wrote a design document that I gave some feedback on: https://github.com/aquasecurity/starboard/pull/740.

But I don't think anything was done after that but as I said I haven't been active in trivy-operator project.
Here @chen-keinan could give some insight.

I would love to see the feature and If you have time to look at it I think go for it :).

**Comment by neiser** [comment]
@NissesSenap Thanks for that super quick reply!

**Comment by chen-keinan** [comment]
@neiser this could be a very good feature and go for it if you wish 🚀  few points :
- TTL -  today each report has by default TTL (24h , configurable)  , I think will be good to keep it for vulnerability cluster reports (avoid false negative)
- GC  - not sure if it is a must as we have TTL but today each report own by one resource 
- it will be great to make it configurable

**Comment by neiser** [comment]
I've updated the issue title to reflect that we should/can implement this feature.

**Comment by sathieu** [comment]
not stale.

@chen-keinan Please add the relevant label to prevent this issue to be marked as stale in the future :pray:.

**Comment by sathieu** [comment]
still not stale.
