### ISSUE TITLE
scan-vulnerabilityreport is preventing nodes from scaling down. 

### ISSUE THREAD

**Issue by BenCoughlan15** [aquasecurity/trivy-operator#675]
Hi, I'm getting the following from GKE in all environments: 

`messageId: "no.scale.down.node.pod.controller.not.found"
parameters: [
0: "scan-vulnerabilityreport-7fb56d857f-bxn6p"`

I've tried to set every type of annotation, including scanJobAnnotations, but to no avail, the jobs are completed and preventing nodes from shutting down. 

Is there any way to set this parameter?

**Comment by chen-keinan** [comment]
@BenCoughlan15  could you please share some of the background.
you have `trivy-operator` installed on GKE and its working ? producing reports ?

**Comment by BenCoughlan15** [comment]
Hey! Yep, it's working, but the pods don't have a controller, so GKE sees the nodes as unable to be shut down. 

I need to add a "safe to evict" pod annotation, but can't see how to do so. 


cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

Otherwise my clusters grow indefinitely.

**Comment by chen-keinan** [comment]
> Hey! Yep, it's working, but the pods don't have a controller, so GKE sees the nodes as unable to be shut down.
> 
> I need to add a "safe to evict" pod annotation, but can't see how to do so.
> 
> cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
> 
> Otherwise my clusters grow indefinitely.

@BenCoughlan15 just to make sure I clearly understand it , the `scan-vulnerability` pods are in status `completed` but are not get deleted afterwards ? 
did you check also if there are errors in `trivy-operator` logs ?

**Comment by jrhunger** [comment]
@BenCoughlan15 check if the jobs still exist as completed in the trivy-system namespace.  If so, have a look at those jobs yaml to see if they have the container mixup described in #509 I found that at least on k8s 1.24.3 this results in the jobs remaining in trivy-system and not getting cleaned up.

**Comment by chen-keinan** [comment]
@BenCoughlan15 any progress with this issue ?

**Comment by chen-keinan** [comment]
@BenCoughlan15  few improvements in  that area has been introduced with `trivy-operator v0.10.1` could please confirm is this is still an issue afterwards

**Comment by chen-keinan** [comment]
@BenCoughlan15 any update ?

**Comment by BenCoughlan15** [comment]
> @BenCoughlan15 any update ? 

Hey, sorry, unfortunately we stopped using Trivy, because of stuff like this actually, and the reporting. 

Thanks for reaching out thought. 👍
