### ISSUE TITLE
trivy.skipDirs is ignored by trivy-operator

### ISSUE THREAD

**Issue by akerge** [aquasecurity/trivy-operator#676]
**TL;DR:** `trivy.skipDirs` is ignored by trivy-operator with full and relative path when `WORKDIR` is set.

**What steps did you take and what happened:**

Assuming:

* `trivy.command: "filesystem"` in trivy-operator conf is equal to `trivy fs .`
* `node_modules` directory is in the `WORKDIR`

From within container executed trivy filesystem scan with `--skip-dirs node_modules`:

`trivy fs . --skip-dirs node_modules`

In trivy-operator deployment yaml tried:

* adding `trivy.skipDirs` with full and relative path to `trivy-operator-trivy-config` ConfigMap:
  * `trivy.skipDirs: "/usr/src/app/node_modules"`
  * `trivy.skipDirs: "node_modules"` (with and without quotes)

**What did you expect to happen:**

Expected the `node_modules` directory to be ignored by trivy-operator as it is ignored by trivy.

**Anything else you would like to add:**

Somewhat related ticket in trivy repo: https://github.com/aquasecurity/trivy/issues/1283

[`trivy --skip-dirs` examples](https://aquasecurity.github.io/trivy/v0.17.2/examples/skip/)

[trivy-operator ConfigMap keys](https://aquasecurity.github.io/trivy-operator/v0.5.0/vulnerability-scanning/trivy/#settings)

**Environment:**

- Trivy-Operator version: v0.2.1
- Trivy version: v0.34.0
- Kubernetes version: v1.19.16
- OS: Ubuntu 22.04.1 LTS

**Comment by chen-keinan** [comment]
@akerge are you running operator in `fs mode` or `image mode (default)` ?

**Comment by akerge** [comment]
Operator is running in `filesystem` mode.

For example this one: https://hub.docker.com/r/tvvignesh/node-skeleton/tags.

**Comment by chen-keinan** [comment]
@akerge I have exposed `skipDir` param via helm and cut a release `trivy-operator v0.9.1` 
tested it with :
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.command=filesystem" \
  --set="trivyOperator.scanJobPodTemplateContainerSecurityContext.runAsUser=0" \
  --set="trivy.ignoreUnfixed=true" \
  --set="trivy.skipDirs=/usr/local/lib/node_modules" \
  --version 0.9.1
```

and found that it works find , please confirm

**Comment by akerge** [comment]
Errored, when tried installing the chart:

```
Error: INSTALLATION FAILED: ClusterComplianceReport.aquasecurity.github.io "nsa" is invalid: spec.compliance.controls.checks: Invalid value: "null": spec.compliance.controls.checks in body must be of type array: "null"
```

I wonder if the `WORKDIR` can be dynamically fed to `skipDirs`?
