### ISSUE TITLE
Resources with long enough names don't get scanned

### ISSUE THREAD

**Issue by cwrau** [aquasecurity/trivy-operator#678]
**What steps did you take and what happened:**

Have an application which `$name-$container` is ~63 characters long

**What did you expect to happen:**
A vulnerabilityreport and metrics about the image

**Anything else you would like to add:**

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.6.0*rc3
- Kubernetes version (use `kubectl version`): 1.24
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): not applicable

**Comment by chen-keinan** [comment]
@cwrau thanks for reporting this issue , dit you got error on `trivy-operator` log ? if so could you put it here

**Comment by dkulchinsky** [comment]
according to the code here:
https://github.com/aquasecurity/trivy-operator/blob/427482dda5352afab11aabcf813be0daad7acdc6/pkg/vulnerabilityreport/builder.go#L251-L260

if the generated report name is too long (> 63 characters), the name will be stored as: "<resource type>-<hash of name & container>", e.g.: `replicaset-66f5df7b4f`

**Comment by cwrau** [comment]
> according to the code here:
> 
> https://github.com/aquasecurity/trivy-operator/blob/427482dda5352afab11aabcf813be0daad7acdc6/pkg/vulnerabilityreport/builder.go#L251-L260
> 
> if the generated report name is too long (> 63 characters), the name will be stored as: `<resource type>-<hash of name & container>`
> 
> For example: `replicaset-66f5df7b4f`

Huh, that was the only thing we could think of why these pods/containers don't get scanned

We have various replicasets with a name length of 51, including the `replicaset-` prefix a length of 62 and with a container suffix `-postgraphile` a length of 64.

The replicasets have `imagePullSecrets`, but other replicasets with `imagePullSecrets` also get scanned.

The only thing we can see in the logs, with debug enabled, is the following;

```log
1.6683553048584166e+09	DEBUG	resourcecontroller	Ignoring managed pod	{"kind": "Pod", "name": "default/REPLICASET_NAME-HASH-qzx4v", "controllerKind": "ReplicaSet", "controllerName": "REPLICASET_NAME-HASH-858d56865b"}
1.6683859012666187e+09	DEBUG	reconciler.ttlreport	RequeueAfter	{"report": "default/replicaset-REPLICASET_NAME-HASH", "durationToTTLExpiration": "38h1m50.733383868s"}
1.66838590318254e+09	DEBUG	resourcecontroller	Checking whether configuration audit report exists	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.668385903183431e+09	DEBUG	resourcecontroller	Configuration audit report exists	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683888465682693e+09	DEBUG	resourcecontroller	Checking whether configuration audit report exists	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683888465684412e+09	DEBUG	resourcecontroller	Configuration audit report exists	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683888465719206e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683888465728645e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "limit": 1}
1.6683888465729718e+09	DEBUG	reconciler.vulnerabilityreport	Pushing back scan job	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "retryAfter": "30s"}
1.6683888765734534e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683888765762196e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "limit": 1}
1.6683888765762873e+09	DEBUG	reconciler.vulnerabilityreport	Pushing back scan job	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "retryAfter": "30s"}
1.6683889065775409e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683889065812094e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "limit": 1}
1.6683889065818274e+09	DEBUG	reconciler.vulnerabilityreport	Pushing back scan job	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "retryAfter": "30s"}
1.6683889365840764e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683889365858104e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "limit": 1}
1.668388936585851e+09	DEBUG	reconciler.vulnerabilityreport	Pushing back scan job	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "retryAfter": "30s"}
1.668388966586908e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683889665887692e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "limit": 1}
1.668388966588833e+09	DEBUG	reconciler.vulnerabilityreport	Pushing back scan job	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 1, "retryAfter": "30s"}
1.668388996589803e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH"}
1.6683889965911934e+09	DEBUG	reconciler.vulnerabilityreport	Checking scan jobs limit	{"kind": "ReplicaSet", "name": "default/REPLICASET_NAME-HASH", "podSpecHash": "6cd74599bf", "count": 0, "limit": 1}
1.668392000152371e+09	DEBUG	resourcecontroller	Ignoring managed pod	{"kind": "Pod", "name": "default/REPLICASET_NAME-HASH-qzx4v", "controllerKind": "ReplicaSet", "controllerName": "REPLICASET_NAME-HASH-858d56865b"}
1.66839200015303e+09	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "Pod", "name": "default/REPLICASET_NAME-HASH-qzx4v"}
1.6683920001531053e+09	DEBUG	reconciler.vulnerabilityreport	Ignoring managed pod	{"kind": "Pod", "name": "default/REPLICASET_NAME-HASH-qzx4v", "controllerKind": "ReplicaSet", "controllerName": "REPLICASET_NAME-HASH-858d56865b"}
```

It looks like they just get pushed back but then never really worked on (the weird timestamp does *not* help in debugging this)

**Comment by chen-keinan** [comment]
@dkulchinsky , yes this is done intentionally, we make name shorter (due to k8s label limitation) but it should not impact scanning

**Comment by cwrau** [comment]
> @dkulchinsky , yes this is done intentionally, we make name shorter (due to k8s label limitation) but it should not impact scanning , did you saw `scan-job` created for these replica-sets ?

Hah, I just saw the job, but one of the containers was OOMKilled then the Job finished and got deleted but there is no report. 😕

(Btw, the `scanJobsConcurrentLimit` doesn't really work, we have a limit of `1` but very often there are 3, 4 or even 5 jobs running concurrently)

> can you do a quick test deploy a simple replica-set with the naming as describe above and let me know if you see that a :
> 
> * `scan-job` is created

yes

> * if the `scan-job` get completed

yes, but one container got `OOMKilled`

> * if it get deleted after point 2
>   * vulnerability report is produced ?

no 😕

The second job, btw awesome that the hash of the job is always the same for the same resource 👍️, had the same result

**Comment by chen-keinan** [comment]
> > @dkulchinsky , yes this is done intentionally, we make name shorter (due to k8s label limitation) but it should not impact scanning , did you saw `scan-job` created for these replica-sets ?
> 
> Hah, I just saw the job, but one of the containers was OOMKilled then the Job finished and got deleted but there is no report. 😕
> 
> (Btw, the `scanJobsConcurrentLimit` doesn't really work, we have a limit of `1` but very often there are 3, 4 or even 5 jobs running concurrently)
> 
> > can you do a quick test deploy a simple replica-set with the naming as describe above and let me know if you see that a :
> > 
> > * `scan-job` is created
> 
> yes
> 
> > * if the `scan-job` get completed
> 
> yes, but one container got `OOMKilled`
> 
> > * if it get deleted after point 2
> >   
> >   * vulnerability report is produced ?
> 
> no 😕
> 
> The second job, btw awesome that the hash of the job is always the same for the same resource 👍️, had the same result

I see , OOM issue require tuning the resources , have you tried it set it up , increase memory ?

**Comment by cwrau** [comment]
> > > @dkulchinsky , yes this is done intentionally, we make name shorter (due to k8s label limitation) but it should not impact scanning , did you saw `scan-job` created for these replica-sets ?
> > 
> > 
> > Hah, I just saw the job, but one of the containers was OOMKilled then the Job finished and got deleted but there is no report. confused
> > (Btw, the `scanJobsConcurrentLimit` doesn't really work, we have a limit of `1` but very often there are 3, 4 or even 5 jobs running concurrently)
> > > can you do a quick test deploy a simple replica-set with the naming as describe above and let me know if you see that a :
> > > 
> > > * `scan-job` is created
> > 
> > 
> > yes
> > > * if the `scan-job` get completed
> > 
> > 
> > yes, but one container got `OOMKilled`
> > > * if it get deleted after point 2
> > >   
> > >   * vulnerability report is produced ?
> > 
> > 
> > no confused
> > The second job, btw awesome that the hash of the job is always the same for the same resource +1, had the same result
> 
> I see , OOM issue require tuning the resources , have you tried it set it up , increase memory ?

Nice, now that we've done that it seems to work 👍️

Thanks for the support 🙏

It would be nice if problems with the scanning would be in the log tho
