### ISSUE TITLE
Option to only keep vulnerability reports/metrics for only the most recent replicaset

### ISSUE THREAD

**Issue by charris-ca** [aquasecurity/trivy-operator#694]
Is there an option to not preserve metrics/vulnerability reports past the most recent one?  Especially for the prometheus metrics, it makes it very difficult to graph when metrics contain many different replicasets for the same image/deployment.

**Comment by chen-keinan** [comment]
@charris-ca are you referring to historical scan on deployment ?

**Comment by charris-ca** [comment]
Yeah referring to the historical scans.

**Comment by chen-keinan** [comment]
which `trivy-operator` version are you using ?

**Comment by chen-keinan** [comment]
@charris-ca  Trivy-operator >= v0.5.0 already support historical reported and metrics cleanup

**Comment by charris-ca** [comment]
I am using version 0.5.0 already.  Which helm value indicates the historical reported number?

**Comment by chen-keinan** [comment]
> I am using version 0.5.0 already. Which helm value indicates the historical reported number?

The historical report cleanup mechanism is enable by default and should apply for every new replicaset update (rollout).
the metrics `trivy-operator` produce is based on existing reports (it do not keep history) , so if existing reports are already do not have historical reports , then you should get only one set of report for every replica set.
btw: you should have also TTL configure with default 24h , so no report should live longer than 24h

**Comment by chen-keinan** [comment]
@charris-ca let me know if still an issue  , I would like to review it with you.

**Comment by chen-keinan** [comment]
@charris-ca any update on this ?

**Comment by charris-ca** [comment]
I think my issue is if you have a situation where more than 1 replica set exists with the TTL limit.  Those metrics are hard to visualize on a per image basis as I don't want to have replicaset as a column.  I've figured out a way around it by looking for the CVE's directly associated with the image repo name.  So I think I'm good now!

**Comment by chen-keinan** [comment]
> I think my issue is if you have a situation where more than 1 replica set exists with the TTL limit. Those metrics are hard to visualize on a per image basis as I don't want to have replicaset as a column. I've figured out a way around it by looking for the CVE's directly associated with the image repo name. So I think I'm good now!

Thanks for the update , do you want to keep the issue open. ?
