### ISSUE TITLE
Unable to install trivy on kuberntes cluster(Rancher)

### ISSUE THREAD

**Issue by hamzanasir443** [aquasecurity/trivy-operator#696]
Dear Seniors

I am trying to install trivy on the Kubernetes cluster by following https://www.vultr.com/docs/how-to-secure-kubernetes-deployments-using-trivy-operator/ now the problem is after being installed successfully. I am unable to find trivy on my cluster and if run the command "kubectl get deployment -n trivy-system" I get the result but the pod is not running. Could you please help me to figure out.
Thanks

**Comment by chen-keinan** [comment]
@hamzanasir443 have you tried to use the [helm install](https://aquasecurity.github.io/trivy-operator/v0.6.0/operator/installation/helm/) ?

**Comment by hamzanasir443** [comment]
> @hamzanasir443 have you tried to use the [helm install](https://aquasecurity.github.io/trivy-operator/v0.6.0/operator/installation/helm/) ?

Yes, the problem remains the same on both.

**Comment by chen-keinan** [comment]
@hamzanasir443 can you share the command you used in helm and the output you got ?

**Comment by hamzanasir443** [comment]
1: helm repo add aqua https://aquasecurity.github.io/helm-charts/
2: helm repo update
3: helm install trivy-operator aqua/trivy-operator \
   --namespace trivy-system \
   --create-namespace \
   --set="trivy.ignoreUnfixed=true" \
   --version v0.0.3
4:kubectl get deployment -n trivy-system 

Output:

**NAME             READY   UP-TO-DATE   AVAILABLE   AGE
trivy-operator   0/1     0            0           42s**

And here you see the container is not running.

**Comment by chen-keinan** [comment]
@hamzanasir443 `v0.0.3` is an old version , latest is `v0.6.0`
didn't you got the these lines after helm install ? : 
```
EST SUITE: None
NOTES:
You have installed Trivy Operator in the trivy-system namespace.
It is configured to discover Kubernetes workloads and resources in
all namespace(s).

Inspect created VulnerabilityReports by:

    kubectl get vulnerabilityreports --all-namespaces -o wide

Inspect created ConfigAuditReports by:

    kubectl get configauditreports --all-namespaces -o wide

Inspect the work log of trivy-operator by:

    kubectl logs -n trivy-system deployment/trivy-operator
```

**Comment by jrhunger** [comment]
Describe the deployment to see if any errors.  If no errors there, query replicasets and describe the replicaset.  Most likely you have some restriction in this cluster that the trivy pods are not passing.  Could be node taints, could be pod security policies, etc. but the results of describing the deployment/replicaset should tell you.

**Comment by hamzanasir443** [comment]
Name: trivy-operator
Namespace:          trivy-system
CreationTimestamp:  Wed, 16 Nov 2022 14:23:47 +0000
Labels:             app.kubernetes.io/instance=trivy-operator
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=trivy-operator
                    app.kubernetes.io/version=0.0.3
                    helm.sh/chart=trivy-operator-0.0.3
Annotations:        deployment.kubernetes.io/revision: 1
                    meta.helm.sh/release-name: trivy-operator
                    meta.helm.sh/release-namespace: trivy-system
Selector:           app.kubernetes.io/instance=trivy-operator,app.kubernetes.io/name=trivy-operator
Replicas:           1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           app.kubernetes.io/instance=trivy-operator
                    app.kubernetes.io/name=trivy-operator
  Service Account:  trivy-operator
  Containers:
   trivy-operator:
    Image:       docker.io/aquasec/trivy-operator:0.0.3
    Ports:       8080/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:probes/healthz/ delay=5s timeout=1s period=10s #success=1 #failure=10
    Readiness:   http-get http://:probes/readyz/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      OPERATOR_NAMESPACE:                                          trivy-system
      OPERATOR_TARGET_NAMESPACES:                                  
      OPERATOR_EXCLUDE_NAMESPACES:                                 kube-system,trivy-system
      OPERATOR_SERVICE_ACCOUNT:                                    trivy-operator
      OPERATOR_LOG_DEV_MODE:                                       false
      OPERATOR_SCAN_JOB_TIMEOUT:                                   5m
      OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT:                         10
      OPERATOR_SCAN_JOB_RETRY_AFTER:                               30s
      OPERATOR_BATCH_DELETE_LIMIT:                                 10
      OPERATOR_BATCH_DELETE_DELAY:                                 10s
      OPERATOR_METRICS_BIND_ADDRESS:                               :8080
      OPERATOR_HEALTH_PROBE_BIND_ADDRESS:                          :9090
      OPERATOR_CIS_KUBERNETES_BENCHMARK_ENABLED:                   false
      OPERATOR_VULNERABILITY_SCANNER_ENABLED:                      true
      OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:  false
      OPERATOR_VULNERABILITY_SCANNER_REPORT_TTL:                   
      OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED:                       false
      OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:   false
      OPERATOR_CONFIG_AUDIT_SCANNER_BUILTIN:                       true
      OPERATOR_CLUSTER_COMPLIANCE_ENABLED:                         false
    Mounts:                                                        <none>
  Volumes:                                                         <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
  Progressing      False   ProgressDeadlineExceeded
OldReplicaSets:    <none>
NewReplicaSet:     trivy-operator-f9cbf94c8 (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  41m   deployment-controller  Scaled up replica set trivy-operator-f9cbf94c8 to 1

**Comment by hamzanasir443** [comment]
Yes this is something concerning pod security policy

**Comment by jrhunger** [comment]
We migrated away from PSP to prepare for 1.25, but previously our deploy first applied a custom PSP for the trivy-system namespace before doing the helm install. The main thing i remember was RunAsAny, but that should only affect the scanning jobs/pods, not the operator.
Honestly.. if you are running 0.0.3 you should try with 0.6.0.  There are so many fixes in the past few releases, and one of them (numeric docker user) may be relevant here.

**Comment by hamzanasir443** [comment]
> We migrated away from PSP to prepare for 1.25, but previously our deploy first applied a custom PSP for the trivy-system namespace before doing the helm install. The main thing i remember was RunAsAny, but that should only affect the scanning jobs/pods, not the operator. Honestly.. if you are running 0.0.3 you should try with 0.6.0. There are so many fixes in the past few releases, and one of them (numeric docker user) may be relevant here.

When I tried to install your mentioned release (0.6.0) I got error 

Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "aggregate-config-audit-reports-view" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "kubectl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "trivy-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "trivy-system"

**Comment by chen-keinan** [comment]
> > We migrated away from PSP to prepare for 1.25, but previously our deploy first applied a custom PSP for the trivy-system namespace before doing the helm install. The main thing i remember was RunAsAny, but that should only affect the scanning jobs/pods, not the operator. Honestly.. if you are running 0.0.3 you should try with 0.6.0. There are so many fixes in the past few releases, and one of them (numeric docker user) may be relevant here.
> 
> When I tried to install your mentioned release (0.6.0) I got error
> 
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "aggregate-config-audit-reports-view" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "kubectl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "trivy-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "trivy-system"

You'll need to uninstall prev. `trivy-operator` chart and install it again.

**Comment by hamzanasir443** [comment]
> 

> kubectl describe deployment -n trivy-system 
Name:               trivy-operator
Namespace:          trivy-system
CreationTimestamp:  Wed, 16 Nov 2022 16:56:48 +0000
Labels:             app.kubernetes.io/instance=trivy-operator
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=trivy-operator
                    app.kubernetes.io/version=0.6.0
                    helm.sh/chart=trivy-operator-0.6.0
Annotations:        deployment.kubernetes.io/revision: 1
                    meta.helm.sh/release-name: trivy-operator
                    meta.helm.sh/release-namespace: trivy-system
Selector:           app.kubernetes.io/instance=trivy-operator,app.kubernetes.io/name=trivy-operator
Replicas:           1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           app.kubernetes.io/instance=trivy-operator
                    app.kubernetes.io/name=trivy-operator
  Service Account:  trivy-operator
  Containers:
   trivy-operator:
    Image:       ghcr.io/aquasecurity/trivy-operator:0.6.0
    Ports:       8080/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:probes/healthz/ delay=5s timeout=1s period=10s #success=1 #failure=10
    Readiness:   http-get http://:probes/readyz/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      OPERATOR_NAMESPACE:                                          trivy-system
      OPERATOR_TARGET_NAMESPACES:                                  
      OPERATOR_EXCLUDE_NAMESPACES:                                 kube-system,trivy-system
      OPERATOR_TARGET_WORKLOADS:                                   pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
      OPERATOR_SERVICE_ACCOUNT:                                    trivy-operator
      OPERATOR_LOG_DEV_MODE:                                       false
      OPERATOR_SCAN_JOB_TIMEOUT:                                   5m
      OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT:                         10
      OPERATOR_SCAN_JOB_RETRY_AFTER:                               30s
      OPERATOR_BATCH_DELETE_LIMIT:                                 10
      OPERATOR_BATCH_DELETE_DELAY:                                 10s
      OPERATOR_METRICS_BIND_ADDRESS:                               :8080
      OPERATOR_METRICS_FINDINGS_ENABLED:                           true
      OPERATOR_METRICS_VULN_ID_ENABLED:                            false
      OPERATOR_HEALTH_PROBE_BIND_ADDRESS:                          :9090
      OPERATOR_VULNERABILITY_SCANNER_ENABLED:                      true
      OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:  true
      OPERATOR_SCANNER_REPORT_TTL:                                 24h
      OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED:                       true
      OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED:                    true
      OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:   true
      OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED:                     true
      OPERATOR_WEBHOOK_BROADCAST_URL:                              
      OPERATOR_WEBHOOK_BROADCAST_TIMEOUT:                          30s
      OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES:                {}
      OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS:             true
    Mounts:                                                        <none>
  Volumes:                                                         <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     trivy-operator-7958b75bb9 (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  76s   deployment-controller  Scaled up replica set trivy-operator-7958b75bb9 to 1
>

**Comment by hamzanasir443** [comment]
How do i scale up the trivy-operator  replicaset to 1 ?

**Comment by hamzanasir443** [comment]
> It is scaled to 1 but having an issue. Do this: kubectl describe replicaset trivy-operator-7958b75bb9

Now that is also the problem I am unable to see the replicaset(Trivy-operator) in my cluster 
> kubectl describe replicaset trivy-operator-7958b75bb9
Error from server (NotFound): replicasets.apps "trivy-operator-7958b75bb9" not found

**Comment by hamzanasir443** [comment]
> sorry, you also need to add -n trivy-system to that command since it's not running in the default namespace.

Name:           trivy-operator-7958b75bb9
Namespace:      trivy-system
Selector:       app.kubernetes.io/instance=trivy-operator,app.kubernetes.io/name=trivy-operator,pod-template-hash=7958b75bb9
Labels:         app.kubernetes.io/instance=trivy-operator
                app.kubernetes.io/name=trivy-operator
                pod-template-hash=7958b75bb9
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 1
                deployment.kubernetes.io/revision: 1
                meta.helm.sh/release-name: trivy-operator
                meta.helm.sh/release-namespace: trivy-system
Controlled By:  Deployment/trivy-operator
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/instance=trivy-operator
                    app.kubernetes.io/name=trivy-operator
                    pod-template-hash=7958b75bb9
  Service Account:  trivy-operator
  Containers:
   trivy-operator:
    Image:       ghcr.io/aquasecurity/trivy-operator:0.6.0
    Ports:       8080/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:probes/healthz/ delay=5s timeout=1s period=10s #success=1 #failure=10
    Readiness:   http-get http://:probes/readyz/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      OPERATOR_NAMESPACE:                                          trivy-system
      OPERATOR_TARGET_NAMESPACES:                                  
      OPERATOR_EXCLUDE_NAMESPACES:                                 kube-system,trivy-system
      OPERATOR_TARGET_WORKLOADS:                                   pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
      OPERATOR_SERVICE_ACCOUNT:                                    trivy-operator
      OPERATOR_LOG_DEV_MODE:                                       false
      OPERATOR_SCAN_JOB_TIMEOUT:                                   5m
      OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT:                         10
      OPERATOR_SCAN_JOB_RETRY_AFTER:                               30s
      OPERATOR_BATCH_DELETE_LIMIT:                                 10
      OPERATOR_BATCH_DELETE_DELAY:                                 10s
      OPERATOR_METRICS_BIND_ADDRESS:                               :8080
      OPERATOR_METRICS_FINDINGS_ENABLED:                           true
      OPERATOR_METRICS_VULN_ID_ENABLED:                            false
      OPERATOR_HEALTH_PROBE_BIND_ADDRESS:                          :9090
      OPERATOR_VULNERABILITY_SCANNER_ENABLED:                      true
      OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:  true
      OPERATOR_SCANNER_REPORT_TTL:                                 24h
      OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED:                       true
      OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED:                    true
      OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS:   true
      OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED:                     true
      OPERATOR_WEBHOOK_BROADCAST_URL:                              
      OPERATOR_WEBHOOK_BROADCAST_TIMEOUT:                          30s
      OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES:                {}
      OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS:             true
    Mounts:                                                        <none>
  Volumes:                                                         <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  5m10s (x18 over 16m)  replicaset-controller  Error creating: pods "trivy-operator-7958b75bb9-" is forbidden: PodSecurityPolicy: unable to admit pod: []
>

**Comment by jrhunger** [comment]
You will need to look into the PSP that is active for the trivy namespace (probably the default one for the cluster).  The trivy helm does not install a PSP to my knowledge, and PSPs have been deprecated for several versions and [removed as of k8s 1.25.](https://kubernetes.io/docs/concepts/security/pod-security-policy/)
It can be interesting to debug PSP issues, due to the way they apply, by whether or not the service account in question has access to read a given policy.  
Probably not a trivy issue, though.

**Comment by hamzanasir443** [comment]
> You will need to look into the PSP that is active for the trivy namespace (probably the default one for the cluster). The trivy helm does not install a PSP to my knowledge, and PSPs have been deprecated for several versions and [removed as of k8s 1.25.](https://kubernetes.io/docs/concepts/security/pod-security-policy/) It can be interesting to debug PSP issues, due to the way they apply, by whether or not the service account in question has access to read a given policy. Probably not a trivy-operator issue, though.

Is there any way to remove pod security policy specifically from trivy operator

**Comment by chen-keinan** [comment]
@hamzanasir443 you can overwrite it in helm chart

**Comment by hamzanasir443** [comment]
> @hamzanasir443 you can overwrite it in helm chart

Could you please assist me with how I will do that?

**Comment by chen-keinan** [comment]
> > @hamzanasir443 you can overwrite it in helm chart
> 
> Could you please assist me with how I will do that?

here is how you set [podSecurityContext](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L331) and [securityContext](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L334)

when you run helm example :
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="securityContext.privileged=true" \
  --version 0.6.0

```

**Comment by hamzanasir443** [comment]
> 

Now the error looks different 

Error: Deployment.apps "trivy-operator" is invalid: spec.template.spec.containers[0].securityContext: Invalid value: core.SecurityContext{Capabilities:(*core.Capabilities)(0xc02c372810), Privileged:(*bool)(0xc0295ab3aa), SELinuxOptions:(*core.SELinuxOptions)(nil), WindowsOptions:(*core.WindowsSecurityContextOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(0xc0295ab3ab), AllowPrivilegeEscalation:(*bool)(0xc0295ab37f), ProcMount:(*core.ProcMountType)(nil), SeccompProfile:(*core.SeccompProfile)(nil)}: cannot set `allowPrivilegeEscalation` to false and `privileged` to true

**Comment by chen-keinan** [comment]
@hamzanasir443 the above is just example you need to set the security context based on you cluster needs

**Comment by chen-keinan** [comment]
@hamzanasir443 have you succeeded to set it up ?

**Comment by hamzanasir443** [comment]
> @hamzanasir443 have you succeeded to set it up ?

No, I am not yet. I don't have expertise in Linux or so that is why I can't understand how to write a custom PSP.

**Comment by jrhunger** [comment]
Maybe worth joining the Rancher slack and asking there. Rancher may have an easy way to exempt namespaces from PSP, etc.
