### ISSUE TITLE
Add support for custom volumes and volume mounts for Helm

### ISSUE THREAD

**Issue by adrianmarcu18** [aquasecurity/trivy-operator#698]
Hello. Would be nice if we could add extra volumes/volumemounts via Values.yaml to the Helm Deployment of Trivy-Operator.
My particular use case is that I want to integrate it with Azure Key Vault so that I can generate k8s secrets for registry credentials.  This requires that the secretProviderClass to be mounted.

**Comment by jrhunger** [comment]
I *think* this would also (with proper mount) enable the trivy DB directory to be mounted from an RWX PVC and shared across scan instances, only being updated when it is sufficiently stale.
