### ISSUE TITLE
Split helm chart and application releases

### ISSUE THREAD

**Issue by cebidhem** [aquasecurity/trivy-operator#701]
Hey there,

Currently, both helm charts and application follow the same versionning, and the same release cycles. 

This prevents us from deploying new features / fixes present in the Helm charts when they are added, forcing the users to wait for next application release.
At the same time, Helm chart versions can be bumped even if there was no change in them, just because the application's features/bug fixes are released.

I think having a distinct release process for both elements can help the users to benefit from features and fixes quicker than what we have at the moment.

This would also clarify the versionning system.

**Comment by chen-keinan** [comment]
@cebidhem sound good , so to summarize :
- app changes force bumping chart and app versions.
- chart changes force bumping only chart version.

**Comment by cebidhem** [comment]
Yes exactly!

Also just thinking about that now, but since you're using git tags for releases, maybe have a new set of git tags prefixed by `helm-`. wdyt ?

**Comment by cebidhem** [comment]
`version` in chart would remain `0.8.0`, but the git tag itself would be `helm-v0.8.0`.

I'm pretty sure some users pull from GitHub, not only from the Helm repo.

**Comment by chen-keinan** [comment]
> `version` in chart would remain `0.8.0`, but the git tag itself would be `helm-v0.8.0`.
> 
> I'm pretty sure some users pull from GitHub, not only from the Helm repo.
OK then  , assuming:
- helm changes , example:
    - bumping helm version to  `0.8.0` and git tag for release is `helm-v0.8.0`
- app changes :
     - bumping helm version to `0.9.0` and app version to `0.8.0` and  git tag for release is `v0.8.0`

**Comment by cebidhem** [comment]
> app changes :
> 
>     * bumping helm version to `0.9.0` and app version to `0.8.0` and  git tag for release is `v0.8.0`

+ git tag for `helm-v0.9.0`. Just to keep consistency since a new version of the helm chart will be effectively released.

**Comment by chen-keinan** [comment]
isn't it confusing as we already creating a tag in[ helm repo](https://github.com/aquasecurity/helm-charts) ? 
the `helm-v0.9.0` in trivy operator repo will be just a marker (no release) ?
 
 Also our pipeline is built in a way that every time you create a tag a release process start , so we need to bypass it for `helm-v0.9.0` ?

**Comment by jrhunger** [comment]
I like having the helm minor version match the trivy minor version.  Perhaps you could use the patch version for helm-only changes?  e.g. helm version 0.8.0 -> 0.8.1 on trivy-operator v0.8.0 ?

**Comment by cebidhem** [comment]
> isn't it confusing as we already creating a tag in[ helm repo](https://github.com/aquasecurity/helm-charts) ? the `helm-v0.9.0` in trivy operator repo will be just a marker (no release) ?

Oh indeed, yes you're right @chen-keinan there's no need to do it in this repo then!

> I like having the helm minor version match the trivy minor version. Perhaps you could use the patch version for helm-only changes? e.g. helm version 0.8.0 -> 0.8.1 on trivy-operator v0.8.0 ?

Yes I understand, and frankly there is no ideal solution. As in you want to be able to know from the version if the chart x.y.z is compatible with the app version y.x.z. 
I would be fine have the fix version of the chart incremented for chart changes only, leaving major.minor of the chart == major.minor of the app.

It would not be semver per se, but it would prevent the versionning to be confusing, and avoid issues like "what version of the chart should I use for this version of the app".

**Comment by chen-keinan** [comment]
@cebidhem @jrhunger I'll try to summarised  the thread , let me know if I missed / misinterpreted  anything:
- helm changes only  bumping fix version in helm repo only 
  - for example: if helm version is `v0.7.0` after `helm` changes it become `v0.7.1`
- app changes
   - fix only 
      - helm is increment fix version only for example:
         - helm version is `v0.7.1` after fix it become `v0.7.2`
      - app increment fix version only for example:
         - app version is `v0.7.0` after fix it become `v0.7.1`
   - features: both helm and app are changed to same minor version
      - for example helm is version `v0.7.2` and app version is `v0.7.1` after minor helm become `v0.8.0` and app become `v0.8.0`

wdyt?

**Comment by chen-keinan** [comment]
Great so I think we are all aligned , I assume if app go minor version then helm also go minor version.
it help helm users to understand that this version include changes (not just hot fix), wdyt ?

**Comment by cebidhem** [comment]
Yes I think we're all aligned with the versionning system!

**Comment by chen-keinan** [comment]
@cebidhem can we close this issue ? I think we are all in agreement :)

**Comment by cebidhem** [comment]
Hey @chen-keinan , I haven't followed but has it been done ? If it's done then yes!

If not, maybe I can have a look in the coming days if you can't.

**Comment by jemag** [comment]
I would actually discourage against trying to have similar versions for both the application and the helm chart, if anything, it just leads to more confusion.

The vast majority of helm charts out there have a separate semver for the application and the helm chart (you can see so with the Bitnami charts, Prometheus, grafana, ingress-nginx, traefik, etc.)

For example, what happens if you want to do a breaking change that targets the Helm chart only? It would not make sense to only bump the PATCH version in that case. While you could technically bump the application version at the same time, it then just adds confusion because the application itself did not go through a breaking change, just the helm chart.

**Comment by jrhunger** [comment]
@jemag this discussion is about changes to the Helm chart that is included in this repo.  So the releases in question are releases for trivy-operator that affect the deploy/helm only.

**Comment by jemag** [comment]
I am aware. Perhaps I am misinterpreting but is seems like you want to keep some relation between the application version and the helm chart version by bumping only the patch version on helm chart changes:

> So if trivy-operator is on v0.7.0 and a helm-only change is made, trivy-operator could increment to 0.7.1

What I am saying is that it would  be less confusing and more in-line with the rest of the community to have fully separate semver versions for the application code and the helm chart. I named some examples in my previous comment, a concrete one similar to the situation here is ingress-nginx which also has its charts in its repo (https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) and also maintains different semver for application and chart.

**Comment by adberger** [comment]
Why do helm releases need a GitHub Tag?

As far as i see, the Helm Chart publishing process is triggered manually: https://github.com/aquasecurity/trivy-operator/blob/main/.github/workflows/publish-helm-chart.yaml#L2-L3

This could be changed to trigger on merge to `main` with a check if the helm chart has changed.

And for the versioning just use version for helm chart version and appVersion for application version (https://helm.sh/docs/topics/charts/#the-chartyaml-file), so both can be according to semVer 2.
A new application release always needs a bump of the helm chart version.
A new helm chart release doesn't need a bump of the application version.

Am I missing something?

**Comment by chen-keinan** [comment]
> Why do helm releases need a GitHub Tag?
> 
> As far as i see, the Helm Chart publishing process is triggered manually: https://github.com/aquasecurity/trivy-operator/blob/main/.github/workflows/publish-helm-chart.yaml#L2-L3
> 
> This could be changed to trigger on merge to `main` with a check if the helm chart has changed.
> 
> And for the versioning just use version for helm chart version and appVersion for application version (https://helm.sh/docs/topics/charts/#the-chartyaml-file), so both can be according to semVer 2. A new application release always needs a bump of the helm chart version. A new helm chart release doesn't need a bump of the application version.
> 
> Am I missing something?

@adberger what you are suggeting ?

**Comment by adberger** [comment]
@chen-keinan Exactly what I've wrote.

I'm not familiar with GitHub workflows but maybe something along the lines:
```
on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'deploy/helm/Chart.yaml'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
...
```

ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges

**Comment by chen-keinan** [comment]
> @chen-keinan Exactly what I've wrote.
> 
> I'm not familiar with GitHub workflows but maybe something along the lines:
> 
> ```
> on:
>   pull_request_target:
>     types:
>       - closed
>     paths:
>       - 'deploy/helm/Chart.yaml'
> 
> jobs:
>   if_merged:
>     if: github.event.pull_request.merged == true
>     runs-on: ubuntu-latest
> ...
> ```
> 
> ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges

it is required to validate that chart version has been bump otherwise very change to chart will publish a new chart release
and also chart changes which depend on app changes should not published new chart without the updated app image

**Comment by adberger** [comment]
> > @chen-keinan Exactly what I've wrote.
> > I'm not familiar with GitHub workflows but maybe something along the lines:
> > ```
> > on:
> >   pull_request_target:
> >     types:
> >       - closed
> >     paths:
> >       - 'deploy/helm/Chart.yaml'
> > 
> > jobs:
> >   if_merged:
> >     if: github.event.pull_request.merged == true
> >     runs-on: ubuntu-latest
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges
> 
> it is required to validate that chart version has been bump otherwise very change to chart will publish a new chart release and also chart changes which depend on app changes should not published new chart without the updated app image

Aren't both of those requirements subject to the PR itself?

If somebody changes helm templates, values etc. without bumping the version in the Chart.yaml, the reviewer(s) should comment on this. Of course you can also catch this use case in the workflow (probably).

**Comment by chen-keinan** [comment]
> > > @chen-keinan Exactly what I've wrote.
> > > I'm not familiar with GitHub workflows but maybe something along the lines:
> > > ```
> > > on:
> > >   pull_request_target:
> > >     types:
> > >       - closed
> > >     paths:
> > >       - 'deploy/helm/Chart.yaml'
> > > 
> > > jobs:
> > >   if_merged:
> > >     if: github.event.pull_request.merged == true
> > >     runs-on: ubuntu-latest
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges
> > 
> > 
> > it is required to validate that chart version has been bump otherwise very change to chart will publish a new chart release and also chart changes which depend on app changes should not published new chart without the updated app image
> 
> Aren't both of those requirements subject to the PR itself?
> 
> If somebody changes helm templates, values etc. without bumping the version in the Chart.yaml, the reviewer(s) should comment on this. Of course you can also catch this use case in the workflow (probably).

do you want to raise a PR ?

**Comment by adberger** [comment]
@chen-keinan Let me know what you think: https://github.com/aquasecurity/trivy-operator/pull/1460
