### ISSUE TITLE
GUI for trivy-operator

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy-operator#72]
Add a Web UI that makes it easy to consume the CRD that the operator generates

**Comment by chen-keinan** [comment]
@nublarsec [trivy-operator-lens-extension](https://github.com/aquasecurity/trivy-operator-lens-extension) available

**Comment by sherifkayad** [comment]
@itaysk @chen-keinan that's really amazing to know that a native GUI is prioritized by you ;) .. just wanted to ask is there a known target release date for that GUI already? .. We are in desperate need for it at the moment.

**Comment by itaysk** [comment]
Hello, after some further consideration we have decided de-prioritize investing in a full fledged web UI for Trivy. We prefer to focus on delivering more value and features to the scanning.

- It's possible to build a UI on top of Trivy Operator in a different repository, so anyone is welcome to work on that. 
- For a quick and easy solution, we've seen some nice Grafana dashboards for Trivy Operator out there. We will likely highlight these in the docs at some point.
- And finally there's the paid Aqua platform that's built on top of Trivy Operator and provides additional functionality including a management console.

**Comment by sameeraksc** [comment]
kubeclarity has a cool UI. wondering why trivy doesn't have a one

**Comment by itaysk** [comment]
another good option by @fjogeleit : https://github.com/fjogeleit/trivy-operator-polr-adapter

**Comment by raoulx24** [comment]
Hi there,

I know that this is an old post, but I think it is ok to post here.

We are a small team of enthusiasts that created a dashboard application for Trivy Operator. Link on [github](https://github.com/raoulx24/trivy-operator-dashboard).

For now, the app has support for
- Vulnerability Reports
- Config Audit Reports
- Cluster RBAC Assessment Reports
- Exposed Secret Reports

In the near future, we plan to implement also the others.

We are glad to share it with the community. And we hope it will be useful, as it is for us. :-)

Cheers

**Comment by aarlint** [comment]
Also a late entry, helm installable dashboard Trivy Glass - https://github.com/arlintdev/trivyglass
