### ISSUE TITLE
Missing vulnerability reports

### ISSUE THREAD

**Issue by adrianmarcu18** [aquasecurity/trivy-operator#731]
**What steps did you take and what happened:**

Since I installed version 0.4.0 of Trivy-Operator I kept bumping into situations where vulnerability reports are not created for some resources. After some time, they started to get created again.
Now, that I upgraded to latest version, 0.7.1, I still have this problem, but it is occurring for even more resources. I can't really trust Trivy anymore at this point that it can scan everything in my cluster and I am just relying on luck, if a resource is scanned or not.

Previously, o version 0.6.0, when I finally saw most of the reports generated I got happy and then, over the weekend, more than 60% of reports were gone, and none got recreated. And no restart fixed it.

Today I upgraded to 0.7.1 and using the trivy-server approach. It is better, but still missing more than 30% of the reports. 

I do see this error, though in the operator logs (since upgrading to 0.6.0):

`{"level":"error","ts":1669370944.5371487,"msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-7cc6d7794b","namespace":"trivy"},"namespace":"trivy","name":"scan-vulnerabilityreport-7cc6d7794b","reconcileID":"0976a9b3-47b9-4e98-9347-5ecbae54e1e5","error":"illegal base64 data at input byte 0; unexpected EOF","errorCauses":[{"error":"illegal base64 data at input byte 0"},{"error":"unexpected EOF"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
`

I mention that I already disabled the scanJobCompressLogs (by setting the value to false)

**What did you expect to happen:**

All resources to be correctly identified, scanned and vulnerability reports generated. I am also expecting that the operator will log a warning or error if it cannot start a scan for a particular resource.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version: 0.7.1

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"83d00b7cbf10e530d1d4b2403f22413220c37621", GitTreeState:"clean", BuildDate:"2022-11-09T19:50:11Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):  Ubuntu 18.04

**Comment by chen-keinan** [comment]
@adrianmarcu18 could you please install the operator with this flag :
`--set="trivyOperator.scanJobCompressLogs=false"`

example : 
`
 helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="trivyOperator.scanJobCompressLogs=false"
  --version 0.7.1 
`

**Comment by adrianmarcu18** [comment]
Mentioned that I did that already.

**Comment by chen-keinan** [comment]
> @adrianmarcu18 could you please install the operator with this flag : `--set="trivyOperator.scanJobCompressLogs=false"`
> 
> example : `helm install trivy-operator ./deploy/helm \ --namespace trivy-system \ --create-namespace \ --set="trivy.ignoreUnfixed=true" \ --set="trivyOperator.scanJobCompressLogs=false" \ --version 0.7.1 `

sorry missed that , are the the scan-jobs stuck in `completed` status  ?

**Comment by chen-keinan** [comment]
> Mentioned that I did that already.

sorry missed that , are the the scan-jobs stuck in `completed` status  when the above error appear? 
if so , could you run:  `kubectl logs <scan-job name> -n trivy-system` and confirm the pod has json report output.

**Comment by adrianmarcu18** [comment]
I will install the new version and let you know how it goes. 

And to give more details, which I seem to understand better after some troubleshooting:
Yes, the scan job gets stuck into completed state. Reason for it is that at least one container of the scan pod doesn't get to write the whole json output to log before it gets to completed.

But this only happens for like 5 scan jobs, which is also the concurrency limit set . So I think it doesn't move onto the next ones until it clears the completed ones.

Also, this sounds specific for later versions. What I mentioned in the start of the issue report, with missing reports while using version 0.4.0 it wasn't related and did not have the same symptoms. Back then I did not have any error shown in the operator. After reading more closed issues from trivy-operator, I suspect it has something to do with the long names for resources, which I noticed are now replaced by a hash number in the vulnerability report.

**Comment by chen-keinan** [comment]
> Also, this sounds specific for later versions. What I mentioned in the start of the issue report, with missing reports while using version 0.4.0 it wasn't related and did not have the same symptoms. Back then I did not have any error shown in the operator. After reading more closed issues from trivy-operator, I suspect it has something to do with the long names for resources, which I noticed are now replaced by a hash number in the vulnerability report.

thanks for the feedback , also note that since version v0.5.0 `trivy-operator` do not keep historical reports by default , so every new deployment update , only latest report will be kept

**Comment by adrianmarcu18** [comment]
Ok, so I installed v0.8.0-rc with compressed logs enabled

- No more stuck completed jobs
- No more errors in operator, except for a container, which is normal to have errors on
- About 50% of the vulnerability reports generated
- No more scan jobs being triggered

Final result: missing vulnerability reports 
So looks like it can't find some of the workloads to scan them. I suspect if I deploy a new version for any of the missing workloads, they will be processed.

**Comment by chen-keinan** [comment]
@adrianmarcu18 could you please elaborate on missing reports as once the operator restarted it should reconcile all [resources](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L20) which it listen , could you please elaborate on resources which are missing

**Comment by adrianmarcu18** [comment]
> @adrianmarcu18 could you please elaborate on missing reports as once the operator restarted it should reconcile all [resources](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L20) which it listen, it will skip scanning if report exist for it already already , could you please elaborate on resources which are missing ?

I will give an example of two namespaces where I have missing reports.

I have one namespace where I deploy two statefulsets (via mongodb operator), and they are both scheduled on the same node.
- sts1-mongodb: I see vulnerability reports created for all containers
- sts2-mongodb: there is not a single vulnerability report created; not a single scan job created

Another example:
A namespace where I have deployed elastic-agent and heartbeat. Same as above, elastic-agent missing the reports, but they are available for heartbeat

I also have a kured namespace where I deployed kured daemonset. In this namespace there is not a single vulnerability report. As well as above, there is no scan job created. the same is applicable for falco daemonset, no reports available.

So there are multiple workload reports missing, some in the same namespace with other resources that do have a vulnerability report.

When I restart operator so it can reconcile, its starting to generate a lot of job scans, which in turn will scan the same workloads that already have a report.

I have also tried to exclude calico-system namespace where I do have a failing job scan. I thought that maybe because a single job fails for a calico pod, maybe it doesn't go through to scan the others. But it seems that excluding that namespace via exclude namespaces doesn't work. It still recreating reports for it.

**Comment by chen-keinan** [comment]
Thanks for the update ,I'll check the exclude namespace issue, could you please share you `cm` settings ? 
you also mention `I suspect if I deploy a new version for any of the missing workloads, they will be processed.` how you confirm it ?

**Comment by adrianmarcu18** [comment]
> Thanks for the update ,I'll check the `exclude namespace` issue #738 , could you please share you `trivy-operator config maps` settings ? you also mention `I suspect if I deploy a new version for any of the missing workloads, they will be processed.` how you confirm it ?

I tried to deploy a new version of elastic-agent and heartbeat. It did try to recreate the report for heartbeat (as it was already there). Luckily enough, it got an OOM trying to scan for heartbeat, moment in which no further jobs have been scheduled. Thus, elastic-agent report still not there. Important here to note is that I did not see anymore the error about the calico pod, which leads me to think the operator stopped the reconciler at first error encounter.

If I would do a wild guess, is that the operator takes each workload one by one, and when it encounters an error, it doesn't schedule new jobs. And each time the operator is restarted, starts from scratch if it doesn't finish a full round.

But I might not be right.

**Comment by chen-keinan** [comment]
> If I would do a wild guess, is that the operator takes each workload one by one, and when it encounters an error, it doesn't schedule new jobs. And each time the operator is restarted, starts from scratch if it doesn't finish a full round.
> 
> But I might not be right.

Yes you are right, the OOM issue / or other errors will not schedule another scanning job. 
This could be the root cause for the missing reports

I suggest to do one of tow in order to progress :
 -  tweak scan job resources (temp solution)
 - with `trivy v0.35.0` we have introduced lower memory footprint consumption you can update the [helm value](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L194) with version 0.35.0

**Comment by chen-keinan** [comment]
@adrianmarcu18 you can try the new `trivy-operator v0.8.0-rc` which include memory and cpu consumption improvements and lower footprint that might help to fix the OOM issue on you env.

**Comment by chen-keinan** [comment]
> @chen-keinan 
> 
> Sorry, did not had a chance to look into this for the past week. But here it is my config.
> 
> `  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
>   TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db
>   TRIVY_DEBUG: "false"
>   TRIVY_LISTEN: 0.0.0.0:4954
>   TRIVY_SKIP_UPDATE: "false"
>   trivy.additionalVulnerabilityReportFields: Target,Class
>   trivy.command: image
>   trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
>   trivy.dbRepositoryInsecure: "false"
>   trivy.mode: ClientServer
>   trivy.resources.limits.cpu: 500m
>   trivy.resources.limits.memory: 500M
>   trivy.resources.requests.cpu: 100m
>   trivy.resources.requests.memory: 100M
>   trivy.serverURL: http://trivy-service.trivy:4954
>   trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
>   trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
>   trivy.tag: 0.35.0
>   trivy.timeout: 40m0s
>   trivy.useBuiltinRegoPolicies: "true"
> `
> BTW, still getting OOMs with 0.35.0. That would not necessarily be an issue as I can increase resources. But what would help would be to not skip the rest of the resources if it encounters an error on one resource. It should mark it as failed and be retried later, but continue on the others. 

Please test with `trivy-operator v0.8.0` I have added a change(in addition to trivy v0.35.0) which suppose to fix the OOM issue

**Comment by adrianmarcu18** [comment]
@chen-keinan 

Using now v0.8.0 and 0.35.0 versions. What I have noticed:

- the namespace that I wanted to exclude is now excluded (so maybe in this version this is also fixed?)
- a note here: looks like trivy namespace is also excluded even if I do not specify that I want it to be excluded (as I want trivy scanned as well)
- being able to exclude that namespace I do not get into the situation that the reports fails for that particular container
- this in turn makes the operator to finish all other reports; so now I can see the missing reports again, which looks pretty good
- an occasional EOF error still occurs though in the operator logs; I do not see though a pod stuck in completed state, so maybe there is some kind of retry implemented?

`{"level":"error","ts":1670575595.0704632,"msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-76764ffc69","namespace":"trivy"},"namespace":"trivy","name":"scan-vulnerabilityreport-76764ffc69","reconcileID":"8fd980da-be92-46c0-9200-dbaa64d67750","error":"unexpected EOF","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
`

**Comment by chen-keinan** [comment]
@adrianmarcu18 thanks for the update ,true,  trivy-operator namspace is included for scanning by default follwing to  v0.8.0.
Please keep monitor your env. And let me know if there are any outstanding issues

**Comment by chen-keinan** [comment]
@adrianmarcu18 is this still an issue ? do you want to keep it open ?

**Comment by adrianmarcu18** [comment]
@chen-keinan Unfortunately, still have missing reports after running it for some time now. The error in the operator logs:
"error":"illegal base64 data at input byte 32765"
So I would say it is not yet a stable deployment, for our use case at least.

**Comment by chen-keinan** [comment]
> @chen-keinan Unfortunately, still have missing reports after running it for some time now. The error in the operator logs: "error":"illegal base64 data at input byte 32765" So I would say it is not yet a stable deployment, for our use case at least.

@adrianmarcu18 thank you for the update , this error is related to `compressLogs` I would give it another try with  flag 
`--set="trivyOperator.scanJobCompressLogs=false"`

**Comment by adrianmarcu18** [comment]
@chen-keinan unfortunately, when disabling compression , the reports might be too big and other errors occurs. 
I think that is best to close this issue as most of the reports are now in, and only occasional occurrences of missing reports. Also, I know now better how the operator works and how to workaround different issues.

Will look forward for more improvements in the future and will closely be following new features/fixes added.

Also, thank you for your patience and the work you do for this project.

**Comment by pschulten** [comment]
@chen-keinan sorry if I'm hijacking this issue, but maybe it's related...

I have the problem, that after a while trivy-operator no longer scans anything anymore (.e.g. new image versions; re-scan by manually deleting a vuln CRD)

The operator is error logging with:
```
"error":"getting logs for pod xyz: container xyz is not valid for pod scan-vulnerabilityreport-xyz
```

This only happens once several orphaned scan-vulnerabilityreport pods are in the cluster. example:
```
NAMESPACE        NAME                                        READY   STATUS      RESTARTS   AGE   LABELS
aaaa-prod        scan-vulnerabilityreport-694588d869-2786t   0/1     Completed   0          14h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=cd63dd68-fe8e-4896-a7cd-e751054feacf,job-name=scan-vulnerabilityreport-694588d869,resource-spec-hash=6dd9685cdb,topic=aaaa,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=aaaa-prod,vulnerabilityReport.scanner=Trivy
aaaa-prod        scan-vulnerabilityreport-8fd55b879-sz8kz    0/1     Completed   0          15h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=2cb8d510-5064-4b2b-8856-0904131e45ed,job-name=scan-vulnerabilityreport-8fd55b879,resource-spec-hash=6dd9685cdb,topic=aaaa,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=aaaa-prod,vulnerabilityReport.scanner=Trivy
aaaa-prod        scan-vulnerabilityreport-9586db848-6l9mf    0/1     Completed   0          12h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=2754254c-48da-46e7-9055-86f7e8a44c2d,job-name=scan-vulnerabilityreport-9586db848,resource-spec-hash=86d6ff7b86,topic=aaaa,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=aaaa-prod,vulnerabilityReport.scanner=Trivy
bbb-prod         scan-vulnerabilityreport-599f67c97-kj6bt    0/2     Completed   0          13h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=8a30e42c-0cb0-4b84-83dc-dd9f0fc8b50e,job-name=scan-vulnerabilityreport-599f67c97,resource-spec-hash=86d6ff7b86,topic=bbb,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=bbb-prod,vulnerabilityReport.scanner=Trivy
bbb-prod         scan-vulnerabilityreport-6975587746-mcqml   0/2     Completed   0          16h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=875fe0bf-99d0-46af-a824-b8906c66f833,job-name=scan-vulnerabilityreport-6975587746,resource-spec-hash=6dd9685cdb,topic=bbb,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=bbb-prod,vulnerabilityReport.scanner=Trivy
ccccccc-prod     scan-vulnerabilityreport-6bcbc4f884-kgqwx   0/2     Completed   0          16h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=1db7901e-8c90-4b09-b41e-0dd1bd22adc9,job-name=scan-vulnerabilityreport-6bcbc4f884,resource-spec-hash=558684f6cf,topic=ccccccc,trivy-operator.resource.kind=ReplicaSet,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=ccccccc-prod,vulnerabilityReport.scanner=Trivy
ccccccc-prod     scan-vulnerabilityreport-bdd68cf-6kqvx      0/2     Completed   0          16h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=66a5b80f-83fa-485c-aaa7-b0e224e9f0d6,job-name=scan-vulnerabilityreport-bdd68cf,resource-spec-hash=c5855f46c,topic=ccccccc,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=ccccccc-prod,vulnerabilityReport.scanner=Trivy
ddd-prod         scan-vulnerabilityreport-5f5587b8b8-8d55n   0/2     Completed   0          14h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=de131d2b-6382-4ca9-b809-ba8a68b62795,job-name=scan-vulnerabilityreport-5f5587b8b8,resource-spec-hash=86d6ff7b86,topic=ddd,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=ddd-prod,vulnerabilityReport.scanner=Trivy
eeeeeeeee-prod   scan-vulnerabilityreport-79bb6ccd47-xcvdq   0/1     Completed   0          16h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=d6e3eb68-1ded-4fac-bc47-66f674820f7c,job-name=scan-vulnerabilityreport-79bb6ccd47,resource-spec-hash=578446748d,topic=eeeeeeeee,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=eeeeeeeee-prod,vulnerabilityReport.scanner=Trivy
eeeeeeeee-prod   scan-vulnerabilityreport-9b45498d7-2w9dq    0/1     Completed   0          15h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=8b7fb976-d22c-4d83-88dd-4cc7edf481a6,job-name=scan-vulnerabilityreport-9b45498d7,resource-spec-hash=6dd9685cdb,topic=eeeeeeeee,trivy-operator.resource.kind=CronJob,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=eeeeeeeee-prod,vulnerabilityReport.scanner=Trivy

```

When I remove the pods with:
```
kubectl get po -A -l trivy-operator.resource.namespace  --field-selector status.phase!=Running,status.phase!=Pending 
```
and restart the trivy-operator everythings works again as expect until enough (don't really know how much of them are needed) new orphaned pods pile up.

**Comment by pschulten** [comment]
you mean trivy-operator releases?
It's happening with different releases. I tried 0.7.0 and 0.9.1

**Comment by chen-keinan** [comment]
> you mean trivy-operator releases? It's happening with different releases. I tried 0.7.0 and 0.9.1

I see ,thanks , I assume that scan is halted when num of scan job reach the [maxConcurent](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L45).

I will check this error `"error":"getting logs for pod xyz: container xyz is not valid for pod scan-vulnerabilityreport-xyz" `
if we could workaround it and avoid deletion and restart

**Comment by jrhunger** [comment]
@pschulten have a look at #509 and see if your completed undeleted jobs have the mismatched labels/annotations described there. Also, which version of k8s are you on? There is a bug in certain versions of kubernetes 1.24 (and maybe 1.23 but fixed in I think 1.24.4 or .5) related to cleanup of errored jobs. Combined those seem to cause trivy-operator to reach its concurrent scan job limit and stop processing new workloads.

**Comment by chen-keinan** [comment]
its looking for container in pod by `MatchLabels["controller-uid"]` and [can't find it](https://github.com/kubernetes/kubernetes/blob/edac6fce2ad4a1366a73afc8ac9ca50b2fbf7fc7/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go#L104) probably be related to #509

**Comment by chen-keinan** [comment]
could be it is happening for `CronJob` resources type only ? 🤔

**Comment by pschulten** [comment]
It's mostly cronjobs but one (from the above example) is a deployment:
```
ccccccc-prod     scan-vulnerabilityreport-6bcbc4f884-kgqwx   0/2     Completed   0          16h   app.kubernetes.io/managed-by=trivy-operator,controller-uid=1db7901e-8c90-4b09-b41e-0dd1bd22adc9,job-name=scan-vulnerabilityreport-6bcbc4f884,resource-spec-hash=558684f6cf,topic=ccccccc,trivy-operator.resource.kind=ReplicaSet,trivy-operator.resource.name=redacted,trivy-operator.resource.namespace=ccccccc-prod,vulnerabilityReport.scanner=Trivy
```
(`trivy-operator.resource.kind=ReplicaSet`)

**Comment by pschulten** [comment]
I think my issue is only caused by https://github.com/aquasecurity/trivy-operator/issues/509, thanks for your infos

**Comment by chen-keinan** [comment]
> I think my issue is only caused by #509, thanks for your infos

@pschulten issue #509 has been fixed with `trivy-operator v0.10.0-rc2` I suggest to upgrade to it when you have time

**Comment by pschulten** [comment]
Thanks. I will. But I'm not working for some days. Merry 🎄

**Comment by chen-keinan** [comment]
> Thanks. I will. But I'm not working for some days. Merry 🎄

sure,  of course Merry Xmas 😄
