### ISSUE TITLE
exclude namespace param doesn't work

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#738]
when setting up the in helm values[ exclude namespace ](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L15) it has been reported by users that it doesn't work. 
the operator do not exclude these namespace from scanning

Related #731

**Comment by simonst** [comment]
same issu here, the ENV Variable `OPERATOR_EXCLUDE_NAMESPACES` is set correctly but namespaces are not getting ignored as expected.

**Comment by chen-keinan** [comment]
@simonst I have make a quick test for `excludeNamespaces` param and find it working , example below
Please do confirm it as well and let me know if you have a different use case
`
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="excludeNamespaces=test_namespace" \
  --version 0.10.1
`
***Note:*** 
excludeNamespaces is a comma separated list of namespaces (or glob patterns)
to be excluded from scanning. Only applicable in the all namespaces install
mode, i.e. when the ***targetNamespaces values is a blank string***

**Comment by simonst** [comment]
Hi @chen-keinan 

thanks for your quick response!
I tried it again as well with the same chart version as you were using. But unfortunately it stills scans all namespaces.


```
helm install trivy-operator aqua/trivy-operator \
   --namespace trivy-system \
   --create-namespace \
   --set trivy.ignoreUnfixed=true \
   --set "excludeNamespaces=syn\,syn-system-upgrade-controller\,syn-synsights\,syn-resource-locker\,syn-prometheus-pushgateway\,syn-nfs-subdir-external-provisioner\,syn-metallb\,syn-ingress-nginx\,syn-fluentbit\,syn-cluster-backup\,syn-cert-manager\,syn-backup\,syn-backup-k8up\,kube-system\,cattle-system\,cattle-prometheus\,cattle-fleet-system" \
   --version 0.10.1
```

The `trivy-operator` has the following ENV variable set:
```
OPERATOR_EXCLUDE_NAMESPACES=syn,syn-system-upgrade-controller,syn-synsights,syn-resource-locker,syn-prometheus-pushgateway,syn-nfs-subdir-external-provisioner,syn-metallb,syn-ingress-nginx,syn-fluentbit,syn-cluster-backup,syn-cert-manager,syn-backup,syn-backup-k8up,kube-system,cattle-system,cattle-prometheus,cattle-fleet-system
```

But I am getting vulnerability reports for all the namespaces.
Do I need to set the comma separated list somehow differently?
Thanks!

**Comment by chen-keinan** [comment]
>
> But I am getting vulnerability reports for all the namespaces. Do I need to set the comma separated list somehow differently? Thanks!

@simonst I tested it with excluding only one namespace (I will try again with  excluding many namespaces) by looking at the [code](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/operator/predicate/predicate.go#L46) , its look ok what you did.

Also wanted to double check that `targetNamespaces` param is not set (empty) in your env, please confirm.

**Comment by simonst** [comment]
The `targetNamespaces (OPERATOR_TARGET_NAMESPACES` is not set, just double checked.

full list of the ENV Variables of the operator:
```
OPERATOR_EXCLUDE_NAMESPACES=syn,syn-system-upgrade-controller,syn-synsights,syn-resource-locker,syn-prometheus-pushgateway,syn-nfs-subdir-external-provisioner,syn-metallb,syn-ingress-nginx,syn-fluentbit,syn-cluster-backup,syn-cert-manager,syn-backup,syn-backup-k8up,kube-system,cattle-system,cattle-prometheus,cattle-fleet-system
OPERATOR_HEALTH_PROBE_BIND_ADDRESS=:9090
OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS=true
OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED=true
OPERATOR_TARGET_WORKLOADS=pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED=true
OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS=true
OPERATOR_NAMESPACE=trivy-system
OPERATOR_SERVICE_ACCOUNT=trivy-operator
OPERATOR_LOG_DEV_MODE=false
OPERATOR_WEBHOOK_BROADCAST_TIMEOUT=30s
OPERATOR_BUILT_IN_TRIVY_SERVER=false
OPERATOR_TARGET_NAMESPACES=
OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT=10
OPERATOR_VULNERABILITY_SCANNER_ENABLED=true
OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED=true
OPERATOR_SCAN_JOB_RETRY_AFTER=30s
OPERATOR_BATCH_DELETE_LIMIT=10
OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED=true
OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS=true
OPERATOR_BATCH_DELETE_DELAY=10s
OPERATOR_METRICS_FINDINGS_ENABLED=true
OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES={}
OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT=false
OPERATOR_SCAN_JOB_TIMEOUT=5m
OPERATOR_METRICS_BIND_ADDRESS=:8080
OPERATOR_METRICS_VULN_ID_ENABLED=false
OPERATOR_WEBHOOK_BROADCAST_URL=
```

**Comment by chen-keinan** [comment]
@simonst I tried to reproduce the issue with excluding multi namespace , still with no success .
once I run :
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="excludeNamespaces=test_namespace" \
  --version 0.10.1
```
the namespaces define in `excludeNamespaces`  get excluded from scanning .

I'll be happy to jump into a session to review your issue if you wish.

**Comment by dkulchinsky** [comment]
Can confirm that setting `excludeNamespaces: "kube-system,my-app,cd-demo,ccs-demo"` in Helm values works just fine for us and the above namespaces are excluded.

the `targetNamespaces` attribute is empty in our case.

**Comment by hilkinr** [comment]
https://thomasroot.com/2023/01/16/trivy-operator-improve-container-runtime-security/

**Comment by IamThomasB** [comment]
I have the same issue.  Version 0.10.1. and helm3

setting the excludeNamespaces parameter has no effect.

No matter whether I name one or more namespaces.
I even explicitly set "targetNamespaces" to an empty string.

my values-file is:
------------------
trivy:
  ignoreUnfixed: true
excludeNamespaces: "kube-system"
targetNamespaces: ""
--------------------

helm upgrade trivy-operator aqua/trivy-operator  --namespace trivy-system  --create-namespace  --version 0.10.1  --values trivy-values.yaml -i

The effective deployment YAML looks like this:

--------------------
...
containers:
  - name: "trivy-operator"
    image: "ghcr.io/aquasecurity/trivy-operator:0.10.1"
    env:
      - name: OPERATOR_NAMESPACE
        value: trivy-system
      - name: OPERATOR_TARGET_NAMESPACES
        value: ""
      - name: OPERATOR_EXCLUDE_NAMESPACES
        value: "kube-system"
...
--------------------


the environment in the pod is:
--------------------
/ $ env | grep NAMESPACE
OPERATOR_EXCLUDE_NAMESPACES=kube-system
OPERATOR_NAMESPACE=trivy-system
OPERATOR_TARGET_NAMESPACES=
--------------------


And I still see vulnerabilities in "kube-system" namespace

**Comment by chen-keinan** [comment]
@IamThomasB  on [validate excluded namespace](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/operator/predicate/predicate.go#L48) maybe GetNamespace() return extra space or else

**Comment by simontrimboy** [comment]
Further to the above I have upgraded the chart to v.0.11.0 (trivy v0.36.0) today and the exclude namespaces attribure is now working as expected.

**Comment by githubcdr** [comment]
slightly offtopic, but this should be a list.

**Comment by thomasroot** [comment]
We also see this issue on our clusters with v0.12.1 of the Trivy-Operator. It looks like that `vulnerabilityreports` and `exposedsecretreports`  respect the `excludeNamespaces` param but other reports do not respect the` excludeNamespaces` param. My trivy-operator deployment runs with the following env variable that was specified by the helm installation: `OPERATOR_EXCLUDE_NAMESPACES=test-thomas,kube-system,kube-node-lease,kube-public` . Unfortunately I can find some rbacAssessments in my namespace `test-thomas` .

**Comment by chen-keinan** [comment]
@positively  we have made a change in that area while upgrading to latest k8s lib , could you check with trivy-operator v0.14.0-rc ?

**Comment by alextylor-orch-id** [comment]
Just to chime in, I also have no namespaces being ignored.
chart: 0.14.1
`excludeNamespaces: "gmp-system,test"`

Operator pod env values
```
  containers:
    - env:
        - name: OPERATOR_NAMESPACE
          value: trivy
        - name: OPERATOR_TARGET_NAMESPACES
        - name: OPERATOR_EXCLUDE_NAMESPACES
          value: 'gmp-system,gmp-public,kube-node-lease,kube-system,kube-public'
```

**Comment by positively** [comment]
@chen-keinan 
actually yes, but could you clarify please, is `v0.14.0-rc` later version than `0.40.0`?

**Comment by chen-keinan** [comment]
@positively `v0.14.0-rc` is the `trivy-operator` version and  `0.40.0` is trivy version

**Comment by chen-keinan** [comment]
@jorikseldeslachts  thanks for the input , I'll have another look

**Comment by derek-mackley** [comment]
Is the current workaround to this to downgrade to the v11.0 chart?

**Comment by mmorejon** [comment]
Still the same issue with `0.15.1` on k3s.

**Comment by xavbourdeau** [comment]
Still not working with `0.16.1` on gke

**Comment by sjedlick** [comment]
Still not working with 0.16.3 on aks
`excludeNamespaces: "gatekeeper-system,kube-*"`

Please re-open this issue

**Comment by etcshad0vv** [comment]
Depending on which scanners you have enabled, since the scan job is the same one performed for all kind of workload reports, you will have to remove any leftover objects and keep operator stopped before you exclude any namespace.

1. Stop the operator
2. Set the `OPERATOR_EXCLUDE_NAMESPACES` to a comma separated list of excluded namespaces(glob-pattern is supported)
3. Before you start the operator, remove from the excluded namespaces any objects that where created while operator was running, **otherwise by design the operator will reconcile** if any object is found for a workload in **any** of the custom resources watched by operator.  If there are leftover objects about the same workload for instance `configaudits` and you deleted only `vuln` while Trivy operator is running then by design operator will reconcile and recreate `vuln` object because the report is generated by the same scanner job. To find out what namespaced resources you would need to clean up:

    ```console
    kubectl api-resources --namespaced=true --api-group=aquasecurity.github.io
    ```
4. Start the operator

This was the only way it worked to me to decrease the scope of trivy operator!

**Comment by jon-rei** [comment]
@etcshad0vv thanks for the tip. I've just tested it on my cluster and it seems to do the trick.

**Comment by etcshad0vv** [comment]
I am glad it did the trick for you, perhaps what we can ask in this issue, during reconciliation the operator to go over the exclusion so we can clean up while operator is working. @chen-keinan fyi! Thank you

**Comment by chen-keinan** [comment]
Closing following to feedback by @etcshad0vv and confirmation @jon-rei
