### ISSUE TITLE
Possible to Schedule Re-Scans

### ISSUE THREAD

**Issue by vennemp** [aquasecurity/trivy-operator#744]
What is the re-scan policy for images in a cluster? I get that if you delete the VulnerabilityReport for an image, it will force a rescan.  But from what I see this is always a manual process or some custom automation.  For compliance reasons, we must scan images every 30 days automatically.  The reason being if an image is clean at runtime, it may not be clean X number of days later as new vulns are discovered and added to the Trivy database.  Is this currently supported by a value in a ConfigMap?

**Comment by chen-keinan** [comment]
@vennemp `trivy-operator` support `TTL (default: 24h) annotation` for every report , meaning that every report will deleted every day and a re-scan will be triggered.  you can make it shorter or longer by [config](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L53) 

Let me know if this is what you are looking for.
