### ISSUE TITLE
Regression: Trivy Operator can not scan its own namespace

### ISSUE THREAD

**Issue by fhielpos** [aquasecurity/trivy-operator#751]
As part of https://github.com/aquasecurity/trivy-operator/pull/525 , this line was changed:

https://github.com/aquasecurity/trivy-operator/blob/6a4870318209299329dff987edfab090d0e98c08/deploy/helm/templates/deployment.yaml#L41

Which now always excludes Trivy Operator own namespace from being scanned. Is there any reason to believe this would be necessary? 

I think that it is beneficial to be able to scan every namespace, specially since you could run Trivy Operator alongside other tools in the same namespace.

Regards,
Franco

**Comment by dirien** [comment]
I could remove the Trivy Namspace from the exclude list. Happy to do the PR, as it was introduced by me! WDYT @chen-keinan?

**Comment by chen-keinan** [comment]
> I could remove the Trivy Namspace from the exclude list. Happy to do the PR, as it was introduced by me! WDYT @chen-keinan?

Sure go for it

**Comment by dirien** [comment]
Created PR #752

**Comment by fhielpos** [comment]
That was fast, thank you!
