### ISSUE TITLE
"Failed to get API Group-Resources" and "unable to run trivy operator: constructing controllers manager"

### ISSUE THREAD

**Issue by johnnykalani** [aquasecurity/trivy-operator#756]
Hi All,

After installing Trivy-Operator with Helm the deployment isn't able to go into ready state.  Would greatly appreciate any guidance.  The Minikube cluster is up, Kube-hunter and trivy (non-operator) works fine.  

% kubectl get deployment -n trivy-system
{"level":"info","ts":1670193098.8578537,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.7.1","Commit":"42c561f1915f0d97d8b8048008188599443fd3c7","Date":"2022-11-21T18:21:59Z","Executable":""}}
{"level":"info","ts":1670193098.858752,"logger":"operator","msg":"Resolved install mode","install mode":"AllNamespaces","operator namespace":"trivy-system","target namespaces":[],"exclude namespaces":",trivy-system","target workloads":["pod","replicaset","replicationcontroller","statefulset","daemonset","cronjob","job"]}
{"level":"info","ts":1670193098.8593328,"logger":"operator","msg":"Watching all namespaces"}
{"level":"error","ts":1670193101.935072,"msg":"Failed to get API Group-Resources","error":"Get \"[https://10.96.0.1:443/api?timeout=32s\](https://10.96.0.1/api?timeout=32s%5C)": dial tcp 10.96.0.1:443: connect: no route to host","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/cluster.New\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/manager/manager.go:344\ngithub.com/aquasecurity/trivy-operator/pkg/operator.Start\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/operator/operator.go:107\nmain.run\n\t/home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:50\nmain.main\n\t/home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:34\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/proc.go:250](http://sigs.k8s.io/controller-runtime/pkg/cluster.New%5Cn%5Ct/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/cluster/cluster.go:160%5Cnsigs.k8s.io/controller-runtime/pkg/manager.New%5Cn%5Ct/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/manager/manager.go:344%5Cngithub.com/aquasecurity/trivy-operator/pkg/operator.Start%5Cn%5Ct/home/runner/work/trivy-operator/trivy-operator/pkg/operator/operator.go:107%5Cnmain.run%5Cn%5Ct/home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:50%5Cnmain.main%5Cn%5Ct/home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:34%5Cnruntime.main%5Cn%5Ct/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/proc.go:250)"}
unable to run trivy operator: constructing controllers manager: Get "[https://10.96.0.1:443/api?timeout=32s](https://10.96.0.1/api?timeout=32s)": dial tcp 10.96.0.1:443: connect: no route to host

**Comment by jrhunger** [comment]
That doesn't look like the output of kubectl get deployment.  What command generated that output?  Are those the logs of the trivy operator pod?

**Comment by johnnykalani** [comment]
Sorry that was from the "kubectl logs deployment/trivy-operator -n trivy-system"

Here's the get deployment:

 trivy-operator % kubectl get deployment -n trivy-system
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
trivy-operator   0/1     1            0           64s

The cluster is working fine, not a true cluster as its minikube created.  Assuming trivy operator is supported on minikube?

**Comment by jrhunger** [comment]
Somethings you can try:
* kubectl -n default get svc
(check for kubernetes. ip should be 10.96.0.1)
* Try running a busybox shell and see if from inside it you can connect to https://10.96.0.1:443/api or https://kubernetes.default.svc.cluster.local/api

**Comment by johnnykalani** [comment]
Pretty strange as all looks good from what I can see.  I wonder if its a limitation with Minikube and if I should try with real nodes?  Really appreciate the help 

 % kubectl get svc kubernetes -n default
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6d23h

% kubectl get pods -n kube-system | grep apiserver
kube-apiserver-minikube            1/1     Running   1 (5h5m ago)    6d23h
 
% kubectl get ep kubernetes -n default
NAME         ENDPOINTS             AGE
kubernetes   172.16.194.131:8443   6d23h

**Comment by jrhunger** [comment]
I don't know anything about minikube. The operator worked for me with kind, though and that seems like a similar thing. Kind was easy to set up per the links in trivy-operator development instructions. Granted I did it on a Linux vm through ssh but if your docker is working I don't know why it wouldn't work on your desktop.

**Comment by johnnykalani** [comment]
I discovered that I have Jenkins running also on port 8080, so that's likely the conflict.  I'll try changing it and see if it makes the difference.

**Comment by chen-keinan** [comment]
@johnnykalani is the problems solved? do you still want to keep the issue open ?

**Comment by AnaisUrlichs** [comment]
@chen-keinan I ran into a similar problem before & Jose helped me solve it 

He told me to update the service -- delete the one in the trivy-system namespace and install this one https://gist.github.com/josedonizetti/ddcf555b5894b405cf8b87a3932ebaa0
He said that it is because of this line: https://github.com/aquasecurity/trivy-operator/blob/main/deploy/static/trivy-operator.yaml#L2360

This is also related to the Slack conversation: https://aquasecurity.slack.com/archives/C03L2H45L3H/p1676995374016649

Sorry, I should have followed up, I thought Jose started a PR 😄

**Comment by chen-keinan** [comment]
> 
> This is also related to the Slack conversation: https://aquasecurity.slack.com/archives/C03L2H45L3H/p1676995374016649
> 
> Sorry, I should have followed up, I thought Jose started a PR 😄

@AnaisUrlichs thanks for your input , I'll take a look at it

**Comment by chen-keinan** [comment]
Closing issue as documentation has been updated with service change
