### ISSUE TITLE
Unable to install trivy-operator

### ISSUE THREAD

**Issue by HW-Jeremy** [aquasecurity/trivy-operator#795]
**What steps did you take and what happened:**

[A clear and concise description of what the bug is, and what commands you ran.]

I want to try trivy-operator in order to scan my containers under kubernetes.

I got the following error when I try to install it via Helm :

`helm install trivy-operator aqua/trivy-operator \
   --namespace trivy-system \
   --create-namespace \
   --set="trivy.ignoreUnfixed=true" \
   --version v0.9.1
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ClusterComplianceReport.spec): unknown field "compliance" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec, ValidationError(ClusterComplianceReport.spec): unknown field "reportType" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec, ValidationError(ClusterComplianceReport.spec): missing required field "name" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec, ValidationError(ClusterComplianceReport.spec): missing required field "description" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec, ValidationError(ClusterComplianceReport.spec): missing required field "version" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec, ValidationError(ClusterComplianceReport.spec): missing required field "controls" in io.github.aquasecurity.v1alpha1.ClusterComplianceReport.spec]`

**What did you expect to happen:**

trivy-operator is installed

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.9.1
- Kubernetes version (use `kubectl version`): 1.24.6

**Comment by chen-keinan** [comment]
@HW-Jeremy thanks for reporting this issue,  is this a clean install ? have you used starboard before in your cluster ? 
can you please send your output for the following command
```
kubectl get crd clustercompliancereports.aquasecurity.github.io  -o yaml
```

**Comment by HW-Jeremy** [comment]
Hi, thanks for your response.

Here the output of the command : 

`kubectl get crd clustercompliancereports.aquasecurity.github.io  -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2022-12-16T13:45:48Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: trivy-operator
    app.kubernetes.io/version: 0.0.3
  name: clustercompliancereports.aquasecurity.github.io
  resourceVersion: "164308757"
  uid: e932e3a0-00a1-468e-8672-e47e21492140
spec:
  conversion:
    strategy: None
  group: aquasecurity.github.io
  names:
    kind: ClusterComplianceReport
    listKind: ClusterComplianceReportList
    plural: clustercompliancereports
    shortNames:
    - compliance
    singular: clustercompliancereport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The age of the report
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: The number of checks that failed with Danger status
      jsonPath: .status.summary.failCount
      name: Fail
      priority: 1
      type: integer
    - description: The number of checks that passed
      jsonPath: .status.summary.passCount
      name: Pass
      priority: 1
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              controls:
                items:
                  properties:
                    defaultStatus:
                      description: define the default value for check status in case
                        resource not found
                      enum:
                      - PASS
                      - WARN
                      - FAIL
                      type: string
                    description:
                      type: string
                    id:
                      description: id define the control check id
                      type: string
                    kinds:
                      items:
                        description: 'kinds define the list of kinds control check
                          apply on , example: Node,Workload '
                        type: string
                      type: array
                    mapping:
                      properties:
                        checks:
                          items:
                            properties:
                              id:
                                description: id define the check id as produced by
                                  scanner
                                type: string
                            required:
                            - id
                            type: object
                          type: array
                        scanner:
                          description: scanner define the name of the scanner which
                            produce data, currently only config-audit and kube-bench
                            are supported
                          pattern: ^config-audit$|^kube-bench$
                          type: string
                      required:
                      - scanner
                      - checks
                      type: object
                    name:
                      type: string
                    severity:
                      description: define the severity of the control
                      enum:
                      - CRITICAL
                      - HIGH
                      - MEDIUM
                      - LOW
                      - UNKNOWN
                      type: string
                  required:
                  - name
                  - id
                  - kinds
                  - mapping
                  - severity
                  type: object
                type: array
              cron:
                description: cron define the intervals for report generation
                pattern: ^(((([\*]{1}){1})|((\*\/){0,1}(([0-9]{1}){1}|(([1-5]{1}){1}([0-9]{1}){1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([0-9]{1}){1}|(([1]{1}){1}([0-9]{1}){1}){1}|([2]{1}){1}([0-3]{1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([1-9]{1}){1}|(([1-2]{1}){1}([0-9]{1}){1}){1}|([3]{1}){1}([0-1]{1}){1})))
                  ((([\*]{1}){1})|((\*\/){0,1}(([1-9]{1}){1}|(([1-2]{1}){1}([0-9]{1}){1}){1}|([3]{1}){1}([0-1]{1}){1}))|(jan|feb|mar|apr|may|jun|jul|aug|sep|okt|nov|dec))
                  ((([\*]{1}){1})|((\*\/){0,1}(([0-7]{1}){1}))|(sun|mon|tue|wed|thu|fri|sat)))$
                type: string
              description:
                type: string
              name:
                type: string
              version:
                type: string
            required:
            - name
            - description
            - version
            - cron
            - controls
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ClusterComplianceReport
    listKind: ClusterComplianceReportList
    plural: clustercompliancereports
    shortNames:
    - compliance
    singular: clustercompliancereport
  conditions:
  - lastTransitionTime: "2022-12-16T13:45:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-12-16T13:45:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1`

**Comment by HW-Jeremy** [comment]
Thanks, it worked!

On the other hand trivy does not manage to scan the pods, I have this error everywhere:

{"level":"error","ts":1671440237.0341504,"logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-64d6b457fc","container":"xxxx","status.reason":"Error","status.message":"2022-12-19T08:57:13.975Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (xxxxx): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* GET https://xxxx: MANIFEST_UNKNOWN: manifest unknown; [map[Name:xxx] map[Tag:develop]]\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:254\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:79\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}

Have you an idea??

**Comment by chen-keinan** [comment]
is you images are pulled from private registries ? if so , is `imagePullSecret` is define on `pod` or `sa` ?

**Comment by HW-Jeremy** [comment]
Yes my image are pulled from private registry (ACR).

`imagePullSecret` not define on `pod` or `sa`

**Comment by chen-keinan** [comment]
> Yes my image are pulled from private registry (ACR).
> 
> `imagePullSecret` not define on `pod` or `sa`

this is the issue , here here how to work with [private registries](https://aquasecurity.github.io/trivy-operator/v0.9.1/tutorials/private-registries/) and [managed registries](https://aquasecurity.github.io/trivy-operator/v0.9.0/vulnerability-scanning/managed-registries/#amazon-elastic-container-registry-ecr)

**Comment by HW-Jeremy** [comment]
Thanks. It was a authentification problem I guess.

Work fine now, I use filesystem command instead of image.
