### ISSUE TITLE
Helm Chart support for ClusterComplianceReport ReportType and Cron Property

### ISSUE THREAD

**Issue by fjogeleit** [aquasecurity/trivy-operator#797]
To enable detailed (all) mode or adjust the `cron` time for the ClusterComplianceReport, you need to manually edit the `ClusterComplianceReport` resource. While this is generally easy to do, it requires additional work if you manage Trivy Operator via GitOps tools like ArgoCD.

By default, these tools resynchronize the modified properties as soon as they are changed, and additional configuration is required to ignore these properties. To improve the usage of this report, I would like to request new values in the Helm Chart to define the `reportType` as well as the `cron` expression directly in the Helm Chart.

**Comment by wpi86** [comment]
Hi, any updates?

**Comment by chen-keinan** [comment]
@wpi86 @fjogeleit  a release with a support for this flag will be available  next week

**Comment by fjogeleit** [comment]
great, thanks for letting us know
