### ISSUE TITLE
docker can not pull image ghcr.io/aquasecurity/trivy-db

### ISSUE THREAD

**Issue by tomsunyu** [aquasecurity/trivy-operator#798]
Hey, the trivy job in kubernetes cluster is always containercreating when I install the trivy-operator by helm charts. I found the docker logs, docker can not pull image: **ghcr.io/aquasecurity/trivy-db**. Network is reachable, docker can pull image: ghcr.io/aquasecurity/trivy-operator:0.9.0.
Also, I pull the trivy-db image by docker.
```
[root@node1 ~]# docker pull ghcr.io/aquasecurity/trivy-db
Using default tag: latest
latest: Pulling from aquasecurity/trivy-db
4bfe20410a74: Pulling fs layer
unexpected end of JSON input
```
So how to solve the problem?

**Comment by chen-keinan** [comment]
@tomsunyu could this is a temp issue ?

from command line you need to use `oras` :
`oras pull ghcr.io/aquasecurity/trivy-db:2`

Can you please add the logs from `trivy-operator`

**Comment by chen-keinan** [comment]
I also suggest to use the `builtInTrivyServer` and download the db only once :
example :
```
helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
  --set="operator.builtInTrivyServer=true" \
   --version 0.9.1
```

**Comment by tomsunyu** [comment]
> I also suggest to use the `builtInTrivyServer` and download the db only once : example :
> 
> ```
> helm install trivy-operator aqua/trivy-operator \
>   --namespace trivy-system \
>   --create-namespace \
>   --set="trivy.ignoreUnfixed=true" \
>   --set="operator.builtInTrivyServer=true" \
>    --version 0.9.1
> ```

I installed it according to the above method, but the pod trivy-server-0 is always restarting. The log is as follows:

```
[root@node1 trivy-operator]# kubectl logs trivy-server-0 -n trivy-system
2022-12-21T01:22:34.192Z        INFO    Need to update DB
2022-12-21T01:22:34.192Z        INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2022-12-21T01:22:34.192Z        INFO    Downloading DB...
```
Can you help?

**Comment by chen-keinan** [comment]
@tomsunyu Its look like you cluster is unable to access `ghcr.io/aquasecurity/trivy-db`  which in a way, I think, related to `docker can not pull image: ghcr.io/aquasecurity/trivy-db. Network is reachable ` your initial issue , can you check it ? 

Do you have a local env. `Kind` just to make sure you succeed to get it work and try to isolate the problem ?

**Comment by tomsunyu** [comment]
> 

So how can I solve the problem if the network fails. Is there any other way ?

**Comment by chen-keinan** [comment]
> > 
> 
> So how can I solve the problem if the network fails. Is there any other way ?

anything you can do to check why your cluster network is not access to `ghcr.io/aquasecurity/trivy-db` the other option will be to download the db by your self to other public  repo where it is accessible and override the this [param](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L308)

**Comment by tomsunyu** [comment]
> 

Thanks. How to download the trivy db to my native harbor registry ？

**Comment by chen-keinan** [comment]
> > 
> 
> Thanks. How to download the trivy db to my native harbor registry ？

you can [pull](oras pull -a ghcr.io/aquasecurity/trivy-db:2`) and push it to harbor registry

**Comment by dkulchinsky** [comment]
> > 
> 
> Thanks. How to download the trivy db to my native harbor registry ？

You can use Harbor replication, that's what we do to maintain a lical mirror that iur trivy cluster uses
