### ISSUE TITLE
compliance -o wide do not show fail and pass count

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#829]
compliance -o wide do not show fail and pass count 
`kubectl get compliance -o wide`

```
NAME   AGE     FAIL   PASS
cis    6m55s
nsa    6m55s
```

**Comment by AP-XD** [comment]
Refer the documentation:
You can use either `k describe clustercompliancereport cis`
or  `k get clustercompliancereport cis  -o=jsonpath='{.status}' | jq`
to get a json output.
Here is the[ link ](https://aquasecurity.github.io/trivy-operator/v0.12.1/docs/compliance/compliance/)for documentation
