### ISSUE TITLE
Filesystem scan mode fails to create cache dir without a `volumeMount`

### ISSUE THREAD

**Issue by akerge** [aquasecurity/trivy-operator#831]
## What steps did you take and what happened?

`trivy-operator` with `trivy.command: "filesystem"` encountered an error:

```
unable to initialize fs cache: failed to create cache dir: mkdir /var/trivyoperator/trivy-db/fanal: permission denied
```

No vulnerability reports were produced.

## What did you expect to happen?

For the deployment work out of the box.

## Anything else you would like to add?

:white_check_mark: **Solution:**

Added a `volumeMount` to trivy-operator deployment:

```
          volumeMounts:
            - name: trivy-cache
              mountPath: /var/trivyoperator/trivy-db
```

```
      volumes:
        - name: trivy-cache
          emptyDir: {}
      securityContext:
        fsGroup: 10000
```

As @chen-keinan suggested, added `runAsUser=0` to `trivyOperator.scanJobPodTemplateContainerSecurityContext`:

```
  scanJob.podTemplateContainerSecurityContext: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true,\"runAsUser\":0}"
```

**Environment:**

- Trivy-Operator version: 0.10.1
- Kubernetes version: 1.19
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 22.04

**Comment by chen-keinan** [comment]
@akerge I tested the `FileSystem` scanning with helm install and didn't got any error :
```
helm install trivy-operator aqua/trivy-operator \
    --namespace trivy-system \
    --create-namespace \
    --set="trivy.command=filesystem" \
    --set="trivyOperator.scanJobPodTemplateContainerSecurityContext.runAsUser=0" \
    --set="trivy.ignoreUnfixed=true" \
    --version 0.10.1
```
I Assume you didn't use the `helm install` , right ? are you using any special policies in your cluster ?

**Comment by akerge** [comment]
Strangely, the issue resolved itself by redeploy and works without `volumeMount`.

Unfortunately currently I don't use helm. AFAIK there shouldn't be any special policies nor constraints.

There are minute cluster specific differences between the pasted trivy-operator.yaml, like Deployment `spec.template.metadata.annotations` and a different metrics port name.

Closing the issue as cannot replicate either.
