### ISSUE TITLE
Add scanned resource name & kind as labels to metrics

### ISSUE THREAD

**Issue by dkulchinsky** [aquasecurity/trivy-operator#839]
Hey folks 👋🏼 

I think it would be very useful if the resource name and kind would be added to the metrics as labels.

currently we have the `name` label (which is the vuln report name) and it may or may not have the details of the resource name, since they are sometimes replaced by a hash if the name is too long.

having these extra labels would be very useful to be able to do join queries to get additional information on the affected resource.

**Comment by chen-keinan** [comment]
@dkulchinsky thank you for the input , could please add an example of how the metric after the change would look like ?

**Comment by chen-keinan** [comment]
@dkulchinsky you can pick it up if you have time

**Comment by dkulchinsky** [comment]
Thanks @chen-keinan, give it a go now.

But I'm a bit confused by the `collectVulnerabilityIdReports` method.

looking at this code [here](https://github.com/aquasecurity/trivy-operator/blob/bd5042d17435529e5bf607547d49e95d4cab2733/pkg/metrics/collector.go#L391-L417), and unless I'm missing something obvious, it looks like the labels starting from position 8 are being overridden.

so, the dynamic labels are added starting from position 8:
```go
				for i, label := range c.GetReportResourceLabels() {
					vulnLabelValues[i+8] = r.Labels[label]
				}
```

which then gets overridden by this lot:
```go
					vulnLabelValues[8] = NewSeverityLabel(vuln.Severity).Label
					vulnLabelValues[9] = vuln.PackageType
					vulnLabelValues[10] = vuln.Class
					vulnLabelValues[11] = vuln.VulnerabilityID
```

I believe what's missing is changing:
```go
				for i, label := range c.GetReportResourceLabels() {
					vulnLabelValues[i+8] = r.Labels[label]
				}
```

to:
```go
				for i, label := range c.GetReportResourceLabels() {
					vulnLabelValues[i+12] = r.Labels[label]
				}
```

since the dynamic labels are expected from position 12 onward.

wdyt? or I'm completely off here?

**Comment by dkulchinsky** [comment]
Hey @chen-keinan, gave a shot here: https://github.com/aquasecurity/trivy-operator/pull/841 and I believe I also addressed the potential issue I described im [comment](https://github.com/aquasecurity/trivy-operator/issues/839#issuecomment-1377668491) above
