### ISSUE TITLE
Lens extension

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/trivy-operator#84]
create a trivy-operator Lens extension (based on Starboard's https://github.com/aquasecurity/starboard-lens-extension)

thanks for @nublarsec for raising this in Slack https://aquasecurity.slack.com/archives/C02KSDSBPGD/p1654184354851129

**Comment by chen-keinan** [comment]
Available now :  [trivy-operator-lens-extension](https://github.com/aquasecurity/trivy-operator-lens-extension)
