### ISSUE TITLE
Bugfix release soon?

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#89]
Are we able to push a new release soon? I use FluxCD to provision the operator, and would really like to see a release containing this unblocking bugfix: https://github.com/aquasecurity/trivy-operator/pull/42. The workaround renaming the ConfigMap does not work very well with a GitOps controller as Flux.

**Comment by chen-keinan** [comment]
coming soon : #90

**Comment by chen-keinan** [comment]
Trivy-operator v0.0.5 has been released

**Comment by erikgb** [comment]
Thanks a lot @chen-keinan. I will check it out tomorrow!
