### ISSUE TITLE
The server token env variable in trivy-operator-trivy-config secret needs to be base64 encoded

### ISSUE THREAD

**Issue by mkotsalainen** [aquasecurity/trivy-operator#897]
**What steps did you take and what happened:**

The helm chart doesn't work with ClientServer mode. The reason is that the secret TRIVY_TOKEN doesn't get base64 encoded like the trivy.serverToken so there's a mismatch.

Compare: 
https://github.com/aquasecurity/trivy-operator/blob/eb495d1fd5cd5303e4b5fbc0b95a15e8d58603ef/deploy/helm/templates/config.yaml#L198
and
https://github.com/aquasecurity/trivy-operator/blob/eb495d1fd5cd5303e4b5fbc0b95a15e8d58603ef/deploy/helm/templates/config.yaml#L184

TRIVY_USERNAME and TRIVY_PASSWORD variables below also needs to be bse64 encoded.

**Comment by chen-keinan** [comment]
@mkotsalainen thank you for raising this issue, feel free to pick it up.
btw: did you tried to use the `builtInServer`
