### ISSUE TITLE
Helm chart privateRegistryScanSecretsNames should allow for multiple secrets in same namespace

### ISSUE THREAD

**Issue by mkotsalainen** [aquasecurity/trivy-operator#908]
Related #898 
https://github.com/aquasecurity/trivy-operator/blob/eb495d1fd5cd5303e4b5fbc0b95a15e8d58603ef/deploy/helm/values.yaml#L93

This won't work if we need more than one secret per namespace unless it accepts an array as value. This might be the case - if so, close this

**Comment by chen-keinan** [comment]
suggested solution is to extend the `privateRegistryScanSecretsNames` to accept key to multi value comma separated.

example: `{"myNamespace":"cred1,cred2,cred3"}`
