### ISSUE TITLE
create our own vulnerability scan jobs

### ISSUE THREAD

**Issue by RasheedJad** [aquasecurity/trivy-operator#924]
I would like to know if there is the possibility that I can create a scanning job (i.e scan-vulnerabilityreport-*) for a set images and then the operator does the rest of work like creating the custom report and also the Prometheus metrics. is that possible?

**Comment by chen-keinan** [comment]
@RasheedJad the answer is yes, if you will create the scan job with the `appropriate labels` on trivy-operator `namespace`,  the operator will reconcile the scan job and create reports and metrics

**Comment by RasheedJad** [comment]
@chen-keinan  any idea about the "appropriate labels" or where are they mentioned in docs or somewhere else so I use them?

**Comment by chen-keinan** [comment]
@RasheedJad no docs for it ,you can check the code , however the simple way is run a scan and view it job description.
like this :  `kubectl get <scan-job> -n trivy-system -o yaml`

**Comment by chen-keinan** [comment]
@RasheedJad could you please advice on use-case for creating `own vulnerability scan jobs`

**Comment by RasheedJad** [comment]
I actually gave up on trivy for a tool called NeuVector and after trying the new tool, I am more satisfied with it.

**Comment by chen-keinan** [comment]
> I actually gave up on trivy for a tool called NeuVector and after trying the new tool, I am more satisfied with it.

thank you for the response . do you mind sharing what was not satisfying for you whilst using `trivy` tool ?

**Comment by chen-keinan** [comment]
closing as not relevant.
