### ISSUE TITLE
Add additional labels or annotations on CRDs like VulnerabilityReport

### ISSUE THREAD

**Issue by weibo-zhao** [aquasecurity/trivy-operator#943]
Hi Trivy-operator community members, 

I want it ask if it is possible to add additional labels or annotations in the VulnerabilityReport crd?

Currently this is the part of VulnerabilityReport yaml file I get. I want to customize it to add some information like the Kubernetes cluster name, dev or live environment, etc. I am using Helm chart to deploy. I have tried all label and annotation key value pairs in current helm chart but they don't change the VulnerabilityReport crd yaml file.

> apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityReport
metadata:
  annotations:
    trivy-operator.aquasecurity.github.io/report-ttl: 24h0m0s
  creationTimestamp: '2023-02-09T12:38:33Z'
  generation: 4
  labels:
    resource-spec-hash: cc65f4d64
    trivy-operator.container.name: kube-proxy
    trivy-operator.resource.kind: DaemonSet
    trivy-operator.resource.name: kube-proxy
    trivy-operator.resource.namespace: kube-system
  managedFields: ...

Any suggestions and improvements are appreciated.
Best regards,
Weibo

**Comment by chen-keinan** [comment]
@weibo-zhao could be nice addition , feel free to pick it up if you have time

**Comment by SamarSidharth** [comment]
Hello @chen-keinan and @weibo-zhao 

I assume that these annotation values will be static provided by the user and the scope would apply to all reports generated by trivy-operator, based on this I see 2 options to pass them as key:value pair 
1. As a field in the trivy-operator CM
2. As a env var in the trivy-operator deployment

We can then populate the reports with these additional annotations

Kindly let me know your views

Thanks

**Comment by chap-dr** [comment]
Hi, I've subscribed to this as this is also something we would very much like to see, would it make sense to do the implementation in a similar fashion as the  [scanJob.templateLabel](https://github.com/aquasecurity/trivy-operator/blob/f57815eac3d9d094da3e91ac364fdeaae04660d1/docs/settings.md?plain=1#L59)?

**Comment by chen-keinan** [comment]
> Hello @chen-keinan and @weibo-zhao
> 
> I assume that these annotation values will be static provided by the user and the scope would apply to all reports generated by trivy-operator, based on this I see 2 options to pass them as key:value pair
> 

make sense , similar to option suggested by @chap-dr
