### ISSUE TITLE
support for trivy v0.37.x - update scanner flag

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-operator#948]
it is require to bump trivy to latest v0.37.x and update [command flags](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L1269).

-replace `-security-checks` with `--scanners`

**Comment by jrhunger** [comment]
This will need release notes as a breaking change for people using a custom image unless they update their image to 0.37+

**Comment by chen-keinan** [comment]
> This will need release notes as a breaking change for people using a custom image unless they update their image to 0.37+

good point however  we can add support for old trivy versions as will , we did something  similar on[ different API change](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L243)
