### ISSUE TITLE
Uninstall trivy-operator, job tasks are not cleaned up

### ISSUE THREAD

**Issue by fengshunli** [aquasecurity/trivy-operator#959]
**What steps did you take and what happened:**

After helm uninstall trivy-operator -n trivy-system is executed, related tasks are not cleaned up
<img width="689" alt="image" src="https://user-images.githubusercontent.com/18587688/218512053-ae6e99f7-764c-4d58-9f19-01613829f069.png">

[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@fengshunli reports should not be cleanup up as they are produce on workload namespaces , it is design to act like these

**Comment by fengshunli** [comment]
You can control the task of cleaning up through ttlSecondsAfterFinished

**Comment by chen-keinan** [comment]
> You can control the task of cleaning up through ttlSecondsAfterFinished

yes, you are right , maybe `ttlSecondsAfterFinished` need to have high value so it will not be cleaned up before operator complete report  processing

**Comment by chen-keinan** [comment]
@fengshunli you want to pick it up ?

**Comment by fengshunli** [comment]
I want to transform the []string of prometheus.MustNewConstMetric into []struct, is this needed again? @chen-keinan

**Comment by chen-keinan** [comment]
> I want to transform the []string of prometheus.MustNewConstMetric into []struct, is this needed again? @chen-keinan 

Not sure regarding the context , is it related to this issue ?

**Comment by fengshunli** [comment]
No, the modification in the collector mentioned earlier
