### ISSUE TITLE
Additional labels for trivy_image_exposedsecrets metric

### ISSUE THREAD

**Issue by dkulchinsky** [aquasecurity/trivy-operator#998]
Hello folks 👋🏼 

I was looking at working on a PR to add additional labels to the `trivy_image_exposedsecrets` metrics, specifically we would like to be able to identify better the secrets that were found and use it in our alerting and dashboards.

I wanted to reach to see if this is something you'd be interested in?

I'd like to add these additional labels:
- secret_target
- secret_rule_id
- secret_category
- secret_title
(perhaps also secret_match in case the above may produce non unique results?)

I'm also debating if these should be added to the existing metric, or perhaps add a separate (optional?) metric like in the case of `trivy_vulnerability_id`? Personally, I don't think this is needed but would appreciate some guidance here.

Thanks!

/cc @chen-keinan

**Comment by chen-keinan** [comment]
@dkulchinsky thank you for looking at it , I would suggest to add separate metric (optional) to avoid cardinality for this metric

**Comment by dkulchinsky** [comment]
@chen-keinan makes sense 👍🏼 thanks for the feedback.

any preference for the metric name?

`trivy_image_exposedsecrets_id`? `trivy_image_exposedsecrets_info`? (naming is hard 😅)

**Comment by chen-keinan** [comment]
> @chen-keinan makes sense 👍🏼 thanks for the feedback.
> 
> any preference for the metric name?
> 
> `trivy_image_exposedsecrets_id`? `trivy_image_exposedsecrets_info`? (naming is hard 😅)

2nd on sound better

**Comment by dkulchinsky** [comment]
> 2nd one sound better

`trivy_image_exposedsecrets_info` it is :)

**Comment by dkulchinsky** [comment]
@chen-keinan https://github.com/aquasecurity/trivy-operator/pull/1000 is ready, please take a look.

PR 1000! 😄
